SC-3515 restore sort button infobox modal
hpi-schul-cloud/nuxt-client pull request #1254
Opened 2020-08-13 09:17 UTC by danielasofrone

# Description

Restored the sorting button to the Registration column and repositioned the info button

## Links to Tickets or other pull requests

- https://ticketsystem.schul-cloud.org/browse/SC-5823

## Changes

Restored the sorting button to the Registration column in the table and repositioned the info button. Upon clicking it, the button opens a modal with information that needs to be reviewed by the user

## Screenshots of UI changes
<img width="1121" alt="Screenshot 2020-08-13 at 10 07 45" src="https://user-images.githubusercontent.com/23704397/90116945-8a926f80-dd56-11ea-9abd-e0661f49a15f.png">
<img width="1117" alt="Screenshot 2020-08-13 at 10 08 16" src="https://user-images.githubusercontent.com/23704397/90116953-8d8d6000-dd56-11ea-9dcd-f5c22f4838c2.png">

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-08-13 12:07 UTC, danielasofrone commented
@schul-cloud-bot update screenshots

2020-08-17 10:22 UTC, danielasofrone commented
@schul-cloud-bot update screenshots

2020-08-19 10:48 UTC, BlackGhostHD requested changes
Looks pretty good already. I would suggest that we make this "i" button reusable. So that the content of the infobox remains separate by the technical implementation.

2020-08-25 13:34 UTC, j-jmnz approved these changes

2020-08-25 14:46 UTC, merged