SC-3788: add matrix messenger integration without configuration
hpi-schul-cloud/nuxt-client pull request #1262
Opened 2020-08-17 13:36 UTC by maxklenk

# Description

- [ ] Configure feature flag
- [ ] Configure embed endpoint
- [ ] Integrate Messenger in all loggedIn pages
- [ ] Terminate Messenger on loggedOut pages
- [ ] Pass current users language to the messenger
- [ ] Configure CORS

## Links to Tickets or other pull requests
- https://ticketsystem.schul-cloud.org/browse/SC-3788

## Changes
- add Messenger component
- include component in layout views

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>
- -

## Deployment
- add messenger environment variables that already exist in the client:
```
MATRIX_MESSENGER_EMBED_URI
MATRIX_MESSENGER_HOMESERVER_URI
FEATURE_MESSENGER_SCHOOL_SETTINGS_VISIBLE
"FEATURE_MESSENGER_SCHOOL_ROOM_ENABLED
```

## New Repos, NPM packages or vendor scripts
- Messenger resource are loaded when required

## Screenshots of UI changes
![Screenshot 2020-08-17 at 3 31 13 PM](https://user-images.githubusercontent.com/3898310/90402014-1c73e280-e09f-11ea-8712-d41cc4375f0b.png)

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-08-19 07:23 UTC, maxklenk commented on src/components/organisms/Messenger/Messenger.unit.js
> +		await wait(1000);
I would like to get rid of those wait calls. Is there another way to wait for the promises inside the component. The promises are mocked so they should be return in the next cycle/tick.

2020-08-19 10:54 UTC, BlackGhostHD commented on src/components/organisms/Messenger/Messenger.unit.js
> +		await wait(1000);
```suggestion
		const wrapper = mount(Messenger, {
			...createComponentMocks({ i18n: true, user: true, store: mockStores }),
		});
		await wrapper.vm.$nextTick();
```

2020-08-19 10:55 UTC, BlackGhostHD commented on src/components/organisms/Messenger/Messenger.unit.js
> +		await wait(1000);
You can try my suggestion, might solve your problem

2020-08-19 10:58 UTC, BlackGhostHD commented on src/layouts/loggedInFull.vue
> +		Messenger,
I missed that in our conversation yesterday; you don't need to include the messenger component here, because the layout uses LegacyLoggedIn and the component has already been added there (otherwise the component is added twice)

2020-08-19 14:37 UTC, maxklenk commented on src/components/organisms/Messenger/Messenger.unit.js
> +		await wait(1000);
Awesome, I have to wait for each promise, so it requires multiple ticks, but works great.

2020-08-20 09:14 UTC, BlackGhostHD commented on src/components/organisms/Messenger/Messenger.vue
> +				.dispatch("schools/find", query)
This API endpoint is not yet enabled for Nuxt in production. You may have to find another way or create a ticket to have this endpoint enabled.

2020-08-20 09:18 UTC, BlackGhostHD submitted a review, later dismissed
Looks good to me. 👍  Maybe @dominikbruechner can review this as well.

2020-10-05 18:13 UTC, janrenz commented
Why is this not merged yet? I prose a shared review session if this otherwise is hard to review

2020-10-08 14:03 UTC, pkleybolte requested changes

2020-10-16 09:26 UTC, CeEv requested changes

2020-10-16 09:26 UTC, CeEv commented on src/components/organisms/Messenger/Messenger.vue
> +			const matches = RegExp("/(course|team)s/([0-9a-f]{24})").exec(path);
const path = 'https://api.schul-cloud.de/courses/5d765d332d0323001a31c82222222222'; will match and it is cut the result after the second 2 at the end.

2020-10-16 09:26 UTC, CeEv commented on src/components/organisms/Messenger/Messenger.vue
> +				options.roomId = matrixRoomId;
If extractRoomTypeAndIdFromPath failed, then matrixRoomId and options.roomId = null;
Must we really execute some more stuff after this? 
Or is this fine and the null is what we want to know that we not show this room at this side.

2020-10-16 09:26 UTC, CeEv commented on src/store/auth.js
> +		if (indexedDB) {
Ok fine and is it is not defined what should be execute? Any error/ warning, post to Sentry?

2020-10-16 09:26 UTC, CeEv commented on src/store/messenger.js
> +		// TODO what is supposed to happen on error?
True todo, error pipline? Console.log is not a option. 

At the moment it is server side rendering. If it is possible that this error it throw by rending? Than we has the trouble with slow sync actions in production. By handlebars in old client the console.log execute on server side, not on client side.

2020-10-16 09:26 UTC, CeEv commented on src/store/messenger.unit.js
> +				).toBe("dummy-server.name");
Please add somethink like  { userId: "dummy-server.name" }, and  { userId: "dummy-user:dummy-server" }, as false input tests

2020-10-16 09:26 UTC, CeEv commented on src/store/messenger.unit.js
> +				expect(spyCommit.mock.calls).toHaveLength(1);
By executing more then one expect in one it, i am happy if you can add what every expect should test. As feedback for test if they are failed.

expect(spyCommit.mock.calls, 'Should has lengh one, because ....').toHaveLength(1);

2020-10-16 09:26 UTC, CeEv commented on src/store/messenger.unit.js
> +				const spyCommit = jest.fn();
I know the syntax
const mocker= jest.fn();
const snapshot = new mocker();

How it work in this way? Can you please validate what is the right way to use it.

2020-10-16 10:52 UTC, pkleybolte commented on src/components/organisms/Messenger/Messenger.unit.js
> +		process.env.FEATURE_MATRIX_MESSENGER_ENABLED = undefined;
You can't have more than one beforeEach. So We can't generate an extra one for the toggles. I guess we will have to deal with this.
There should no be to many cases like this though, because most feature toggles should be server side only.

2020-10-16 10:54 UTC, pkleybolte commented on src/components/organisms/Messenger/Messenger.unit.js
> +		window.localStorage.setItem("mx_hs_url", "domain");
I'll remove them again at the end of the test just in case.

2020-10-16 11:56 UTC, tofixx commented on src/components/organisms/Messenger/Messenger.unit.js
> +		process.env.FEATURE_MATRIX_MESSENGER_ENABLED = undefined;
you may integrate commons.configuration to solve this...

2020-10-16 11:57 UTC, pkleybolte commented on src/components/organisms/Messenger/Messenger.vue
> +			return process.env.FEATURE_MATRIX_MESSENGER_ENABLED === "true";
There is no config file like in the server in Nuxt.
And compile time they are written from the nuxt.config.js into that var. The nuxt.config.js is not available at runtime or in the tests though.

2020-10-16 12:00 UTC, tofixx commented on src/components/organisms/Messenger/Messenger.vue
> +			return process.env.FEATURE_MATRIX_MESSENGER_ENABLED === "true";
sure, however the config must match client/server because of that i would load the values not as configuration but upon login as part of school/user view permissions/setting instead. for now this may stay while we could add schema validation using commons.configutration and export the whole configuration afterwards to be used...

2020-10-16 12:03 UTC, pkleybolte commented on src/store/messenger.unit.js
> +				const spyCommit = jest.fn();
I used the syntax for creating a mock function using jest only.
The are a couple of other libs for mocks. The syntax you mentioned is used by at least one other lib.

2020-10-16 12:16 UTC, pkleybolte commented on src/store/messenger.unit.js
> +				expect(spyCommit.mock.calls).toHaveLength(1);
expect() does not provide the possibility to add a custom error message.

2020-10-16 12:37 UTC, pkleybolte commented on src/components/organisms/Messenger/Messenger.unit.js
> +		await wrapper.vm.$nextTick(); // getSession
nextTick not necessary anymore. Removed.

2020-10-16 12:39 UTC, pkleybolte commented on src/components/organisms/Messenger/Messenger.vue
> +				options.roomId = matrixRoomId;
The user might not be in a specific room at all, but he can still use the overall chat room. That is the roomID == null case.

2020-10-16 12:48 UTC, pkleybolte commented on src/store/auth.js
> +		if (indexedDB) {
If  it is not defined then nothing is stored there by matrix and we don't need to remove anything.

I don't know if the data is stored anywhere else permanently if no indexedDB is present or if it is only held in a var until the tab is closed. I can't find any information about that.

2020-10-16 13:45 UTC, CeEv commented on src/components/organisms/Messenger/Messenger.unit.js
> +		process.env.FEATURE_MATRIX_MESSENGER_ENABLED = undefined;
Yes and no. This should simulate the stuff that is executed in client browser. For test it should work with the common but it simulate it in the wrong way. The right way is to change process env, and re-execute the env file.

2020-10-16 13:48 UTC, CeEv commented on src/components/organisms/Messenger/Messenger.vue
> +				options.roomId = matrixRoomId;
ok

2020-10-16 13:49 UTC, CeEv commented on src/store/messenger.unit.js
> +				expect(spyCommit.mock.calls).toHaveLength(1);
https://github.com/hpi-schul-cloud/schulcloud-server/pull/1843/files#diff-9e55f73328d4c9b8eb2e6aa86f713f6badfaa32b45c80524cf9fd0ea8c9a2824R54  this work well

2020-10-16 13:50 UTC, CeEv commented on src/store/messenger.unit.js
> +				const spyCommit = jest.fn();
ok

2020-10-16 14:56 UTC, pkleybolte commented on src/components/organisms/Messenger/Messenger.vue
> +			return process.env.FEATURE_MATRIX_MESSENGER_ENABLED === "true";
I moved to the messenger's store.
I guess it makes sense to put the feature flags into the store so the components don't need to worry where they come from.
We can decide late if we put the feature flags into the store module that relates to the feature or we could have one store module for all the flags.

2020-10-16 15:06 UTC, pkleybolte reviewed
The Changes I recommended are done

2020-10-16 15:23 UTC, CeEv commented on src/components/organisms/Messenger/Messenger.vue
> +			return process.env.FEATURE_MATRIX_MESSENGER_ENABLED === "true";
I like the solution with one store.

2020-10-16 15:24 UTC, CeEv commented on src/components/organisms/Messenger/Messenger.vue
> +			return process.env.FEATURE_MATRIX_MESSENGER_ENABLED === "true";
But at the moment nuxt.config.js exist.

2020-10-16 15:33 UTC, CeEv approved these changes

2020-10-16 16:15 UTC, merged