SC-4260 sampleRate added for sentry configuration
hpi-schul-cloud/nuxt-client pull request #1277
Opened 2020-08-24 08:41 UTC by tofixx

# Description

Adding `sampleRate`and fix `environment` in Sentry configuration. 

## Links to Tickets or other pull requests
https://ticketsystem.schul-cloud.org/browse/SC-4260

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-08-24 12:24 UTC, CeEv requested changes

2020-08-24 12:24 UTC, CeEv commented on sentry.config.js
> +	: 1.0;
I like if we have the default value 0.0.

2020-08-25 07:17 UTC, tofixx commented on sentry.config.js
> +	: 1.0;
How to set it in every live system and develop @CeEv ?

2020-08-27 13:37 UTC, CeEv requested changes

2020-08-27 13:37 UTC, CeEv commented on sentry.config.js
> +const environment = process.env.NODE_ENV || "development";
Please move all ENVs to single point and set defaults one time. Please keep in mind that we want to render it in browser in future.

2020-08-27 15:21 UTC, tofixx commented on sentry.config.js
> +const environment = process.env.NODE_ENV || "development";
This is not part of this story. I removed the default value and keep it in my mind. There are no other places setting the value but 50 calls to process.env in 21 files which should be cleaned up in a follow up.

2020-08-27 15:24 UTC, tofixx commented on sentry.config.js
> +	: 1.0;
@JanuszTaterka and @mcirikovic have been asked for input on this question and would support 1.0 as default.

2020-08-28 10:01 UTC, CeEv commented on sentry.config.js
> +	: 1.0;
We already discuss it over month and after the last crash off all instances because adding 1.0 as default @janrenz follow my proposal to set it in every instance to 0.1 and the default to 0.0. 
If you want to change it, please discuss it again with @janrenz.

2020-08-28 10:09 UTC, CeEv commented on sentry.config.js
> +const environment = process.env.NODE_ENV || "development";
Can you please create a ticket for it?

2020-08-28 10:20 UTC, janrenz commented on sentry.config.js
> +	: 1.0;
i like default off or 0, unless we have mode specific defaults.

2020-08-28 10:38 UTC, tofixx commented
I will close this pr, I thought we wanted to enable this setting as additional option.

2020-08-28 10:38 UTC, closed without merging