SC-5410 - language dropdown for user
hpi-schul-cloud/nuxt-client pull request #1295
Opened 2020-08-28 12:02 UTC by ABialoskorski

# Description

added dropdown in account page for selecting user language
## Links to Tickets or other pull requests

- https://ticketsystem.schul-cloud.org/browse/SC-5410

## Screenshots of UI changes

2020-08-31 08:10 UTC, DanielRieckhof requested changes

2020-08-31 08:10 UTC, DanielRieckhof commented on src/components/organisms/LanguageSwitcher.vue
> +			languages: ["Deutsch", "English"],
The current solution handles two languages. What is a third one is added? Should we already think about this?

2020-08-31 08:10 UTC, DanielRieckhof commented on src/components/organisms/LanguageSwitcher.vue
> +					v-for="lang in languages"
I think the component should work with language codes. Language names should be provided by translation files.

2020-08-31 08:13 UTC, ABialoskorski commented on src/components/organisms/LanguageSwitcher.vue
> +					v-for="lang in languages"
In my opinion they should not be provided by translation files, because even when language is english we always want to have 'deutsch' not 'german'

2020-08-31 08:15 UTC, ABialoskorski commented on src/components/organisms/LanguageSwitcher.vue
> +			languages: ["Deutsch", "English"],
de, en are only two languages which will be supported, at least in several months, nobody said anything about other languages

2020-08-31 11:34 UTC, ABialoskorski commented
@schul-cloud-bot update screenshots

2020-08-31 11:52 UTC, mwolowyk-cap commented on src/components/organisms/LanguageSwitcher.vue
> +			languages: ["Deutsch", "English"],
Please use objects instead of strings {"de": "Deutsch"}

2020-08-31 11:58 UTC, mwolowyk-cap requested changes
CHANGELOG is missing

2020-08-31 11:58 UTC, mwolowyk-cap commented on src/components/organisms/LanguageSwitcher.vue
> +			const language = lang.toLowerCase().substring(0, 2);
Please use key value instead

2020-08-31 11:58 UTC, mwolowyk-cap commented on src/pages/account/index.vue
> +			return this.currentUser.defaultLanguage === "de" ? "Deutsch" : "English";
also keys. What if there will be more languages?

2020-08-31 11:58 UTC, mwolowyk-cap commented on src/pages/account/locale/edit.vue
> +			return this.$user.defaultLanguage === "de" ? "Deutsch" : "English";
see above

2020-08-31 11:58 UTC, mwolowyk-cap commented on src/serverMiddleware/routes.js
> +	`^/account/?$`,
comment these lines before merge

2020-09-01 05:30 UTC, ABialoskorski commented on src/components/organisms/LanguageSwitcher.vue
> +			const language = lang.toLowerCase().substring(0, 2);
done

2020-09-01 05:30 UTC, ABialoskorski commented on src/pages/account/locale/edit.vue
> +			return this.$user.defaultLanguage === "de" ? "Deutsch" : "English";
done

2020-09-01 05:30 UTC, ABialoskorski commented on src/serverMiddleware/routes.js
> +	`^/account/?$`,
done

2020-09-01 07:27 UTC, mwolowyk-cap approved these changes

2020-09-01 07:37 UTC, merged