SC-6137 illustration 404 Page not found
hpi-schul-cloud/nuxt-client pull request #1325
Opened 2020-09-08 12:54 UTC by DevSchmidtchen

Ticket: https://ticketsystem.hpi-schul-cloud.org/browse/SC-6137

**Affected page:** Page not found (Error-Code 404)
<img width="707" alt="404 page" src="https://user-images.githubusercontent.com/16440155/92478747-e8de3100-f1e2-11ea-8f65-df7cce77f6a9.png">

2020-09-11 11:46 UTC, ABialoskorski submitted a review, later dismissed

2020-09-11 11:46 UTC, ABialoskorski commented on src/components/templates/PageNotFound.vue
> +	<svg
better idea is to load svg into assets/img directory and the use it with <img src="@assets/img/page-not-found.svg">

2020-09-11 11:48 UTC, DevSchmidtchen commented on src/components/templates/PageNotFound.vue
> +	<svg
Not in my case, because the styling based on the primary color (as you can see in the style tags) only works with inline SVGs.

2020-09-17 12:46 UTC, dominikbruechner requested changes
https://storybook.test.schul-cloud.org/?path=/story/4-base-ui-components-base-ui--base-image

BaseImage already supports fillColor, please adapt accordingly :)

2020-09-17 13:27 UTC, DevSchmidtchen commented
> https://storybook.test.schul-cloud.org/?path=/story/4-base-ui-components-base-ui--base-image
> 
> BaseImage already supports fillColor, please adapt accordingly :)

I changed it to BaseImage and it should now work exactly as it did before! :)

2020-09-17 13:32 UTC, dominikbruechner commented on src/components/templates/ErrorPage.vue
> +		<img v-else alt="PC-Reparatur" src="@assets/img/pc_repair.png" />
```suggestion
		<img v-else role="presentation src="@assets/img/pc_repair.png" />
```

2020-09-17 13:34 UTC, dominikbruechner commented on src/components/templates/ErrorPage.vue
> +		<img v-else role="presentation src="@assets/img/pc_repair.png" />
```suggestion
		<img v-else role="presentation" alt="" src="@assets/img/pc_repair.png" />
```

2020-09-17 13:34 UTC, dominikbruechner approved these changes

2020-10-05 13:08 UTC, DanielRieckhof approved these changes

2020-10-05 13:20 UTC, ABialoskorski approved these changes

2020-10-05 13:21 UTC, merged