SC-6021: fallback icons for EdgeHTML
hpi-schul-cloud/nuxt-client pull request #1332
Opened 2020-09-10 14:44 UTC by haniapalac

# Description

Due to the fact that there are problems with webpack rendering components for icon with vue-svg-loader library, we needed to find a workaround for the legacy Edge browser which was not rendering any material icons for the new admin tables. The fallback icons will be loaded from the assets directory when no material or font awesome icon is available.

## Links to Tickets or other pull requests

https://ticketsystem.hpi-schul-cloud.org/browse/SC-6021

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

"svg-inline-loader": "^0.8.2" is added to load svgs directly not through a component.

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-09-14 14:25 UTC, luizzaly submitted a review, later dismissed

2020-09-29 11:19 UTC, mwolowyk-cap approved these changes

2020-09-29 11:41 UTC, haniapalac commented
@schul-cloud-bot update screenshots

2020-09-30 08:49 UTC, luizzaly commented on src/components/base/BaseIcon.vue
> +					`error loading icon "${this.icon}" from "${this.source}". It might be not available or you are using the legacy Edge browser.`,
can you add an a11y key here please? :)

2020-09-30 08:50 UTC, luizzaly requested changes
Please add an i18 key for the error message!

2020-09-30 09:23 UTC, haniapalac commented on src/components/base/BaseIcon.vue
> +					`error loading icon "${this.icon}" from "${this.source}". It might be not available or you are using the legacy Edge browser.`,
done :-)

2020-09-30 14:53 UTC, luizzaly approved these changes

2020-10-01 06:55 UTC, merged