Feature/sc 6510 make use of merlin content
hpi-schul-cloud/nuxt-client pull request #1391
Opened 2020-09-29 11:53 UTC by Ojself

[SC-6510](https://ticketsystem.hpi-schul-cloud.org/browse/SC-6510)
[server pr](https://github.com/hpi-schul-cloud/schulcloud-server/pull/1770)

Created a service that generates a merlin url upon material request. This gets triggered when the material is searched and the user wants to go to the website of said content OR when the material is stored in a lesson and the lesson gets fetched to the client side.

This is done because the url expires after 2 hours and a new url needs to be created.

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-09-29 15:16 UTC, virgilchiriac approved these changes

2020-09-29 15:16 UTC, JenyMzo approved these changes

2020-10-05 13:06 UTC, ABialoskorski commented on src/components/organisms/LernstoreDetailView.vue
> +						Zum Inhalt
please use de.json and en.json here

2020-10-05 13:06 UTC, ABialoskorski commented on src/components/organisms/LernstoreDetailView.vue
> +						Zum Inhalt
here the same

2020-10-05 13:08 UTC, ABialoskorski approved these changes
pls use interpolation, but nevertheless nice code ;)

2020-10-07 08:11 UTC, Ojself commented on src/components/organisms/LernstoreDetailView.vue
> +						Zum Inhalt
Done

2020-10-07 08:11 UTC, Ojself commented on src/components/organisms/LernstoreDetailView.vue
> +						Zum Inhalt
Done

2020-10-07 08:26 UTC, ABialoskorski approved these changes

2020-10-07 11:45 UTC, JenyMzo submitted a review, later dismissed

2020-10-08 08:06 UTC, Ojself commented
@schul-cloud-bot update screenshots

2020-10-09 08:00 UTC, JenyMzo submitted a review, later dismissed

2020-10-09 08:04 UTC, virgilchiriac approved these changes

2020-10-09 08:18 UTC, ABialoskorski submitted a review, later dismissed

2020-10-09 08:27 UTC, Ojself commented
@schul-cloud-bot update screenshots

2020-10-09 08:32 UTC, Ojself commented
@schul-cloud-bot update screenshots

2020-10-09 08:45 UTC, virgilchiriac approved these changes

2020-10-09 08:59 UTC, JenyMzo approved these changes

2020-10-09 09:25 UTC, ABialoskorski approved these changes

2020-10-12 08:08 UTC, CordlessWool commented on src/components/organisms/LernstoreDetailView.vue
> +		},
what are doing this? async methods in view do not work with html selectors and co

2020-10-12 09:05 UTC, JenyMzo requested changes

2020-10-12 09:05 UTC, JenyMzo commented on src/components/organisms/LernstoreDetailView.vue
> +		},
As far as I know as long as you don't call the async method directly in the template (because the render is sync) it's fine, this is being called inside a @click so maybe what would be necessary here is adding a spinner (or some pre-loader) while the content get's loaded.

2020-10-12 10:35 UTC, CordlessWool approved these changes

2020-10-13 14:14 UTC, JenyMzo approved these changes

2020-10-13 14:18 UTC, JenyMzo commented
@schul-cloud-bot update screenshots

2020-10-14 08:06 UTC, CordlessWool approved these changes

2020-10-14 08:06 UTC, merged