Feature/sc 6278/validate create user forms
hpi-schul-cloud/nuxt-client pull request #1397
Opened 2020-10-01 11:51 UTC by pkleybolte

# Description

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6278

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-10-01 12:40 UTC, pkleybolte commented
@schul-cloud-bot update screenshots

2020-10-02 06:18 UTC, pkleybolte commented
@schul-cloud-bot update screenshots

2020-10-05 13:14 UTC, CordlessWool commented on src/components/atoms/ErrorMessage.vue
> +</style>
shouldn't it more general? So you can also do warnings, inforamtion and success?

2020-10-06 13:12 UTC, sarahschaefer requested changes
Hi, As it looks like teh checkbox is aligned to the top of the writing, I would also align the error icon to the top

2020-10-06 13:22 UTC, pkleybolte commented
@schul-cloud-bot update screenshots


> Hi, As it looks like teh checkbox is aligned to the top of the writing, I would also align the error icon to the top

No, the checkbox and its label are vertically centered as is the error icon

2020-10-06 13:28 UTC, pkleybolte commented on src/components/atoms/ErrorMessage.vue
> +</style>
Done

2020-10-06 13:40 UTC, sarahschaefer requested changes
Then please top-align both, or even better centre-align only to the first line (if possible :-))

There are some rules for the input field error handling (see attachment) 
<img width="554" alt="Screenshot 2020-10-06 at 15 37 33" src="https://user-images.githubusercontent.com/60662857/95209053-305bdb00-07ea-11eb-99c2-110f19a551cd.png">

Thank you!

2020-10-08 08:14 UTC, pkleybolte commented
@schul-cloud-bot update screenshots

2020-10-08 08:37 UTC, Metauriel approved these changes

2020-10-08 11:44 UTC, sarahschaefer requested changes
The Warning Icon is to far down

2020-10-08 12:36 UTC, sarahschaefer approved these changes

2020-10-08 12:45 UTC, CeEv approved these changes

2020-10-08 12:55 UTC, merged