SC-7198 - changes links in login page
hpi-schul-cloud/nuxt-client pull request #1416
Opened 2020-10-12 11:26 UTC by virgilchiriac

# Description

## Links to Tickets or other pull requests

- https://ticketsystem.schul-cloud.org/browse/SC-7198

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-10-12 11:29 UTC, janrenz requested changes

2020-10-12 11:29 UTC, janrenz commented on locale/de.json
> -	"pages.loginInstances.open_hpi_link": "https://open.schul-cloud.org/login",
this one stays the same

2020-10-12 11:32 UTC, janrenz submitted a review, later dismissed

2020-10-12 11:32 UTC, janrenz commented on locale/de.json
> -	"pages.loginInstances.open_hpi_link": "https://open.schul-cloud.org/login",
ok, in fact this one was changed , too

2020-10-12 11:32 UTC, virgilchiriac commented on locale/de.json
> -	"pages.loginInstances.open_hpi_link": "https://open.schul-cloud.org/login",
brandenburg stays. This one changed

2020-10-12 11:53 UTC, ABialoskorski approved these changes

2020-10-12 11:54 UTC, ABialoskorski commented
@schul-cloud-bot update screenshots

2020-10-12 15:19 UTC, CeEv approved these changes

2020-10-13 07:32 UTC, pkleybolte approved these changes

2020-10-13 10:54 UTC, merged