SC-7020: editor document item
hpi-schul-cloud/nuxt-client pull request #1423
Opened 2020-10-15 15:13 UTC by haniapalac

# Description

A new component that could be used to display an editor document, homework, file etc.

## Links to Tickets or other pull requests

https://ticketsystem.hpi-schul-cloud.org/browse/SC-7020

https://github.com/hpi-schul-cloud/styles/tree/feature/SC-7020 -> PR for the styles repo change

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

![image](https://user-images.githubusercontent.com/25037067/96149391-8d9e0d80-0f09-11eb-974f-5c7a443ba82a.png)

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-10-19 10:09 UTC, luizzaly reviewed
Can we please give the subtitle a margin-bottom: calc(0.5 * (var(--space-xs))); ? 👍

2020-10-20 14:35 UTC, haniapalac commented
@schul-cloud-bot update screenshots

2020-10-22 12:39 UTC, LukasSielski requested changes

2020-10-22 12:39 UTC, LukasSielski commented on src/components/molecules/TaskItem.vue
> +			<base-image
Does the scope of the ticket includes providing a proper color for icons? (course colors)? Becasue for now it is impossible to pass proper color to SVG component.

2020-10-23 13:28 UTC, LukasSielski requested changes

2020-10-23 13:28 UTC, LukasSielski commented on src/components/molecules/TaskItem.vue
> +}
In current implementation of the `base-image` component, we need to provide also the `width`. Otherwise the SVG will have `width: 0`. In storybook you are not displaying SVG strictly but with use of the `img` tag, that is why it has width in storybook. I have tested with strict SVG element and without setting the width explicitly - it has 0.
```suggestion
.image {
        width: calc(var(--text-md) + var(--text-lg));
	height: calc(var(--text-md) + var(--text-lg));
	object-fit: contain;
	margin-right: var(--space-sm);
	border-radius: var(--radius-sm);
}
```

2020-10-23 13:28 UTC, LukasSielski commented on src/components/molecules/TaskItem.vue
> +			/>
We can pass $attrs which will hold `imgSrc` and `fill` properties which will be passed to the parent component. This way we can write e.g. `<task-item fill="purple" imgSrc="<some_svg_path>"></task-item>` to assing an SVG and a color to the SVG component.

```suggestion
			<base-image
				v-if="$attrs.imgSrc"
				v-bind="$attrs"
				class="image"
				role="presentation"
			/>
```

2020-10-23 13:28 UTC, LukasSielski commented on src/components/molecules/TaskItem.vue
> +		image: {
I'd rather remove image property as it is only passed to the next component.

2020-10-26 14:19 UTC, haniapalac commented on src/components/molecules/TaskItem.vue
> +			/>
Done :-)

2020-10-26 14:19 UTC, haniapalac commented on src/components/molecules/TaskItem.vue
> +		image: {
Done :-)

2020-10-26 14:20 UTC, haniapalac commented on src/components/molecules/TaskItem.vue
> +}
Done :-)

2020-10-26 14:56 UTC, haniapalac commented
@schul-cloud-bot update screenshots

2020-10-27 09:07 UTC, LukasSielski submitted a review, later dismissed

2020-10-28 12:25 UTC, luizzaly approved these changes

2020-10-29 09:04 UTC, merged