Feature/SC-2710 - Custom Timezone
hpi-schul-cloud/nuxt-client pull request #1442
Opened 2020-10-21 11:30 UTC by DanielRieckhof

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-10-21 12:11 UTC, mwolowyk-cap requested changes

2020-10-21 12:11 UTC, mwolowyk-cap commented on src/pages/administration/students/consent.vue
> +							dayjs(slotProps.data, 'DD.MM.YYYY').format($t('format.date'))
it seams to be an error here: you replaced YYYY-MM-DD with format.date.
DD.MM.YYYY should be replaced with format.date

2020-10-21 12:11 UTC, mwolowyk-cap commented on src/pages/administration/students/consent.vue
> +						{{ dayjs(slotProps.data, "DD.MM.YYYY").format($t("format.date")) }}
Why you don't replace the second "DD.MM.YYYY" with the format.date?

2020-10-21 12:15 UTC, DanielRieckhof commented on src/pages/administration/students/consent.vue
> +						{{ dayjs(slotProps.data, "DD.MM.YYYY").format($t("format.date")) }}
I have to check, how the date is handled at all. Seems that it as been converted to german date format in between.

2020-10-26 14:45 UTC, ABialoskorski commented on src/plugins/datetime.js
> +	return result;
```
	`return dayjs.tz();`
```

2020-10-26 14:47 UTC, ABialoskorski commented on src/plugins/datetime.js
> +import "dayjs/locale/en";
`import "dayjs/locale/de";
import "dayjs/locale/en";`
are these 2 needed?

2020-10-26 14:48 UTC, ABialoskorski commented
nice plugin ;)

2020-10-26 14:49 UTC, ABialoskorski commented
@schul-cloud-bot update screenshots

2020-10-26 14:50 UTC, ABialoskorski commented on src/plugins/datetime.js
> +	console.log(
console.logs are nice but then test for storybook is failing 
![image](https://user-images.githubusercontent.com/40116220/97187702-feafb180-17a2-11eb-9239-ce64dafa48fb.png)

2020-10-26 15:49 UTC, ABialoskorski commented
@schul-cloud-bot update screenshots

2020-10-27 05:10 UTC, DanielRieckhof commented on src/plugins/datetime.js
> +	console.log(
We can also remove this debugging. I think it's only needed for debugging

2020-10-27 05:34 UTC, DanielRieckhof commented on src/plugins/datetime.js
> +import "dayjs/locale/en";
`import "dayjs/locale/en";`
seems to be unneeded

2020-10-27 06:40 UTC, ABialoskorski submitted a review, later dismissed

2020-10-27 09:00 UTC, ABialoskorski requested changes

2020-10-27 09:13 UTC, ABialoskorski commented on tests/plugins/datetime.unit.js
> +		const dateUTC = fromUTC(dateString).utc().format("DD.MM.YYYY");
done ;)

2020-10-27 09:29 UTC, ABialoskorski approved these changes

2020-10-27 12:53 UTC, pkleybolte commented on src/pages/administration/students/consent.vue
> +						console.log(
Looks like this console.log was for debugging and isn't needed in production.

2020-10-27 12:53 UTC, pkleybolte commented on src/plugins/datetime.js
> +const setDefaultFormats = (app) => {
No Unit Test yet

2020-10-27 12:53 UTC, pkleybolte commented on src/plugins/datetime.js
> +const initDefaultTimezone = (app, store) => {
No Unit Test yet

2020-10-27 12:53 UTC, pkleybolte commented on src/plugins/datetime.js
> +export default ({ app, store }) => {
No Unit Test yet. This would probably be the way to test initDefaultTimezone and setDefaultFormats, too.

2020-10-27 12:53 UTC, pkleybolte commented on tests/plugins/datetime.unit.js
> +	it("printDateFromDeUTC", () => {
The `printDateFromDeUTC(null)` and `printDateFromDeUTC("")` cases could easily be tested, too.

2020-10-27 12:53 UTC, pkleybolte commented on tests/plugins/datetime.unit.js
> +	it("inputDateFromDeUTC", () => {
The `inputDateFromDeUTC(null)` and `inputDateFromDeUTC("")`  cases could easily be tested, too.

2020-10-27 12:53 UTC, pkleybolte commented on tests/plugins/datetime.unit.js
> +	it("fromInputDateTime", () => {
`fromInputDateTime(dateFormat);` can be tested, too.

2020-10-27 13:01 UTC, ABialoskorski commented on src/pages/administration/students/consent.vue
> +						console.log(
done ;)

2020-10-27 14:22 UTC, ABialoskorski commented on tests/plugins/datetime.unit.js
> +	it("printDateFromDeUTC", () => {
done ;)

2020-10-28 08:29 UTC, pkleybolte approved these changes

2020-10-28 09:06 UTC, pkleybolte submitted a review, later dismissed

2020-10-28 09:07 UTC, mwolowyk-cap requested changes

2020-10-28 09:07 UTC, mwolowyk-cap commented on src/plugins/datetime.js
> +export const printDate = (date) => {
Could we have the same naming convention like in the old client?

2020-10-28 09:07 UTC, mwolowyk-cap commented on src/plugins/datetime.js
> +export const inputRangeDate = (offset = 0, offsetBase = "y") => {
for me the function name is difficult to understand

2020-10-28 09:07 UTC, mwolowyk-cap commented on src/pages/administration/datasources/index.vue
> +									relativeDate: fromNow(fromUTC(element.lastRun)),
why should we put two functions here and not wrap it in the library?

2020-10-28 09:07 UTC, mwolowyk-cap commented on src/plugins/datetime.js
> +export const fromUTC = (date) => {
I don't think that we should expose this function. This function is never used in pure format. It is always wrapped by another function like printDate or fromNow.

2020-10-28 09:07 UTC, mwolowyk-cap commented on src/plugins/datetime.js
> +export const printDateFromDeUTC = (date) => {
Moreover the function name tells a lot of internal implementation details. We need to have something more general.

2020-10-28 09:09 UTC, mwolowyk-cap reviewed
Please see previous comments

2020-10-28 09:10 UTC, mwolowyk-cap submitted a review, later dismissed

2020-10-28 09:11 UTC, mwolowyk-cap reviewed
see above

2020-10-28 09:14 UTC, mwolowyk-cap reviewed
Let's implement it the same way like in the old client. So it will be easier to use.

2020-10-28 09:22 UTC, ABialoskorski approved these changes

2020-10-30 08:41 UTC, ABialoskorski commented
@schul-cloud-bot update screenshots

2020-10-30 13:30 UTC, ABialoskorski approved these changes

2020-11-02 07:35 UTC, merged