SC-6293 - restricts Lern-Store with permission
hpi-schul-cloud/nuxt-client pull request #1449
Opened 2020-10-22 07:15 UTC by virgilchiriac

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-10-22 10:40 UTC, Ojself approved these changes

2020-10-22 11:56 UTC, ABialoskorski approved these changes

2020-10-22 12:14 UTC, JenyMzo approved these changes

2020-10-22 12:30 UTC, CordlessWool requested changes

2020-10-22 12:30 UTC, CordlessWool commented on src/store/auth.js
> +		);
use permissions/user route here

2020-10-22 15:09 UTC, virgilchiriac commented on src/store/auth.js
> +		);
The permissions/user route does not take out the LERNSTORE_VIEW permission from the role, when school has 
```
"permissions": {
        "student": {
            "LERNSTORE_VIEW": false
        }
```
Moreover, we use the roles/user route in client [here](https://github.com/hpi-schul-cloud/schulcloud-client/blob/develop/helpers/authentication.js#L118)

2020-10-22 17:37 UTC, virgilchiriac commented on src/store/auth.js
> +		);
As this behaviour is unclear if it is on purpose, I reported it as a possible bug, so that it can be solved separately and does not block this feature.
[ARC-125](https://ticketsystem.hpi-schul-cloud.org/browse/ARC-125)

2020-10-23 11:43 UTC, merged

2020-10-26 08:15 UTC, CordlessWool commented on src/store/auth.js
> +		);
Should be not so complicate to solve this bug in the backend. There is nothing unclear, just solve the bug in the backend and use the correct route!