Sc 7461 tabbar shadow underline
hpi-schul-cloud/nuxt-client pull request #1470
Opened 2020-10-27 15:22 UTC by xavero-evandro

# Description
- The shadow underneath the tabbar is missing. there is a 3dp shadow underneath.
 - Make sure this shadow goes right to the end of the screen
## Links to Tickets or other pull requests

https://ticketsystem.hpi-schul-cloud.org/browse/SC-7461

## Changes

Added a underline shadow to the whole tabbar

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

![5-molecules-tabs-tabs_1-snap](https://user-images.githubusercontent.com/11357308/97322891-89121700-1870-11eb-97b0-05322bef9481.png)

## Approval for review

- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-10-27 15:22 UTC, xavero-evandro commented
@schul-cloud-bot update screenshots

2020-10-28 07:42 UTC, haniapalac commented on .dccache
> +[{"/Users/xavero/Projects/nuxt-client/src/components/organisms/Tabs/Tabs.vue":"1"},[3651,1603811580967.4438,"2"],"bf8c0d49e61288037feac7e6a67c088e9c360dd580f8c9f194c0c61018df39d5"]
What is this file? Or can we remove it?

2020-10-28 07:42 UTC, haniapalac commented on src/components/organisms/Tabs/Tabs.vue
> +	<div class="test">
Why is the class named test? Or can the name be more connected to what the component does/this wrapper is about?

2020-10-28 07:42 UTC, haniapalac commented on src/components/organisms/Tabs/Tabs.vue
> +	// border-bottom: 2px solid var(--color-gray-light);
I guess we can remove this line altogether.

2020-10-28 07:42 UTC, haniapalac commented on src/components/organisms/Tabs/Tabs.vue
> +		height: 2px;
Maybe this could be changed to relative units?

2020-10-28 07:42 UTC, haniapalac commented on src/components/organisms/Tabs/Tabs.vue
>  		max-width: 450px;
Maybe we can have relative units here too?

2020-10-28 07:42 UTC, haniapalac commented on src/components/organisms/Tabs/Tabs.vue
>  		max-width: 1023px;
Maybe relative units here too?

2020-10-28 11:57 UTC, janrenz submitted a review, later dismissed
the dccache file still seems present in the PR

2020-11-04 14:04 UTC, xavero-evandro commented
@schul-cloud-bot update screenshots

2020-11-04 15:16 UTC, haniapalac requested changes

2020-11-04 15:16 UTC, haniapalac commented on src/components/organisms/Tabs/Tabs.vue
> +	max-width: 450px;
For now you can use local variables if we can't update the styles library. Shouldn't we also use rescalable units like rems?

2020-11-04 15:16 UTC, haniapalac commented on src/components/organisms/Tabs/Tabs.vue
>  		max-width: 1023px;
Here as well we should use rescaleable units.

2020-11-04 15:16 UTC, haniapalac commented on src/components/organisms/Tabs/Tabs.vue
> +	max-width: 450px;
use rems or vw etc.

2020-11-05 10:22 UTC, haniapalac submitted a review, later dismissed

2020-11-06 08:34 UTC, xavero-evandro commented
@schul-cloud-bot update screenshots

2020-11-07 22:22 UTC, xavero-evandro commented
@schul-cloud-bot update screenshots

2020-11-10 10:58 UTC, haniapalac submitted a review, later dismissed

2020-11-12 13:27 UTC, xavero-evandro commented
@schul-could-bot update screenshots

2020-11-12 13:54 UTC, haniapalac approved these changes

2020-11-12 14:04 UTC, xavero-evandro commented
@schul-cloud-bot update screenshots

2020-11-12 14:20 UTC, merged