Feature/sc 7108 create a component header
hpi-schul-cloud/nuxt-client pull request #1474
Opened 2020-10-28 13:59 UTC by LukasSielski

# Description
Header for the course details page.

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7108

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-10-28 14:04 UTC, LukasSielski commented
@schul-cloud-bot update screenshots

2020-10-28 14:19 UTC, LukasSielski commented
@schul-cloud-bot update screenshots

2020-10-28 15:28 UTC, haniapalac requested changes

2020-10-28 15:51 UTC, pkleybolte requested changes

2020-10-28 15:51 UTC, pkleybolte commented on src/components/base/BaseHeader.vue
> +			return this.$attrs.hasOwnProperty("actions");
I would prefer to add `actions` to `props`. It is way easier to see what attribute this component needs that way.

2020-10-28 15:51 UTC, pkleybolte commented on src/components/base/BaseHeader.vue
> +					<context-menu :show.sync="active" v-bind="$attrs" v-on="$listeners" />
`v-bind="$attrs"` could be written as `:actions="actions"`, right?
Unfortunately I don't see a nicer solution for `v-on="$listeners"` though.

2020-10-28 15:51 UTC, pkleybolte commented on src/components/molecules/CourseHeader.unit.js
> +	it(...isValidComponent(CourseHeader));
Please add tests:
it("should show nextLessonDate",...)
it("renders a link with correct url",...)

2020-10-29 07:58 UTC, ABialoskorski commented on src/components/base/BaseHeader.vue
> +					<base-button design="text icon" @click="triggerContextMenu">
I would do @click="this.active = !this.active" so You don't need method for that

2020-10-29 10:11 UTC, LukasSielski commented
@schul-cloud-bot update screenshots

2020-10-29 10:28 UTC, haniapalac approved these changes

2020-10-29 10:53 UTC, LukasSielski commented
Please don't merge it yet as some UX addjustments needs to be done.

2020-10-29 11:09 UTC, LukasSielski commented
@schul-cloud-bot update screenshots

2020-10-29 11:42 UTC, pkleybolte approved these changes

2020-10-29 11:45 UTC, haniapalac approved these changes

2020-10-29 11:48 UTC, merged