Feature/sc 7027 create a page course including the business logic
hpi-schul-cloud/nuxt-client pull request #1479
Opened 2020-11-02 08:11 UTC by LukasSielski

# Description
New course page for Kursinhalte initiative. There are still some things which needs to be discussed with UX, but review can be started.

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7027

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-11-02 10:13 UTC, haniapalac commented on src/layouts/loggedInFullNoPadding.vue
> +		isInline() {
what is the isInline() responsible for?

2020-11-02 10:13 UTC, haniapalac commented on src/pages/courses/_id/index.vue
> +		<base-grid column-width="4rem" class="no-margin">
will we have the column-width always hardcoded?

2020-11-02 10:13 UTC, haniapalac commented on src/pages/courses/_id/index.vue
> +									v-html="$t('pages.courses._id.empty_course_description')"
Why do you load the text via v-html?

2020-11-02 10:13 UTC, haniapalac commented on src/pages/courses/_id/index.vue
> +				status: lesson.hidden ? "Entwurf" : "",
Maybe we could have an i18n key here?

2020-11-02 10:13 UTC, haniapalac commented on src/pages/courses/_id/index.vue
> +			const prefix = `Aufgabe bis ${dueDate.format("DD/MM/YYYY")}`;
Maybe an i18n key here too?

2020-11-02 10:13 UTC, haniapalac commented on src/pages/courses/_id/index.vue
> +				return `${prefix} - endet in ${remainingHours} ${
same here

2020-11-02 10:13 UTC, haniapalac commented on src/pages/courses/_id/index.vue
> +					remainingHours === 1 ? "Stunde" : "Stunden"
and here

2020-11-02 10:13 UTC, haniapalac commented on src/pages/courses/_id/index.vue
> +		prepareSubtitleForHomework(homework) {
I'm not sure about the naming of the method here tbh.

2020-11-02 10:13 UTC, haniapalac commented on src/pages/courses/_id/index.vue
> +		adaptHomework(homework) {
Not sure if the naming 'adapt' is very clear too me tbh.

2020-11-02 10:13 UTC, haniapalac commented on src/pages/courses/_id/index.vue
> +				if (moment().day() > weekDayIdentifier) weekDayIdentifier += 7;
What does this if statement do?

2020-11-02 10:20 UTC, LukasSielski commented on locale/de.json
> +	"pages.courses._id.educational_content": "Lerninhalte",
I saw that in other places in this file it is used, so I asssume that it is some kind of guideline

2020-11-02 10:21 UTC, LukasSielski commented on src/layouts/loggedInFullNoPadding.vue
> +		isInline() {
@haniapalac 
To be honest i have no idea, this files is a copy of loggedInFull which has a padding which we don't want on the course details page

2020-11-02 10:23 UTC, LukasSielski commented on src/pages/courses/_id/index.vue
> +		<base-grid column-width="4rem" class="no-margin">
@haniapalac 
As discussed with @luizzaly this value provides necessary amount of columns (present in sketch) for desktop and mobile devices. Currently there is no way to make it in another way.

2020-11-02 10:25 UTC, LukasSielski commented on src/pages/courses/_id/index.vue
> +				if (moment().day() > weekDayIdentifier) weekDayIdentifier += 7;
@haniapalac The functionality of this metod is a copy paste from our legacy client, which determines next date of recurring events each week. It says that if a date of lesson is alredy behind of current week day, transform it to next week date as it is recurring event.

2020-11-02 10:30 UTC, LukasSielski commented on src/components/base/BaseButton.scss
> +		--button-background: #ea8500; // TODO: add this to styles repository after deployment is fixed
To be honest I forgot to delete this styling as floating action button is out of scope of this ticket and whole epic in general

2020-11-02 10:31 UTC, LukasSielski commented on src/pages/courses/_id/index.vue
> +									v-html="$t('pages.courses._id.empty_course_description')"
@haniapalac 
Just saw such inserting in another place. I will do it "normal" :)

2020-11-02 10:39 UTC, haniapalac commented on src/pages/courses/_id/index.vue
> +				if (moment().day() > weekDayIdentifier) weekDayIdentifier += 7;
ah, that makes sense now, thanks for explaining!

2020-11-02 10:59 UTC, luizzaly commented
Can you please share screenshots as well?

2020-11-02 11:42 UTC, JanuszTaterka requested changes
I agree with Hanna's comment. I don't have any further remarks.

2020-11-02 15:40 UTC, haniapalac commented on locale/en.json
> +	"pages.courses._id.educational_content": "Educational content",
what about the rest of the translations to English?

2020-11-03 08:00 UTC, LukasSielski commented on locale/en.json
> +	"pages.courses._id.educational_content": "Educational content",
@haniapalac 
It is a good questuion, this one was added by me, but then i realized that maybe this is something which maybe UX should deliver. I will consult this with UX member.

2020-11-03 10:49 UTC, LukasSielski commented on locale/en.json
> +	"pages.courses._id.educational_content": "Educational content",
@haniapalac 
I have contacted @konstanti-sc , and the decision is that EN translations can be provided at the end of the initiative, so I will delete all eng translations which I have added by my own.

2020-11-03 11:01 UTC, haniapalac commented on src/layouts/loggedInFullNoPadding.vue
> +		isInline() {
Okay, I talked to Artur Bialoskorski and apparently this is needed when lernstore is accessed via courses.

2020-11-03 11:11 UTC, ABialoskorski commented on src/pages/courses/_id/index.vue
> +				if (moment().day() > weekDayIdentifier) weekDayIdentifier += 7;
please take a look on dayjs, we have changed right now moment.js in old client and the all logic of that because we jave added timezones

2020-11-04 09:31 UTC, haniapalac approved these changes

2020-11-04 11:56 UTC, LukasSielski commented
@schul-cloud-bot update screenshots

2020-11-04 13:03 UTC, mwolowyk-cap commented on src/pages/courses/_id/index.vue
> +				if (moment().day() > weekDayIdentifier) weekDayIdentifier += 7;
@LukasSielski we've introduced a wrapper class `daytime.js` for daysjs package which should handle all daytime functionality. Please use the existing functions or extend it with the functionality you need. The idea is that the internal framework is hidden in the wrapper and can be replaced if needed. Please also look here: https://docs.hpi-schul-cloud.org/display/TSC/Server+Code+Conventions

2020-11-06 08:18 UTC, mwolowyk-cap commented on src/layouts/loggedInFullNoPadding.vue
> +		isInline() {
It checks whether url query has` inline=true.`
This parameter is used to display the page without sidebar and topbar. It is used for Lernstore.

2020-11-06 08:40 UTC, mwolowyk-cap requested changes

2020-11-06 08:40 UTC, mwolowyk-cap commented on src/pages/courses/_id/index.vue
> +			)} ${dueDate.format("DD/MM/YYYY")}`;
why the format here is hardcoded?

2020-11-06 08:40 UTC, mwolowyk-cap commented on src/pages/courses/_id/index.vue
> +			const now = moment();
Don't use moment at all please

2020-11-06 08:40 UTC, mwolowyk-cap commented on src/pages/courses/_id/index.vue
> +import moment from "moment";
Remove moment completely from here. Use datetime functions

2020-11-12 13:52 UTC, haniapalac commented on src/pages/courses/_id/index.vue
> +			// const now = moment();
Maybe just remove the commented out lines

2020-11-13 08:05 UTC, haniapalac approved these changes

2020-11-13 08:44 UTC, JanuszTaterka approved these changes

2020-11-13 09:01 UTC, mwolowyk-cap submitted a review, later dismissed

2020-11-13 11:52 UTC, haniapalac approved these changes

2020-11-13 12:27 UTC, mwolowyk-cap approved these changes

2020-11-16 08:25 UTC, haniapalac commented
@schul-cloud-bot update screenshots

2020-11-16 09:35 UTC, haniapalac submitted a review, later dismissed

2020-11-16 11:06 UTC, haniapalac approved these changes

2020-11-16 12:10 UTC, merged