Feature/SC-7488/implement roles section
hpi-schul-cloud/nuxt-client pull request #1511
Opened 2020-11-09 14:20 UTC by murat-merdoglu-hpi

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-11-09 14:47 UTC, CordlessWool commented on src/components/organisms/Ldap/Roles.vue
> +import BaseInput from "@components/base/BaseInput/BaseInput.vue";
Base Components should not be imported, they are avalible by default (HINT for future: this means also creating a new base component should be only done if a component is/will be used very often)

2020-11-09 14:49 UTC, CordlessWool commented on src/components/organisms/Ldap/Roles.vue
> +import { required } from "vuelidate/lib/validators";
Required should be done by the input component itself. Please take a look in the input component, how it works or ask @pkleybolte

2020-11-09 14:50 UTC, CordlessWool commented on src/components/organisms/Ldap/Roles.vue
> +					),
Why define it here instead of directly use the i18n string int the html part?

2020-11-09 14:51 UTC, CordlessWool commented on src/components/organisms/Ldap/Roles.vue
> +			validationMessages: [{ key: "required", message: "not be blank" }],
Messages should be everytime i18n but also here the input component should support this

2020-11-09 14:52 UTC, CordlessWool commented on src/components/organisms/Ldap/Roles.vue
> +		},
same as above with the input validation

2020-11-09 14:52 UTC, CordlessWool commented on src/components/organisms/Ldap/Roles.vue
> +	},
why this renaming here?

2020-11-09 14:53 UTC, CordlessWool commented on src/components/organisms/Ldap/Roles.vue
> +	},
also if data will chnaged this will not tiggered again

2020-11-10 09:03 UTC, murat-merdoglu-hpi commented on src/components/organisms/Ldap/Roles.vue
> +import BaseInput from "@components/base/BaseInput/BaseInput.vue";
removed

2020-11-10 09:06 UTC, murat-merdoglu-hpi commented on src/components/organisms/Ldap/Roles.vue
> +import { required } from "vuelidate/lib/validators";
It was the only test of validation. Because it is out of this ticket's scope, it is removed.

2020-11-10 09:07 UTC, murat-merdoglu-hpi commented on src/components/organisms/Ldap/Roles.vue
> +					),
The i18n strings were defined directly.

2020-11-10 09:08 UTC, murat-merdoglu-hpi commented on src/components/organisms/Ldap/Roles.vue
> +	},
It is removed.

2020-11-10 09:09 UTC, murat-merdoglu-hpi commented on src/components/organisms/Ldap/Roles.vue
> +			validationMessages: [{ key: "required", message: "not be blank" }],
Validations removed for this ticket. It is out of scope.

2020-11-10 09:10 UTC, murat-merdoglu-hpi commented on src/components/organisms/Ldap/Roles.vue
> +		},
validations removed for this ticket. it is out of scope

2020-11-10 10:30 UTC, murat-merdoglu-hpi commented
@schul-cloud-bot update screenshots

2020-11-10 11:49 UTC, CordlessWool commented on src/pages/administration/ldap/ldap-config.vue
> +import Roles from "@components/organisms/Ldap/Roles.vue";
If only use roles, I would firstly think about our roles, please more spezific

2020-11-10 14:32 UTC, murat-merdoglu-hpi commented on src/pages/administration/ldap/ldap-config.vue
> +import Roles from "@components/organisms/Ldap/Roles.vue";
Component name is changed.

2020-11-10 14:33 UTC, murat-merdoglu-hpi commented
@schul-cloud-bot update screenshots

2020-11-10 15:16 UTC, CordlessWool requested changes
I do not want to remove the checks like required in total, but should and could be handled by the input field. Do changes to the input field trigger changes to data in main section?

2020-11-10 15:16 UTC, CordlessWool commented on src/pages/administration/ldap/ldap-config.vue
> +			fetchedData: {
at least it is not only fetched data, could also be changed data: use something like configData

2020-11-10 15:16 UTC, CordlessWool commented on src/pages/administration/ldap/ldap-config.vue
> +			fetchedData: {
keep empty for pr, or set to values to the values we want ot have at the end

2020-11-10 15:16 UTC, CordlessWool commented on src/pages/administration/ldap/ldap-config.vue
> +	layout: "loggedInFull",
what is layout?

2020-11-10 17:59 UTC, pkleybolte commented on src/components/organisms/Ldap/RolesSection.vue
> +			v-model="data.member"
`data` is a prop. You should never mutate a prop. It is a bad practice in Vue. If you had made `member` a prop, Vue would print a warning in the console.

To avoid this you need to emit events whenever one of the fields changes. Basically you need to build it in the same pattern as it is done in<base-input> and described [here](https://www.digitalocean.com/community/tutorials/vuejs-add-v-model-support) in more detail.

Splitting forms is always a big hassle. I would not create the sub component if I do not have to. 
So far the ldap-config page is only 60 lines. I would keep the whole form in there. 
The two components are coupled anyways. To understand the structure of `data` I have to understand the whole RolesSection component. So it doesn't really hide any complexity, but adds to it.

2020-11-10 17:59 UTC, pkleybolte commented on src/pages/administration/ldap/ldap-config.vue
> +export default {
Recently we created the first example of unit tests for a page. Please add some test.
You can refer to `src\pages\administration\teachers\new.unit.js` to find an example.

2020-11-10 18:02 UTC, pkleybolte commented on src/components/organisms/Ldap/RolesSection.vue
> +			v-model="data.member"
I just found the other PR :-) The ldap-config page is getting big.
Unfortunately that doesn't change the fact, that you should never mutate props.

2020-11-11 08:27 UTC, murat-merdoglu-hpi commented
@schul-cloud-bot update screenshots

2020-11-11 08:27 UTC, murat-merdoglu-hpi commented on src/pages/administration/ldap/ldap-config.vue
> +			fetchedData: {
Corrected

2020-11-11 08:31 UTC, murat-merdoglu-hpi commented on src/pages/administration/ldap/ldap-config.vue
> +	layout: "loggedInFull",
It was to makes the layout 100 percent. And corrected.

2020-11-11 08:58 UTC, murat-merdoglu-hpi commented on src/components/organisms/Ldap/RolesSection.vue
> +			v-model="data.member"
The pattern is applied.

2020-11-11 22:11 UTC, murat-merdoglu-hpi commented on src/pages/administration/ldap/ldap-config.vue
> +export default {
Added component tests.

2020-11-12 08:09 UTC, CordlessWool commented on src/components/organisms/Ldap/LdapRolesSection.vue
> +			class="ldapDataUser"
Do you need a class for each input field?

2020-11-12 08:10 UTC, CordlessWool requested changes

2020-11-12 08:10 UTC, CordlessWool commented on src/pages/administration/ldap/ldap-config.vue
> +				user: "cn=ehemalige,ou=rolle",
do not forget to keep it empty before merging (you do not have to push or commit it)

2020-11-12 10:46 UTC, murat-merdoglu-hpi commented on src/pages/administration/ldap/ldap-config.vue
> +				user: "cn=ehemalige,ou=rolle",
corrected

2020-11-12 11:05 UTC, pkleybolte approved these changes

2020-11-12 11:05 UTC, pkleybolte commented on src/components/organisms/Ldap/LdapRolesSection.unit.js
> +		);
You are testing the static part of the template. More important would be the dynamic aspects
"should have the correct default value for member/student/teacher/admin/user"
"member/student/teacher/admin/user should emit an event when changed"

2020-11-12 12:28 UTC, monaweitzenberg reviewed
thx :) looks well

2020-11-12 15:03 UTC, murat-merdoglu-hpi commented
@schul-cloud-bot update screenshots

2020-11-12 16:10 UTC, CordlessWool approved these changes

2020-11-12 21:29 UTC, murat-merdoglu-hpi commented
@schul-cloud-bot update screenshots

2020-11-12 22:10 UTC, merged