Feature/sc 7489 input validation
hpi-schul-cloud/nuxt-client pull request #1518
Opened 2020-11-11 15:21 UTC by j-jmnz

# Description
Input validation for LDAP section

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7489

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-11-12 11:17 UTC, pkleybolte requested changes
You added validation, but didn't unit test it.

2020-11-12 11:17 UTC, pkleybolte commented on src/components/organisms/Ldap/LdapRolesSection.vue
> +					message: "Please match LDAP path format",
Please use $t for this label for the translations.

2020-11-12 11:17 UTC, pkleybolte commented on src/utils/ldapValidationRegex.js
> +export const ldapPathValidationRegex = helpers.regex(
Do you expect this to be used anywhere except for LdapRolesSection.vue? Otherwise I would prefer to define it in LdapRolesSection.vue before `export default`.
Just a suggestion, not must.

2020-11-12 11:44 UTC, j-jmnz commented on src/utils/ldapValidationRegex.js
> +export const ldapPathValidationRegex = helpers.regex(
Yes, it will be used in 3 other components, thanks for the suggestion :)

2020-11-12 11:44 UTC, j-jmnz commented on src/components/organisms/Ldap/LdapRolesSection.vue
> +					message: "Please match LDAP path format",
These are just placeholders :) they'll be properly replaced before merging it

2020-11-16 12:31 UTC, Parnswir commented on src/components/organisms/Ldap/LdapClassesSection.unit.js
> +		classPfad: "class=path",
Why does it have an Engrisch name?

2020-11-16 12:31 UTC, Parnswir commented on src/components/organisms/Ldap/LdapClassesSection.unit.js
> +		// temporary fix for validation model not updating
temporary fix == it will stay there for a while. What's the problem?

2020-11-16 12:31 UTC, Parnswir commented on src/components/organisms/Ldap/LdapClassesSection.vue
> +			:label="$t('pages.administration.ldap.classes.pfad.title')"
again, why mix English and German?

2020-11-16 12:31 UTC, Parnswir commented on src/utils/ldapValidationRegex.js
> +export const ldapPathValidationRegex = helpers.regex(
Maybe a comment would help understanding what this beast will accept

2020-11-16 12:32 UTC, Parnswir commented
The validations themselves look good to me though!

2020-11-16 12:38 UTC, j-jmnz commented on src/components/organisms/Ldap/LdapClassesSection.unit.js
> +		classPfad: "class=path",
Namings were determined on SC-7488, if they are wrong please suggest the correct ones and I'll add them to this PR :)

2020-11-16 12:39 UTC, j-jmnz commented on src/components/organisms/Ldap/LdapClassesSection.unit.js
> +		// temporary fix for validation model not updating
Already talked with @pkleybolte about this issue, it's just happening in the unit testing, he'll look into this

2020-11-16 12:39 UTC, j-jmnz commented on src/components/organisms/Ldap/LdapClassesSection.vue
> +			:label="$t('pages.administration.ldap.classes.pfad.title')"
Namings were determined on SC-7488, if they are wrong please suggest the correct ones and I'll add them to this PR :)

2020-11-16 21:06 UTC, pkleybolte commented on src/components/organisms/Ldap/LdapClassesSection.unit.js
> +	it("invalid validation is true when any of the input values are invalid", async () => {
I change this unit test as an example for other inputs.
To update the model it is not enough to set a value in the input, but you also need to handle the change in the parent and change in the props hence the `listeners`.

In general I prefer to test from UI perspective instead of the model.
It is better to check if the error is displayed than checking if the model is invalid.

You can even add a test to ensure, that even if you start with invalid props there is no error displayed, but after the user entered and left the field (blur event) the error should be displayed.

2020-11-16 21:06 UTC, pkleybolte commented on src/components/organisms/Ldap/LdapClassesSection.unit.js
> +	it("invalid validation is true when any of the input values are invalid", async () => {
I wanted to check the content of the error message too, but so far I don't know how the unit tests determine the locale. If it depends on the OS language, it could run successfully on my machine, but fail in Travis.

2020-11-16 21:06 UTC, pkleybolte commented on src/components/organisms/Ldap/LdapClassesSection.vue
> +			:label="$t('pages.administration.ldap.classes.pfad.title')"
Pfad=path

2020-11-16 21:06 UTC, pkleybolte commented on src/components/organisms/Ldap/LdapConnectionSection.unit.js
> +	it("invalid validation is false when valid values are sent thorugh props", async () => {
Copy paste error everywhere
It is "through" not "thorugh"

2020-11-17 16:03 UTC, pkleybolte approved these changes

2020-11-17 16:29 UTC, merged