SC-7543 - ldap submit data page
hpi-schul-cloud/nuxt-client pull request #1580
Opened 2020-11-25 16:29 UTC by j-jmnz

# Description
Added verification and submissions functionality.
Added data submissions page.

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7543

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-11-26 15:40 UTC, pkleybolte requested changes

2020-11-26 15:40 UTC, pkleybolte commented on src/store/ldap-config.js
> +const formatData = (data = {}, action) => {
This is basically a mapper, but I had to read it to understand that.
I would prefer two functions like `serverToClientDataMapper` and `clientToServerDataMapper`. 
And maybe one line of comment each about what they are for.

2020-11-26 15:40 UTC, pkleybolte commented on src/store/ldap-config.js
> +		systemData: {},
It is called a system in the DB, but here we don't need to care.

If I understand it correctly you keep the LDAP information in three versions.
1. Version currently saved in the server
2. verified, but not yet saved. Called `temp` why not call it `verified`?
3. submitted

I think you don't need the 3rd. After it was submitted and you get a success back, it should be the version currently saved on the server.

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/activate/index.vue
> +		<base-button @click="backButtonHandler">Züruck</base-button>
Translation missing

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/activate/index.vue
> +		<h1 class="h3">Folgende Datensätze stehen zur Synchronization bereit</h1>
Translation missing

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/activate/index.vue
> +				<span>Schüler:innen</span>
Translation missing

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/activate/index.vue
> +				<span>Lehrer:innen</span>
Translation missing

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/activate/index.vue
> +				<span>Admins</span>
Translation missing

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/activate/index.vue
> +				<span>Klassen</span>
Translation missing

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/activate/index.vue
> +			Im Folgenden kannst du an Beispielen überprüufen, ob wir die Attribute
Translation missing

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/activate/index.vue
> +		<p class="subtitle-text">Beispeil Nutzer:innen</p>
Translation missing

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/activate/index.vue
> +		<p class="subtitle-text">Beispiel Klasse</p>
Translation missing

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/activate/index.vue
> +			<base-button @click="backButtonHandler">Züruck</base-button>
Translation missing

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/activate/index.vue
> +				>Synchronization aktivieren</base-button
Translation missing

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/activate/index.vue
> +					title="Deine Konfiguration ist gespeichert Die Synchronisation kann bis zu einigen Stunden andauern."
Translation missing

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/activate/index.vue
> +					text="Ok"
Translation missing

2020-11-26 15:40 UTC, pkleybolte commented on src/store/ldap-config.js
> +};
Unit tests are missing for the store

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/index.vue
> +<template>
Unit tests are missing

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/activate/index.vue
> +<template>
Unit tests are missing

2020-11-26 15:40 UTC, pkleybolte commented on src/pages/administration/ldap/config/activate/index.vue
> +<template>
I'm not sure about the router behavior myself. Could place it under `src/pages/administration/ldap/config/activate.vue`?
Naming all the pages index.vue makes it more difficult to find the right file (and especially the right tab if you opened multiple of them)

2020-11-26 18:52 UTC, j-jmnz commented on src/store/ldap-config.js
> +		systemData: {},
Thanks for the suggestion, I'll change the namings.
This is how the versions work (with the new namings):

- `data`: system data currently saved in the server.
- `verified`: server response after verification with the verification status, errors, and sample data.
- `submitted`: server response after activation with the activation status, errors, and sample data. 
- `temp`: current input info, needed to maintain the state when going from the activate page back to the config page. 

About your last remark, we need `submitted` because it's the response to the activation request, which is needed to know whether it was successful, or if not, its errors; which could be different from the verification errors.

2020-11-30 09:32 UTC, pkleybolte commented on src/mixins/ldapErrorHandling.js
> +		errorHandler(error) {
Mixins have a couple of disadvantages. If possible it is better to define a helper function somewhere. In this case that should be easily possible. You might need to add $t as a parameter though, because this.$t is not available for a plain function.

2020-11-30 09:32 UTC, pkleybolte commented on src/pages/administration/ldap/activate.vue
> +					case "email":
This doesn't look shorter or easier than
```
<tr v-if=verified.users.sample.email">
    <td>$t("pages.administration.ldap.activate.email")</td>
    <td>{{ verified.users.sample.email }}
</tr>
```
But I don't really mind it.

2020-11-30 09:32 UTC, pkleybolte commented on src/pages/administration/ldap/activate.vue
> +					this.$toast.error(message);
According to [Error Handling Guildelines](https://docs.hpi-schul-cloud.org/display/TSC/Error+Handling+Guildelines#ErrorHandlingGuildelines-ErrorsintheNuxt-Client) this should be a <info-message type="error"> instead of a toast.

2020-11-30 09:32 UTC, pkleybolte commented on src/pages/administration/ldap/config.vue
> +							this.$toast.error(message);
Again `<info-message type="error">` instead of toast.

2020-11-30 09:32 UTC, pkleybolte commented on src/pages/administration/ldap/config.vue
> +						this.$t("pages.administration.ldap.index.verified")
To handle success similar to the error I would prefer `<info-message type="success">`, but that is a question for UX.

2020-11-30 09:32 UTC, pkleybolte commented on src/pages/administration/ldap/activate.vue
> +<template>
I know pages in the Nuxt repo don't have any unit tests, but that is no reason not to write any for new pages ;-)
There is a basic example for testing a page here: `src\pages\administration\teachers\new.unit.js`

2020-12-02 08:48 UTC, pkleybolte approved these changes

2020-12-03 15:44 UTC, mwolowyk-cap commented
Please add UI screenshots of the changes

2020-12-09 11:19 UTC, j-jmnz commented
@schul-cloud-bot update screenshots

2020-12-09 23:28 UTC, Metauriel approved these changes

2020-12-09 23:29 UTC, merged

2020-12-10 07:30 UTC, murat-merdoglu-hpi approved these changes