SC-7023: redirect, edit and delete actions for the task item
hpi-schul-cloud/nuxt-client pull request #1593
Opened 2020-12-03 14:11 UTC by haniapalac

# Description

## Links to Tickets or other pull requests

https://ticketsystem.hpi-schul-cloud.org/browse/SC-7023
## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-12-08 11:59 UTC, ABialoskorski commented
@schul-cloud-bot update screenshots

2020-12-08 12:38 UTC, ABialoskorski commented
@schul-cloud-bot update screenshots

2020-12-10 15:14 UTC, haniapalac commented
@schul-cloud-bot update screenshots

2020-12-10 15:46 UTC, haniapalac commented
@schul-cloud-bot update screenshots

2020-12-10 16:28 UTC, luizzaly commented
![Uploading Bildschirmfoto 2020-12-10 um 16.31.56.png…]()

2020-12-10 16:29 UTC, luizzaly commented
<img width="907" alt="Bildschirmfoto 2020-12-09 um 15 54 36" src="https://user-images.githubusercontent.com/39086430/101800152-3ed9b200-3b0d-11eb-9cb7-790304ad32a2.png">

2020-12-10 16:33 UTC, luizzaly commented on locale/de.json
> +	"pages.courses._id.modal.title.topic": "Willst du die Topic wirklich löschen?",
please correct to: Willst du das Editor Dokument wirklich löschen?

2020-12-10 16:36 UTC, luizzaly requested changes

2020-12-11 09:31 UTC, LukasSielski commented on locale/de.json
> +	"pages.courses._id.modal.title.topic": "Willst du die Topic wirklich löschen?",
done

2020-12-11 09:35 UTC, LukasSielski commented on locale/de.json
> +	"pages.courses._id.tab.groups": "Groups",
done

2020-12-11 09:51 UTC, LukasSielski commented
@schul-cloud-bot update screenshots

2020-12-11 11:14 UTC, pkleybolte requested changes

2020-12-11 11:14 UTC, pkleybolte commented on src/pages/courses/_id/index.vue
> +			const actionsTemplate = JSON.parse(JSON.stringify([...this.taskActions]));
Looks like a hacky way to clone this, but ok

2020-12-11 11:14 UTC, pkleybolte commented on src/store/courses.js
> +				this.$toast.success(successDeleteNotification);
Does this really work?
`this.$toast` should not be available in stores. Store only care about state, not about how it is visualized. Thus toasts should not be triggered by an action, but form a page or component.

2020-12-11 11:14 UTC, pkleybolte commented on src/store/courses.js
> +	actions: {
Missing tests for this new action

2020-12-11 11:17 UTC, LukasSielski commented on src/pages/courses/_id/index.vue
> +			const actionsTemplate = JSON.parse(JSON.stringify([...this.taskActions]));
The problem is, if we use just simpy takActions and even if it seems like a copy it is not because all what comes from data() is an Observer type and we change reference which makes it impossible to copy. This method was proposed by creator of Vue :D

2020-12-11 11:19 UTC, LukasSielski commented on src/store/courses.js
> +				this.$toast.success(successDeleteNotification);
As discussed during the error handling concept, we should handle errors in the actions functions. For now it is simply a toast message but in the future it will be changed to some more complicated handling with revert action. This is only a temporaty solution which works :) I can always catch it in the page but this is what we try to omit now.

2020-12-11 11:23 UTC, LukasSielski commented on src/store/courses.js
> +	actions: {
Yep, my bad... Will add it

2020-12-11 12:32 UTC, pkleybolte commented on src/store/courses.js
> +				this.$toast.success(successDeleteNotification);
The actions should catch the error and adjust the state accordingly. They should not render anything.
The error concept says errors should be displayed with `<info-message type="error">`

2020-12-11 12:46 UTC, LukasSielski commented on src/store/courses.js
> +				this.$toast.success(successDeleteNotification);
Yes, I agree but for  now UX team has decided, that we should simply display toast message instead of using some components

2020-12-11 12:47 UTC, LukasSielski commented on src/store/courses.js
> +				this.$toast.success(successDeleteNotification);
Therefore our concept for handling errors finds no usage here in my opinion.

2020-12-11 13:53 UTC, monaweitzenberg reviewed
UX had review

2020-12-14 07:16 UTC, ABialoskorski commented
mongod --dbpath "C:\SchulCloud\DB

2020-12-14 07:16 UTC, ABialoskorski commented
@schul-cloud-bot update screenshots

2020-12-14 07:24 UTC, ABialoskorski commented on src/components/base/BaseModal.stories.js
> +	.add("Delete Dialog", () => ({
I will take care

2020-12-14 08:00 UTC, ABialoskorski commented on src/components/base/BaseModal.stories.js
> +	.add("Delete Dialog", () => ({
done

2020-12-14 09:26 UTC, ABialoskorski commented on src/components/molecules/DeleteModal.vue
> +<template>
I will take care

2020-12-14 09:34 UTC, LukasSielski commented on src/components/molecules/DeleteModal.unit.js
> +        await wrapper.vm.$nextTick();
using await on trigger method call can save you call of $nextTick

2020-12-14 09:55 UTC, ABialoskorski commented on src/components/molecules/TaskItem.vue
> +			const card = document.getElementById(`card-${this.id}`);
done ;)

2020-12-14 11:13 UTC, haniapalac commented on src/components/molecules/TaskItem.vue
> +			const card = document.getElementById(`card-${this.id}`);
Makes perfect sense. Fixed :-)

2020-12-14 11:13 UTC, haniapalac commented on src/components/molecules/TaskItem.vue
> +			:id="'id-' + id"
id removed, ref used for tests

2020-12-14 12:44 UTC, ABialoskorski commented
@schul-cloud-bot update screenshots

2020-12-14 13:36 UTC, luizzaly commented
<img width="361" alt="Bildschirmfoto 2020-12-14 um 14 33 17" src="https://user-images.githubusercontent.com/39086430/102087107-5a003680-3e19-11eb-9731-3f4fa9cf9542.png">

Somehow for me on responsive mode it is hard to change tabs, as I have to click on the empty space next to the icon and cant click on the icon itself... please check that out again

2020-12-14 13:52 UTC, luizzaly commented
Could you please share screenshots of what have changed! thx :)

2020-12-14 15:12 UTC, luizzaly commented on locale/de.json
> +	"pages.courses._id.editorDocument.deleteError": "Editor Dokument konnte nicht gelöscht werden.",
please correct to Editor-Dokument konnte nicht gelöscht werden

2020-12-14 15:12 UTC, luizzaly commented on locale/de.json
> +	"pages.courses._id.editorDocument.deleteSuccess": "Editor Dokument erfolgreich gelöscht!",
Same here: Editor-Dokument erfolgreich gelöscht!

2020-12-14 15:19 UTC, luizzaly commented on src/store/courses.js
> +				this.$toast.success(successDeleteNotification);
I thought that we can not get any further information about the error on the client atm? Can we?

2020-12-14 15:43 UTC, luizzaly approved these changes

2020-12-14 16:15 UTC, haniapalac commented
@schul-cloud-bot update screenshots

2020-12-15 07:02 UTC, ABialoskorski approved these changes

2020-12-15 10:28 UTC, pkleybolte approved these changes

2020-12-15 10:33 UTC, merged