Feature/sc 8323 clear collection when querying
hpi-schul-cloud/nuxt-client pull request #1626
Opened 2021-01-07 16:45 UTC by Ojself

# Description
🚫 Before: When doing a search in the Learning-Store, the previous result was visible for a split second for the user
✅ Now: The previous result is cleared from the state and never shown to the user when using the Learning-Store.

See ticket for visual aid

## Links to Tickets or other pull requests

https://ticketsystem.hpi-schul-cloud.org/browse/SC-8323

## Changes
Collection in Lern-Store will now not render the previous results when doing a new search
The changes are required because it improves user experience

## New Repos, NPM pakages or vendor scripts

One new package "object-hash":
https://www.npmjs.com/package/object-hash
Object hash to store the queries in the state

## Screenshots of UI changes
There's a .mp4 in the ticket showing the result of the new code

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

2021-01-07 18:48 UTC, Ojself commented
@schul-cloud-bot update screenshots

2021-01-08 10:59 UTC, Ojself commented
@schul-cloud-bot update screenshots

2021-01-08 15:01 UTC, virgilchiriac approved these changes

2021-01-10 20:42 UTC, Ojself commented
@schul-cloud-bot update screenshots

2021-01-11 13:37 UTC, Ojself commented
@schul-cloud-bot update screenshots

2021-01-11 14:17 UTC, Ojself commented
@schul-cloud-bot update screenshots

2021-01-11 14:34 UTC, Ojself commented
@schul-cloud-bot update screenshots

2021-01-11 15:06 UTC, Ojself commented
@schul-cloud-bot update screenshots

2021-01-11 16:22 UTC, virgilchiriac commented
storybook seems to be broken due to the upgrade
http://stories.1626.nuxt.schul-cloud.surge.sh/

2021-01-11 17:34 UTC, virgilchiriac requested changes

2021-01-11 17:34 UTC, virgilchiriac commented on package.json
> +		"@storybook/vue": "^6.1.11",
looks like the upgrade breaks storybook

2021-01-11 19:38 UTC, Ojself commented
@schul-cloud-bot update screenshots

2021-01-12 09:32 UTC, virgilchiriac approved these changes

2021-01-12 11:51 UTC, Ojself commented
Duplicated: 
https://github.com/hpi-schul-cloud/nuxt-client/pull/1632

2021-01-12 11:51 UTC, closed without merging