SC-8250 - Connect UI for bulk delete
hpi-schul-cloud/nuxt-client pull request #1671
Opened 2021-02-24 17:46 UTC by uidp

# Description
add bulk delete functionality to admin tables

## Links to Tickets or other pull requests
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8250
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/2309

## Changes
- delete multiple users in chunks reduce server load
- show progress indicator

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-02-25 17:43 UTC, uidp commented
@schul-cloud-bot update screenshots

2021-02-26 08:46 UTC, pkleybolte requested changes

2021-02-26 08:46 UTC, pkleybolte commented on src/components/molecules/ProgressModal.vue
> +		color: {
unused prop

2021-02-26 08:46 UTC, pkleybolte commented on src/pages/administration/teachers/index.vue
> +		<progress-modal
Second modal without translations. Please remove

2021-02-26 08:46 UTC, pkleybolte commented on src/serverMiddleware/routes.js
> +	`^/administration/students/?$`,
For local testing only. Needs to be removed before merging.

2021-02-26 09:51 UTC, uidp commented on src/pages/administration/teachers/index.vue
> +		<progress-modal
done.

2021-02-26 09:52 UTC, uidp commented on src/serverMiddleware/routes.js
> +	`^/administration/students/?$`,
done.

2021-02-26 11:00 UTC, pkleybolte approved these changes

2021-02-26 11:20 UTC, merged