SC-8724 - remove registration filter for teachers
hpi-schul-cloud/nuxt-client pull request #1679
Opened 2021-02-26 14:08 UTC by j-jmnz

# Description

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8724

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-02-26 14:24 UTC, murat-merdoglu-hpi submitted a review, later dismissed

2021-02-26 15:25 UTC, j-jmnz commented
@schul-cloud-bot update screenshots

2021-03-01 15:47 UTC, CordlessWool commented
Should be not removed completely, only for external managed users

2021-03-01 15:53 UTC, CordlessWool requested changes

2021-03-01 15:53 UTC, CordlessWool commented on src/utils/adminFilter.js
> -		},
Should be not removed completely, only for external managed users

2021-04-13 12:20 UTC, closed without merging