add ellipsis
hpi-schul-cloud/nuxt-client pull request #1680
Opened 2021-02-26 14:53 UTC by j-jmnz

# Description

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8720

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-02-26 15:17 UTC, uidp approved these changes

2021-02-26 15:25 UTC, j-jmnz commented
@schul-cloud-bot update screenshots

2021-03-01 10:08 UTC, monaweitzenberg requested changes
I checked the ticket on local. the tables are still jumping by switching the pages. and I figured out another issue – If the email address contains a minus then this is interpreted as a break character. Example at the email address waldemar.wunderlich@schul-cloud.org -> the system does the following:
![image](https://user-images.githubusercontent.com/63390574/109482531-67bf7280-7a7e-11eb-87ea-ead4c8e15e86.png)

2021-03-01 13:24 UTC, monaweitzenberg approved these changes

2021-03-01 13:26 UTC, merged