Bugfix/SC-8851 fix broken queries in admin tables
hpi-schul-cloud/nuxt-client pull request #1700
Opened 2021-03-29 11:23 UTC by Tratori

Base links to copy
- https://ticketsystem.schul-cloud.org/browse/SC-8851

2021-04-13 13:13 UTC, pkleybolte requested changes
Tests are missing

2021-04-13 13:13 UTC, pkleybolte commented on src/pages/administration/teachers/index.vue
> +			if (this.$options.debounce) {
Why `this.$options` instead of a normal field in `data`

2021-04-14 15:58 UTC, virgilchiriac commented
@j-jmnz should this be rejected & closed?

2021-04-15 08:34 UTC, j-jmnz commented
This PR is getting closed. This issue was solved in https://ticketsystem.hpi-schul-cloud.org/browse/SC-8880.

2021-04-15 08:34 UTC, closed without merging