Creating config store
hpi-schul-cloud/nuxt-client pull request #1759
Opened 2021-04-29 09:49 UTC by murat-merdoglu-hpi

# Short Description

## Links to Ticket and related Pull-Requests

- https://ticketsystem.hpi-schul-cloud.org/browse/SC-9004

## Changes

- Config store created to fetch env variables from backend

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-05-19 11:24 UTC, CeEv commented on http-headers.config.js
> +=================================================================
I love it. :D

2021-05-19 11:36 UTC, CeEv requested changes

2021-05-19 11:36 UTC, CeEv commented on src/store/env-config.js
> +export const getters = {
On the most places the .env.[name] is called directly from state. Is this fine, when the getter exist?

2021-05-20 09:33 UTC, Metauriel commented on nuxt.config.js
> +		"@plugins/configInit",
comment that this needs to go first

2021-05-20 09:38 UTC, Metauriel commented on src/store/env-config.js
> +	},
find a way of warning a developer about accessing a variable that doesnt exist

2021-05-20 09:47 UTC, Metauriel commented on src/middleware/links-fallback.js
figure out what this file actually does

2021-05-20 15:09 UTC, dominikbruechner commented on src/pages/administration/teachers/index.vue
> +			return this.env.ADMIN_TABLES_DISPLAY_CONSENT_COLUMN;
I just stumbled upon it... it is inverting the ENV variable? Just double-check because the logic seems a bit unclear. maybe !this.env.ADMIN_TABLES_DISPLAY_CONSENT_COLUM? I just do not understand it

2021-05-20 15:10 UTC, dominikbruechner commented on src/plugins/configInit.js
> +};
is it retrying if it fails? in what cases could it fail? do we have defaults?

2021-05-20 15:11 UTC, dominikbruechner commented on src/store/auth.js
> +		if (rootState["env-config"].env.FEATURE_TEAMS_ENABLED) {
this really should be moved to user perm at some point ^^

2021-05-20 15:29 UTC, dominikbruechner commented on src/store/autoLogout.js
> +		defaultRemainingTimeInSeconds: 3600 * 2,
can we move this in some kind of configuration file? I think i f I would start looking for it, maybe I would search in the store, but maybe not. just a suggestion

2021-05-20 15:33 UTC, dominikbruechner commented on src/store/env-config.js
> +	},
+1

2021-05-21 08:15 UTC, pkleybolte commented on src/pages/administration/teachers/index.vue
> +			return this.env.ADMIN_TABLES_DISPLAY_CONSENT_COLUMN;
Reading from the console is always as a string. So if the string was "false" the boolean value had to be false.
The var loaded from the server in JSON format is a boolean already. No conversion needed anymore.

2021-05-21 08:54 UTC, j-jmnz commented on src/store/env-config.js
> +	},
There is actually no use for this getter as we are mostly reaching to the rootState to access this store. Can we get rid of this?

2021-05-21 14:37 UTC, pkleybolte commented on src/plugins/configInit.js
> +};
I added a retry mechanism to the store module. If it fails it uses some defaults, but prints the error in the console.

2021-05-21 14:40 UTC, pkleybolte commented on src/store/autoLogout.js
> +		defaultRemainingTimeInSeconds: 3600 * 2,
This exists until loading of the vars from the server is done or failed.
This is just to have a value so that the user is not shown the modal before the state is properly initialized.

2021-05-21 14:42 UTC, pkleybolte commented on src/store/env-config.js
> +	},
A var can always be null. From my point of view it is not necessary to check here. Depends on the var and how it is used in the component.
Some vars that are necessary to even start the client have defaults in `requiredVars`

2021-05-27 14:10 UTC, CeEv approved these changes

2021-05-28 08:29 UTC, merged