SC-9023 - Homeworks Dashboard
hpi-schul-cloud/nuxt-client pull request #1763
Opened 2021-05-06 08:12 UTC by dominikbruechner

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-05-11 13:55 UTC, dominikbruechner commented on src/components/organisms/HomeworksList.vue
> +		<template v-for="(homework, index) of homeworks">
Empty States we are implementing as part of the next sprint. 

A Loading State is a very good point to keep in mind, also showing an error if the return of a result fails.

2021-05-12 08:36 UTC, CeEv commented on src/components/organisms/HomeworksList.vue
> +		<template v-for="(homework, index) of homeworks">
out of sprint scope -> put to miro

2021-05-12 08:43 UTC, CeEv commented on src/components/organisms/HomeworksList.vue
> +			<v-list-item :key="homework._id" :href="'/homework/' + homework._id">
out of sprint scope -> put to miro

2021-05-12 08:59 UTC, CeEv commented on src/store/homeworks.unit.js
> +				expect(receivedRequests[0].url).toStrictEqual("/v3/task/dashboard/");
todo: think about it :D

2021-05-12 09:29 UTC, dominikbruechner commented on src/components/organisms/HomeworksList.vue
> +			<v-list-item :key="homework._id" :href="'/homework/' + homework._id">
resolved

2021-05-12 10:19 UTC, pkleybolte requested changes
My comments are minor issues. 
But since most tests are still todo I don't approve yet.

2021-05-12 10:19 UTC, pkleybolte commented on src/store/homeworks.js
>  const base = serviceTemplate("homework");
I'm not a big fan of the `serviceTemplate`. I prefer actions designed for a specific task over general CRUD operations.

You are no using any of the provided actions. If you don't need it, don't use it.

2021-05-12 10:19 UTC, pkleybolte commented on src/components/organisms/HomeworksList.vue
> +		...mapGetters("homeworks", {
My personal opinion is, that the component that triggers the loading of data should also get it from the store and pass the data on. So far this component is not reused so it does not matter that much.

If it is reused:

- Should all instances of the list show the same items based on the store? -> access store here
- Should different instances of the list show different items based on what search params the parent set? ->access store in parent

2021-05-12 11:22 UTC, dominikbruechner commented on src/components/organisms/HomeworksList.vue
> +		...mapGetters("homeworks", {
We will choose Should different instances of the list show different items based on what search params the parent set? ->access store in parent , as we probably need to filter data depending on where the widget will be used

2021-05-12 11:23 UTC, dominikbruechner commented on src/components/organisms/HomeworksList.vue
> +		...mapGetters("homeworks", {
generally agreed

2021-05-12 11:24 UTC, dominikbruechner commented on src/store/homeworks.js
>  const base = serviceTemplate("homework");
as we discussed: we are just using the state template and the commit('set') functionality, which is well implemented in the service-template, so we stick for now with the service-template

2021-05-12 11:24 UTC, dominikbruechner commented on src/pages/beta/dashboard/index.vue
> +<template>
yes

2021-05-17 08:31 UTC, dominikbruechner commented on src/pages/beta/dashboard/index.vue
> +	created() {
done by @martynakrysinska

2021-05-17 08:32 UTC, dominikbruechner commented on src/components/organisms/HomeworksList.unit.js
> +		const wrapper = mount(HomeworksList, {
resolved by @martynakrysinska

2021-05-17 08:40 UTC, dominikbruechner commented on src/components/organisms/HomeworksList.unit.js
> +	it("Should render complete homework items list", async () => {
added test

2021-05-17 08:51 UTC, martynakrysinska approved these changes
Approved

2021-05-17 08:52 UTC, merged