Feature/sc 9050 homeworks dashboard empty state
hpi-schul-cloud/nuxt-client pull request #1778
Opened 2021-05-18 06:36 UTC by martynakrysinska

# Short Description

Implemented empty state for the new homeworks dashboard. 

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-05-18 07:39 UTC, dominikbruechner commented on src/pages/beta/dashboard.vue
> +			v-if="homeworks.length === 0"
here you can do v-else

2021-05-18 13:31 UTC, dominikbruechner requested changes
Hey there, generally nice work, particularly regarding the tests!

One thing that I thought about. This component already exists and is already used on many pages: https://storybook.test.hpi-schul-cloud.org/?path=/story/5-molecules-emptystate--default 

The EmptyState Layout for tasks looks a bit different. And we might want to use v-img. 
I really would like to have generic components, in my opinion, the case for keeping the new one would be that it plays nicely with vuetify. 

Suggestion: Rename the component to vCustomEmptyState and make it generic

Also, please add a storyBook entry, for now, you could place it next to the v-btn story which we have on the f-odyssey branch

cheers ✌️

2021-05-18 13:31 UTC, dominikbruechner commented on src/components/molecules/TasksEmptyState.vue
> +			default: () => tasksEmptyState,
To make it reusable, I would suggest to make it _required: true_ and pass the image path always as a prop

2021-05-18 13:31 UTC, dominikbruechner commented on src/components/molecules/TasksEmptyState.vue
> +			default: () => tasksEmptyState,
imagePath: {
			type: String,
			required: true,
		},

2021-05-18 13:31 UTC, dominikbruechner commented on src/components/molecules/TasksEmptyState.vue
> +		<h3 class="h4 text-center mt-3">{{ subtitle }}</h3>
as title and subtitle are not required, I would suggest to add a v-if (you would need to try this out, if it works with the default "" value)

Additionally: If we do not display a h1 element, then this needs to be changed accordingly

```suggestion
		<h1 v-if="title" class="h4 text-center mt-8">{{ title }}</h1>
		<h2 v-if="subtitle" class="h4 text-center mt-3">{{ subtitle }}</h2>
```

2021-05-18 13:31 UTC, dominikbruechner commented on src/components/molecules/TasksEmptyState.vue
> +		imgHeight: "400px"
I would add the imgHeight as a prop with default value

2021-05-18 13:31 UTC, dominikbruechner commented on src/components/organisms/HomeworksList.vue
> +			taskImage,
We should generally rename this to taskIconSvg, to make it clearer (just realizing after re-reading my code)

2021-05-18 13:31 UTC, dominikbruechner commented on src/pages/beta/dashboard.vue
> +		<homeworks-list v-if="homeworks.length > 0" :homeworks="homeworks"/>
this might or might not work with v-if="homeworks", or did you try it already ?

2021-05-18 13:31 UTC, dominikbruechner commented on src/components/molecules/TasksEmptyState.unit.js
> +	beforeEach(() => {
nice!

2021-05-18 13:31 UTC, dominikbruechner commented on src/components/molecules/TasksEmptyState.unit.js
> +		wrapper.destroy();
also nice!

2021-05-20 07:33 UTC, martynakrysinska commented on src/pages/beta/dashboard.vue
> +			v-if="homeworks.length === 0"
Done

2021-05-20 07:33 UTC, martynakrysinska commented on src/components/molecules/TasksEmptyState.vue
> +			default: () => tasksEmptyState,
Done

2021-05-20 07:42 UTC, martynakrysinska commented on src/components/molecules/TasksEmptyState.vue
> +		<h3 class="h4 text-center mt-3">{{ subtitle }}</h3>
I made the title required, but left subtitle optional in case we want to display a shorter message. And the h2 will only be shown if the subtitle is passed as a prop.

2021-05-20 07:50 UTC, martynakrysinska commented on src/components/molecules/TasksEmptyState.vue
> +		imgHeight: "400px"
Done

2021-05-20 08:00 UTC, martynakrysinska commented on src/pages/beta/dashboard.vue
> +		<homeworks-list v-if="homeworks.length > 0" :homeworks="homeworks"/>
This will actually display the HomeworksList component with no items on it, so the length check seems necessary here.

2021-05-25 07:10 UTC, dominikbruechner approved these changes

2021-05-25 07:32 UTC, dominikbruechner commented on src/pages/tasks/open.vue
> -	layout: "defaultVuetify",
shouln't this stay here?

2021-05-25 07:32 UTC, dominikbruechner commented on src/components/molecules/vCustomEmptyState.vue
> +	layout: "defaultVuetify",
and go out of here?

2021-05-25 07:32 UTC, dominikbruechner commented on src/pages/tasks/open.vue
> -	layout: "defaultVuetify",
the layouts should always be used on page level

2021-05-25 07:35 UTC, dominikbruechner commented on src/components/molecules/vCustomEmptyState.vue
> +	<v-container>
in this case v-container is put twice (once in the page, once in the component), better to keep it outside of the component?

2021-05-26 06:41 UTC, martynakrysinska commented on src/components/molecules/vCustomEmptyState.vue
> +	<v-container>
The template root expects only one element, that's why I wrapped the BaseImage and headers in the v-container.

2021-05-26 06:51 UTC, martynakrysinska commented on src/pages/tasks/open.vue
> -	layout: "defaultVuetify",
Done. I deleted the layout from HomeworksList as well. Now it is only in open.vue.

2021-05-26 08:08 UTC, merged