SC-9077 - store/use of store refactoring
hpi-schul-cloud/nuxt-client pull request #1783
Opened 2021-05-21 15:37 UTC by j-jmnz

# Short Description

## Links to Ticket and related Pull-Requests
https://ticketsystem.hpi-schul-cloud.org/browse/SC-9077

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-05-26 20:10 UTC, CeEv requested changes

2021-05-26 20:10 UTC, CeEv commented on src/components/organisms/DatasourceRunWebuntis.vue
> +import { mapState } from "vuex";
I think in generally we should not give any componet or side a direct access to the store, like $store.state.xxx..
Any data should comsume over $store.getters.xxx..
The same for mutations.

2021-05-26 20:10 UTC, CeEv commented on src/components/organisms/DatasourceRunWebuntis.vue
> +		...mapState("webuntis-metadata", {
And really i think the service template in the stores is shit. :D 
But this is not a part of your PR.

2021-05-27 07:19 UTC, j-jmnz commented on src/components/organisms/DatasourceRunWebuntis.vue
> +import { mapState } from "vuex";
According to vuex good practices, it is preferable to consume data by giving direct access to the store or by mapping the state to the component over having redundant getters that return the state as it is without any modification.
You can read a bit more about this over here: https://dev.to/timothyokooboh/vuex-best-practices-45dd

2021-05-27 07:44 UTC, dominikbruechner commented on src/components/organisms/DatasourceRunWebuntis.vue
> +		...mapState("webuntis-metadata", {
We need a service template v2, which delivers us all the standard methods for custom endpoints like GET/PATCH/DELETE/POST, while sticking to good practices. 

Particulary we need per default a #loading# state.

2021-05-27 07:46 UTC, dominikbruechner commented on src/components/organisms/DatasourceRunWebuntis.vue
> +import { mapState } from "vuex";
https://hackernoon.com/correct-and-efficient-way-to-use-vuex-part-i-wf15432eu 

Here as well.
I am talking to Cedric about this as well, after reading up on this I am also making the case for the use of MapState, if we do not need to filter data

2021-05-27 08:25 UTC, j-jmnz commented on src/components/organisms/DatasourceRunWebuntis.vue
> +		...mapState("webuntis-metadata", {
@dominikbruechner that's the follow-up of this ticket 👍

2021-05-27 08:33 UTC, pkleybolte approved these changes

2021-05-27 09:00 UTC, merged