Feature/odyssey homeworks loading state
hpi-schul-cloud/nuxt-client pull request #1789
Opened 2021-05-27 12:04 UTC by martynakrysinska

# Short Description

First implementation of the loading state for homeworks list and its headers, however the work is still in progress.

The templates of open.vue and HomeworkList.vue have way too many if/else statements. This still requires refactoring and consideration for error state that we want to add in the future. 
Mocking the store with different states seems  repetitive, im still not sure what would be the best solution for that. 

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-05-27 13:20 UTC, dominikbruechner commented on src/pages/tasks/open.vue
> +			v-if="homeworks.length === 0 && !loading.homeworks"
Probably you want to do something like:

`
IF loading.homeworks
   //show skeleton loader for headline
   //show skeleton loader for homeworks list
ELSE {
   IF homeworks.length > 0
      //show homeworks headline
      //show homeworksList
  ELSE
     //show emptystate
}
`

2021-05-28 09:09 UTC, CeEv requested changes

2021-05-28 09:09 UTC, CeEv commented on src/store/homeworks.js
> +			commit("setLoading", { homeworks: true });
try catch is missing, if you get an error from axios then you want to write it to store > error in future. But you must also setLoading to false in error case. 

Moving loading to service template bring you also to a problem. The page should not know what key is loading, it is loading or not. It is fine if you define more loading keys. Because it is possible to send more then on request over different dispatch. In a perfect world it should not because for this you must write a additional dispatch that combine it, but in real live you can run into this situations.
But the page will only the info is load or is not.

Also the loading getter not return homework : true ..it return all possible keys inside of loading are true. But the service template do not know all keys. You can set it directly by initial the store and go over Object.keys and array.every ..but this is hidden logic outside the main store.

2021-05-28 09:11 UTC, CeEv requested changes

2021-05-28 09:11 UTC, CeEv commented on src/store/homeworks.js
>  			const res = await this.$axios.$get("/v3/task/dashboard/");
The test if missing for axios throw an error.

2021-05-31 07:48 UTC, CeEv approved these changes

2021-05-31 13:35 UTC, dominikbruechner commented
@schul-cloud-bot update screenshots

2021-05-31 13:44 UTC, merged