SC-9090 - loading state and template refactoring
hpi-schul-cloud/nuxt-client pull request #1793
Opened 2021-06-01 10:21 UTC by j-jmnz

# Short Description
Implementation of a loading state and service-template refactoring

## Links to Ticket and related Pull-Requests
https://ticketsystem.hpi-schul-cloud.org/browse/SC-9090

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-06-08 18:45 UTC, j-jmnz commented
@schul-cloud-bot update screenshots

2021-06-08 21:11 UTC, j-jmnz commented
@schul-cloud-bot update screenshots

2021-06-09 11:55 UTC, j-jmnz commented
@schul-cloud-bot update screenshots

2021-06-11 09:11 UTC, pkleybolte requested changes

2021-06-11 09:11 UTC, pkleybolte commented on src/pages/content/_id/index.vue
>  	async asyncData({ store, params }) {
Using `asyncData` is bad for two reasons:
1. It is nuxt specific (and in the long term we would like to get rid of it and use plain vue)
2. It blocks rendering the page until it is done. Better UX is rendering a page and showing a spinner.

Dispatch can be done in `mounted`. The returned object contains data from the store and should be mapped in `computed`.

If possible, please refactor. If it is too much effort now, please leave comments like this explanation in the code.

2021-06-11 09:11 UTC, pkleybolte commented on src/store/content.js
> -		return this.$axios.$get(`/edu-sharing/${id}`);
I like that you noticed and fixed this :-)

2021-06-16 06:48 UTC, pkleybolte approved these changes

2021-06-16 11:28 UTC, merged