Decomposed dueDate hint chip
hpi-schul-cloud/nuxt-client pull request #1802
Opened 2021-06-10 15:33 UTC by dominikbruechner

# Short Description

Refactored remaining time label.

- Decomposed into an own component
- added thorough unit tests
- added storybook entry

<img width="791" alt="Screenshot 2021-06-10 at 17 29 52" src="https://user-images.githubusercontent.com/7567881/121553861-f6df0d80-ca11-11eb-9165-762a26f6348e.png">

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-06-10 15:55 UTC, dominikbruechner commented
@schul-cloud-bot update screenshots

2021-06-10 16:09 UTC, CeEv requested changes

2021-06-10 16:09 UTC, CeEv commented on src/components/molecules/VCustomChipTimeRemaining.vue
> +			type: String,
type enums are missed enum: ["warning", "overdue"] 
And a test that check wrong inputs too i think.

2021-06-10 16:09 UTC, CeEv commented on src/components/molecules/VCustomChipTimeRemaining.vue
> +			type: String,
If is is possible to break it
validator (val) {
      return // test right format
    }
    
 Add test for wrong format.

2021-06-11 13:06 UTC, CeEv approved these changes

2021-06-11 13:07 UTC, CeEv approved these changes

2021-06-11 13:08 UTC, CeEv approved these changes

2021-06-11 13:46 UTC, merged