Feature/teacher homework dashboard
hpi-schul-cloud/nuxt-client pull request #1810
Opened 2021-06-16 13:49 UTC by dominikbruechner

# Short Description

- Added ListItem for teachers
- - Refactored ListItem and HomeworksList for students and teachers
- Added new route for tasks for teachers

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-06-17 07:44 UTC, martynakrysinska requested changes

2021-06-17 07:44 UTC, martynakrysinska commented on src/components/organisms/HomeworksList.unit.js
> +				type: "student",
let's write some tests for props today :)
so far we've neglected that too much

2021-06-17 07:44 UTC, martynakrysinska commented on src/components/molecules/vHomeworkItemStudent.unit.js
> +	it("computedDueDateLabel() method should be able to render a shortened date", () => {
let's test the rest of the methods too? isCloseToDueDate(dueDate), isOverDue() and homeworkHref() still have no tests.

blame goes on me here as well, because i implemented some of them

2021-06-17 07:44 UTC, martynakrysinska commented on src/components/molecules/vHomeworkItemStudent.vue
> +			required: true,
this could use a validator

2021-06-17 07:44 UTC, martynakrysinska commented on src/components/molecules/vHomeworkItemTeacher.vue
> +		homeworkGradingHref: (id) => {
again: unit test is missing for this method and it would look cleaner with a template string like this:

return `/homework/${id}#activatetabid=submissions`

EDIT:

github editor ate the backticks

2021-06-17 07:44 UTC, martynakrysinska commented on src/components/organisms/HomeworksList.vue
> +				v-if="type === 'student'"
now when the size of the HomeworksList is reduced, i think it would be better to take the v-if out of the loop, because it's considered a bad pattern and just create two separate templates and check for the type ("student" or "teacher") before looping over homeworks.

2021-06-17 07:44 UTC, martynakrysinska commented on src/pages/tasks/asked.vue
> +</style>
isn't it an exact copy of open.vue? maybe we should try to find a way to use the same page like for the student?

2021-06-17 07:57 UTC, dominikbruechner commented on src/components/organisms/HomeworksList.unit.js
> +				type: "student",
we actually have a validator in place for this prop in homeworksList - do you think we still should add a test?

2021-06-17 07:58 UTC, dominikbruechner commented on src/pages/tasks/asked.vue
> +</style>
we can think about moving it into a layout file

2021-06-17 08:00 UTC, dominikbruechner commented on src/components/molecules/vHomeworkItemTeacher.vue
> +		homeworkGradingHref: (id) => {
github also allows you to suggest code changes - it is the little page icon with a +- on top of the text input field

2021-06-17 08:24 UTC, dominikbruechner commented on src/components/molecules/vHomeworkItemStudent.unit.js
> +	it("computedDueDateLabel() method should be able to render a shortened date", () => {
i am not completely sure about testing the methods OR just checking if the rendered page/labels/etc. cointain the right values
I guess it is blackbox-testing of methods VS result in the UI --> Gut feeling is to rather check the UI results

2021-06-17 08:32 UTC, dominikbruechner commented on src/components/molecules/vHomeworkItemTeacher.vue
> +			return "/homework/" + id + "#activetabid=submissions";
```suggestion
			return `/homework/${id}#activetabid=submissions`;
```

2021-06-23 09:52 UTC, martynakrysinska submitted a review, later dismissed

2021-06-24 17:39 UTC, dominikbruechner commented on src/pages/tasks/assigned.vue
> +}
Do you still need this here?

2021-06-24 17:41 UTC, dominikbruechner commented on src/pages/tasks/assigned.vue
> +}
Also, is the max-width still in place?

2021-06-24 17:42 UTC, dominikbruechner commented on src/pages/tasks/assigned.vue
> +}
maybe it just need to be moved into the dashboard main

2021-06-24 17:43 UTC, martynakrysinska commented on src/pages/tasks/assigned.vue
> +}
yeah, i must've forgotten to move it to the main dashboard, it should be also deleted from open.vue

2021-06-24 17:43 UTC, dominikbruechner commented
The archtitecture looks nice ! I just browsed through, and left one comment.

2021-06-25 08:16 UTC, Metauriel approved these changes

2021-06-25 10:06 UTC, CeEv requested changes

2021-06-25 10:06 UTC, CeEv commented on src/utils/sidebarBaseItems.js
> +		permission: "Task_Dashboard_View_v3",
This can not work, if you run npm run setup the permission do not exist.

2021-06-25 10:06 UTC, CeEv commented on src/utils/sidebarBaseItems.js
> +		permission: "TEACHER_LIST",
TASK_DASHBOARD_VIEW_V3

2021-06-25 10:06 UTC, CeEv commented on stories/mockData/Homeworks.js
> +export const invalidHomeworks = [
use create function and bash functions instant

2021-06-25 11:38 UTC, martynakrysinska commented on src/components/organisms/HomeworksDashboardMain.vue
> +			<v-skeleton-loader :type="'text'" :max-width="'30%'" />
text would be treated as JavaScript expression instead of a string

2021-06-25 11:40 UTC, martynakrysinska commented on src/components/organisms/HomeworksDashboardMain.vue
> +			<v-skeleton-loader :type="'text'" :max-width="'30%'" />
i could however get rid of the binding and do just "type" instead of ":type"

2021-07-06 08:02 UTC, closed without merging