Feature/sc 9159 news typescript frontend
hpi-schul-cloud/nuxt-client pull request #1815
Opened 2021-06-23 09:13 UTC by mwolowyk-cap

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-06-28 09:19 UTC, mwolowyk-cap commented on src/components/organisms/FormNews.vue
> +				: this.$ts("components.organisms.FormNews.errors.missing_date");
Don't change the domain logic. Put default date = now

2021-06-28 09:24 UTC, mwolowyk-cap commented
@schul-cloud-bot update screenshots

2021-06-28 14:01 UTC, mwolowyk-cap commented
@schul-cloud-bot update screenshots

2021-06-28 16:09 UTC, pkleybolte requested changes
Unit Test are missing for NewsEditView, NewsDetailView, all of edit.vue and index.vue

2021-06-29 07:43 UTC, mwolowyk-cap commented
> Unit Test are missing for NewsEditView, NewsDetailView, all of edit.vue and index.vue

@pkleybolte These components are not in use yet. They are currently disabled. Before usage they have to be tested.

2021-06-29 08:08 UTC, closed without merging