WIP: School Administration Page in Nuxt + Vuetify
hpi-schul-cloud/nuxt-client pull request #1837
Opened 2021-07-13 13:29 UTC by odalys-hpi

# Short Description

Reimplementation of the school administration page with vuetify.

## Links to Ticket and related Pull-Requests

https://ticketsystem.hpi-schul-cloud.org/browse/SC-9083

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-07-14 16:33 UTC, pkleybolte requested changes

2021-07-14 16:33 UTC, pkleybolte commented on src/components/organisms/administration/SchoolPolicyFormDialog.vue
> +								@input="$v.description.$touch"
Just a suggestion for UX improvement:
Wait a second after input before $touch, or even better wait until the user stopped typing.

2021-07-14 16:33 UTC, pkleybolte commented on src/components/organisms/vCustomDialog.vue
> +	props: {
To enable the use of v-model for the parent (as you are doing in line 2), you can add this:
```
model: {
		prop: "isOpen",
		event: "dialog-closed",
	},
```
and send `false` as a payload with your event

2021-07-15 09:12 UTC, odalys-hpi commented on src/store/schools.js
> +				// TODO - ask if I need to check for process.env.LDAP... here
can be removed

2021-07-15 14:29 UTC, odalys-hpi commented on src/components/organisms/administration/GeneralSettings.vue
> +			<template v-if="loading">
Doing that gives an error message saying it should be moved to a wrapper element

2021-07-16 15:02 UTC, odalys-hpi commented on src/components/organisms/administration/GeneralSettings.vue
> +				!this.school.officialSchoolNumber &&
Without the check it would still send the value to the server, which causes an error there. Maybe there's a better solution for this?

2021-08-02 13:05 UTC, pkleybolte requested changes

2021-08-30 12:30 UTC, Metauriel approved these changes

2021-08-30 15:32 UTC, murat-merdoglu-hpi commented
@schul-cloud-bot update screenshots

2021-08-30 15:59 UTC, Metauriel submitted a review, later dismissed

2021-08-30 17:03 UTC, murat-merdoglu-hpi commented
@schul-cloud-bot update screenshots

2021-08-30 17:11 UTC, murat-merdoglu-hpi approved these changes

2021-08-30 18:19 UTC, merged