Feature/sc 9201 student homework dashboard panels
hpi-schul-cloud/nuxt-client pull request #1838
Opened 2021-07-15 13:01 UTC by martynakrysinska

# Short Description

This PR includes:
- refactoring of HomeworksDashboardPanels component
- integrating HomeworksDashboardPanels component into HomeworksDashboardStudent component
- some code clean up of the tasks dashboards 

  This Pull-Request template helps the reviewers as well as servers as a checklist for you. Please feel out all possible sections.

  Quality guidelines:
    - Code should be self-explanatory; Document code that is not self-explanatory
    - Code respects SOLID principles, DRY, YAGNI, KISS
    - Think about potential bugs this Pull Request might introduce
    - Keep security in mind
    - Write tests (Unit and Integration), including for error cases. Don't decrease coverage
    - Business logic should be implemented in the API; never trust the client
    - UI changes should be discussed & agreed with the UX-Team before staring
    - Keep the CHANGELOG up-to-date
    - Boyscout rule: leave the code in a better state than you found it. Remove unnecessary lines. Listen to the linter.
-->

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-07-15 13:51 UTC, dominikbruechner requested changes
Looks good, besides what I wrote for the DashboardPanels component and the following:

The teacher's unit tests include:
- it("Should render not disabled 'no due date' panel, and disabled empty other panel", 
- it("Should render not disabled 'with due date' panel, and disabled empty other panel", 

these two tests can be generalized, and then unit test the HomeworksDashboardPanels component directly. 

otherwise todo bien nice work 🥇

2021-07-15 13:51 UTC, dominikbruechner commented on CHANGELOG.md
> +
I guess you could move that to unreleased

2021-07-15 13:51 UTC, dominikbruechner commented on CHANGELOG.md
> +
```suggestion
```

2021-07-15 13:51 UTC, dominikbruechner commented on package.json
> +	"version": "26.5.2",
```suggestion
	"version": "26.5.1",
```
probably we can leave that for now at 26.5.1

2021-07-15 13:51 UTC, dominikbruechner commented on src/components/organisms/HomeworksDashboardMain.stories.js
> -						getOpenHomeworks: () => homeworks,
why does this need to go? all good if anticipated

2021-07-15 13:51 UTC, dominikbruechner commented on package-lock.json
> +	"version": "26.5.2",
```suggestion
	"version": "26.5.1",
```

2021-07-15 13:51 UTC, dominikbruechner commented on src/components/organisms/HomeworksDashboardPanels.vue
> +						{{ dueDateHomeworks.length + overDueHomeworks.length }}
here I fixed a small bug, you missed the overDueHomeworks

2021-07-15 13:51 UTC, dominikbruechner commented on src/components/organisms/HomeworksDashboardPanels.vue
> +		}),
Now I understand what you meant on rc.

I am not totally agreeing with this approach, as of the following reasoning:
- The dashboardPanel component should, in my opinion, be dumb and shouldn't care about slot content and data structure
- By mapping the getters you basically make it resistant to reuse
- I would even go further and define even the headlines as props, and then rename the component to vDoublePanels or something

You can also leave it as is, taking this into account, and adapt it when needed at some point.

2021-07-15 13:51 UTC, dominikbruechner commented on src/components/organisms/HomeworksDashboardTeacher.unit.js
> +	it("Should render homeworks list component, with second panel expanded per default", () => {
thanks 👏

2021-07-15 13:51 UTC, dominikbruechner commented on src/components/organisms/HomeworksList.vue
> +		isListFilled: function () {
👏

2021-07-15 13:54 UTC, martynakrysinska commented on src/components/organisms/HomeworksDashboardMain.stories.js
> -						getOpenHomeworks: () => homeworks,
we're not using this getter now when the student also has homeworks without due date listed separately

2021-07-15 16:11 UTC, martynakrysinska commented on src/components/organisms/HomeworksDashboardPanels.vue
> +						{{ dueDateHomeworks.length + overDueHomeworks.length }}
thanks!

2021-07-15 16:12 UTC, martynakrysinska commented on src/components/organisms/HomeworksDashboardMain.stories.js
> -						getOpenHomeworks: () => homeworks,
thanks, tomorrow i will still work on the tests, hence WIP label

2021-07-19 08:23 UTC, dominikbruechner commented on src/components/organisms/HomeworksDashboardPanels.unit.js
> +		expect(wrapper.find(".v-expansion-panel--disabled").exists()).toBe(true);
```suggestion
		const expansionPanels = wrapper.findAll(".v-expansion-panel");
		expect(expansionPanels.exists()).toBe(true);
		expect(expansionPanels.at(0).classes()).toContain(
			"v-expansion-panel--disabled"
		);
		expect(expansionPanels.at(1).classes()).toContain(
			"v-expansion-panel--disabled"
		);
```

2021-07-19 08:28 UTC, dominikbruechner commented on src/components/organisms/HomeworksDashboardPanels.vue
> +<template>
we need a storybook entry as well for this component (for the screenshot tests)

2021-07-19 10:06 UTC, dominikbruechner commented
@schul-cloud-bot update screenshots

2021-07-19 14:12 UTC, martynakrysinska commented
@schul-cloud-bot update screenshots

2021-07-19 14:25 UTC, dominikbruechner approved these changes

2021-07-19 14:30 UTC, merged