SC-9192 Fix path mapping
hpi-schul-cloud/nuxt-client pull request #1844
Opened 2021-07-22 14:34 UTC by uidp

# Short Description
Access feathers and NestJS apps by their verision prefixes.

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-07-22 14:37 UTC, tofixx commented on src/plugins/axios.js
> +		if (!config.url.match(/^\/v\d\//)) {
is this applied only for calls against our api server or globally? i think it should not be applied to other external calls...?!

2021-07-22 14:39 UTC, uidp commented on src/plugins/axios.js
> +		if (!config.url.match(/^\/v\d\//)) {
unfortunately this is globally applied.

2021-07-27 13:44 UTC, tofixx submitted a review, later dismissed

2021-08-02 14:23 UTC, pkleybolte approved these changes

2021-08-10 14:54 UTC, tofixx approved these changes

2021-08-13 07:31 UTC, virgilchiriac submitted a review, later dismissed

2021-08-13 09:42 UTC, mamutmk5 requested changes
It is possible to solve the _v1_ part without a breaking change?

2021-08-13 09:42 UTC, mamutmk5 commented on src/components/organisms/AddContentButton.vue
> +								`/v1/edu-sharing/merlinToken/?merlinReference=${element.merlinReference}`
It is possible to solve the _v1/_ part without a breaking change?

2021-08-16 07:25 UTC, mamutmk5 approved these changes

2021-08-16 09:07 UTC, merged