SC-9232 - gender specific role names
hpi-schul-cloud/nuxt-client pull request #1853
Opened 2021-07-30 13:50 UTC by murat-merdoglu-hpi

# Short Description

## Links to Ticket and related Pull-Requests

- https://ticketsystem.hpi-schul-cloud.org/browse/SC-9232

## Changes

- User role names in topbar are fixed 
- i18n file entries are added

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-07-30 13:57 UTC, alriese submitted a review, later dismissed

2021-08-02 13:17 UTC, pkleybolte requested changes

2021-08-02 13:17 UTC, pkleybolte commented on src/components/legacy/PopupIconInitials.vue
> -				<span> {{ firstname }} {{ lastname }} <user-role /> </span>
This was the only place using the user-role component. Please remove it as well.

2021-08-03 14:16 UTC, murat-merdoglu-hpi commented on src/components/legacy/PopupIconInitials.vue
> -				<span> {{ firstname }} {{ lastname }} <user-role /> </span>
removed

2021-08-04 13:55 UTC, pkleybolte approved these changes

2021-08-04 14:33 UTC, alriese approved these changes

2021-08-04 15:24 UTC, j-jmnz approved these changes

2021-08-05 07:32 UTC, merged