Feature/bc 94 color clean up
hpi-schul-cloud/nuxt-client pull request #1889
Opened 2021-09-03 08:29 UTC by monaweitzenberg

# Short Description

clean up the colors in the old client and nuxt and fixing small UX issues

## Links to Ticket and related Pull-Requests

https://ticketsystem.hpi-schul-cloud.org/browse/BC-94

## Changes
cleaning primary, secondary and accent color; delete tertiary color

## Screenshots of UI changes
![dBildungsCloud](https://user-images.githubusercontent.com/63390574/131974999-7a373a9f-9560-43e5-9198-0e4b6a817a84.png)
<img width="1224" alt="open" src="https://user-images.githubusercontent.com/63390574/131975002-e4eb8262-946b-434b-a02d-12774afa0877.png">
<img width="1222" alt="default" src="https://user-images.githubusercontent.com/63390574/131975007-fd3d9c83-2ff6-4112-b695-7fafee93ed4a.png">
![Upload
<img width="1220" alt="brb" src="https://user-images.githubusercontent.com/63390574/131975016-a0465587-cd83-48cd-9cda-c536a2640811.png">
ing thr.png…]()

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-09-03 09:27 UTC, pkleybolte requested changes

2021-09-03 09:27 UTC, pkleybolte commented on src/themes/brb/styles/custom-styles.scss
> +	// background-color: var(--color-primary);
better remove than comment

2021-09-03 09:27 UTC, pkleybolte commented on src/themes/demo/styles/variables/_colors.scss
> +	--color-primary: #b1063a;
primary defined twice

2021-09-03 09:27 UTC, pkleybolte commented on src/themes/demo/styles/variables/_colors.scss
> +	--color-accent: #e98404;
Is this the right color?

2021-09-03 09:27 UTC, pkleybolte commented on src/themes/int/styles/variables/_colors.scss
> +	--color-primary: #0a688c;
color correct?

2021-09-03 09:27 UTC, pkleybolte commented on src/themes/n21/vuetify.options.js
> +				primary: "#6E9CD2",
color  correct? different color in _colors.scss

2021-09-03 09:27 UTC, pkleybolte commented on src/themes/int/styles/variables/_colors.scss
> +	--color-primary: #0a688c;
Change in vuetify options necessary?

2021-09-03 09:27 UTC, pkleybolte commented on src/themes/demo/styles/variables/_colors.scss
> +	--color-primary: #b1063a;
change in vuetify options necessary?

2021-09-03 09:27 UTC, pkleybolte commented on src/themes/brb/styles/variables/_colors.scss
> +	--color-primary: #0a9396;
change in vuetify options necessary?

2021-09-03 09:27 UTC, pkleybolte commented on src/themes/base/styles/variables/_colors.scss
> +	--color-secondary: #455b6a;
change in vuetify options necessary?

2021-09-03 09:27 UTC, pkleybolte commented on src/themes/open/styles/variables/_colors.scss
> +	--color-primary: #df0b40;
no secondary color defined
change in vuetify options necessary?

2021-09-03 09:27 UTC, pkleybolte commented on src/themes/thr/styles/variables/_colors.scss
> +	--color-primary: #2876d0;
change in vuetify options necessary?

2021-09-03 15:29 UTC, monaweitzenberg commented on src/themes/brb/styles/custom-styles.scss
> +	// background-color: var(--color-primary);
Da dann die Datei keinen Sinn mehr macht, habe ich sie gleich gelöscht. :)

2021-09-03 15:38 UTC, monaweitzenberg commented on src/themes/demo/styles/variables/_colors.scss
> +	--color-primary: #b1063a;
theme demo hat keine vuetify options Datei. Soll das so?

2021-09-03 15:40 UTC, monaweitzenberg commented on src/themes/demo/styles/variables/_colors.scss
> +	--color-accent: #e98404;
yes, it is.

2021-09-06 08:44 UTC, pkleybolte requested changes

2021-09-06 08:44 UTC, pkleybolte commented on src/themes/demo/styles/variables/_colors.scss
>  	--color-primary: #b10438;
Demo uses the vuetify.options.js of base, but base has a different primary. We need a vuetify.options.js to have a consistent primary color in vuetify and non-vuetify components.

2021-09-06 10:57 UTC, monaweitzenberg commented on src/themes/base/styles/variables/_colors.scss
> +	--color-secondary: #455b6a;
There was nothing to adjust.

2021-09-06 10:59 UTC, monaweitzenberg commented on src/themes/brb/styles/variables/_colors.scss
> +	--color-primary: #0a9396;
The vuetify options are now also adjusted.

2021-09-06 11:02 UTC, monaweitzenberg commented on src/themes/int/styles/variables/_colors.scss
> +	--color-primary: #0a688c;
The vuetify options are now also adjusted. And colors are correct.

2021-09-06 11:03 UTC, monaweitzenberg commented on src/themes/thr/styles/variables/_colors.scss
> +	--color-primary: #2876d0;
The vuetify options are now also adjusted.

2021-09-06 14:21 UTC, luizzaly commented
<img width="1356" alt="Bildschirmfoto 2021-09-06 um 16 17 49" src="https://user-images.githubusercontent.com/39086430/132231134-f40ebdbf-53b4-49b2-93b5-368ea04530cc.png">

Bei aktuellen Aufgaben in "open" scheint noch das falsche Logo gezogen zu werden..

2021-09-07 07:14 UTC, luizzaly approved these changes
looks good! 👍🏼

2021-09-07 13:10 UTC, pkleybolte approved these changes

2021-09-08 07:22 UTC, monaweitzenberg commented
@schul-cloud-bot update screenshots

2021-09-09 06:42 UTC, pkleybolte approved these changes

2021-09-09 13:42 UTC, merged