Feature/bc 167 layouts
hpi-schul-cloud/nuxt-client pull request #1897
Opened 2021-09-09 08:27 UTC by pkleybolte

# Short Description
I created a wireframe that is supposed to be the basic of future pages.
The wireframe contains the breadcrump and title to keep a consistent layout.
The actual page content should go into the default slot.

## Links to Ticket and related Pull-Requests
https://ticketsystem.hpi-schul-cloud.org/browse/BC-167

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-09-13 14:00 UTC, murat-merdoglu-hpi submitted a review, later dismissed

2021-09-16 09:47 UTC, odalys-dataport requested changes

2021-09-16 09:47 UTC, odalys-dataport commented on locale/es.json
> +	"global.topbar.actions.contactAdmin": "Contacta a al admin de tu escuela",
This should be only "al"

2021-09-16 09:47 UTC, odalys-dataport commented on locale/de.json
> +	"global.topbar.actions.training": "Fortbildungen",
Reminder to compare with legacy client translations

2021-09-16 09:47 UTC, odalys-dataport commented on src/components/molecules/DefaultWireframe.unit.js
> +import { mount } from "@vue/test-utils";
`DefaultWireframe` component should go into templates (folder structure)

2021-09-16 09:47 UTC, odalys-dataport commented on src/components/molecules/DefaultWireframe.unit.js
> +	it("shows breadcrumps", () => {
*breadcrumbs

2021-09-16 09:47 UTC, odalys-dataport commented on src/components/molecules/DefaultWireframe.vue
> +import vCustomBreadcrumbs from "@components/molecules/vCustomBreadcrumbs.vue";
`vCustomBreadcrumbs` probably should be an atom

2021-09-16 09:47 UTC, odalys-dataport commented on src/components/molecules/DefaultWireframe.vue
> +export type Breadcrump = {
*Breadcrumb

2021-09-16 09:47 UTC, odalys-dataport commented on src/components/molecules/DefaultWireframe.vue
> +	// padding: 0 36px;
can this be removed?

2021-09-16 09:47 UTC, odalys-dataport commented on src/pages/administration/school-settings.vue
> +	<default-wireframe
Idea: Default loading state for full page

2021-09-16 09:47 UTC, odalys-dataport commented on src/pages/administration/students/index.vue
> +		:full-width="true"
If it feels more comfortable to be explicit here, we could make full-width required as well

2021-09-17 12:31 UTC, odalys-dataport submitted a review, later dismissed

2021-09-20 07:36 UTC, odalys-dataport approved these changes

2021-09-20 08:49 UTC, murat-merdoglu-hpi approved these changes

2021-09-20 11:38 UTC, merged