feature/BC-252 -  creating avatar component
hpi-schul-cloud/nuxt-client pull request #1900
Opened 2021-09-13 13:03 UTC by murat-merdoglu-hpi

# Short Description

- avatars components created
- store file added

## Links to Ticket and related Pull-Requests

- https://ticketsystem.hpi-schul-cloud.org/browse/BC-252

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-09-13 14:57 UTC, pkleybolte requested changes
Tests for all the new components are missing

2021-09-13 14:57 UTC, pkleybolte commented on src/components/atoms/vRoomAvatar.vue
> +			:value="(showBadge && item.notification) || false"
`|| false` is redundant

2021-09-13 14:57 UTC, pkleybolte commented on src/components/atoms/vRoomEmptyAvatar.vue
> +		avatarTitle() {
unused computed property

2021-09-13 14:57 UTC, pkleybolte commented on src/components/organisms/vCustomDialog.unit.js
> +	hasButtons: true,
Test missing for `hasButtons: false`

2021-09-13 14:57 UTC, pkleybolte commented on src/pages/rooms-overview/index.vue
> +			@dialog-closed="groupDialog.isOpen = false"
redundant. `v-model` does this for you

2021-09-13 14:57 UTC, pkleybolte commented on src/pages/rooms-overview/index.vue
> +						cols="4"
More columns than the main grid has for mobile.

2021-09-13 14:57 UTC, pkleybolte commented on src/store/rooms.ts
> +	get getRoomData(): Object {
Type definition is missing. We know more about the structure than it being an object.

2021-09-16 11:59 UTC, murat-merdoglu-hpi commented on src/components/organisms/vCustomDialog.unit.js
> +	hasButtons: true,
added missing tests.

2021-09-16 12:00 UTC, murat-merdoglu-hpi commented on src/store/rooms.ts
> +	get getRoomData(): Object {
It has now type definitions.

2021-09-16 13:17 UTC, pkleybolte requested changes

2021-09-16 13:17 UTC, pkleybolte commented on src/pages/rooms-overview/index.vue
> +			return this.roomsData.filter(
instead of `filter` you can use `find`. You are ignoring every element except for the first one in line 153/159 anyway.

2021-09-16 13:17 UTC, pkleybolte commented on src/pages/rooms-overview/index.vue
> +			this.groupDialog.groupData = this.roomsData.filter(
`find` is better than `filter(...)[0]`

2021-09-16 13:51 UTC, murat-merdoglu-hpi commented on src/components/molecules/vRoomGroupAvatar.vue
> +			return this.items.group.slice(0, this.maxItems);
It shows the max items only in the pageview inside the groupComponent. They don't disappear actually. If a user clicks on the group component then a modal appears and the user can see all items in the modal. The pagination will be inside the modal view later on, like android phones.

2021-09-17 12:39 UTC, pkleybolte approved these changes

2021-09-17 12:47 UTC, merged