BC-68 - fix server manifest error
hpi-schul-cloud/nuxt-client pull request #1904
Opened 2021-09-17 14:21 UTC by virgilchiriac

# Short Description

moves e2e with each commit, to have them testing each image build
makes sure image exists, before the e2e runs

## Links to Ticket and related Pull-Requests
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2670/
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3000/
- https://ticketsystem.hpi-schul-cloud.org/browse/BC-68

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-09-17 15:06 UTC, mamutmk5 requested changes
I suggest for the file the name push.yml and as workflow name: push workflow

2021-09-20 07:44 UTC, virgilchiriac commented
> I suggest for the file the name push.yml and as workflow name: push workflow

@mamutmk5  done

2021-09-24 09:13 UTC, mamutmk5 requested changes

2021-09-24 09:13 UTC, mamutmk5 commented on .github/workflows/push.yml
>        - master
why have you not remove master?

2021-09-24 09:23 UTC, mamutmk5 approved these changes

2021-09-24 10:39 UTC, merged