BC-295 - improve security (npm ci ignores NODE_ENV=production)
hpi-schul-cloud/nuxt-client pull request #1906
Opened 2021-09-20 10:28 UTC by virgilchiriac

# Short Description

Because npm ci ignores NODE_ENV=production, the build now explicitly needs to ignore dev dependencies so that are not part of the build image.

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-09-20 11:23 UTC, Loki-Afro requested changes
please wait with this merge until BC-266 is through, you may need to change things

2021-09-20 11:25 UTC, mamutmk5 requested changes
Please Respect the **AGPv3** and the _6. Conveying Non-Source Forms_.
That's some how a docker image for me.

2021-09-20 11:25 UTC, mamutmk5 commented on Dockerfile.client
> +RUN rm -rf node_modules && npm cache clean --force && npm install --production
I think olny run _npm install --production_ shoud do it.
Why: ist starts with an folder who only inclued to files _package.json_ and _package-lock.json_. There is no folder like node_modules or even something at the npm cahce.
```suggestion
RUN npm install --production
```

2021-09-20 11:25 UTC, mamutmk5 commented on .dockerignore
> +ansible
Must be include at the immage, by AGLPv3

2021-09-20 11:25 UTC, mamutmk5 commented on .dockerignore
> +CHANGELOG.md
Must be include at the immage, by AGLPv3

2021-09-20 11:25 UTC, mamutmk5 commented on .dockerignore
> +.eslintrc.json
Must be include at the immage, by AGLPv3

2021-09-20 11:25 UTC, mamutmk5 commented on .dockerignore
> +.mergify.yml
Must be include at the immage, by AGLPv3

2021-09-20 11:25 UTC, mamutmk5 commented on .dockerignore
> +.pullapprove.yml
Must be include at the immage, by AGLPv3

2021-09-20 11:25 UTC, mamutmk5 commented on .dockerignore
> +.travis.yml*
File shoud be not more exist

2021-09-20 11:25 UTC, mamutmk5 commented on .dockerignore
> +docs
Must be include at the immage, by AGLPv3

2021-09-20 11:25 UTC, mamutmk5 commented on .dockerignore
> +test
Must be include at the immage, by AGLPv3

2021-09-20 11:25 UTC, mamutmk5 commented on .dockerignore
> +webpack.config.js
Must be include at the immage, by AGLPv3

2021-09-20 11:31 UTC, Loki-Afro requested changes
@mamutmk5 any source for your AGPLv3 comments? i would rather have the smallest image possible

2021-09-20 11:31 UTC, Loki-Afro commented on Dockerfile.client
> +RUN rm -rf node_modules && npm cache clean --force && npm install --production
doing npm install will ignore the package-lock.json leading to non reproduce able builds - don't do that!

2021-09-20 12:23 UTC, virgilchiriac commented
nuxt build depends on webpack, which is a deep devDependency. 
because we run  nuxt build also on startup, this needs to wait for BC-266

2021-09-20 14:33 UTC, Loki-Afro requested changes
do not merge this before bc-266

and use npm ci instead npm install - you want that you verify the package-json.lock,otherwise we have unstable builds.

fix your dev dependencies as well, it is worth nothing if your local system is compromised.

and/or find a way to use npm ci and only install prod dependencies

2021-09-27 12:04 UTC, virgilchiriac commented
the build needs dev dependencies, therefor we need to rethink the image artifacts: instead of copy all items, we should only use the ones needed to run the application

2021-09-27 12:04 UTC, closed without merging