Feature/bc 309 310 adjust task course filter
hpi-schul-cloud/nuxt-client pull request #1907
Opened 2021-09-20 12:15 UTC by odalys-dataport

# Short Description

Adds the amount of tasks to the course filter per course.
Fixes an issue where the correct panel wasn't opened when filtering tasks.

## Links to Ticket and related Pull-Requests

- https://ticketsystem.hpi-schul-cloud.org/browse/BC-309
- https://ticketsystem.hpi-schul-cloud.org/browse/BC-310

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

![Screenshot 2021-09-17 at 16 58 38](https://user-images.githubusercontent.com/82401838/134000515-3a70e90e-3528-49af-919f-feef115ad13c.png)

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-09-24 08:05 UTC, CeEv requested changes

2021-09-24 09:24 UTC, odalys-dataport commented on src/components/organisms/TasksDashboardMain.vue
> +	mounted() {
As far as I know, using `mounted` here is considered best practice

2021-09-24 09:25 UTC, CeEv submitted a review, later dismissed

2021-09-28 05:49 UTC, CeEv requested changes

2021-09-28 05:49 UTC, CeEv commented on src/components/molecules/vCustomDoublePanels.vue
> +				if (this.isPanelTwoDisabled && expanded === 1) {
else if { }
but let us speak about this block

2021-09-28 07:40 UTC, monaweitzenberg submitted a review, later dismissed
Well done :)

2021-09-30 06:04 UTC, monaweitzenberg approved these changes
well done. Thanks from the users to you Odalys <3

2021-09-30 09:28 UTC, CeEv approved these changes

2021-09-30 09:51 UTC, merged