Feature/bc 155 substitution teacher filter2
hpi-schul-cloud/nuxt-client pull request #1947
Opened 2021-10-26 02:45 UTC by CeEv

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-11-01 21:14 UTC, CeEv commented on src/components/atoms/vCustomSwitch.vue
> +	color: var(--color-secondary);
Do not work at the moment.

2021-11-01 21:22 UTC, CeEv commented on src/components/templates/TasksDashboardMain.vue
> +.custom-switch-position {
Should orientated on parent element and not set it directly. 
Maybe by wrap it over div and managed the div from parent side.

2021-11-01 21:55 UTC, CeEv commented on src/components/molecules/vTaskItemTeacher.vue
> +			// TODO: only for spain it must be a suffix
Important must be solved

2021-11-02 16:34 UTC, odalys-dataport requested changes

2021-11-02 16:34 UTC, odalys-dataport commented on src/components/templates/TasksDashboardMain.vue
> +						@input-changed="setSubstitutionFilter"
Maybe we should keep the wording consistent and use "substitute" instead of "substitution". I looked it up today and "substitute" would be correct, my wording in the jira ticket was wrong.

2021-11-02 16:34 UTC, odalys-dataport commented on src/components/templates/TasksDashboardMain.vue
> +			// TODO: refactor
Yesssss :D This function has been bugging me for a while now

2021-11-02 16:34 UTC, odalys-dataport commented on src/components/templates/TasksDashboardMain.vue
> +.custom-switch-position {
`v-row` should only be used as a wrapper together with `v-col`. If we just wrap it in a div instead of v-row and remove this class, everything works fine

2021-11-02 16:34 UTC, odalys-dataport commented on src/store/tasks.js
> +// it is a teacher based interpretation or and why or condition?
What do you mean here? "Completed" is a category for students only into which tasks are sorted that are either submitted or graded

2021-11-02 16:34 UTC, odalys-dataport commented on src/store/tasks.js
> +		// TODO: enum "error", "pending", "completed", "" -> "" should get notLoaded / notInitialized or so and not empty string and this should set by creating this store
we should find a client wide solution for this

2021-11-02 16:37 UTC, CeEv commented on locale/de.json
> +	"common.words.substitute": "Vertretungs",
Is already fixed :P

2021-11-02 16:40 UTC, CeEv commented on src/store/tasks.js
> +		// TODO: enum "error", "pending", "completed", "" -> "" should get notLoaded / notInitialized or so and not empty string and this should set by creating this store
Typescript give us the enum like const and validate it by it self. I mark it for the ts pr on which places i want this.

2021-11-02 17:51 UTC, CeEv commented on src/store/tasks.js
> +// it is a teacher based interpretation or and why or condition?
Not really the condition task.status.submitted >= 1 || task.status.graded >= 1 can only solved by teachers for student is the maximum = 1 by submitte and graded.
But the hasCompletedTasks > filterCompleted has no teacher in name. Let us look into it tomorrow.

2021-11-09 08:30 UTC, CeEv commented on src/components/molecules/vTaskItemTeacher.vue
> +			// TODO: only for spain it must be a suffix
is solved, remove this comment

2021-11-10 11:02 UTC, CeEv commented
@schul-cloud-bot update screenshots

2021-11-10 12:34 UTC, odalys-dataport requested changes

2021-11-10 12:34 UTC, odalys-dataport commented on locale/en.json
> +	"components.organisms.TasksDashboardMain.filter.substitution": "Tasks from substititions",
There's a typo here in `substitutions`, but we should probably name it `substitutes` to be consistent

2021-11-10 12:34 UTC, odalys-dataport commented on src/components/templates/TasksDashboardMain.stories.js
> +	// coursesTeacher,
Can we remove these comments?

2021-11-10 12:34 UTC, odalys-dataport commented on src/components/templates/TasksDashboardMain.unit.js
> +				text: "Chemie (undefined)", // undefined?
Why is undefined expected here?

2021-11-10 12:34 UTC, odalys-dataport commented on src/components/templates/TasksDashboardMain.vue
> +							$t('components.organisms.TasksDashboardMain.filter.substitution')
Should probably name this `components.organisms.TasksDashboardMain.filter.substitute` for consistency

2021-11-10 12:34 UTC, odalys-dataport commented on src/components/templates/TasksDashboardMain.vue
> +			<!-- v-model="getSelectedCourseFilters" -->
Remove this?

2021-11-10 12:34 UTC, odalys-dataport commented on src/components/templates/TasksDashboardMain.vue
> +				:value="getSelectedCourseFilters"
Why is it better to use value instead of v-model here?

2021-11-10 12:34 UTC, odalys-dataport commented on src/components/templates/TasksDashboardMain.vue
> +		isTeacher: function () {
Love it, was about to do it in my PR as well 😅

2021-11-10 12:34 UTC, odalys-dataport commented on src/store/tasks.js
> +	return overdued;
typo: "overdue"

2021-11-10 12:34 UTC, odalys-dataport commented on src/store/tasks.js
> +			(task) => task.status.isSubstitutionTeacher === false
Is it too late to change it to `isSubstituteTeacher` in server? 😬

2021-11-10 12:34 UTC, odalys-dataport commented on src/store/tasks.unit.js
> +			it("should return true by finished (graded+submitted) tasks", () => {
graded+submitted would be completed still until the user marks it as finished, no?

2021-11-11 08:42 UTC, CeEv commented on src/components/templates/TasksDashboardMain.vue
> +				:value="getSelectedCourseFilters"
v-model throw an error, because it has no setter on the same key if the key is part of the store. It can implement over js get(), set() sub methodes that mapped to different store actions...but i found no similar code in vue. For this case i do not want to introduce new handling.

2021-11-11 08:48 UTC, CeEv commented on src/components/templates/TasksDashboardMain.unit.js
> +				text: "Chemie (undefined)", // undefined?
The mock is inconsistent ...tab+component-role vs input task data types. I hope this is cleanup by the ts change, otherwise i must setup the mocks in otherway or create a seperate mock for it.

2021-11-11 08:50 UTC, CeEv commented on src/components/templates/TasksDashboardMain.vue
> +		isTeacher: function () {
:D

2021-11-11 08:51 UTC, CeEv commented on src/store/tasks.js
> +			(task) => task.status.isSubstitutionTeacher === false
Only the vue client pr is open. Lets do it in a ticket that have client and server ...and please remember me. ;)

2021-11-11 08:53 UTC, CeEv commented on src/store/tasks.unit.js
> +			it("should return true by finished (graded+submitted) tasks", () => {
Oh i use finished as name in the test before the ux want to rename closed to finished. It is confusing now... i rename it.

2021-11-11 08:56 UTC, CeEv commented on src/store/tasks.unit.js
> +			it("should return true by finished (graded+submitted) tasks", () => {
The second point: it is in the context of the teacher. Let look together is this an expected behavior. I am not completely sure.

2021-11-11 10:16 UTC, odalys-dataport approved these changes

2021-11-11 16:25 UTC, merged