Feature/bc 537 add task fab
hpi-schul-cloud/nuxt-client pull request #1955
Opened 2021-11-08 10:56 UTC by odalys-dataport

# Short Description

Implements a FloatingActionButton with vuetify for the whole application. Replaces currently used fab (in admin tables for example).

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-11-11 10:41 UTC, odalys-dataport commented
@schul-cloud-bot update screenshots

2021-11-15 10:38 UTC, odalys-dataport commented
@schul-cloud-bot update screenshots

2021-11-16 17:21 UTC, CeEv requested changes

2021-11-16 17:21 UTC, CeEv commented on CHANGELOG.md
> +- BC-537 - added new vuetify floating action button
please move it to unreleased ..next release is added. :P

2021-11-16 17:21 UTC, CeEv commented on src/components/atoms/vCustomFab.unit.ts
> +		// apparantly testing scroll behaviour is not possible with jest
Not part of this ticket, but it should possible to add plugins for jest and it look like we need some more features. Maybe it already exist packages for it. 

Or maybe the way over define the event work for us.
https://github.com/tony19-sandbox/vue-test-utils-window-scroll/commit/43524f877f30f00916004de31a08c02adfd9783a#diff-f9b32ed8eb59920fdb32aed218c8e9fead4ac9a71f591a4f1211aa7449f8729fR15

2021-11-16 17:21 UTC, CeEv commented on src/components/atoms/vCustomFab.vue
> +	position: fixed !important;
To many !important; See my other comment.

2021-11-16 17:21 UTC, CeEv commented on src/components/atoms/vCustomFab.vue
> +			mdiClose,
Adding the icon on this place look unnessasary.

2021-11-16 17:21 UTC, CeEv commented on src/components/atoms/vCustomFab.vue
> +			extended: !!this.title,
It is expended when the input prop title is defined  and "<span v-if="extended">{{ title }}</span>"  look not intuitive. Why not set it directly?

2021-11-16 17:21 UTC, CeEv commented on src/components/atoms/vCustomFab.vue
> +			if (this.scrollTimer !== -1) {
I must meditate over this code snipped.

2021-11-16 17:27 UTC, odalys-dataport commented on nuxt.config.js
> +		// TODO - test production build with this
I created a ticket for this, I'll remove the code

2021-11-16 17:36 UTC, odalys-dataport commented on src/components/atoms/vCustomFab.stories.js
> +			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis maximus venenatis laoreet. Quisque condimentum, elit nec aliquet pretium, eros massa ultricies elit, at rhoncus turpis ligula ut ju
That's actually a great idea, thanks!

2021-11-17 10:18 UTC, odalys-dataport commented on src/components/atoms/vCustomFab.vue
> +	position: fixed !important;
This line had to be done, because of a vuetify bug, where it adds an inline `position: relative` when you click the fab and messes everything up.

2021-11-17 10:18 UTC, odalys-dataport commented on src/components/templates/TasksDashboardMain.vue
> +	<default-wireframe
We're adding the scroll handler to the page here

2021-11-17 10:20 UTC, odalys-dataport commented on src/themes/base/styles/vuetify-custom.scss
> +$btn-focus-opacity: 0 !important;
I've already spent a long time trying to do it without important, but vuetify kept finding ways to overwrite it. I'd leave it like this for now and look into it at a later time.

2021-11-17 11:51 UTC, odalys-dataport commented on src/themes/base/styles/vuetify-custom.scss
> +$btn-focus-opacity: 0 !important;
I was able to remove the `important` statement here with removing the `dark` property form the button. It seems there is another vuetify variable set in the dark theme that handles focus states

2021-11-18 10:04 UTC, odalys-dataport commented on src/components/atoms/vCustomFab.vue
> +			mdiClose,
I have to add this here, so I can use it.

2021-11-18 11:30 UTC, CeEv approved these changes

2021-11-18 11:31 UTC, merged