BC-653 use reusable workflows for auto deployment
hpi-schul-cloud/nuxt-client pull request #1957
Opened 2021-11-10 15:58 UTC by alriese

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-11-10 16:28 UTC, mamutmk5 requested changes

2021-11-10 16:28 UTC, mamutmk5 commented on .github/workflows/push.yml
> +         echo "IMAGE_EXISTS=$(docker manifest inspect ghcr.io/${{ github.repository }}:${{ github.sha }} > /dev/null && echo 1 || echo 0)" >> $GITHUB_ENV
No, don't work so the package name includes tennens.
```suggestion
         echo "IMAGE_EXISTS=$(docker manifest inspect ghcr.io/${{ github.repository }}-${{ matrix.tennens }}:${{ github.sha }} > /dev/null && echo 1 || echo 0)" >> $GITHUB_ENV
```

2021-11-10 16:28 UTC, mamutmk5 commented on .github/workflows/clean.yml
> +  deploy:
We shoud rename it to clean.
```suggestion
  clean:
```

2021-11-12 14:18 UTC, virgilchiriac requested changes

2021-11-12 14:18 UTC, virgilchiriac commented on CHANGELOG.md
> +- BC-589 - BC-653 - Change auto deployment to a reusable workflow
why is this in the middle of the file? Should be on top....

2021-11-12 14:19 UTC, virgilchiriac approved these changes

2021-11-15 12:53 UTC, mamutmk5 approved these changes

2021-11-15 13:05 UTC, merged