BC-157 - Add typescript to task store
hpi-schul-cloud/nuxt-client pull request #1958
Opened 2021-11-11 14:56 UTC by uidp

# Short Description
BC-157 - Add typescript to task store

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-11-15 15:05 UTC, CeEv requested changes

2021-11-15 15:05 UTC, CeEv commented on src/store/tasks.ts
> +		if (!this._taskApi) {
How the pagination is resolved in this context? (fetchAll)

2021-11-15 15:05 UTC, CeEv commented on src/store/tasks.unit.ts
> +					taskControllerFindAll: jest.fn(() => ({
It shoul work without pagination.

2021-11-15 15:05 UTC, CeEv commented on src/store/tasks.ts
> +	pagination: Pagination = {
We have no pagination that is stored at the place in context of not finished tasks.

2021-11-15 15:05 UTC, CeEv commented on src/store/tasks.unit.ts
> +import { Task, TaskModule } from "./tasks";
I look into it after the requested changes are applayed. ( mark me self @CeEv )

2021-11-19 21:12 UTC, uidp commented on src/store/task.filter.ts
> +	withDueDate(): TaskFilter {
yes. we have to also think about how we can get rid of the `new Date()` comparison. the business logic shouldn't really depend on the client's current system time. that's maybe something we have to resolve soon.

2021-11-19 21:12 UTC, uidp commented on src/store/task.filter.ts
> +	// it is a teacher based interpretation or and why or condition?
resolved by merge.

2021-11-19 21:12 UTC, uidp commented on src/store/task.filter.unit.ts
> +export const taskFactory = new TaskFactory();
yes. we should do that. but we first have to decide how we want to use factories and where to put the files. like we have done with the files under `store/types`. we maybe can use a path like `store/factories`

2021-11-19 21:12 UTC, uidp commented on src/store/tasks.ts
> +	pagination: Pagination = {
right. removed that.

2021-11-19 21:12 UTC, uidp commented on src/store/tasks.ts
> +	setTasks(tasks: Task[]) {
right. added that.

2021-11-19 21:12 UTC, uidp commented on src/store/tasks.ts
> +		this.substituteFilter = enabled;
that has been discussed and i think it's resolved now.

2021-11-19 21:12 UTC, uidp commented on src/store/tasks.ts
> +	_taskApi?: TaskApiInterface;
we have to access the task api somehow. this is the reference to it.

2021-11-19 21:12 UTC, uidp commented on src/components/templates/TasksDashboardMain.vue
> +		TaskModule.getAllTasks();
yes. works the same in all components and pages.

2021-11-22 08:33 UTC, CeEv commented on src/components/templates/TasksDashboardMain.unit.js
> +	// it("Should disable filter when active tab contains empty list and no course is selected", () => {
Should this comment stand in?

2021-11-22 08:33 UTC, CeEv commented on src/components/templates/TasksDashboardMain.unit.js
> +		// it("Should set correct course name with task count for filter", () => {
Should this comment stand in?

2021-11-22 08:35 UTC, CeEv commented on tests/unit/setup.js
> +Object.defineProperty = (o, p, c) =>
This is a fine solution for tests.

2021-11-26 08:31 UTC, CeEv commented on src/store/task.filter.ts
> +	withDueDate(): TaskFilter {
Odalyse want to make a list of needed refacotor changes. We should add this also to it. @odalys-dataport;

2021-11-26 16:42 UTC, odalys-dataport approved these changes

2021-11-26 16:49 UTC, merged