BC-724 - Listing elements and search
hpi-schul-cloud/nuxt-client pull request #1966
Opened 2021-11-19 13:09 UTC by murat-merdoglu-hpi

# Short Description
- Implemented all elements' list page
- Added search feature to list page
- Added search feature to the dashboard
- Created a new iterating elements' component

## Links to Ticket and related Pull-Requests
https://ticketsystem.hpi-schul-cloud.org/browse/BC-724

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-11-19 16:16 UTC, pkleybolte requested changes

2021-11-19 16:16 UTC, pkleybolte commented on src/pages/rooms-overview.vue
>  		await RoomsModule.fetch(); // TODO: this method will receive a string parameter (Eg, mobile | tablet | desktop)
TODO is not handled in this ticket? Is there a follow up ticket you could mention here?

2021-11-19 16:16 UTC, pkleybolte commented on src/pages/rooms-overview.vue
> +				// TODO: default naming
TODO is not handled in this ticket? Is there a follow up ticket you could mention here?

2021-11-19 16:16 UTC, pkleybolte commented on src/pages/rooms-overview.vue
> +		searchItems(filterText) {
Nice to have:
As computed property.

2021-11-19 16:16 UTC, pkleybolte commented on src/serverMiddleware/routes.js
> +	`^/rooms-list/?$`,
Is the task to open this route handled?

2021-11-19 16:16 UTC, pkleybolte commented on src/store/rooms.ts
> -import { DroppedObject, RoomsData } from "./types/rooms";
Types are externalized to the /types folder in another ticket.
Please do it for these and the following types as well.

2021-11-19 16:16 UTC, pkleybolte commented on src/store/rooms.ts
> +			const { data } = await $axios.$get("/v3/courses/");
If it is api/v3 there should be a generated client available that we can use here.

2021-11-19 20:29 UTC, murat-merdoglu-hpi commented on src/pages/rooms-overview.vue
>  		await RoomsModule.fetch(); // TODO: this method will receive a string parameter (Eg, mobile | tablet | desktop)
The server has not supported a device-based dashboard yet, and there is no open ticket by now.

2021-11-19 21:16 UTC, murat-merdoglu-hpi commented on src/serverMiddleware/routes.js
> +	`^/rooms-list/?$`,
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/62

2021-11-22 16:23 UTC, murat-merdoglu-hpi commented on src/store/rooms.ts
> -import { DroppedObject, RoomsData } from "./types/rooms";
done

2021-11-22 16:23 UTC, murat-merdoglu-hpi commented on src/pages/rooms-overview.vue
> +		searchItems(filterText) {
done

2021-11-22 16:24 UTC, murat-merdoglu-hpi commented on src/pages/rooms-list.vue
> +		searchItems(filterText: string): void {
done

2021-11-22 17:07 UTC, pkleybolte approved these changes

2021-11-22 17:14 UTC, merged