BC-661 Add school logo to top bar. Refactor legacyLoggedIn
hpi-schul-cloud/nuxt-client pull request #1968
Opened 2021-11-23 19:46 UTC by pkleybolte

# Short Description

## Links to Ticket and related Pull-Requests
https://ticketsystem.hpi-schul-cloud.org/browse/BC-661

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-11-24 09:21 UTC, murat-merdoglu-hpi requested changes

2021-11-24 09:21 UTC, murat-merdoglu-hpi commented on src/components/legacy/TheTopBar.vue
> +			<div v-if="school" class="school-name item">
The icon size differs between legacy client and nuxt pages.

2021-11-25 19:21 UTC, murat-merdoglu-hpi approved these changes

2021-11-25 19:21 UTC, murat-merdoglu-hpi commented on src/layouts/legacyLoggedIn.vue
> +					:school="school"
Do we need to pass 'user' data as a prop instead of 'this.$user'?

2021-11-26 16:14 UTC, pkleybolte commented on src/layouts/legacyLoggedIn.vue
> +					:school="school"
Actually I don't like `this.$user`. 
On first glance it is a bit of magic. I don't like magic in software projects.
On second glance it is realized with a global mixin. Mixins are criticized. Global mixins get even more criticism. Why should every ever so simple component need a reference to the user? 
I think it is more straightforward if components that need to know the user, get it form the store.

2021-11-26 16:24 UTC, murat-merdoglu-hpi approved these changes

2021-11-29 14:19 UTC, merged