Feature/bc 922 rooms overview fab
hpi-schul-cloud/nuxt-client pull request #1996
Opened 2021-12-09 13:42 UTC by pkleybolte

# Short Description

## Links to Ticket and related Pull-Requests
https://ticketsystem.hpi-schul-cloud.org/browse/BC-922

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2021-12-10 09:54 UTC, MartinSchuhmacher requested changes

2021-12-10 09:54 UTC, MartinSchuhmacher commented on src/components/templates/DefaultWireframe.vue
> +		position: relative !important;
check if !important can be removed

2021-12-10 12:39 UTC, MartinSchuhmacher submitted a review, later dismissed

2021-12-10 12:44 UTC, MartinSchuhmacher commented
@schul-cloud-bot update screenshots

2021-12-10 13:45 UTC, MartinSchuhmacher submitted a review, later dismissed

2021-12-13 10:25 UTC, murat-merdoglu-hpi approved these changes

2021-12-13 11:17 UTC, merged