Feature/bc 1071 finish/archive & restore task action
hpi-schul-cloud/nuxt-client pull request #2034
Opened 2022-01-26 08:36 UTC by odalys-dataport

# Short Description

Closing and opening of tasks over the 3-dot-menu

## Links to Ticket and related Pull-Requests

https://ticketsystem.hpi-schul-cloud.org/browse/BC-1071

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-02-02 13:48 UTC, SevenWaysDP requested changes

2022-02-02 13:48 UTC, SevenWaysDP commented on src/store/tasks.ts
> +		} catch (error) {
this is a problem

2022-02-07 14:12 UTC, SevenWaysDP requested changes

2022-02-07 14:12 UTC, SevenWaysDP commented on src/serverApi/v3/api.ts
> +        importUserControllerFindAllImportUsers: async (firstName?: string, lastName?: string, loginName?: string, match?: Array<'auto' | 'admin' | 'none'>, flagged?: boolean, classes?: string, role?:
Many functions have been renamed. Please check!

2022-02-07 14:27 UTC, odalys-dataport commented on src/components/templates/TasksDashboardStudent.vue
> +					class="pb-16"
Yes, it is :)

2022-02-07 14:28 UTC, odalys-dataport commented on src/serverApi/v3/api.ts
> +        importUserControllerFindAllImportUsers: async (firstName?: string, lastName?: string, loginName?: string, match?: Array<'auto' | 'admin' | 'none'>, flagged?: boolean, classes?: string, role?:
Mmh I'll update the server and generate again to be sure, thanks!

2022-02-07 14:45 UTC, SevenWaysDP submitted a review, later dismissed

2022-02-07 15:24 UTC, SevenWaysDP approved these changes

2022-02-07 15:42 UTC, merged