Feature/BC-1269 - Drag&Drop for courses card
hpi-schul-cloud/nuxt-client pull request #2070
Opened 2022-03-04 12:58 UTC by murat-merdoglu-hpi

# Short Description
- Implemented Drag&Drop operations for course cards

## Links to Ticket and related Pull-Requests
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1269

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-03-07 09:25 UTC, virgilchiriac commented on src/store/types/room.ts
> +}
should use instead BoardElementResponseTypeEnum from api.ts

2022-03-07 09:28 UTC, virgilchiriac requested changes

2022-03-07 09:28 UTC, virgilchiriac commented on src/store/room.ts
> +			await this.fetchContent(this.roomData.roomId);
why we need to fetch data? if the first call is not succesfull, is should be enought to handle the exception, or?

2022-03-07 09:34 UTC, virgilchiriac commented on src/components/templates/RoomDashboard.vue
> +.ghost {
In wonder if we should make this class global, insteaad of being scoped only for this component...

2022-03-07 09:34 UTC, murat-merdoglu-hpi commented on src/store/room.ts
> +			await this.fetchContent(this.roomData.roomId);
Because the first call returns nothing, the second one is used to refresh the board elements.

2022-03-07 09:37 UTC, murat-merdoglu-hpi commented on src/store/types/room.ts
> +}
I prefer to define the enums on front-end side. What if a backend user changes the code with no idea if it is used in FE.

2022-03-07 09:57 UTC, MartinSchuhmacher commented on locale/en.json
> +	"pages.room.locked.label.info": "You are not allowed the view the task details.",
"...not allowed to view ..."

2022-03-07 09:57 UTC, MartinSchuhmacher commented on src/components/molecules/RoomLessonCard.vue
> +			if (this.role == Roles.Teacher) {
maybe check for explicit "==="?

2022-03-07 09:57 UTC, MartinSchuhmacher commented on src/components/molecules/RoomLessonCard.vue
> +			if (this.role == Roles.Teacher) {
maybe check for explicit "==="?

2022-03-07 09:57 UTC, MartinSchuhmacher commented on src/components/molecules/RoomLessonCard.vue
> +			if (this.role == Roles.Student) {
maybe check for explicit "==="?

2022-03-07 09:57 UTC, MartinSchuhmacher commented on src/components/molecules/RoomLockedCard.unit.ts
> +	it("should show error message when it is clicked", async () => {
here seems to go something wrong within the test

2022-03-07 09:57 UTC, MartinSchuhmacher commented on src/components/molecules/RoomTaskCard.vue
> +			if (this.role == Roles.Teacher) {
maybe check for explicit "==="?

2022-03-07 09:57 UTC, MartinSchuhmacher commented on src/components/molecules/RoomTaskCard.vue
> +			if (this.role == Roles.Student) {
maybe check for explicit "==="?

2022-03-07 09:57 UTC, MartinSchuhmacher commented on src/components/molecules/RoomTaskCard.vue
> +			if (this.role == Roles.Teacher) {
maybe check for explicit "==="?

2022-03-07 09:57 UTC, MartinSchuhmacher commented on src/components/molecules/RoomLessonCard.vue
>  						name: this.$t("pages.room.taskCard.label.revert"),
should be a different language label from lessonCard instead from taskCard if its in RoomLessonCard, right?

2022-03-07 09:57 UTC, MartinSchuhmacher commented on src/components/molecules/RoomTaskCard.vue
> +			if (this.role == Roles.Student) {
maybe check for explicit "==="?

2022-03-07 09:57 UTC, MartinSchuhmacher commented on src/serverApi/v3/api.ts
> +     * ElementType. Can be any of: \"task\", \"lesson\", \"lockedlesson\"
this was changed by the backend as it should be "lockedtask" here, should we re-create api.ts to have the correct description here?

2022-03-07 09:57 UTC, MartinSchuhmacher commented on src/store/room.ts
> +			await this.fetchContent(this.roomData.roomId);
I think the items need to be re-fetched after sorting, or does the api hands them back already in the correct order? in case not I guess there needs to happen some kind of fetching

2022-03-07 09:58 UTC, MartinSchuhmacher commented on src/store/room.ts
> +			await this.fetchContent(this.roomData.roomId);
ah did not see Murats comment during my review, so you can  ignore my comment ^^

2022-03-07 10:28 UTC, virgilchiriac commented on src/store/room.ts
> +			});
what we do with the error? Should we not display something back?

2022-03-07 13:36 UTC, virgilchiriac commented on src/components/molecules/RoomLockedCard.vue
> +			defaultTitleColor: "#54616e",
could be something [from the theme](https://github.com/hpi-schul-cloud/nuxt-client/blob/main/src/themes/base/styles/variables/_colors.scss), like primary, or --color-secondary?

2022-03-07 13:43 UTC, virgilchiriac commented on src/store/room.ts
> +	};
is there a reason why we don't replace the old error completly?

2022-03-11 19:09 UTC, murat-merdoglu-hpi commented on src/store/room.ts
> +			});
If we fetch it in catch block, businessError state will be reset.

2022-03-14 12:24 UTC, MartinSchuhmacher commented on locale/de.json
> +	"pages.room.locked.label.info": "Sie sind nicht berechtigt, die Aufgabendetails anzuzeigen.",
"...die Aufgabendetails anzusehen."

2022-03-14 12:24 UTC, MartinSchuhmacher commented on src/components/templates/RoomDashboard.unit.ts
> +let mockData = {
why is this let? was not able to find a re-declaration

2022-03-14 16:39 UTC, murat-merdoglu-hpi commented on src/store/room.ts
> +	};
Error handling will be done in another ticket. 
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1394

2022-03-14 17:40 UTC, virgilchiriac approved these changes

2022-03-15 08:31 UTC, merged