Bc 857
hpi-schul-cloud/nuxt-client pull request #2076
Opened 2022-03-11 09:22 UTC by Loki-Afro

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-03-17 15:23 UTC, CeEv commented on .dockerignore
> +**/*.unit.js
The linter want a line break.

2022-03-17 15:25 UTC, CeEv requested changes

2022-03-17 15:26 UTC, CeEv requested changes

2022-03-18 09:04 UTC, Loki-Afro commented on Dockerfile
> +CMD [ "./run.sh"]
linter should not care about Dockerfile

2022-03-18 09:05 UTC, Loki-Afro commented on Dockerfile
> +FROM docker.io/node:16
so?

2022-03-18 09:28 UTC, Loki-Afro commented on .dockerignore
> +**/*.unit.js
linter should not care about .dockerignore

2022-03-18 09:51 UTC, odalys-dataport submitted a review, later dismissed

2022-03-18 11:44 UTC, CeEv approved these changes

2022-03-18 12:05 UTC, merged