Bc 1447 language key fab
hpi-schul-cloud/nuxt-client pull request #2089
Opened 2022-03-17 14:22 UTC by luizzaly

# Short Description

Adjusted languages keys for FAB. Added common label "Erstellen"

## Links to Ticket and related Pull-Requests
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1447

<img width="1397" alt="Bildschirmfoto 2022-03-17 um 15 22 28" src="https://user-images.githubusercontent.com/39086430/158827357-cc0dd322-ef03-4e99-955d-3dc5b59fd27a.png">

2022-03-17 19:04 UTC, MartinSchuhmacher requested changes

2022-03-17 19:04 UTC, MartinSchuhmacher commented on src/components/atoms/vCustomFab.vue
> +
<img width="296" alt="grafik" src="https://user-images.githubusercontent.com/55735359/158876532-4a47acc5-f2d2-4d43-ac4b-2d3ea93b0f3a.png">

I added this property on my branch https://github.com/hpi-schul-cloud/nuxt-client/pull/2084 
please check if that also solves the issue you wanted to solve here, so we can be consistent without creating a new class

2022-03-18 10:57 UTC, monaweitzenberg commented on locale/de.json
>  	"pages.administration.teachers.fab.import.aria": "Lehrkraft importieren",
solved!

2022-03-18 10:57 UTC, monaweitzenberg commented on locale/de.json
> +	"pages.rooms.fab.add": "Neuer Kurs ",
solved!

2022-03-18 10:57 UTC, monaweitzenberg commented on locale/de.json
>  	"pages.rooms.fab.import.aria": "Kurs importieren",
solved!

2022-03-18 11:01 UTC, monaweitzenberg commented on src/components/atoms/vCustomFab.vue
> +
solved!

2022-03-23 16:21 UTC, monaweitzenberg commented on src/components/atoms/vCustomFab.vue
> +				<span class="v-fab-action">
That makes sense :) removed

2022-03-23 16:30 UTC, MartinSchuhmacher approved these changes

2022-03-24 14:37 UTC, merged