Feature/n21 51 custom login link
hpi-schul-cloud/nuxt-client pull request #2109
Opened 2022-03-25 15:38 UTC by fzoubi-cap

# Short Description

A field for the login link for Niedersachsen new GUI. This field generates the login link, and has a copy functionality.

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-03-29 15:32 UTC, uidp submitted a review, later dismissed

2022-03-30 07:54 UTC, IgorCapCoder commented on src/store/types/env-config.ts
> +	FEATURE_LOGIN_LINK_ENABLED?: boolean;
good point! Yes we have, but we didn't create a PR for that 😅 .. coming right up! and thx ^^

2022-03-31 08:27 UTC, Metauriel submitted a review, later dismissed

2022-04-14 12:03 UTC, mamutmk5 requested changes
missing the translation for ukraine

2022-04-19 13:20 UTC, Metauriel approved these changes

2022-04-19 13:52 UTC, merged