BC-1460 - Course menu actions
hpi-schul-cloud/nuxt-client pull request #2113
Opened 2022-03-30 17:28 UTC by murat-merdoglu-hpi

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.hpi-schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-03-31 14:14 UTC, MartinSchuhmacher requested changes

2022-03-31 14:14 UTC, MartinSchuhmacher commented on src/pages/rooms/_id/index.unit.ts
> +		it("should have 'Share Course' menu if 'FEATURE_COURSE_SHARE' flag set", () => {
"...set to true"

2022-03-31 14:14 UTC, MartinSchuhmacher commented on src/pages/rooms/_id/index.unit.ts
> +		it("should have 'Copy/Duplicate Course' menu if 'FEATURE_COURSE_COPY' flag set", () => {
"...set to true"

2022-03-31 14:14 UTC, MartinSchuhmacher commented on src/pages/rooms/_id/index.unit.ts
> +		it("should call shareCourse method when 'Invite to the course' menu clicked", async () => {
I guess the "Invite to the course" needs to be changed for shareCourse :)

2022-04-01 12:21 UTC, murat-merdoglu-hpi commented on src/store/room.ts
> +	courseShareToken: string = "";
Changed.
Maybe we should work on access modifiers generally soon.

2022-04-01 13:25 UTC, MartinSchuhmacher approved these changes

2022-04-01 13:26 UTC, merged