BC-1614 Rename env-var for student-visibilty-toggle
hpi-schul-cloud/nuxt-client pull request #2136
Opened 2022-04-14 12:25 UTC by dyedwiper

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.dbildungscloud.de/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-04-21 12:23 UTC, CeEv requested changes

2022-04-27 08:23 UTC, odalys-dataport requested changes

2022-05-02 09:50 UTC, CeEv commented on src/components/organisms/administration/PrivacySettings.vue
> +			EnvConfigModule.getTeacherStudentVisibilityIsConfigurable,
For no i think not. It is not displayed if it is not configurable. It take always the setting from the school.
In future with a additional ticket it should be changed. Always displayed and if configurable is false / or not set in school display the default value.

2022-05-02 12:45 UTC, dyedwiper commented on src/components/organisms/administration/PrivacySettings.vue
> +			EnvConfigModule.getTeacherStudentVisibilityIsConfigurable,
No. The permissions are only read from the database. The logic stayed the same here as before.

2022-05-02 13:09 UTC, dyedwiper commented on src/components/organisms/administration/PrivacySettings.unit.js
> +				TEACHER_STUDENT_VISIBILITY__IS_CONFIGURABLE: true,
The button is not displayed. That's the same as before. Another ticket for changing that has been opened.

2022-05-03 07:43 UTC, CeEv approved these changes

2022-05-03 07:55 UTC, merged