feature/BC-1761 - Adding more info on Lesson Card's chip
hpi-schul-cloud/nuxt-client pull request #2167
Opened 2022-05-11 13:35 UTC by murat-merdoglu-hpi

# Short Description
- Adding more info on Lesson Card's chip

## Links to Ticket and related Pull-Requests
- https://ticketsystem.dbildungscloud.de/browse/BC-1761
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/3455

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.dbildungscloud.de/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-05-12 09:50 UTC, MartinSchuhmacher requested changes

2022-05-12 09:50 UTC, MartinSchuhmacher commented on locale/de.json
> +	"common.words.planned": "planned",
Please change languages accordingly

2022-05-12 09:50 UTC, MartinSchuhmacher commented on src/components/molecules/RoomLessonCard.unit.ts
> +				const expectedString = "Aufgaben: 3 published / 2 draft"; // TODO: change the hardcoded words to lang values
maybe implement language keys here

2022-05-18 13:49 UTC, Metauriel approved these changes

2022-05-18 17:54 UTC, MartinSchuhmacher approved these changes
great work!

2022-05-18 18:02 UTC, merged