feature/BC-1550 - Creating copy result component
hpi-schul-cloud/nuxt-client pull request #2170
Opened 2022-05-16 07:47 UTC by murat-merdoglu-hpi

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.dbildungscloud.de/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-05-19 18:06 UTC, MartinSchuhmacher requested changes

2022-05-19 18:06 UTC, MartinSchuhmacher commented on src/components/molecules/CopyResult.unit.ts
> +declare let createComponentMocks: Function;
why is "declare let" used here? did not see that yet

2022-05-19 18:06 UTC, MartinSchuhmacher commented on src/pages/TestComponent.page.vue
> +						Open Copy Result
language key?

2022-05-20 06:58 UTC, murat-merdoglu-hpi commented on src/components/molecules/CopyResult.unit.ts
> +declare let createComponentMocks: Function;
Because this 'createComponentMocks' exists already for the js test files. We need to declare it again for ts unit files as far as I know.

2022-05-20 07:00 UTC, murat-merdoglu-hpi commented on src/pages/TestComponent.page.vue
> +						Open Copy Result
This page is only used to see the component and will be removed after the first usage of the component somewhere.

2022-05-20 07:00 UTC, murat-merdoglu-hpi commented on src/pages/TestComponent.page.vue
> +				<h4>Copy Result</h4>
This page is only used to see the component and will be removed after the first usage of the component somewhere.

2022-05-20 07:18 UTC, MartinSchuhmacher approved these changes

2022-05-20 12:57 UTC, merged