Bc 1644 not allow change name sync school
hpi-schul-cloud/nuxt-client pull request #2176
Opened 2022-05-20 14:04 UTC by christian-darsow

# Short Description

Changing the name of the school on the new admin page should only be possible for non-synced schools, otherwise editing should be disabled.

## Links to Ticket and related Pull-Requests

https://ticketsystem.dbildungscloud.de/browse/BC-1644

## Changes

## Data-security <sub><sup>details [on Confluence](https://docs.dbildungscloud.de/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-05-20 14:41 UTC, MartinSchuhmacher requested changes

2022-05-20 14:41 UTC, MartinSchuhmacher commented on src/store/schools.unit.ts
> +				expect(schoolsModule.schoolIsSynced).toStrictEqual(false);
since we still support active moodle systems there should also be a test for this system in getIsSynced

2022-05-20 14:41 UTC, MartinSchuhmacher commented on src/components/organisms/administration/GeneralSettings.unit.js
> +			schoolsModule.setSystems([]);
I am not sure if this test is correct or at least if there should be another test. Because even if a school has the `provider: "general"` system it is by definition not a synced school. There should be one systems array with only the `iserv-idm` case and another systems array for this case where `general`is set as provider and it would still be a editable. A combination of `general` and `iserv-idm` inside one array is no realistic case. Maybe you can then have it a third case like this is now, if there is no system at all.

2022-05-23 09:37 UTC, christian-darsow commented on src/store/schools.unit.ts
> +				expect(schoolsModule.schoolIsSynced).toStrictEqual(false);
To test all possible cases for synced and non-synced schools tests for moodle and itslearning schools have now been added

2022-05-23 09:39 UTC, christian-darsow commented on src/components/organisms/administration/GeneralSettings.unit.js
> +			schoolsModule.setSystems([]);
An explicit test for non-synced school has been added and the mocked systems collection has been adapted to be realistic

2022-05-23 12:15 UTC, MartinSchuhmacher requested changes

2022-05-23 12:15 UTC, MartinSchuhmacher commented on src/components/organisms/administration/GeneralSettings.unit.js
> +					systems: [{ $oid: "0000d186816abba584714c91" }],
I recommend using the variable here as otherwise the value here needs to be changed as well once the value in the variable is changed.

2022-05-23 14:23 UTC, virgilchiriac approved these changes

2022-05-23 16:32 UTC, MartinSchuhmacher submitted a review, later dismissed

2022-05-25 11:59 UTC, virgilchiriac submitted a review, later dismissed

2022-05-27 08:41 UTC, MartinSchuhmacher approved these changes

2022-05-27 09:55 UTC, merged