BC-168 - remove obsolete layouts
hpi-schul-cloud/nuxt-client pull request #2216
Opened 2022-06-28 18:25 UTC by odalys-dataport

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-06-30 08:51 UTC, MartinSchuhmacher requested changes

2022-06-30 08:51 UTC, MartinSchuhmacher commented on src/layouts/legacyLoggedIn.vue
> +		<skip-links />
is that needed at all?

2022-06-30 08:55 UTC, odalys-dataport commented on src/utils/navbarBaseItems.js
> +		title: "global.topbar.loggedOut.actions.steps",
I renamed the keys like this, because the layout that's referred is removed

2022-06-30 08:56 UTC, odalys-dataport commented on src/layouts/legacyLoggedIn.vue
> +		<skip-links />
skip links are a necessary accessibility feature for navigating with the keyboard

2022-06-30 19:29 UTC, MartinSchuhmacher commented on src/utils/navbarBaseItems.js
> +		title: "global.topbar.loggedOut.actions.steps",
I understand why you changed it...but to which value did you change it? I can not find a language key with the name "global.topbar.loggedOut.actions.steps"

2022-07-01 11:51 UTC, MartinSchuhmacher approved these changes

2022-07-04 11:52 UTC, merged