sorting drafts by createdAt desc
hpi-schul-cloud/nuxt-client pull request #2244
Opened 2022-07-27 11:19 UTC by odalys-dataport

# Short Description

Change sorting of draft tasks to show newest created on top.

https://ticketsystem.dbildungscloud.de/browse/BC-2072

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-07-28 05:56 UTC, MartinSchuhmacher requested changes
I see a lot of changed behaviour in TaskItemTeacher and tasks store but no adjusted tests for either of them. Please fix that.

2022-07-28 05:56 UTC, MartinSchuhmacher commented on src/components/molecules/TaskItemTeacher.vue
> +			// TODO: do we really need a label for no submission date?
please decide on that topic within this PR so this comment can be removed and dont just push the decision in the future

2022-07-28 05:56 UTC, MartinSchuhmacher commented on locale/ua.json
> +	"components.molecules.TaskItemMenu.labels.createdAt": "створено при",
Please put a capital "С" here in the beginning

2022-07-28 12:42 UTC, MartinSchuhmacher requested changes

2022-07-28 12:42 UTC, MartinSchuhmacher commented on src/store/tasks.ts
> +			);
due to the sorting implemented in getCourseFilters I would suggest adding a test case for that as well in the according test file

2022-07-28 12:42 UTC, MartinSchuhmacher commented on src/components/molecules/TaskItemTeacher.vue
> -						{{ `&nbsp;– ${plannedLabel}` }}
remove computed plannedLabel and test for it if not necessary?

2022-07-28 12:42 UTC, MartinSchuhmacher commented on src/components/molecules/TaskItemTeacher.vue
> -		dueDateLabel() {
remove tests for dueDateLabel?

2022-07-28 14:38 UTC, odalys-dataport commented on src/components/molecules/TaskItemTeacher.vue
> -		dueDateLabel() {
I'm a bit confused. plannedLabel and dueDateLabel got moved to taskLabel and tested there

2022-07-29 14:34 UTC, MartinSchuhmacher approved these changes

2022-08-01 11:59 UTC, MartinSchuhmacher commented on src/components/molecules/TaskItemTeacher.vue
> +				if (isToday(new Date(createdAt))) {
does the isToday method require the new Date() ? 
if the call would look like `isToday(createdAt)` i think it would look smoother

2022-08-01 11:59 UTC, MartinSchuhmacher commented on src/plugins/datetime.js
> +		date.getDate() == today.getDate() &&
please check for === instead of just ==

2022-08-01 17:56 UTC, MartinSchuhmacher approved these changes

2022-08-01 18:33 UTC, merged