Draft: Bc 2225 improve notification styling
hpi-schul-cloud/nuxt-client pull request #2245
Opened 2022-07-28 09:39 UTC by OliverHappe

# Short Description

Refactors Alert-Notification to be accessible, easier to use and fit our new styling guidelines

## Links to Ticket and related Pull-Requests

https://ticketsystem.dbildungscloud.de/browse/BC-2225

## Changes

 * use `v-alert` instead of `v-snackbar` for notifications
 * add typescript typing to store
 * smaller api for Alert-Component
 * Rename from `Snackbar` to `Alert`
 * Acessible color choices and aria-labeling

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-07-28 14:39 UTC, odalys-dataport commented on src/pages/RoomDetails.page.vue
>  			if (businessError.statusCode !== "") {
We should use specified error messages for each entity as according to designs

2022-07-28 14:41 UTC, odalys-dataport requested changes

2022-07-28 14:41 UTC, odalys-dataport commented on src/components/molecules/Alert.vue
> +const DEFAULT_TIMEOUT = 5000;
This should be defined in store as well I think

2022-07-28 14:41 UTC, odalys-dataport commented on src/components/molecules/Alert.vue
> +.alert_wrapper-mobile {
our class naming convention is kebab case

2022-07-29 07:51 UTC, OliverHappe commented on src/pages/RoomDetails.page.vue
>  			if (businessError.statusCode !== "") {
i suggest we move this to the modal refactoring since we will be redesigning the whole feedback flow in that ticket

2022-07-29 08:07 UTC, MartinSchuhmacher requested changes

2022-07-29 08:34 UTC, OliverHappe commented on src/components/molecules/Alert.vue
> +	bottom: 5vh;
i could not find any vh variables; spacing and size variables are all in `rem` which might be suitable for this. 

i picked 5vh to have the same placement as vuetify's snackbar on mobile screens

2022-07-29 12:35 UTC, MartinSchuhmacher commented on src/components/molecules/Alert.vue
> +	bottom: 5vh;
alright, makes sense to me

2022-07-29 12:35 UTC, MartinSchuhmacher approved these changes

2022-07-29 12:48 UTC, merged