BC-2362 - show alert in top bar
hpi-schul-cloud/nuxt-client pull request #2273
Opened 2022-09-12 14:25 UTC by virgilchiriac

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-09-14 12:51 UTC, odalys-dataport requested changes

2022-09-14 12:51 UTC, odalys-dataport commented on src/components/legacy/TheTopBar.unit.js
>  import TheTopBar from "./TheTopBar";
Please remove comments, if they aren't necessary

2022-09-14 12:51 UTC, odalys-dataport commented on src/components/molecules/StatusAlerts.vue
> +<script>
If this is a new component, it should be implemented with typescript and the composition api

2022-09-14 12:51 UTC, odalys-dataport commented on src/plugins/datetime.js
> +export const timeAgo = (date) => {
This looks like it's doing the same or something similar like the function `fromNow` in this plugin, so maybe we can refactor this?

2022-09-14 12:51 UTC, odalys-dataport commented on src/utils/store-accessor.ts
> -	copyModule = getModule(CopyModule, store);
Thanks for keeping this sorted! :)

2022-09-14 13:22 UTC, virgilchiriac commented on src/plugins/datetime.js
> +export const timeAgo = (date) => {
is indeed a method of datejs, but doing the opposite. Can be refactored so that it looks the same and taking account the UTC convertion

2022-09-20 11:51 UTC, tofixx commented on src/plugins/datetime.js
> +export const timeAgo = (date) => {
merged the bahaviour into fromNow. however "to" and "fromNow" seems to work each in both directions (past/future). just kept using local time, added this as new flag in fromNow

2022-09-20 11:52 UTC, tofixx commented on src/plugins/datetime.js
> +	if (isLocalTimeZone == true){
fromNow and daysjs.to seems to have same behaviour, just checked here for local time to skip utc here

2022-09-23 10:11 UTC, murat-merdoglu-hpi commented
The implementation should be the 'mobile first' design approach.

![image](https://user-images.githubusercontent.com/64781656/191939196-a0d46a88-9d10-45e9-9c5c-690cfb9ed362.png)

2022-09-23 10:16 UTC, murat-merdoglu-hpi commented on src/components/legacy/TheTopBar.unit.js
> +		const wrapper = shallowMount(TheTopBar, {
Try to avoid using the `shallowMount` method. `shallowMount`method doesn't render its child components. But the newly created component `StatusAlert.vue` is its child.

2022-10-13 05:48 UTC, murat-merdoglu-hpi approved these changes

2022-10-14 11:37 UTC, OliverHappe commented on src/store/status-alerts.ts
> +	async fetchStatusAlerts() {
missing return type void

2022-10-14 11:37 UTC, OliverHappe commented on src/components/legacy/TheTopBar.vue
> +				data-test-id="top-menu-btn"
i think this should be data-testid

2022-10-14 11:37 UTC, OliverHappe commented on src/components/legacy/TheTopBar.vue
> +					data-test-id="status-alerts-icon"
data-testid

2022-10-14 11:37 UTC, OliverHappe commented on src/components/legacy/TheTopBar.vue
> +		showStatusAlertIcon() {
show[...] suggest to me that this function is a toggle/ setter to actually show the statusalert-icon.

i suggest to instead call it "isShowStatusAlertIcon" to clearly convey that this is a getter describing a specific state of the component.

2022-10-14 11:37 UTC, OliverHappe commented on src/components/legacy/TheTopBar.vue
> +			const color = this.statusAlertDanger()
i think statusAlertDanger() is a superflous codesplit. 

suggestion:

`const isDangerStatusAlert: boolean = <body of statusAlertDanger()>`

use isDangerStatusAlert as a condition in the `color` assignment. 

remove statusAlertDanger() method.

2022-10-14 11:37 UTC, OliverHappe commented on src/components/legacy/TheTopBar.vue
> +			return color;
i think the color variable is superflous - we can return the result immediately without assigning it first

2022-10-14 11:37 UTC, OliverHappe commented on src/components/molecules/StatusAlerts.unit.ts
> +describe("@components/molecules/StatusAlerts", () => {
a test to check if nothing is rendered if there are no statusalerts would be a nice addition

2022-10-14 11:37 UTC, OliverHappe commented on src/components/molecules/StatusAlerts.vue
> +	padding-top: var(--space-xs-4);
please use the vuetify spacing utility classes. e.g. `pt-2`

2022-10-14 11:37 UTC, OliverHappe commented on src/components/molecules/StatusAlerts.vue
> +			<v-card-text class="py-2">
the parent div also has padding. i suggest to merge the two elements if possible. i don't see a reason for the outer div to wrap v-card-text.

2022-10-14 14:41 UTC, odalys-dataport commented on src/components/molecules/StatusAlerts.unit.ts
> +describe("@components/molecules/StatusAlerts", () => {
this is tested in the top bar

2022-10-17 08:21 UTC, OliverHappe commented on src/components/molecules/StatusAlerts.unit.ts
> +describe("@components/molecules/StatusAlerts", () => {
i think it's important to view one component as a relevant unit when writing unit tests. 

desired behavior should not only be tested in components outside of that unit. the topbar should only test if StatusAlert component exists. Behavior of StatusAlert should be tested in StatusAlert unit tests

2022-10-17 12:42 UTC, odalys-dataport commented on src/components/molecules/StatusAlerts.unit.ts
> +describe("@components/molecules/StatusAlerts", () => {
aah ok, done :)

2022-10-18 07:40 UTC, OliverHappe approved these changes

2022-10-18 07:50 UTC, merged