BC-2427 - Elevations Vuetify
hpi-schul-cloud/nuxt-client pull request #2279
Opened 2022-09-28 08:00 UTC by uidp

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-09-29 19:17 UTC, odalys-dataport commented on src/layouts/loggedOut.vue
> +	<div class="page v-application">
What does this class do?

2022-09-29 19:20 UTC, odalys-dataport commented
I see that the elevation.scss was not removed. What would be necessary to achieve that?

2022-09-30 09:32 UTC, odalys-dataport commented on src/layouts/loggedOut.vue
> +	<div class="page v-application">
This might be resolved with the current PR regarding enabling vuetify everywhere
https://github.com/hpi-schul-cloud/nuxt-client/pull/2282

2022-10-06 20:57 UTC, odalys-dataport requested changes
Please fix failing unit tests

2022-10-10 06:20 UTC, monaweitzenberg submitted a review, later dismissed
looks fine for me

2022-10-10 09:04 UTC, odalys-dataport approved these changes

2022-10-10 09:04 UTC, merged