BC-2426 - theme and colors
hpi-schul-cloud/nuxt-client pull request #2284
Opened 2022-10-04 06:47 UTC by christian-darsow

# Short Description

Define colors per theme only via vuetify settings. 
Map old color vars to vuetify color system.

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-2426

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-10-05 17:20 UTC, odalys-dataport requested changes

2022-10-05 17:20 UTC, odalys-dataport commented on src/themes/base/styles/utility/_colors.scss
>  // apply to toasts
Can we move these styles to toast component itself?

2022-10-06 06:27 UTC, christian-darsow commented on src/themes/base/styles/utility/_colors.scss
>  // apply to toasts
Lets please investigate on this in a follow up ticket

2022-10-06 20:54 UTC, odalys-dataport requested changes

2022-10-06 20:54 UTC, odalys-dataport commented on src/themes/base/styles/vuetify-custom.scss
> +		background-color: var(--v-primary-darken1) !important;
Can we use this instead? I'm not sure, but if it works it would be prettier

[$btn-states](https://vuetifyjs.com/en/api/v-btn/#sass-btn-states)	
```(
  'states': (
    'activated': $btn-active-opacity,
    'focus': $btn-focus-opacity,
    'hover': $btn-hover-opacity
  )
);```

2022-10-06 20:54 UTC, odalys-dataport commented on src/themes/base/vuetify.options.js
> +					base: "#ffffff",
white is set to #ffffff by vuetify itself, why are we overwriting this?

2022-10-06 20:54 UTC, odalys-dataport commented on src/themes/base/vuetify.options.js
> +					darken1: "#444444",
Are these discussed with UX? Maybe we can use these colors provided by vuetify instead. The only big difference would be in our base gray (#aaaaaa) and vuetify's base grey (#9e9e9e)

grey lighten-3 -> #EEEEEE
grey lighten-2 -> #E0E0E0
grey darken-3 -> #424242 (veeery similar)

https://vuetifyjs.com/en/styles/colors/#material-colors

2022-10-06 20:54 UTC, odalys-dataport commented on src/themes/brb/vuetify.options.js
> +					darken1: "#086e71",
Just out of curiosity, does defining these mean we "lose" all other variants like primary-darken3?

2022-10-06 20:54 UTC, odalys-dataport commented on src/themes/base/vuetify.options.js
> -				warning: "#FF8311",
Why are primary, secondary and accent color being removed being removed? I see they are defined in default theme. I think I'd prefer it if they were defined in base theme and "inherited" by default theme, if that's possible, but I have no strong opinion on this.

2022-10-07 05:51 UTC, christian-darsow commented on src/themes/brb/vuetify.options.js
> +					darken1: "#086e71",
Yeap, if we define the color vars in this way, vuetify "only" generates the defined ones. So lose darken2, darken3, ...

2022-10-07 05:57 UTC, christian-darsow commented on src/themes/base/vuetify.options.js
> -				warning: "#FF8311",
Primary, secondary and accent are only valid for the default theme (and different for brb, n21, ...). In my opion it's therefore more explicit and clearer to define them there. all values in base are in this way valid for all themes --- well, the base :)

2022-10-07 05:58 UTC, christian-darsow commented on src/themes/base/vuetify.options.js
> +					darken1: "#444444",
Yes, all values are discussed with UX, we also had tried other gray values but then decided to stay with the values we currently use

2022-10-07 06:06 UTC, christian-darsow commented on src/themes/base/vuetify.options.js
> +					base: "#ffffff",
I did that just to have a color var defined in the same way, we can use all other colors. var(--v-white-base)

2022-10-07 06:27 UTC, christian-darsow commented on src/themes/base/styles/vuetify-custom.scss
> +		background-color: var(--v-primary-darken1) !important;
I agree, I like this style! I didnt know that sass var before, but it looks like a way to define opacity values for all buttons at once and not define bg color only for eg primary button. If you have any idea of how to map that, let's do it!

2022-10-08 19:30 UTC, odalys-dataport commented on src/themes/base/vuetify.options.js
> -				warning: "#FF8311",
Could we run into issues with not having a fall back color defined in base in case the other themes fail to load properly in any way?

2022-10-08 19:32 UTC, odalys-dataport commented on src/themes/base/vuetify.options.js
> +					darken1: "#444444",
Alright, then maybe let's find a better name for our own color, because having "grey" and "gray" could be confusing and cause human errors in the future

2022-10-08 19:41 UTC, odalys-dataport commented on src/themes/brb/vuetify.options.js
> +					darken1: "#086e71",
We could think about setting this option then, if we don't need variations and/or creating them ourselves

```
theme: {
    options: { variations: false },
  },
  ```

2022-10-10 06:56 UTC, christian-darsow commented on src/themes/base/vuetify.options.js
> -				warning: "#FF8311",
I would say a missing or miss-configuration of a theme is always an issue. I don't have a strong opinion on what wrong color is worse, vuetify fallback or other-instance fallback. If you say fallback to the default instance is better, lets reintroduce it

2022-10-10 07:15 UTC, monaweitzenberg approved these changes
hex-values looking fine

2022-10-10 07:17 UTC, christian-darsow commented on src/themes/base/vuetify.options.js
> +					darken1: "#444444",
very good point. I would suggest to then call it "grey" and overwrite the material values.

2022-10-10 15:31 UTC, odalys-dataport approved these changes

2022-10-11 13:49 UTC, merged