BC-2409 - vue3 i18n
hpi-schul-cloud/nuxt-client pull request #2300
Opened 2022-11-01 07:09 UTC by christian-darsow

# Short Description

Vue 3 POC: Implement I18n

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-2409

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-11-01 08:43 UTC, virgilchiriac commented on vue3_poc/src/store/types/Language.ts
> +	German = "de",
why not going with all 4 langs already?

2022-11-01 10:54 UTC, christian-darsow commented on vue3_poc/src/store/types/Language.ts
> +	German = "de",
Actually only because we focused in that POC ticket on en + de (and also the lang switch therefore only provides those two options etc)

2022-11-07 11:19 UTC, uidp requested changes

2022-11-07 11:19 UTC, uidp commented on vue3_poc/package.json
> +		"@intlify/unplugin-vue-i18n": "^0.7.0",
What exactly are the advantages of using this plugin? Do we really want to have that now at this point?

2022-11-07 11:19 UTC, uidp commented on vue3_poc/src/components/LanguageSelector.spec.ts
> +		const selectLanguageSpy = vi.spyOn(wrapper.vm, "selectLanguage");
The method `selectLanguage` belongs to the internal implementation of the component and shouldn't be tested IMHO. We should only test the external behaviour of a component. So checking that `i18n.global.locale` gets altered by the click should be enough.

2022-11-07 11:19 UTC, uidp commented on vue3_poc/src/plugins/vuetify.ts
> +	locale: {
Why do we have to do that again seperately although we have the language config in `plugins/i18n.ts` already?

2022-11-07 14:23 UTC, christian-darsow commented on vue3_poc/package.json
> +		"@intlify/unplugin-vue-i18n": "^0.7.0",
While probably not needed for the poc, this plugin takes care of proper build configuration. In the end it reduces bundle size and therefore improves performance. If you think it might be better (clearer) to not have such things now, lets remove it and come back to this docs later https://vue-i18n.intlify.dev/guide/advanced/optimization.html

2022-11-07 14:31 UTC, christian-darsow commented on vue3_poc/src/components/LanguageSelector.spec.ts
> +		const selectLanguageSpy = vi.spyOn(wrapper.vm, "selectLanguage");
Thanks for that :) Makes absolutely sense to me and I changed that test

2022-11-07 14:56 UTC, uidp approved these changes

2022-11-09 06:49 UTC, merged