N21-402 implement collaboraitve files page
hpi-schul-cloud/nuxt-client pull request #2307
Opened 2022-11-04 15:02 UTC by arnegns

# Short Description
This PR contains the first implementation of the new collaborative files section.

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-221

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-11-07 11:01 UTC, uidp requested changes

2022-11-07 11:01 UTC, uidp commented on src/store/files.ts
> +export default class FilesModule extends VuexModule {
The name `FilesModule` is quite general for just the collaborative files. Can we find a more specific name an keep the general name for general files when we need it?

2022-11-07 11:01 UTC, uidp commented on src/store/types/file.ts
> +export enum FileType {
Naming? See above.

2022-11-07 12:53 UTC, arnegns commented on src/pages/files/FilesOverview.page.vue
> +		const headers: DataTableHeader[] = [
Done

2022-11-07 12:58 UTC, Metauriel commented on src/components/base/BaseTable/BaseTable.vue
> +<template>
It probably makes sense to use the vuetify component. maybe look at the task overview as an example

2022-11-10 13:28 UTC, arnegns commented on src/utils/i18n-util.ts
> +export function i18n() {
We removed our wrapper for that

2022-11-10 13:29 UTC, arnegns commented on src/pages/files/FilesOverview.page.vue
> +				if (pathArray.length == 2) {
We have moved all functions to a file like this

2022-11-10 13:31 UTC, arnegns commented on src/serverApi/v3/files/file-meta-list.response.ts
> +import { FileMetaResponse } from "@/serverApi/v3/files/file-meta.response";
Allright :) We have moved the files to another place. Thanks for the advice

2022-11-10 13:34 UTC, arnegns commented on src/store/files.ts
> +export default class FilesModule extends VuexModule {
We named the module files module because it should be the general files module. As you can see in the screenshot the sidebar entry call "Dateien" and will replace "Meine Dateien".

2022-11-10 13:39 UTC, arnegns commented on src/utils/i18n-util.ts
> +			return "uk"; // TODO https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes use everywhere uk (language code)
I dont get what you mean with fallback.. The reason why we needs a mapping from UA to uk is because UA is the country code and uk the language code which is wrongly used in the bildungscloud. We wanted to change this in i18n.js but the codes also come from the server.

2022-11-10 13:41 UTC, arnegns commented on src/router/routes.js
> +		path: "/cfiles/teams/:catchAll(.*)",
It has to be that dynamic because we dont know how many folders exists in one team. Maybe we change everything behind the /teams/... to a query param

2022-11-10 14:13 UTC, arnegns commented on src/store/files.ts
> +export default class FilesModule extends VuexModule {
I thought it will replace it for every instance and not only for nds. UX designed a mockup for this.
But its okay for us, then we ll give an other name and then it can be renamed in the future.

2022-11-10 15:08 UTC, hoeppner-dataport commented on src/store/files.ts
> +export default class FilesModule extends VuexModule {
I see... I think "Files"-MenuItem will replace "My Files"-MenuItem... but this store accesses the collaborativeFiles or NextCloud-Files and should be named this way... and there is/might be another store, that accesses the fileStorage-Service...  and maybe both stores will be used on the files.page in the future.

2022-11-10 15:34 UTC, OliverHappe commented on src/store/types/file.ts
> +export class File {
please do not use classes. 

Always use `interface` or `type`.

please move this file to `/store/types` (a better project structure is currently being developed in the frontend arch group atm. let's use the old places even if they are unintuitive for easier refactoring later)

2022-11-10 15:34 UTC, OliverHappe commented on src/components/templates/default-wireframe.types.ts
> +	disabled?: boolean;
i htink boolean fields should never be undefined (optional) if we do not have to distinguish between the value being `false` and `undefined`.

2022-11-10 15:34 UTC, OliverHappe commented on src/components/templates/default-wireframe.types.ts
> +	dataTestid?: String;
dataTestId should always be required. It makes writing tests (esp. e2e-tests) much easier if all elements have an ID

2022-11-10 15:34 UTC, OliverHappe commented on src/components/templates/default-wireframe.types.ts
> +	testId?: String;
what is the difference between testId and dataTestId? I suggest to pick one (preferably `testId`) if they cover the same functionality

2022-11-10 15:34 UTC, OliverHappe commented on src/components/templates/default-wireframe.types.ts
> +	actions?: FabAction[];
actions should be required. 

instead of not specifying the property we should use an empty array. it gives us stricter typing in components and also does not warrant to check for the properties existance whenever we might want to use Array-Functions

2022-11-10 15:34 UTC, OliverHappe commented on src/pages/files/file-table-item.ts
> +	lastChanged: Date;
is this an actual Date instance in the data or just a date string?

We did not have this discussion in the arch group yet but i suggest to not use the Date-Class in interfaces since it is an actual Class instance which is not "clonable" usiong object spread.

Instead i suggest to use a timestamp string in the data. 

@uidp @hoeppner-dataport @odalys-dataport  what do you think?

2022-11-10 15:34 UTC, OliverHappe commented on src/pages/files/FilesOverview.page.vue
> +			return moment(value).locale(locale()).fromNow();
could you please verify that this function is called only on the initial render of the page and does not refresh constantly?

2022-11-10 15:34 UTC, OliverHappe commented on src/pages/files/FilesOverview.page.vue
> +		const click = function (item: FileTableItem): void {
please use fat-arrow syntax like in line 101

2022-11-10 15:34 UTC, OliverHappe commented on src/pages/files/file-table-utils.ts
> +	return [
I do not think that moving component related business logic to another TS file is a good practice in view. 

I suggest to either 

**A**

Keep these functions in the component. It is ok for Smart components to include business logic.

**B**

Create a [Composable](https://vuejs.org/guide/reusability/composables.html) covering this business logic. 

or **C**

create subcomponents for the different tabs

**Edit**: lets discuss tomorrow which way is the best for us. :)

------
keep in mind that everything that is exported here, currently is exported on a global scope within the whole project.

Functions should be named according to the scope they are relevant for. e.g. `getDeepBreadcrumbs` sounds like a quite generic implementation to create a breadcrumb format based on a string-Array. But in the implementation here it is clear that it is only supposed to be used in the context of the Files-Subpage. We have to careful with global exports (read: any exports) until a better project structure is in place.

2022-11-10 15:34 UTC, OliverHappe commented on src/pages/files/file-table-utils.ts
> +export type FilesPage = {
I think FilesPage as a type name is a bit unfortunate. It can easily be confused with the type of a FilesPage component. 

I suggest `FilesPageConfig` since this closer describes what this object actually contains. Configurational data for the view of a FilesPage :)

2022-11-11 13:41 UTC, arnegns commented on src/pages/files/file-table-utils.ts
> +	return [
As we discussed, we build a composable

2022-11-11 13:42 UTC, arnegns commented on src/pages/files/file-table-utils.ts
> +export type FilesPage = {
Good suggestion :)

2022-11-11 14:19 UTC, arnegns commented on src/pages/files/FilesOverview.page.vue
> +			return moment(value).locale(locale()).fromNow();
I verified this :)

2022-11-16 10:10 UTC, uidp requested changes

2022-11-16 10:10 UTC, uidp commented on src/pages/files/file-table-utils.composable.ts
> +	function getHeaders(t: (key: string) => string): DataTableHeader[] {
Functions should be defined consistently using the arrow notation like `const doStuff = () => {}` and not like `function doStuff() {}`. We do not have a linter rule for that yet.

2022-11-16 10:10 UTC, uidp commented on src/router/guards/permission.guard.ts
> +			next(fallbackRoute);
Shouldn't we display an error page instead of quietly redirecting to another page if the user doesn't have the right permissions to access a route?

2022-11-16 10:22 UTC, arnegns commented on src/components/templates/default-wireframe.types.ts
> +export type Fab = {
Honestly I cant answer these questions. 
In this case we only moved all types which were defined in the component. We only wanted to reuse the Breadcrumb. If you want we revert this change and only move the breadcrumb.

2022-11-16 10:25 UTC, OliverHappe approved these changes

2022-11-16 10:25 UTC, OliverHappe commented on src/pages/files/file-table-utils.composable.ts
> +		t: (key: string) => string,
can we think of usecases where it is useful to give different implementations of the translate function? 

if not it might be cleaner to supply t once to the composable and bind it in the composables internal scope.

2022-11-16 10:25 UTC, OliverHappe commented on src/pages/files/file-table-utils.composable.ts
> +export function fileTableComposable(
composable naming convention as suggested by vue is `use<FeatureName>` so i suggest to rename this to  `useFileTableUtils`

2022-11-16 10:26 UTC, arnegns commented on src/pages/files/FilesOverview.page.vue
> +				return "uk"; // TODO https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes use everywhere uk (language code)
I hope it is temporary but not because the translation is missing, more because the usage is wrong. Not only in client, also in the server

2022-11-16 10:28 UTC, OliverHappe commented on src/router/guards/permission.guard.ts
> +			next(fallbackRoute);
i think that behavior is in development in our sprint right now? 

maybe we approve this routeguard and refactor it to use the new pattern for permission error pages once it is done?

2022-11-16 10:45 UTC, arnegns commented on src/pages/files/file-table-utils.composable.ts
> +export function fileTableComposable(
Thanks for the advice :)

2022-11-16 13:16 UTC, OliverHappe approved these changes

2022-11-16 13:17 UTC, merged