Ew 366
hpi-schul-cloud/nuxt-client pull request #2311
Opened 2022-11-11 12:34 UTC by pkleybolte

# Short Description
Must not be merged before [EW-306](https://ticketsystem.dbildungscloud.de/browse/EW-306's) PRs

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/EW-306
https://ticketsystem.dbildungscloud.de/browse/EW-366

https://github.com/hpi-schul-cloud/schulcloud-client/pull/2999
https://github.com/hpi-schul-cloud/nuxt-client/pull/2299
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3696

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-12-13 10:38 UTC, psachmann requested changes

2022-12-13 10:38 UTC, psachmann commented on src/pages/administration/Migration.page.vue
> +			return envConfigModule.getEnv.SC_THEME.toLowerCase === "brb";
Are the brackets missing? `.toLowerCase()`

2022-12-13 16:36 UTC, pkleybolte commented on src/pages/administration/Migration.page.vue
> +			return "https://docs.dbildungscloud.de/x/VAEbDg?frameable=true";
We could get them from in an env var from the server. They should never change though. That's why I didn't bother.

Actually it improved from a hard coded URL pointing to a movable page to a hard coded URL to a permalink. :grimacing:

2022-12-16 07:21 UTC, psachmann approved these changes

2022-12-16 10:05 UTC, merged