BC-2599 - editor component
hpi-schul-cloud/nuxt-client pull request #2312
Opened 2022-11-11 15:05 UTC by christian-darsow

# Short Description

Implement an editor component for task creation 

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-2599

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-11-18 13:07 UTC, odalys-dataport requested changes

2022-11-18 13:07 UTC, odalys-dataport commented on src/components/molecules/Editor.vue
> +	margin: var(--space-xs) 0 var(--space-md) 0;
Please use vuetify classes instead

2022-11-18 13:07 UTC, odalys-dataport commented on src/components/molecules/Editor.vue
> +						return ["bold", "italic", "underline"];
I'm curious about the decision of what to put into the simple mode and why

2022-11-18 15:10 UTC, christian-darsow commented on src/components/molecules/Editor.vue
> +
I totally agree :)

2022-11-18 15:29 UTC, christian-darsow commented on src/components/molecules/Editor.vue
> +			// as we don't have a translation for ua yet we map to en
There is no such decision. It's just that the translations for en + de + es are already done by CK itself - and for UA we will need to do this on our own in a follow-up ticket. maybe we can even give that back to the community?

2022-11-18 15:32 UTC, christian-darsow commented on src/components/molecules/Editor.vue
> +						return ["bold", "italic", "underline"];
This decision came directly out of my head :) 
But yes, simply there is no decision about modes and features in modes so far
So we might also end up with more then two modes

2022-11-18 17:39 UTC, christian-darsow commented on src/components/molecules/Editor.vue
> +	margin: var(--space-xs) 0 var(--space-md) 0;
I removed the styling for now until we have an UI

2022-11-18 17:42 UTC, christian-darsow commented on src/components/molecules/Editor.vue
> +export default defineComponent({
I'm not sure about that. For vue3 it seems also to be fine for JS components https://vuejs.org/guide/typescript/overview.html#definecomponent -> looking at the tipp there. If the same goes for the plugin we use in vue2 stays unclear to me. Lets talk again on that :)

2022-11-21 18:19 UTC, odalys-dataport approved these changes

2022-11-24 09:56 UTC, merged