BC-2364 Display toast when trying to send mail to an already registered user
hpi-schul-cloud/nuxt-client pull request #2313
Opened 2022-11-14 10:30 UTC by MateuszSapala

# Short Description
When an administrator/teacher tries to send an email to an already registered user, the corresponding toast is displayed

## Links to Ticket and related Pull-Requests
- https://ticketsystem.dbildungscloud.de/browse/BC-2364
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/

## Changes
- toast with a message about an already registered user
- translations for toast

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-11-14 10:40 UTC, sszafGCA submitted a review, later dismissed

2022-11-18 10:36 UTC, sszafGCA approved these changes

2022-11-18 13:18 UTC, Metauriel requested changes

2022-11-18 13:18 UTC, Metauriel commented on src/pages/administration/StudentOverview.page.vue
> +					this.$toast.info(
do we know that this is the only issue that might arise? Do we have a way of interpreting the actual error from the backend, and do some handling based on that? (eg. use this message if user is already registered, and a general error message if something else went wrong)

2022-11-18 14:08 UTC, MateuszSapalaPassCon commented on src/pages/administration/StudentOverview.page.vue
> +					this.$toast.info(
Example response from backend:
{
   "totalReceivedIds":[
      {
         "_id":"6370ed01b3a28164d4736396",
         "roles":[
            {
               "_id":"0000d186816abba584714c99",
               "name":"student",
               "updatedAt":"2022-05-20T13:33:18.077Z",
               "createdAt":"2017-01-01T00:06:37.148Z",
               "roles":[
                  "0000d186816abba584714c95"
               ],
               "permissions":[
                  "TASK_DASHBOARD_VIEW_V3",
                  "JOIN_MEETING",
                  "TEAM_CREATE",
                  "TEAM_EDIT"
               ],
               "__v":0,
               "displayName":"Schüler",
               "id":"0000d186816abba584714c99"
            }
         ],
         "firstName":"Mateusz",
         "lastName":"Sapala",
         "email":"example@gmail.com",
         "schoolId":"5f2987e020834114b8efd6f8",
         "preferences":{
            "registrationMailSend":true
         },
         "fullName":"Mateusz Sapala",
         "id":"6370ed01b3a28164d4736396"
      }
   ],
   "totalMailsSend":1,
   "alreadyRegisteredUsers":null
}

Backend code: https://github.com/hpi-schul-cloud/schulcloud-server/blob/main/src/services/user/services/MailRegistrationLink.js#L85-L89
Don't know what author meant but it probably should look like:
return {
        totalReceivedIds: mailUsers.length,
	totalMailsSend,
	alreadyRegisteredUsers: mailUsers.length - totalMailsSend,
};

Than response for unregistered user would look like:
{
   "totalReceivedIds":1
   "totalMailsSend":1,
   "alreadyRegisteredUsers":0
}
And for registered user like :
{
   "totalReceivedIds":1
   "totalMailsSend":0,
   "alreadyRegisteredUsers":1
}

I can write fix for this backend and I can change error handling to base on "already Registered Users", but it'll be basically the same logic as it is. I don't see any further improvements as the backend doesn't return any other useful information. @Metauriel should I write fix for backend and if so should it be a separate ticket?

2022-11-21 07:26 UTC, MateuszSapalaPassCon commented on src/pages/administration/StudentOverview.page.vue
> +					this.$toast.info(
Also if something else happened in the backend causing it to return a unsuccessfull return code, nuxt will show toast with a generic error message "Registration link(s) could not be sent" (https://github.com/hpi-schul-cloud/nuxt-client/blob/BC-2364-student- registration-already done-toast/src/pages/administration/StudentOverview.page.vue#L515-L520)

2022-11-21 09:10 UTC, Metauriel commented on src/pages/administration/StudentOverview.page.vue
> +					this.$toast.info(
if other errors result in a different message, its fine for me

2022-11-21 09:40 UTC, Metauriel approved these changes

2022-11-21 09:41 UTC, merged