N21-434 enable sanis migration
hpi-schul-cloud/nuxt-client pull request #2325
Opened 2022-11-29 12:44 UTC by IgorCapCoder

# Short Description
Adds a Migration section in the school administration page with a switch to enable the migration from IServ to SANIS for the school.

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-434

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2022-12-02 11:35 UTC, MarvinOehlerkingCap requested changes

2022-12-02 11:35 UTC, MarvinOehlerkingCap commented on src/store/schools.unit.ts
> +				const setOauthMigrationAvailableSpy = jest.spyOn(schoolsModule, "setOauthMigrationAvailable");
Don't use a spy here. Just check if the schoolsModule.oauthMigrationAvailable has the expected value. (Also change this for all other tests)

2022-12-02 11:35 UTC, MarvinOehlerkingCap commented on src/pages/administration/SchoolSettings.page.vue
> +						class="oauth-migration"
why do you need a class here?

2022-12-02 11:35 UTC, MarvinOehlerkingCap commented on src/components/administration/AdminMigrationSection.vue
> +			:disabled="!isMigrationAvailable"
feature check is missing

2022-12-02 11:44 UTC, mrikallab commented on src/components/administration/AdminMigrationSection.vue
> +			:disabled="!isMigrationAvailable"
discussed and done.

2022-12-02 11:48 UTC, mrikallab commented on src/store/types/schools.ts
> +	oauthUserMigration: boolean;
right and changed it, thanks :)

2022-12-02 11:48 UTC, mrikallab commented on src/store/env-config.ts
> +		// TODO: Set default to false
done

2022-12-02 11:50 UTC, mrikallab commented on src/store/schools.unit.ts
> +
I don't know :(

2022-12-02 13:55 UTC, MarvinOehlerkingCap submitted a review, later dismissed

2022-12-05 12:26 UTC, OliverHappe commented on src/components/administration/AdminMigrationSection.vue
> +		const isMigrationEnabled: Ref<boolean | undefined> = ref(
do `false` and `undefined` describe different states in this context?

if not i suggest to evaluate undefined to false in this ref:

`const isMigrationEnabled: Ref<boolean> = ref(schoolsModule.getOauthMigration ?? false);`

2022-12-05 12:30 UTC, OliverHappe commented on src/store/schools.ts
> +		} catch (error: any) {
i would avoid to use explicit `any` anywhere in the app. 

I am aware that there is no good pattern for error-handling in stores atm so I don't want to suggest any elaborate change here. 

instead of `any` i would either suggest `unknown` to properly convey that no known type exists or `{}` to match the type-definition of `this.error`

2022-12-05 12:33 UTC, OliverHappe commented on src/store/schools.ts
> +import {Year, FederalState, School, IOauthMigration} from "./types/schools";
desctructured imports should have wrapping whitespaces

2022-12-05 12:49 UTC, IgorCapCoder commented on src/store/types/schools.ts
> +	oauthUserMigration?: boolean;
Yes, this is also optional in the api. This will enable users of this school to migrate from iserv to sanis and will be set by the admin via the implemented switch and therefor it won't be present at every school.

2022-12-05 12:51 UTC, IgorCapCoder commented on src/store/schools.ts
> +		} catch (error: any) {
done

2022-12-05 14:00 UTC, OliverHappe commented on src/components/administration/AdminMigrationSection.unit.ts
> +            expect(switchComponent.vm.$props.disabled).toBeFalsy();
sorry that i missed this in the initial review. 

vue-test-utils gives you the wrapper.props() function to get a snapshot evaluation of props during the test runtime. 

vm.$props is more of an internal api and should be avoided

you can either use switchComponent.props() to get all props or switchComponent.props('disabled') to only get the value of disabled

2022-12-05 14:05 UTC, OliverHappe approved these changes
i added one more comment as a code quality suggestion. 

still approved, @IgorCapCoder if you do the suggested changes pls ping me in chat for re-approval :)

2022-12-05 14:25 UTC, IgorCapCoder commented on src/components/administration/AdminMigrationSection.unit.ts
> +            expect(switchComponent.vm.$props.disabled).toBeFalsy();
good idea, changed it

2022-12-05 14:29 UTC, OliverHappe submitted a review, later dismissed

2022-12-05 15:37 UTC, OliverHappe approved these changes

2022-12-05 15:53 UTC, merged