N21-496 add migrationMandatory switch
hpi-schul-cloud/nuxt-client pull request #2343
Opened 2022-12-16 15:11 UTC by IgorCapCoder

# Short Description
- change migrationEnable switch to button
- add a switch for mandatory migrations
- get migration flags from server
- add warning for finishing migration

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-496
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3794

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-01-06 08:38 UTC, arnegns requested changes

2023-01-06 08:38 UTC, arnegns commented on locale/de.json
> +	"components.administration.adminMigrationSection.endWarningCard.agree": "Ja, Migration abschließen",
Are they documentated in confluence?

2023-01-06 08:38 UTC, arnegns commented on src/components/administration/AdminMigrationSection.vue
> +			v-if="!isMigrationAvailable && !showEndWarning && !showStartWarning"
You could take this logic to a extra function with a describing name

2023-01-06 08:38 UTC, arnegns commented on src/components/administration/AdminMigrationSection.vue
> +			v-if="!showEndWarning && !showStartWarning"
use v-if instead of v-show when you have problems with change detection

2023-01-06 08:38 UTC, arnegns commented on src/components/administration/AdminMigrationSection.vue
> +		const migrationSwitchLabel: ComputedRef<string> = computed(() => {
Please dont change the label of the switch. This is not goof for useablitity reasons. I dont think that ux would like that. Please dont forget to remove the locale key :)

2023-01-06 08:38 UTC, arnegns commented on src/components/administration/AdminMigrationSection.vue
> +				>
Please let UX take a look on deployed branch before merging

2023-01-06 08:38 UTC, arnegns commented on src/components/administration/AdminMigrationSection.unit.ts
> +            expect(switchComponent.exists()).toBe(true);
You dont need this expect if you check a property one line lower

2023-01-06 08:38 UTC, arnegns commented on src/store/types/schools.ts
> +export type OauthMigrationApiResponse = {
Please remove all these types. It will be auto generated with npm run generate-client:server

2023-01-06 08:38 UTC, arnegns commented on src/store/schools.ts
> +			this.setOauthMigration(mappedOauthMigration.enabled);
Please create an own object for all of these states. So you can capsulate this migration logic.

2023-01-06 08:38 UTC, arnegns commented on src/store/schools.ts
> +			console.log("available: ", mappedOauthMigration.available, "mandatory: ", mappedOauthMigration.mandatory, "enabled: ", mappedOauthMigration.enabled)
remove console logs

2023-01-06 08:38 UTC, arnegns commented on src/store/schools.ts
> +			const oauthMigration: OauthMigrationApiResponse = await $axios.$get(`v3/school/${this.school._id}/migration`);
Please use auto generated api instead of axios with npm run generate-client:server. You can take a look to sharecourse store: https://github.com/hpi-schul-cloud/nuxt-client/blob/957e50cca4baac9ae6c5d2ab9e2c95937b251f51/src/store/share-course.ts#L31-L31

2023-01-06 08:38 UTC, arnegns commented on src/store/schools.ts
> +			const oauthMigration = await $axios.$put(`v3/school/${this.school._id}/migration`, { oauthMigrationPossible: mapOauthMigration.oauthMigrationPossible, oauthMigrationMandatory: mapOauthMigration.oa
See above

2023-01-06 08:38 UTC, arnegns commented on src/store/schools.ts
> +	oauthUserMigration: boolean = false;
please make a new object / class with these new properties

2023-01-06 08:41 UTC, arnegns commented on src/store/school/oauth-migration.mapper.ts
> +export const mapOauthMigrationRequestToApi = (request: OauthMigrationRequest): OauthMigrationApiRequest => {
you could this directly in the action and remove the request objects

2023-01-06 08:43 UTC, arnegns commented on src/store/school/oauth-migration.mapper.ts
> +export const mapApiToOauthMigrationResponse = (response: OauthMigrationApiResponse): OauthMigrationResponse => {
I dont get why you have two response objects. please get rid of one of that

2023-01-09 08:10 UTC, arnegns requested changes

2023-01-09 08:10 UTC, arnegns commented on src/store/schools.ts
> +	oauthMigration = {
Where is the type?

2023-01-13 10:51 UTC, arnegns submitted a review, later dismissed

2023-01-23 10:03 UTC, OliverHappe requested changes
Please split up the existing AdminMigrationSection Component into smaller components

2023-01-23 10:03 UTC, OliverHappe commented on src/store/schools.ts
> +				migrationCompletionDate: oauthMigration.data.oauthMigrationFinished,
is there a reason the names on the api and in our state do not match? maybe it's worth aligning them?

2023-01-23 10:03 UTC, OliverHappe commented on src/components/administration/AdminMigrationSection.unit.ts
> +        const wrapper: Wrapper<any> = mount(AdminMigrationSection, {
why did you switch from shallowMount to mount?

2023-01-23 10:06 UTC, OliverHappe commented on src/components/administration/AdminMigrationSection.vue
> +					color="primary"
did you consult with UX-people that two primary actions next to each other are ok here?

I think it might be underusing contextual styling for an important action like this

2023-01-23 10:53 UTC, IgorCapCoder commented on src/components/administration/AdminMigrationSection.unit.ts
> +        const wrapper: Wrapper<any> = mount(AdminMigrationSection, {
to test the cards, i needed to use a click event and check if elemnts were present and that does not work properly on shallowMount (it seemed to be a standard procedure to use mount in this case. At least that is what was suggested on stackoverflow ^^)

2023-01-23 11:25 UTC, IgorCapCoder commented on src/store/schools.ts
> +				migrationCompletionDate: oauthMigration.data.oauthMigrationFinished,
hm... intriguing idea 😅 - done :)

2023-01-24 15:34 UTC, IgorCapCoder commented on src/components/administration/AdminMigrationSection.vue
> +		<v-card v-if="showStartWarning" class="migration-start-card">
done. i splitted them even in 2 seperate components :)

2023-01-24 15:35 UTC, IgorCapCoder commented on src/components/administration/AdminMigrationSection.vue
> +					color="primary"
yes and changed it afterwards :D

2023-01-30 09:08 UTC, OliverHappe submitted a review, later dismissed

2023-01-30 09:36 UTC, OliverHappe approved these changes

2023-01-30 09:53 UTC, merged