BC-2697 - fix publish task
hpi-schul-cloud/nuxt-client pull request #2353
Opened 2022-12-29 11:28 UTC by WojciechGrancow

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-01-04 16:16 UTC, muratmerdoglu-dp commented on package.json
> +		"node-gyp": "^9.3.0",
Is this dependency really required?

2023-01-04 16:29 UTC, muratmerdoglu-dp commented on src/components/molecules/RoomTaskCard.vue
> +				new Date(new Date(scheduledDate).getTime() - delay) > new Date()
Does the error occur only after the `publish(isPlanned)` button clicked? Have you tested the `finish` and `revert` functions?

2023-01-05 07:34 UTC, WojciechGrancow commented on src/components/molecules/RoomTaskCard.vue
> +				new Date(new Date(scheduledDate).getTime() - delay) > new Date()
yes, this error occur only when task was switched from draft to publish.
With finish and revert functions behaviour of app (UI) is OK

2023-01-05 08:37 UTC, uidp commented on package.json
> +		"node-gyp": "^9.3.0",
Don't think we need that to solve the issue, right?

2023-01-05 08:54 UTC, WojciechGrancow commented on package.json
> +		"node-gyp": "^9.3.0",
this dependecny is required on my local environment, so I make correction in PR

2023-01-05 10:07 UTC, WojciechGrancow commented on src/components/molecules/RoomTaskCard.vue
> +				new Date(new Date(scheduledDate).getTime() - delay) > new Date()
ok i will check it but, on the branch, becouse it is not possible to reproduce on local env

2023-01-11 14:04 UTC, muratmerdoglu-dp reviewed
The package-lock.json file should be removed!

2023-01-12 08:21 UTC, muratmerdoglu-dp requested changes

2023-01-12 08:21 UTC, muratmerdoglu-dp commented on src/components/molecules/RoomTaskCard.unit.ts
> +				const inFutureDate = new Date(Date.now() + 3600 * 1000 * 24);
```suggestion
				jest.useFakeTimers("modern").setSystemTime(new Date()); // this line sets a permanent fake time
				const inFutureDate = new Date(Date.now() + 5001);
```

2023-01-12 08:21 UTC, muratmerdoglu-dp commented on package-lock.json
> +				"node-gyp": "^9.3.0",
This `package-lock.json` file should be removed.

2023-01-13 09:36 UTC, WojciechGrancow commented on package-lock.json
> +				"node-gyp": "^9.3.0",
packed-lock removed form commited changes

2023-01-16 08:29 UTC, muratmerdoglu-dp approved these changes

2023-01-16 17:57 UTC, merged