N21-469 externaltools list school admin
hpi-schul-cloud/nuxt-client pull request #2360
Opened 2023-01-09 07:38 UTC by arnegns

# Short Description
Adds an new section in school administration for managing ctl tools.

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-469

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-01-09 13:28 UTC, mrikallab requested changes

2023-01-09 13:28 UTC, mrikallab commented on src/components/administration/ExternalToolsSection.vue
> +		};
You should add TODO here

2023-01-09 13:37 UTC, arnegns commented on src/serverApi/v3/base.ts
> +export const BASE_PATH = "http://localhost:3031/api/v3".replace(/\/+$/, "");
Thanks

2023-01-10 07:21 UTC, mrikallab approved these changes

2023-01-10 14:41 UTC, closed without merging