N21-470 delete school external tool
hpi-schul-cloud/nuxt-client pull request #2361
Opened 2023-01-10 11:18 UTC by arnegns

# Short Description
Add the delete functionality of an external school from list.
Please review before https://github.com/hpi-schul-cloud/nuxt-client/pull/2360

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-01-10 12:59 UTC, mrikallab requested changes

2023-01-10 12:59 UTC, mrikallab commented on locale/de.json
> +	"components.administration.externalToolsSection.dialog.content": "Möchten Sie das externe Tool <b>{itemName}</b> von Ihrer Schule entfernen? </br></br> Wenn Sie das externe Tool von Ihrer Schule ent
"components.administration.externalToolsSection.table.loading.text": like in ua translation is missing here

2023-01-10 12:59 UTC, mrikallab commented on locale/en.json
> +	"components.administration.externalToolsSection.dialog.content": "Would you like to remove the external tool <b>{itemName}</b> from your school? </br></br> If you remove the external tool from your
components.administration.externalToolsSection.table.loading.text": like in ua translation is missing here

2023-01-10 13:02 UTC, mrikallab submitted a review, later dismissed

2023-01-10 13:10 UTC, OliverHappe commented on src/components/administration/AdminMigrationSection.vue
> +		// TODO: https://ticketsystem.dbildungscloud.de/browse/BC-443
👍🏻

2023-01-10 13:53 UTC, OliverHappe requested changes

2023-01-10 13:53 UTC, OliverHappe commented on src/components/administration/ExternalToolsSection.vue
> +				<v-icon @click="editTool(item)">
clickable icons are not accessible. 

either use a v-btn or `role="button"`. also make sure that all controls are accessible via tab-focus

2023-01-10 13:53 UTC, OliverHappe commented on src/components/administration/ExternalToolsSection.vue
> +		const headers: DataTableHeader[] = useSchoolExternalToolUtils(t).getHeaders;
I suggest to destructure the composable at the start of the setup function (after injects?). This makes external dependencies of the component more clear.

for example: https://vuejs.org/guide/reusability/composables.html#extracting-composables-for-code-organization

using composables directly across the setup function might add complexity when multiple composables are used.

2023-01-10 13:53 UTC, OliverHappe commented on src/components/administration/ExternalToolsSection.vue
> +				<v-icon @click="editTool(item)">
maybe it's worth it to extract the edit buttons into a "toolbar" component? 

this component will just have emits for each button within the toolbar (edit & delete).

After this encapsulation we can better separate visualization (row of buttons) and business logic (still left in this component) 

it also might make adding buttons in the future easier since there is a defined place for it -> the toolbar

2023-01-10 13:53 UTC, OliverHappe commented on src/store/types/school-external-tool.ts
> +	version?: number;
are the optional fields truly optional?

what is the difference between an undefined and unknown status?

2023-01-10 13:53 UTC, OliverHappe commented on src/components/administration/ExternalToolSection.unit.ts
> +					await wrapper.vm.$nextTick()
prefer `await Vue.nextTick()` to avoid `.vm` internal Test-Utils API.

also it might be unneccessary if you await the trigger before:

`await deleteButton.trigger('click')`

2023-01-10 13:53 UTC, OliverHappe commented on src/components/administration/ExternalToolSection.unit.ts
> +				wrapper.vm.itemToDelete = { name: expectedName, status: SchoolExternalToolStatus.Latest, outdated: false };
is it possible to set this value by using the actual UI?

e.g. clicking the delete Button to set this value.

also reading the value could be done in a similar manner, by reading the UI or checking for emitted values (e.g. to the store)

while this unit test tests for a part of the expected behavior it is not actually testing the behavior of the component as it would happen during runtime.

2023-01-10 13:53 UTC, OliverHappe commented on src/components/administration/ExternalToolSection.unit.ts
> +		describe('when itemToDelete is not set', () => {
same comment as in `when itemToDelete is set > should return the name` applies

2023-01-10 14:58 UTC, arnegns commented on src/components/administration/ExternalToolsSection.vue
> +				<v-icon @click="editTool(item)">
I tested this and the icon is clickable without the role. But i changed it :)

2023-01-10 15:03 UTC, arnegns commented on src/components/administration/ExternalToolsSection.vue
> +		const headers: DataTableHeader[] = useSchoolExternalToolUtils(t).getHeaders;
Thanks for the advice :) !

2023-01-11 08:32 UTC, arnegns commented on src/components/administration/ExternalToolSection.unit.ts
> +					await wrapper.vm.$nextTick()
Yes, this works :) Thanks!

2023-01-11 08:33 UTC, arnegns commented on src/components/administration/ExternalToolSection.unit.ts
> +		describe('when itemToDelete is not set', () => {
Ups

2023-01-12 08:06 UTC, OliverHappe submitted a review, later dismissed
approved  mit vorbhalt des einen kommentars zu function names

2023-01-12 08:06 UTC, OliverHappe commented on src/components/administration/ExternalToolsSection.vue
> +			onDeleteTool: deleteTool,
ich glaub beim refactorn gestern hat die IDE hier nicht ganz verstanden was du wolltest. ich denke es ist besser wenn die functions in der component und im template den gleichen namen haben.

2023-01-12 08:10 UTC, arnegns commented on src/components/administration/ExternalToolsSection.vue
> +			onDeleteTool: deleteTool,
Sieht so aus :D Hab ich gerade gezogen :)

2023-01-12 08:11 UTC, OliverHappe approved these changes

2023-01-12 08:27 UTC, merged