BC-2907 toogle switch for teachers substitute courses
hpi-schul-cloud/nuxt-client pull request #2365
Opened 2023-01-16 11:28 UTC by sszafGCA

# Short Description

## Links to Ticket and related Pull-Requests

- https://ticketsystem.dbildungscloud.de/browse/BC-2907

- https://github.com/hpi-schul-cloud/schulcloud-server/pull/3811

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-01-20 11:13 UTC, odalys-dataport requested changes

2023-01-20 11:13 UTC, odalys-dataport commented on src/store/rooms.ts
> +	async align(payload: DroppedObject): Promise<boolean> {
As far as I know vuex actions should follow the fire and forget principle and not return a value

2023-01-20 11:13 UTC, odalys-dataport commented on src/pages/RoomOverview.page.vue
> +	props: {
I'm not sure how you pass props to a page component. Can this be moved into data or a computed property?

2023-01-20 11:13 UTC, odalys-dataport commented on src/pages/RoomOverview.page.vue
> +		isTeacher(roles) {
Naming `isTeacher` suggests this method will return a boolean value, which it doesn't consistently

2023-01-20 11:15 UTC, odalys-dataport commented
Was the placement of the toggle discussed with UX?

2023-01-20 13:34 UTC, virgilchiriac commented
UX related - not good is also that the alert is persisted: once it shows up, it stays opened, no matter if other drag opperation starts
either close on new drag, or maybe use something like snackbar, aka alert with a timeout

2023-01-23 21:34 UTC, sszafGCA commented on src/components/templates/RoomWrapper.vue
> +		<template v-else-if="!isLoading && !hasRooms && !hasImportToken">
moved

2023-01-23 21:36 UTC, sszafGCA commented on src/pages/RoomOverview.page.vue
> +						></v-custom-switch>
fixed

2023-01-23 21:42 UTC, sszafGCA commented on src/pages/RoomOverview.page.vue
> +		}); // TODO: this method will receive a string parameter (Eg, mobile | tablet | desktop)
These TODOs where there before and I don' t want to fix it or neither remove them. I don' t know how this should be correctly implemented because earlier implementation sent this parameter as undefined so I left it as it was.

2023-01-23 21:48 UTC, sszafGCA commented on src/store/rooms.ts
> +				undefined,
I dont know anything about this parameter I didn't add this comment and I guess that's not the part of this story so it won't be added in the follow up ticket

2023-01-23 21:52 UTC, sszafGCA commented on src/pages/RoomOverview.page.vue
> +		isTeacher(roles) {
there is similiar implemenation and naming for method named IsNotStudent in ContentCard.vue I was basing namig of the method on it. So maybe you have some proposition how it should be named?

2023-01-24 12:04 UTC, odalys-dataport commented on src/pages/RoomOverview.page.vue
> +		}); // TODO: this method will receive a string parameter (Eg, mobile | tablet | desktop)
I see, thank you!

2023-01-24 12:10 UTC, odalys-dataport commented on src/store/rooms.ts
> +				undefined,
Thank you for the clarification!

2023-01-24 16:54 UTC, sszafGCA commented on src/pages/RoomOverview.page.vue
> +	props: {
removed it not needed

2023-01-24 16:54 UTC, sszafGCA commented on src/pages/RoomOverview.page.vue
> +		isTeacher(roles) {
Chnaged implementation to return boolean

2023-01-24 20:12 UTC, sszafGCA commented on src/pages/RoomOverview.page.vue
> +						color="rgb(10,122,201)"
changed

2023-01-24 20:12 UTC, sszafGCA commented on src/store/rooms.ts
> +	async align(payload: DroppedObject): Promise<boolean> {
changed

2023-01-25 07:00 UTC, sszafGCA commented
Implemented alert with timeout

2023-01-25 12:51 UTC, odalys-dataport approved these changes

2023-01-26 12:33 UTC, odalys-dataport approved these changes

2023-01-30 14:28 UTC, bn-pass approved these changes

2023-01-30 16:23 UTC, bn-pass approved these changes

2023-01-30 16:38 UTC, bn-pass approved these changes

2023-01-30 17:08 UTC, merged