Keep error info after language changed
hpi-schul-cloud/nuxt-client pull request #2367
Opened 2023-01-16 12:15 UTC by wiaderwek

# Short Description

Keep the same error page content after language change (page reload)

QA notes
Tested on MSwindows 10, chrome - screenshot one and iPad PRO (12.9-5gen) iOS(16.3) Safari - screenshot two - see section "Screenshots of UI changes".

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-2828

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

![2828](https://user-images.githubusercontent.com/118526182/212891811-f3a789fb-2997-42a4-b5f9-8a8329d2ff0b.gif)
![2828_ipad](https://user-images.githubusercontent.com/118526182/214546738-5bcec9f1-39a0-4e82-87e2-102cd619e7b8.gif)

## Checklist before merging

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-01-18 08:13 UTC, muratmerdoglu-dp reviewed
It'd be better to handle the localStorage processes in a store file for reusability.

2023-01-18 08:20 UTC, wiaderwek commented on src/pages/Error.page.vue
> +			);
I believe so, since if it is reloaded page we want to take error data from local storage, as after reload injected data will always point to general error.

2023-01-18 08:22 UTC, wiaderwek commented on .eslintignore
> +/src/pages/Error.page.vue
Unfortunately, there is a parsing error related to casting object, so it is impossible to ignore just one line as lint cannot event parse a file. This is mostly realted to mixing vue and nuxt validation - should be removed after nuxt removal I belive

2023-01-18 08:31 UTC, wiaderwek commented on src/pages/Error.page.vue
> +		let applicationErrorModule: ApplicationErrorModule | undefined;
Because if it is reloaded we want to takie data from localStorage and if not we will inject them

2023-01-26 15:55 UTC, muratmerdoglu-dp requested changes

2023-01-26 15:55 UTC, muratmerdoglu-dp commented on src/pages/ErrorPage.unit.ts
> +				getEntriesByType: jest.fn(), //.mockReturnValue([{ type: navigationType }]),
Please remove the comment!

2023-01-26 16:19 UTC, muratmerdoglu-dp approved these changes

2023-01-26 16:57 UTC, merged