N21-500 migration page
hpi-schul-cloud/nuxt-client pull request #2373
Opened 2023-01-24 10:45 UTC by MarvinOehlerkingCap

# Short Description
- add new public page for the migration flow https://docs.dbildungscloud.de/x/UADjDQ

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-500

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-01-27 11:03 UTC, IgorCapCoder submitted a review, later dismissed

2023-02-02 08:59 UTC, odalys-dataport requested changes
I wasn't able to test this on the dev instance under this link
https://nbc-n21-500-migration-page.cd.dbildungscloud.dev/migration

Do you have another testing instance?

2023-02-02 08:59 UTC, odalys-dataport commented on src/store/user-migration.ts
> +			this.setLoading(false);
Please add error handling

2023-02-02 08:59 UTC, odalys-dataport commented on src/store/systems.ts
> +			console.log(`Some error occurred while loading system data: ${e}`);
Please add error handling

2023-02-02 08:59 UTC, odalys-dataport commented on src/pages/user-migration/UserMigration.page.vue
> +		<img src="@assets/img/migration/migration.svg" alt="" />
Please add an alternative text for the image

2023-02-02 08:59 UTC, odalys-dataport commented on src/pages/user-migration/UserMigration.page.vue
> +				v-html="
Is there a way to avoid usage of v-html?

2023-02-02 08:59 UTC, odalys-dataport commented on src/pages/user-migration/UserMigration.page.vue
> +				>
Please add an aria-label

2023-02-02 08:59 UTC, odalys-dataport commented on src/pages/user-migration/UserMigration.page.vue
> +				>
Please add an aria-label

2023-02-02 08:59 UTC, odalys-dataport commented on src/pages/user-migration/UserMigration.page.vue
> +		if (!props.targetSystem || !props.sourceSystem || !props.origin) {
This logic should be in the store in my opinion. I think if you set a business error in the store, this will be dealt with automatically, but I'm not 100% sure about that

2023-02-02 09:54 UTC, MarvinOehlerkingCap commented on src/pages/user-migration/UserMigration.page.vue
> +				v-html="
I don't know of a way to use line breaks in a translation without v-html. If you know more let me know.

2023-02-02 10:06 UTC, MarvinOehlerkingCap commented on src/pages/user-migration/UserMigration.page.vue
> +				>
The button has text that describes what it is doing, so I don't think an aria-label helps here. Or are we adding aria-labels to all buttons now, because I can't see a lot of v-btns in the project that use aria-labels?

2023-02-02 10:23 UTC, odalys-dataport commented on src/pages/user-migration/UserMigration.page.vue
> +				v-html="
I see, thanks for explaining

2023-02-02 10:28 UTC, MarvinOehlerkingCap commented on src/pages/user-migration/UserMigration.page.vue
> +		if (!props.targetSystem || !props.sourceSystem || !props.origin) {
This is not store logic, but a validation of the query parameters that the page gets called with. The user should not be able to access the page without proper parameters. That's why you didn't see anything on the deployed page, but it is supposed to take you to an error page. I will look into that again.

2023-02-02 11:15 UTC, odalys-dataport commented on src/pages/user-migration/UserMigration.page.vue
> +		if (!props.targetSystem || !props.sourceSystem || !props.origin) {
I see, thanks for clarifying

2023-02-03 08:11 UTC, merged

2023-02-07 08:22 UTC, OliverHappe commented on src/layouts/loggedOut.vue
> +					<Nuxt />
did you already merge in the nuxt removal branch?

2023-02-07 08:23 UTC, OliverHappe commented on src/pages/user-migration/UserMigration.page.unit.ts
> +	const setup = (props: object) => {
i would appreciate a better typing than object.

while it is fine for now, this does not give any information to people adding or refacturing tests in the future.

2023-02-07 08:24 UTC, OliverHappe commented on src/pages/user-migration/UserMigration.page.unit.ts
> +			it("should throw an error", () => {
just for my understanding: having this in a callback is required to check if dependency injection failures get handled correctly?

2023-02-07 14:40 UTC, MarvinOehlerkingCap commented on src/layouts/loggedOut.vue
> +					<Nuxt />
yes

2023-02-07 14:43 UTC, MarvinOehlerkingCap commented on src/pages/user-migration/UserMigration.page.unit.ts
> +			it("should throw an error", () => {
you have to give the `expect()` function a callback function in order for jest to handle exceptions in synchronous function calls correctly. Otherwise the test will just throw the error before jest can intercept it.