N21 499 extends student list by 2 timestamps
hpi-schul-cloud/nuxt-client pull request #2378
Opened 2023-01-25 11:07 UTC by IgorCapCoder

# Short Description
adds 2 Login-System-Migration related timestamps into the admin/students table, that are only shown when the migration feature flag is set to true

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-499

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes
![image](https://user-images.githubusercontent.com/93926487/213402091-a4f915c3-8850-4af7-a08e-0680992eb046.png)

## Checklist before merging

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-01-26 16:32 UTC, arnegns submitted a review, later dismissed

2023-01-27 08:32 UTC, IgorCapCoder commented on locale/de.json
> +	"common.labels.migrated": "Zuletzt migriert am",
all the other table column header are common label. Even after checking the administration.students options, there are no table ones, so i think common label is the best option here...🤷‍♂️

2023-01-30 08:37 UTC, OliverHappe requested changes
Just a minor possible improvement, otherwise it looks good :)

2023-01-30 08:37 UTC, OliverHappe commented on src/pages/administration/StudentOverview.page.vue
> +				editedColumns = editedColumns.filter(
I think chaining the filter-statements instead of assigning the value twice is a nice performance improvement

so `editedColumns = editedColumns.filter(...).filter(...)`

2023-01-30 08:37 UTC, uidp approved these changes

2023-01-30 08:58 UTC, IgorCapCoder commented on src/pages/administration/StudentOverview.page.vue
> +				editedColumns = editedColumns.filter(
Good call. I used an and (&&) operator instead :)

2023-01-30 09:34 UTC, OliverHappe submitted a review, later dismissed

2023-01-30 10:29 UTC, OliverHappe approved these changes

2023-01-30 10:29 UTC, merged