BC-2918 - Accessible inline edit (label, aria)
hpi-schul-cloud/nuxt-client pull request #2384
Opened 2023-02-03 13:44 UTC by MartinSchuhmacher

# Short Description
- the title and text element fields do not have visible labels in the context of inline editing like a typical form field 
- it is therefore important, especially for screen readers etc., to pay particular attention to the requirements for low-barrier use
- e.g. an invisible label or aria-label are possible

## Links to Ticket and related Pull-Requests
BC-2918

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-02-03 13:56 UTC, virgilchiriac commented on src/components/card-elements/CardElement.vue
> +				:aria-label="$t('components.cardElement.dragElement')"
do we need also title attr besides area-label?

2023-02-06 08:51 UTC, odalys-dataport commented on src/components/card-elements/CardElement.vue
> +				:aria-label="$t('components.cardElement.dragElement')"
a title attr is not necessary :)

2023-02-06 09:11 UTC, odalys-dataport requested changes

2023-02-06 09:11 UTC, odalys-dataport commented on src/components/card-elements/TitleCardElement.vue
> +			:aria-label="$t('components.cardElement.titleElement')"
Screen Reader is reading "Titleelement Title" here, I think it might be reading the placeholder too. We should fix that

2023-02-07 13:12 UTC, christian-darsow commented on src/components/card-elements/RichTextCardElement.vue
> +			:aria-label="$t('components.cardElement.richTextElement')"
the CK5 already comes with an aria-label on itself, so no need to add this here

2023-02-08 09:09 UTC, odalys-dataport commented
Implemented in BC-2923

2023-02-08 09:09 UTC, closed without merging