N21-547 adjusted admin migration section and changed locales
hpi-schul-cloud/nuxt-client pull request #2401
Opened 2023-02-15 13:38 UTC by arnegns

# Short Description
Finalizes the texts of the admin migration ui.

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-547

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes
![image](https://user-images.githubusercontent.com/12628806/219042644-23b8bf92-04c6-44d6-97dc-304ca9fa429b.png)

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-02-16 11:32 UTC, MarvinOehlerkingCap commented on src/components/administration/AdminMigrationSection.unit.ts
> +				cardComponent.find(".agree-btn-end");
you are not using the return value of find here anymore. I think you can remove this then.

2023-02-16 11:33 UTC, MarvinOehlerkingCap approved these changes

2023-02-17 08:02 UTC, hoeppner-dataport requested changes

2023-02-17 08:02 UTC, hoeppner-dataport commented on src/locales/de.json
> +	"components.administration.adminMigrationSection.endWarningCard.text": "Bitte bestätigen, dass die Account-Migration zu SANIS abgeschlossen werden soll.<br><br><span class=\"red--text\">Achtung:</sp
I think it is not a good idea to put html into language constants. Can you somehow avoid that by spliting up the content into multiple language constants.

2023-02-17 10:55 UTC, arnegns commented on src/locales/de.json
> +	"components.administration.adminMigrationSection.endWarningCard.text": "Bitte bestätigen, dass die Account-Migration zu SANIS abgeschlossen werden soll.<br><br><span class=\"red--text\">Achtung:</sp
I thought about it but I should have to create a bunch of constants for this and I decided against it because it is really specific for sanis, and should be refactored after the migration. So that is more generel for oauth to oauth system and not for specific systems. Everthing else is generalized

2023-02-17 10:58 UTC, arnegns commented on src/components/administration/MigrationEndWarningCard.vue
> +		<v-card-title style="word-break: break-word"
You re right, thanks for the advice :)

2023-02-17 12:05 UTC, hoeppner-dataport approved these changes

2023-02-20 08:17 UTC, merged