BC-3253 - Fix nuxtclient-ldap-deployment
hpi-schul-cloud/nuxt-client pull request #2403
Opened 2023-02-15 16:09 UTC by BlexToGo

# Short Description

Fix so that the `nuxtclient-ldap-deployment` on staging comes back up after #2345 

## Links to Ticket and related Pull-Requests

BC-3253

## Changes

Apply all the changes made to `ansible\roles\nuxt-client-core\templates\deployment.yml.j2` during #2345 also to `ansible\roles\nuxt-client-ldap\templates\deployment.yml.j2`

## Deployment

Only applicable on staging as other environments don't have `-ldap-deployment` deployments.

2023-02-15 16:55 UTC, virgilchiriac submitted a review, later dismissed

2023-02-15 17:01 UTC, uidp requested changes

2023-02-15 17:01 UTC, uidp commented on ansible/roles/nuxt-client-ldap/templates/deployment.yml.j2
> +          name: conf-dir
👍

2023-02-15 17:01 UTC, uidp commented on ansible/roles/nuxt-client-ldap/templates/deployment.yml.j2
> +        emptyDir: {}
👍

2023-02-15 17:17 UTC, BlexToGo commented on ansible/roles/nuxt-client-ldap/templates/deployment.yml.j2
> -        - name: LEGACY_CLIENT_URL
I just added `LEGACY_CLIENT_URL` again 👍 Though `ansible\roles\nuxt-client-core\templates\deployment.yml.j2` does not contain `LEGACY_CLIENT_URL`, could this be an issue or is `LEGACY_CLIENT_URL` just necessary for `nuxtclient-ldap-deployment`?
https://github.com/hpi-schul-cloud/nuxt-client/blob/main/ansible/roles/nuxt-client-core/templates/deployment.yml.j2#L38-L41

2023-02-15 17:44 UTC, virgilchiriac submitted a review, later dismissed

2023-02-17 13:36 UTC, uidp commented on ansible/roles/nuxt-client-ldap/templates/deployment.yml.j2
> -        - name: LEGACY_CLIENT_URL
Unfortunately I'm not that familiar with ansible. We need the `LEGACY_CLIENT_URL` env variable when starting the NGINX process of the nuxt-client pod. If that's the case we are fine.

2023-02-17 13:37 UTC, uidp submitted a review, later dismissed

2023-02-17 16:26 UTC, BlexToGo commented
Removed `LEGACY_CLIENT_URL` again after discussing it with @uidp because `nuxtclient-ldap-deployment` also uses the `nuxtclient-configmap` which already contains the `LEGACY_CLIENT_URL` environment variable because it's defined in `dof_app_deploy`
https://github.com/hpi-schul-cloud/dof_app_deploy/blob/e5b54f331988c2211cd6144862d2c5da80ef2d7f/ansible/group_vars/all/config.yml#L31-L35

2023-02-17 16:30 UTC, BlexToGo commented on ansible/roles/nuxt-client-ldap/templates/deployment.yml.j2
> -        - name: LEGACY_CLIENT_URL
Discussed this with @uidp, see latest commit and comment

2023-02-17 19:22 UTC, uidp approved these changes

2023-02-20 08:45 UTC, Loki-Afro approved these changes

2023-02-22 16:56 UTC, merged