BC-3217 - Create Task card from course detail view
hpi-schul-cloud/nuxt-client pull request #2405
Opened 2023-02-20 16:36 UTC by christian-darsow

# Short Description
As a teacher, I want to create a new taskcard from within a course so that the new taskcard is per default part of the current course.

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-3217

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-02-23 13:13 UTC, virgilchiriac approved these changes

2023-02-24 09:38 UTC, virgilchiriac commented on src/pages/RoomDetails.page.vue
> +				if (envConfigModule.getEnv.FEATURE_TASK_CARD_ENABLED) {
one thing, we are based on course create permission above, but is not bullet-proof. 
I mean, should also check for permission to create task-card, i.e. the button should not be visible for students. But that is true for the other buttons, so the section should be refactor in my oppinion

2023-02-27 07:26 UTC, christian-darsow commented on src/pages/RoomDetails.page.vue
> +				if (envConfigModule.getEnv.FEATURE_TASK_CARD_ENABLED) {
So, just to understand: there is a chance that also students have permission to create courses?

2023-02-27 12:23 UTC, virgilchiriac submitted a review, later dismissed

2023-02-27 13:06 UTC, odalys-dataport requested changes

2023-02-27 13:06 UTC, odalys-dataport commented on src/router/vue-client-route.js
> +	`^/task-cards/new/rooms/${mongoId}?$`,
I thought we agreed on having the courseId as a query parameter?

2023-02-27 14:29 UTC, odalys-dataport requested changes

2023-02-27 14:29 UTC, odalys-dataport commented on src/pages/TaskCard.page.vue
> +		});
as the code in onMounted is growing we should probably separate this into functions if we can

2023-02-27 15:21 UTC, virgilchiriac commented on src/pages/RoomDetails.page.vue
> +						dataTestid: "fab_button_add_beta_task",
vue renders thje attributet as data-testid

2023-02-27 15:33 UTC, virgilchiriac commented on src/pages/room-details.unit.ts
> +		it("should not show if FEATURE_TASK_CARD_ENABLED is false", () => {
done

2023-02-27 15:35 UTC, virgilchiriac commented on src/pages/TaskCard.page.vue
> +		});
this refactoring should be done with adding list fo available courses to select from

2023-02-27 15:35 UTC, virgilchiriac commented on src/pages/RoomDetails.page.vue
> +						ariaLabel: this.$t("pages.rooms.fab.add.betatask"),
done

2023-02-27 15:37 UTC, virgilchiriac commented on src/router/vue-client-route.js
> +	`^/task-cards/new/rooms/${mongoId}?$`,
done, but only the path having course because the other case is out of scope
(the ticket is only about adding task-card from course / room. There is another ticket to add task from task-overview - so no course selected) and also to be able to select the course from list).

2023-02-27 15:38 UTC, virgilchiriac commented on src/pages/room-details.unit.ts
> +			$router.resolve.mockReturnValue( { href: '/task-cards/new/123'})
fixed

2023-02-27 15:38 UTC, virgilchiriac commented on src/pages/TaskCard.page.vue
> +			></v-select>
done

2023-02-28 08:43 UTC, odalys-dataport requested changes

2023-02-28 08:43 UTC, odalys-dataport commented on src/pages/RoomDetails.page.vue
> +							name: "task-card-new2",
maybe instead we name them "room-task-card-new" and "task-card-new"

2023-02-28 15:15 UTC, odalys-dataport submitted a review, later dismissed

2023-03-01 10:59 UTC, odalys-dataport approved these changes

2023-03-01 12:13 UTC, merged