N21-508 school admin updates tool
hpi-schul-cloud/nuxt-client pull request #2407
Opened 2023-02-21 14:58 UTC by MarvinOehlerkingCap

# Short Description
- school external tools can be edited

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-508

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-02-23 13:22 UTC, arnegns requested changes

2023-02-23 13:22 UTC, arnegns commented on src/pages/administration/external-tool/ExternalToolConfigOverview.page.vue
> +			toolTemplate.value =
The server error: "Could not find the Tool Template" should be translated. Look into: https://github.com/hpi-schul-cloud/nuxt-client/blob/c6af72e4aaa26448a9dd81c885adfbdfa6380430/src/composables/external-tool-mappings.composable.ts#L72-L72

2023-02-23 13:22 UTC, arnegns commented on src/pages/administration/external-tool/ExternalToolConfigOverview.page.vue
> +				if (editConfig) {
Can you set some loading state here in display it when we are loading a tool configuration on overview page. The select has a loading attribute

2023-02-23 13:22 UTC, arnegns commented on src/components/administration/external-tool/ExternalToolConfigParameter.vue
>  			></v-text-field>
Nice :) !

2023-02-23 13:22 UTC, arnegns commented on src/components/administration/external-tool/ExternalToolConfigParameter.vue
> +		const parameter: Ref<ToolParameter> = ref(props.value);
Also good :) ... dont know why it wont work before

2023-02-23 13:22 UTC, arnegns commented on src/router/routes.ts
> +		children: [
Nice :)

2023-02-23 13:29 UTC, arnegns submitted a review, later dismissed

2023-03-03 08:56 UTC, Loki-Afro commented on package.json
> +		"flush-promises": "^1.0.2",
is this needed? don't see where you use it ..

2023-03-03 09:08 UTC, MartinSchuhmacher requested changes

2023-03-03 09:08 UTC, MartinSchuhmacher commented on src/pages/administration/external-tool/ExternalToolConfigOverview.page.vue
> +					isEdit
I would like to be more precise with naming here. `isEdit` does not tell me what exactly this value should mean. regarding the context I assume it means `isEditMode` or `isEditable` but as its not clear in the first place please choose a more precise name

2023-03-03 09:08 UTC, MartinSchuhmacher commented on src/pages/administration/external-tool/ExternalToolConfigOverview.page.vue
> +		const isEdit: Ref<boolean> = ref(!!props.configId && props.configId !== "");
see comment above

2023-03-03 09:08 UTC, MartinSchuhmacher commented on src/pages/administration/external-tool/ExternalToolConfigOverview.page.vue
> +			if (toolTemplate.value) {
I find that part of the code very hard to read and suggest to put at least the `forEach` part in a separate function to improve readability

2023-03-03 09:08 UTC, MartinSchuhmacher commented on src/store/external-tools.ts
> +			console.log(
should we really use `console.log` for that?

2023-03-03 09:08 UTC, MartinSchuhmacher commented on src/store/external-tools.ts
> +			console.log(
see above

2023-03-03 09:15 UTC, MarvinOehlerkingCap commented on package.json
> +		"flush-promises": "^1.0.2",
It is used in tests to make sure the components onMounted function fully resolves before the test runs. Otherwise the component is not correctly setup yet.
https://github.com/hpi-schul-cloud/nuxt-client/blob/3f28394fce723d5d1a3413d0814e3bd1ee7a6245/src/pages/administration/external-tool/ExternalToolConfigOverview.page.unit.ts#L77-L77

2023-03-03 10:46 UTC, MarvinOehlerkingCap commented on src/store/external-tools.ts
> +			console.log(
idk, but there is no guideline for logging

2023-03-03 11:18 UTC, MartinSchuhmacher approved these changes
thx for the changes, console.log as we discussed also unclear to me

2023-03-06 10:16 UTC, MartinSchuhmacher approved these changes

2023-03-06 10:19 UTC, merged