BC-3197 Remove old share lesson functionality
hpi-schul-cloud/nuxt-client pull request #2410
Opened 2023-02-23 10:24 UTC by MateuszSapalaPassCon

# Short Description
Remove old share lesson functionality and change FEATURE_LESSON_SHARE_NEW flag into FEATURE_LESSON_SHARE.

## Links to Ticket and related Pull-Requests
- https://ticketsystem.dbildungscloud.de/browse/BC-3197

## Changes
Remove old share lesson code.

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-03-01 08:08 UTC, sszafGCA submitted a review, later dismissed

2023-03-01 11:04 UTC, hoeppner-dataport requested changes

2023-03-01 11:04 UTC, hoeppner-dataport commented on src/pages/room-details.unit.ts
> -		expect(hasImportLessonAction).toBe(false);
It should be enough to remove the check for the importLessonAction here, I assume.

2023-03-01 11:55 UTC, MateuszSapalaPassCon commented on src/pages/room-details.unit.ts
> -		expect(hasImportLessonAction).toBe(false);
You are absolutely right. I restored the test and removed the importLessonAction, as you suggested:
https://github.com/hpi-schul-cloud/nuxt-client/blob/ff8cd20940aafff76eac85e87f1a9bc60087b767/src/pages/room-details.unit.ts#L207-L212

2023-03-01 12:06 UTC, hoeppner-dataport approved these changes

2023-03-03 14:17 UTC, hoeppner-dataport approved these changes

2023-03-03 14:26 UTC, merged