N21 539 migration error page
hpi-schul-cloud/nuxt-client pull request #2422
Opened 2023-03-03 07:49 UTC by MarvinOehlerkingCap

# Short Description
- adds a page that is displayed in case the user login migration fails

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-539

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-03-06 09:58 UTC, arnegns requested changes

2023-03-06 09:58 UTC, arnegns commented on src/locales/de.json
> +	"pages.userMigration.error.description": "Der Umzug des Anmeldesystems von {sourceSystem} zu {targetSystem} ist leider fehlgeschlagen. Um die Niedersächsische Bildungscloud mit dem Anmeldesystem {ta
There is a placeholder for the instance name.. maybe you could use this for "Niedersächsische Bildungscloud"

2023-03-06 09:58 UTC, arnegns commented on src/pages/user-migration/UserLoginMigrationError.page.vue
> +						supportLink:
We could use the env: ACCESSIBILITY_REPORT_EMAIL .. we only need the to pass this in dof app deploy to nuxt. I think this should be nicer

2023-03-06 09:58 UTC, arnegns commented on src/router/routes.ts
> +		beforeEnter: (to: Route, from: Route, next: NavigationGuardNext) => {
Like the other PR. This should be moved to a composable or in the component itself if we cant reuse this logic

2023-03-08 14:34 UTC, arnegns submitted a review, later dismissed

2023-03-08 14:34 UTC, arnegns commented on src/pages/user-login-migration/UserLoginMigrationError.page.vue
> +			alt="migration error logo"
Maybe we can translate alt's

2023-03-08 14:34 UTC, arnegns commented on src/router/guards/query-parameter.guard.ts
> +export function createQueryParameterValidationGuard(
Can you rename also the file to validate-query-parameter.guard?

2023-03-08 14:34 UTC, arnegns commented on src/store/env-config.ts
> +
Nice :)

2023-03-09 13:24 UTC, OliverHappe commented on src/pages/user-login-migration/UserLoginMigrationError.page.vue
> +		const hasData: Ref<boolean> = ref(false);
small suggestions: call this isLoading and init with true. isLoading is used all the time across the app to convey the state where we wait for data to load.

2023-03-10 08:51 UTC, MarvinOehlerkingCap commented on src/pages/user-login-migration/UserLoginMigrationError.page.vue
> +		const hasData: Ref<boolean> = ref(false);
Do I understand it right that I should rename hasData to isLoading?

2023-03-10 10:22 UTC, OliverHappe approved these changes

2023-03-10 10:59 UTC, merged