BC-3222 - show task card on room board
hpi-schul-cloud/nuxt-client pull request #2425
Opened 2023-03-06 12:20 UTC by odalys-dataport

# Short Description

## Links to Ticket and related Pull-Requests

https://ticketsystem.dbildungscloud.de/browse/BC-3222

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-03-07 08:26 UTC, MartinSchuhmacher commented on src/components/molecules/RoomTaskCard.vue
> +				if (this.isBetaTask) {
I was thinking if it makes sense to put this redirect into a separate private function like `redirectTask` or something, as I am not a huge fan of two if statements

2023-03-07 08:26 UTC, MartinSchuhmacher commented on src/locales/en.json
> +	"pages.room.taskCard.label.betaTask": "Beta-Task",
english should not use "-", just use `Beta task`

2023-03-07 08:26 UTC, MartinSchuhmacher commented on src/locales/es.json
> +	"pages.room.taskCard.label.betaTask": "Tarea Beta",
`Tarea beta` would be my suggestion

2023-03-07 08:26 UTC, MartinSchuhmacher commented on src/locales/ua.json
> +	"pages.room.taskCard.label.betaTask": "Бета-завдання",
same as above, ukrainian also does not use hiphens here (at least not in russian and its the similar grammar), so simply `Бета завдання` is enough

2023-03-07 08:26 UTC, MartinSchuhmacher commented on src/pages/RoomDetails.page.vue
> +	async beforeRouteEnter(to, from, next) {
in case this new behaviour substitutes the old one, I would remove the commented function

2023-03-07 08:26 UTC, MartinSchuhmacher commented on src/components/molecules/RoomTaskCard.vue
> +			return !!this.task.taskCard;
not a big fan of conversions, maybe a straight `!== null` would give the straight answer to the check here

2023-03-07 08:26 UTC, MartinSchuhmacher commented on src/components/molecules/RoomTaskCard.vue
> +			return this.isBetaTask ? "task" : "";
are there plans for other colors as well? because below you name a class "beta-task" with separate background color. does this "task" here mean a different task then or are they supposed to be used for the same "type" of task? then a matching naming might come in handy

2023-03-07 11:21 UTC, odalys-dataport commented on src/pages/RoomDetails.page.vue
> +	async beforeRouteEnter(to, from, next) {
While it does work on local, apparantly it does not work on dev instance

2023-03-08 13:48 UTC, MartinSchuhmacher commented on src/router/routes.ts
> +// routes configuration sorted in alphabetical order
I dont think that comment is necessary for future work

2023-03-08 13:48 UTC, MartinSchuhmacher commented on src/router/routes.ts
> +	// deprecated?
can we handle the deprecated routes/create a follow up ticket instead of writing a comment here which will not be tackled in the future?

2023-03-09 08:46 UTC, OliverHappe requested changes

2023-03-09 14:17 UTC, OliverHappe requested changes

2023-03-09 14:17 UTC, OliverHappe commented on src/components/molecules/RoomTaskCard.unit.ts
> +			const taskCard = wrapper.find(".task-card");
a card should not be a button without role=button

2023-03-09 14:17 UTC, OliverHappe commented on src/components/molecules/RoomTaskCard.unit.ts
> +			const taskCard = wrapper.find(".task-card");
imo it's cleaner to not use classes as a selector for wrappers.

in this case .findComponent(VCard) should be used. especially since the class you are trying to find here is added dynamically. it should be obvious which element you are selecting when looking at the template.

2023-03-09 14:17 UTC, OliverHappe commented on src/components/molecules/RoomTaskCard.vue
> +					<div class="title-section" tabindex="0">
titles should use an <hX> element to be accessible for screenreaders

2023-03-09 14:17 UTC, OliverHappe commented on src/components/molecules/RoomTaskCard.vue
> +					<div class="title-section" tabindex="0">
why is there a tabindex on the title?

2023-03-09 14:17 UTC, OliverHappe commented on src/components/molecules/RoomTaskCard.vue
> +					v-html="task.description"
why no interpolation for the description string? v-html poses a potential xss vulnerability!

2023-03-09 15:43 UTC, odalys-dataport commented on src/components/molecules/RoomTaskCard.unit.ts
> +			const taskCard = wrapper.find(".task-card");
good point, I added the role to v-card

2023-03-09 15:44 UTC, odalys-dataport commented on src/components/molecules/RoomTaskCard.unit.ts
> +			const taskCard = wrapper.find(".task-card");
You're right, I just copied from the existing tests and didn't care too much. Adjusted it for my new test, would not like to adjust it for all tests though.

2023-03-09 15:49 UTC, odalys-dataport commented on src/components/molecules/RoomTaskCard.vue
> +					<div class="title-section" tabindex="0">
good question, I removed it for both old and new

I made the name of the task an h6 now. The title section is the subtitle above the task name. I didn't name it like that, it's from the existing code

2023-03-09 15:50 UTC, odalys-dataport commented on src/components/molecules/RoomTaskCard.vue
> +					v-html="task.description"
this is also from the existing code and not from my changes

2023-03-10 08:49 UTC, OliverHappe approved these changes

2023-03-10 09:48 UTC, merged