BC-3364 Update the HOMEWORK_CREATE and HOMEWORK_EDIT permissions
hpi-schul-cloud/nuxt-client pull request #2426
Opened 2023-03-06 18:53 UTC by MateuszSapalaPassCon

# Description
Update fab items for the admin on the room details page. Actions won't be displayed if the user doesn't have the necessary permissions.

ps. Why task creation has been hidden behind the COURSE_CREATE permission?

## Links to Tickets or other pull requests
- https://ticketsystem.dbildungscloud.de/browse/BC-3364
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/3934

## Changes
Permission validation is done for each item instead of just COURSE_CREATE.

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-03-07 09:21 UTC, sszafGCA approved these changes

2023-03-07 14:28 UTC, virgilchiriac submitted a review, later dismissed

2023-03-10 12:31 UTC, odalys-dataport requested changes

2023-03-10 12:31 UTC, odalys-dataport commented on src/pages/RoomDetails.page.vue
> +				authModule.getUserPermissions.includes("HOMEWORK_CREATE".toLowerCase())
Looks like you mixed up `HOMEWORK_CREATE` and `TOPIC_CREATE` permission

2023-03-10 13:32 UTC, MateuszSapalaPassCon commented on src/pages/RoomDetails.page.vue
> +				authModule.getUserPermissions.includes("HOMEWORK_CREATE".toLowerCase())
You are right, thanks for noticing. It is fixed now

2023-03-10 15:06 UTC, odalys-dataport approved these changes

2023-03-10 15:20 UTC, merged