BC-2931 - Show task card in Task Overview page
hpi-schul-cloud/nuxt-client pull request #2447
Opened 2023-03-15 17:41 UTC by MartinSchuhmacher

# Short Description
Summary of making beta tasks (tasks with task card) appear correctly in task overview.

## Links to Ticket and related Pull-Requests
BC-2931

## Changes
- beta tasks lead to correct task card view from task overview
- beta tasks appear different then old tasks (in coordination with UX)

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-03-21 16:59 UTC, odalys-dataport requested changes

2023-03-21 16:59 UTC, odalys-dataport commented on src/components/molecules/TaskItemStudent.unit.js
> +	it("Should link regularly to page for old tasks", () => {
maybe clearer wording like below would be nicer "should direct user to legacy task details page"

2023-03-21 16:59 UTC, odalys-dataport commented on src/components/molecules/TaskItemStudent.vue
> -			class="mx-n4 mx-sm-0"
you can have normal string classes and computed classes simultaneously, also we can use optional class assignment and then get rid of the getStyleClasses function

```
class="mx-n4 mx-sm-0"
:class="{ 'beta-task-background': isBetaTask }"
```

2023-03-21 16:59 UTC, odalys-dataport commented on src/components/molecules/TaskItemStudent.vue
> +						taskLabel
kinda weird formatting, maybe put curly brackets in the same line

2023-03-21 16:59 UTC, odalys-dataport commented on src/components/molecules/TaskItemTeacher.unit.js
> +	it("should compute regular href value for old tasks", () => {
same as TaskItemStudent.unit.js

2023-03-21 16:59 UTC, odalys-dataport commented on src/components/molecules/TaskItemTeacher.vue
> +							}}</v-chip
next line for v-chip closing tag

2023-03-21 16:59 UTC, odalys-dataport commented on src/components/molecules/TaskItemTeacher.vue
> +			:class="getStyleClasses"
same comments as in TaskItemStudent.vue

2023-03-21 16:59 UTC, odalys-dataport commented on src/components/molecules/TaskItemTeacher.vue
> +							>{{ task.status.submitted }}/{{
weird formatting again, but maybe it's just my opinion

2023-03-21 16:59 UTC, odalys-dataport commented on src/components/templates/TasksDashboardMain.vue
>  			if (!this.isStudent) {
we should check for HOMEWORK_CREATE permission here as well

2023-03-21 16:59 UTC, odalys-dataport commented on src/pages/TaskCard.page.vue
> +				:disabled="isCreationMode ? false : !!course"
maybe we can merge this condition into isCreationMode and name it isCourseDisabled

2023-03-22 17:06 UTC, MartinSchuhmacher commented on src/components/molecules/TaskItemStudent.vue
> +						taskLabel
I tried putting it in the same line with different variants but then the label always gets several lines due to the line breaks, so I would prefer to leave it like this so the value stays correct

2023-03-22 17:07 UTC, MartinSchuhmacher commented on src/pages/TaskCard.page.vue
> +				:disabled="isCreationMode ? false : !!course"
dont know what you mean by this comment. what exactly shoud I merge into `isCreationMode` ?

2023-03-23 07:08 UTC, christian-darsow commented on src/router/routes.ts
> +		path: `/tasks/create-task-card`,
Lets change the path and name of the route to be in sync with the changes in BC-3613
path: /tasks/create-beta-task
name: tasks-beta-task-new

2023-03-23 09:08 UTC, odalys-dataport approved these changes

2023-03-23 17:33 UTC, odalys-dataport submitted a review, later dismissed

2023-03-27 10:20 UTC, christian-darsow approved these changes

2023-03-27 11:01 UTC, merged