BC-3507 - Fix beta task reload
hpi-schul-cloud/nuxt-client pull request #2453
Opened 2023-03-20 09:52 UTC by christian-darsow

# Short Description

After creating a beta task the task is not immediately shown on the room details page. The page needs to be reloaded for the task to be visible.

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-3507

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-03-20 10:49 UTC, MartinSchuhmacher approved these changes

2023-03-20 19:26 UTC, MartinSchuhmacher requested changes

2023-03-20 19:26 UTC, MartinSchuhmacher commented on src/components/molecules/RoomTaskCard.vue
> +				if (this.isBetaTask) {
to be honest I would like that part of "seting the route" being in a separate private function

2023-03-20 19:26 UTC, MartinSchuhmacher commented on src/pages/TaskCard.page.vue
>  				dueDate.value = endOfSchoolYear.toISOString();
the seting of the courseId above here is not necessary because it is done in the `createTaskCard` function, correct?

2023-03-21 07:08 UTC, christian-darsow commented on src/components/molecules/RoomTaskCard.vue
> +				if (this.isBetaTask) {
yeap, good idea! created a new computed property for that

2023-03-21 07:14 UTC, MartinSchuhmacher submitted a review, later dismissed

2023-03-21 09:09 UTC, odalys-dataport commented on src/pages/TaskCard.page.vue
> +				];
Shouldn't we adjust the initial data in store instead of here?

2023-03-21 11:21 UTC, christian-darsow commented on src/pages/TaskCard.page.vue
> +				];
I think (now) it's easier to read like this having all the initial values next to each other, initial cardElements, duedate etc and not getting one of those from the store. and just in case we want ot have other initial values somewhere, e.g two text contents, also more flexible.  what do you think?

2023-03-21 17:00 UTC, odalys-dataport commented on src/pages/TaskCard.page.vue
> +				];
mmh let's leave it like this for now and think about if it makes more sense in the store

2023-03-21 17:18 UTC, odalys-dataport requested changes

2023-03-21 17:18 UTC, odalys-dataport commented on src/pages/TaskCard.page.vue
> +				const initialCardElements = [
with the title refactor pr, this needs to be refactored as well, right?

2023-03-22 07:05 UTC, christian-darsow commented on src/pages/TaskCard.page.vue
> +				const initialCardElements = [
yeap, right. I thought that merging main into it would solve this or at least give me a hint of a conflict. but not

2023-03-22 08:38 UTC, odalys-dataport approved these changes

2023-03-22 12:16 UTC, merged