N21-736 make new school admin page the default
hpi-schul-cloud/nuxt-client pull request #2457
Opened 2023-03-21 15:32 UTC by MarvinOehlerkingCap

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-03-22 10:21 UTC, arnegns approved these changes

2023-03-22 10:24 UTC, arnegns commented on src/locales/de.json
> +	"pages.administration.school.index.back": "alten Administrationsseite",
Where is the "Zur" ?

2023-03-22 10:33 UTC, MarvinOehlerkingCap commented on src/locales/de.json
> +	"pages.administration.school.index.back": "alten Administrationsseite",
The requested text has no "Zur"

2023-03-22 10:38 UTC, arnegns submitted a review, later dismissed

2023-03-27 08:08 UTC, MartinSchuhmacher requested changes

2023-03-27 08:59 UTC, merged