N21-654 implementation of migration final finish
hpi-schul-cloud/nuxt-client pull request #2458
Opened 2023-03-22 08:49 UTC by IgorCapCoder

# Short Description
qith the introduction of the oauthMigrationFinalFinish attribute, some logic changes and text adjustments are being made here

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-654
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4001
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/492

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-03-22 10:33 UTC, arnegns requested changes
Please add tests

2023-03-24 09:50 UTC, arnegns approved these changes
Please add the test

2023-03-24 09:50 UTC, arnegns commented on src/store/env-config.ts
> +	get getMigrationEndGracePeriod() {
missing test

2023-03-24 10:02 UTC, IgorCapCoder commented on src/store/env-config.ts
> +	MIGRATION_END_GRACE_PERIOD: process.env.MIGRATION_END_GRACE_PERIOD,
... and the default value is derived process.env. If you would like to see it in another way, i'm open to suggestions

2023-03-24 13:56 UTC, arnegns commented on src/components/administration/MigrationWarningCard.vue
> +				const days = envConfigModule.getMigrationEndGracePeriod / 86400000;
Please magic numbers in extra const

2023-03-24 13:56 UTC, arnegns commented on src/components/administration/MigrationWarningCard.vue
> +			} else {
You dont need a else if you return

2023-03-24 14:06 UTC, arnegns approved these changes

2023-03-27 11:25 UTC, MartinSchuhmacher commented on src/components/administration/AdminMigrationSection.unit.ts
> +				oauthMigrationFinalFinish: "",
whats the difference between "finished"  and "finalfinish"? word wise this is confusing, maybe changing variable names would improve readability

2023-03-27 11:25 UTC, MartinSchuhmacher commented on src/components/administration/AdminMigrationSection.unit.ts
> +	describe("when checkbox is not clicked", () => {
clicked -> checked/unchecked? not clear whats the result of that click supposed to be

2023-03-27 11:25 UTC, MartinSchuhmacher commented on src/components/administration/AdminMigrationSection.unit.ts
> +	describe("when checkbox is clicked", () => {
same here

2023-03-27 11:25 UTC, MartinSchuhmacher commented on src/components/administration/AdminMigrationSection.unit.ts
> +		it("should show finalFinish text when migration grace period has expired", async () => {
also using finalFinish here makes me more wanting the change, I suggested above ^^

2023-03-27 11:56 UTC, MartinSchuhmacher submitted a review, later dismissed

2023-03-27 14:04 UTC, merged