N21 638 error page schoolnumber mismatch
hpi-schul-cloud/nuxt-client pull request #2460
Opened 2023-03-22 14:07 UTC by mrikallab

# Short Description
This PR is about the error page, which will be shown when schoolnumbers mismatch in user migration flow.

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-638

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-03-23 10:02 UTC, arnegns requested changes

2023-03-23 10:02 UTC, arnegns commented on src/router/routes.ts
> +				!isDefined(value) || (isString(value) && /[0-9]{5}/.test(value)),
You could move this function in to a const with a better name and then you would not have code duplication

2023-03-24 11:27 UTC, mrikallab commented on src/router/routes.ts
> +				!isDefined(value) || (isString(value) && /[0-9]{5}/.test(value)),
done

2023-03-28 06:39 UTC, MarvinOehlerkingCap requested changes

2023-03-28 06:39 UTC, MarvinOehlerkingCap commented on src/pages/user-login-migration/UserLoginMigrationError.page.vue
> +		<h1 class="pl-4 pr-4" style="white-space: nowrap">
no inline style

2023-03-29 07:52 UTC, MartinSchuhmacher requested changes

2023-03-29 07:52 UTC, MartinSchuhmacher commented on src/locales/de.json
> +	"pages.userMigration.error.schoolNumberMismatch": "Die Schulnummer <b>{sourceSystem} {sourceSchoolNumber}</b> und die Schulnummer <b>{targetSystem} {targetSchoolNumber}</b> bitte zu der Problemstell
that sentence does not make sense to me, especially that double "Schulnummer"

2023-03-29 07:52 UTC, MartinSchuhmacher commented on src/pages/user-login-migration/UserLoginMigrationError.page.vue
> +				data-testId="text-schoolNumberMismatch"
why mixing "-" and camelCase here? Please choose one way

2023-03-29 07:52 UTC, MartinSchuhmacher commented on src/router/routes.ts
> +				!isDefined(value) || isOfficialSchoolNumber(value),
so validating this two number means its either "not defined" OR "an official school number"?
validating something via checking if its "not defined" sounds strange to me

2023-03-29 08:41 UTC, mrikallab commented on src/locales/de.json
> +	"pages.userMigration.error.schoolNumberMismatch": "Die Schulnummer <b>{sourceSystem} {sourceSchoolNumber}</b> und die Schulnummer <b>{targetSystem} {targetSchoolNumber}</b> bitte zu der Problemstell
Hi Martin, 
this sentence was discussed with UI/UX, it was agreed on february, 21, 2023.

2023-03-29 12:06 UTC, MarvinOehlerkingCap approved these changes

2023-03-29 12:47 UTC, MartinSchuhmacher commented on src/pages/user-login-migration/UserLoginMigrationError.page.vue
> +				data-testId="text-schoolnumbermismatch"
```suggestion
				data-testId="text-schoolnumber-mismatch"
```

2023-03-29 12:47 UTC, MartinSchuhmacher commented on src/pages/user-login-migration/UserLoginMigrationError.page.unit.ts
> +					.find("[data-testId=text-schoolnumbermismatch]")
```suggestion
					.find("[data-testId=text-schoolnumber-mismatch]")
```

2023-03-29 12:48 UTC, MartinSchuhmacher commented on src/router/routes.ts
> +				!isDefined(value) || isOfficialSchoolNumber(value),
understood 👍

2023-03-29 12:52 UTC, MartinSchuhmacher approved these changes

2023-03-30 09:21 UTC, MartinSchuhmacher submitted a review, later dismissed

2023-03-30 10:37 UTC, arnegns submitted a review, later dismissed

2023-03-30 13:14 UTC, merged