BC-3008 - Delete a TaskCard
hpi-schul-cloud/nuxt-client pull request #2465
Opened 2023-03-27 08:39 UTC by MartinSchuhmacher

# Short Description
As a teacher i want to be able to delete a task.

## Links to Ticket and related Pull-Requests
BC-3008

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-03-30 07:23 UTC, MartinSchuhmacher commented on src/pages/TaskCard.page.vue
> +				isDeletable.value = !!taskCardData.id;
basically only if a taskCard does not have an ID, which in turn only happens if there is no taskCard at all. And then we also dont need the delete option.
That was my thought behind it :)

2023-03-30 07:26 UTC, MartinSchuhmacher commented on src/store/task-card.ts
> +	async deleteTaskCard(): Promise<void> {
I can implement that if you think its better. To me I just thought that we do not use it, as we anyway have only the current taskCard in state so there can be no confusion or something. Was that the issue here?

2023-03-30 08:10 UTC, christian-darsow commented on src/store/task-card.ts
> +	async deleteTaskCard(): Promise<void> {
I would argue that these delete methods (like the fetch) in gerenal are more like static methods centralized in a store. as a method that can be used from a beta-task list (somewhere) . where we then just pass the id.

2023-03-30 08:13 UTC, christian-darsow commented on src/pages/TaskCard.page.vue
> +				isDeletable.value = !!taskCardData.id;
I wonder if the whole form / component shouldnt behave different if there is no taskCard? kind of error handling if the id is eg wrong. I mean this check doesnt hurt, but maybe raises this question? what do you think?

2023-03-30 09:09 UTC, odalys-dataport commented on src/store/task-card.ts
> +	async deleteTaskCard(): Promise<void> {
I agree with Christian :)

2023-03-30 09:21 UTC, odalys-dataport requested changes

2023-03-30 09:21 UTC, odalys-dataport commented on src/locales/de.json
> +	"pages.taskCard.deleteTaskCard.text": "Bist du dir sicher, dass du die Beta-Aufgabe löschen möchtest?",
I think it would be better if we'd mention the task title here like "Bist du dir sicher, dass du die Beta-Aufgabe "Titel Lorem ipsum" löschen möchtest?"

2023-03-30 09:21 UTC, odalys-dataport commented on src/pages/TaskCard.page.vue
> +					{{ $t("common.actions.remove") }}
I agree with Ankush here, that we should consistently use remove or delete

2023-03-30 09:21 UTC, odalys-dataport commented on src/pages/TaskCard.page.vue
> +				isDeletable.value = !!taskCardData.id;
I think you're right, we're not checking if findTaskCard sets the data correctly or throws an error

2023-03-30 09:21 UTC, odalys-dataport commented on src/pages/TaskCard.page.vue
> +			if (hasErrors.value) {
Why are you checking for this. User should be able to delete an invalid task card as well I think. Or am I missunderstanding this?

2023-03-30 11:57 UTC, MartinSchuhmacher commented on src/store/task-card.ts
> +	async deleteTaskCard(): Promise<void> {
if you both agree then I will just do so :D

2023-03-30 11:59 UTC, MartinSchuhmacher commented on src/pages/TaskCard.page.vue
> +				isDeletable.value = !!taskCardData.id;
I will try to implement something that hopefully works as expected 👍

2023-03-30 11:59 UTC, MartinSchuhmacher commented on src/locales/de.json
> +	"pages.taskCard.deleteTaskCard.text": "Bist du dir sicher, dass du die Beta-Aufgabe löschen möchtest?",
👍

2023-03-30 11:59 UTC, MartinSchuhmacher commented on src/pages/TaskCard.page.vue
> +					{{ $t("common.actions.remove") }}
👍

2023-03-30 12:01 UTC, MartinSchuhmacher commented on src/pages/TaskCard.page.vue
> +			if (hasErrors.value) {
hmm...I had something in mind with the dateTimeInput...but yeah makes no sense to me neither anymore

2023-03-31 10:18 UTC, christian-darsow commented on src/store/task-card.unit.ts
> +				await taskCardModule.deleteTaskCard(mockTaskCardData.id);
Just to clarify also in the test that the delete does not depend on the state I would suggest to remove these pieces, Line 267 etc

2023-03-31 10:25 UTC, christian-darsow commented on src/pages/TaskCard.page.vue
> +				if (taskCardData.id !== "") {
Lets keep it like this for now I would say - but have a new ticket for handling unsuccessful beta-task fetching as it has nothing to do with the delete but will make this check unnecessary finally :)

2023-04-03 09:44 UTC, MartinSchuhmacher commented on src/pages/TaskCard.page.vue
> +				if (taskCardData.id !== "") {
will be handled with error handling for id of task card (redirect to error page)

2023-04-03 11:58 UTC, christian-darsow approved these changes

2023-04-03 12:09 UTC, merged