BC-3509 - restrict timepicker
hpi-schul-cloud/nuxt-client pull request #2472
Opened 2023-03-31 15:13 UTC by christian-darsow

# Short Description

Add option to restrict the time picker to not pick times in the past

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-3509

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-04-11 18:34 UTC, odalys-dataport requested changes

2023-04-11 18:34 UTC, odalys-dataport commented on src/pages/TaskCard.page.vue
> +				isLoading.value = false;
shouldn't we rather compute a loading state out of the store loading states?

2023-04-12 06:59 UTC, christian-darsow commented on src/pages/TaskCard.page.vue
> +				isLoading.value = false;
Yeap, absolutely! Just forgot about that I wanted to use the new state you introduced recently. Will change that

2023-04-12 07:00 UTC, christian-darsow commented on src/components/date-time-picker/DatePicker.vue
> +		type Rule = (value: string | null) => boolean | string;
Good idea!

2023-04-12 07:03 UTC, christian-darsow commented on src/pages/TaskCard.page.vue
> +				:is-open="false"
My IDE (and the component) tells me that this prop is required, I would like to keep it (and not get that error shown in IDE all the time)

2023-04-12 07:06 UTC, christian-darsow commented on src/components/date-time-picker/DatePicker.vue
> +					ref="inputfield"
Yeap, change that

2023-04-12 07:16 UTC, christian-darsow commented on src/components/date-time-picker/DateTimePicker.vue
> +		const dateIsToday = (dateString: string) => {
Thanks for the hint. Sure, lets use it

2023-04-17 10:39 UTC, odalys-dataport submitted a review, later dismissed

2023-04-17 20:55 UTC, MartinSchuhmacher commented on src/components/date-time-picker/DatePicker.vue
> +				: model.value;
in case there is a value, it formats the value. otherwise it takes the value as it is.
the handling of the "else" case does not feel right to me

2023-04-17 20:55 UTC, MartinSchuhmacher commented on src/components/date-time-picker/DatePicker.vue
> +		}, 200);
why there is that arbitrary value of 200 set here? can that be based on some actual action being completed?

2023-04-17 20:55 UTC, MartinSchuhmacher commented on src/components/date-time-picker/DatePicker.vue
> +		}, 50);
same here as above

2023-04-17 20:55 UTC, MartinSchuhmacher commented on src/components/date-time-picker/DatePicker.vue
> +			transform: translateY(-6px) scale(0.75) !important;
I'm no fan of that `important` property, please specify the class more if needed
also the specified values seem odd to me, in case of the scale maybe a proportional value can be set?

2023-04-17 20:55 UTC, MartinSchuhmacher commented on src/components/date-time-picker/DatePicker.vue
> +			display: none !important;
same here as above with `important`

2023-04-17 20:55 UTC, MartinSchuhmacher commented on src/components/date-time-picker/DateTimePicker.unit.ts
> +	maxDate?: string;
as we work with TypeScript here, maybe we should work with Date types instead of just strings?

2023-04-18 11:56 UTC, christian-darsow commented on src/components/date-time-picker/DatePicker.vue
> +				: model.value;
do you mean it would be easier to read if the else part explicitly returns an empty string?

2023-04-18 11:59 UTC, christian-darsow commented on src/components/date-time-picker/DatePicker.vue
> +		}, 50);
Unfortunately there is no such other event/hook that could then trigger this function call, therefore it is debounced to have a smooth UI

2023-04-18 13:22 UTC, christian-darsow commented on src/components/date-time-picker/DatePicker.vue
> +			transform: translateY(-6px) scale(0.75) !important;
Good point, removed that by using vuetify vars here instead

2023-04-18 13:22 UTC, christian-darsow commented on src/components/date-time-picker/DatePicker.vue
> +			display: none !important;
yeap, as above. Fixed

2023-04-19 05:46 UTC, christian-darsow commented on src/components/date-time-picker/DateTimePicker.unit.ts
> +	maxDate?: string;
As talked about we take the date-handling, in detail the date-as-string handling to the next level for general discussion. for now we leave it as is in this PR

2023-04-19 06:03 UTC, MartinSchuhmacher approved these changes

2023-04-19 13:39 UTC, merged