BC-3108 - beta task visibility
hpi-schul-cloud/nuxt-client pull request #2493
Opened 2023-04-14 14:02 UTC by christian-darsow

# Short Description

Implement component for planning the visibilty of a beta task

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-3108

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-04-21 07:21 UTC, MartinSchuhmacher commented on src/components/beta-task/types/visibilty.ts
> +export type VisibleState = "visible" | "notVisible" | "visibleAt";
to be more (type) precise, maybe `visibleAt` could be `visibleAtDate` (similar to BE) ?

update: you also named it like that in the taskcard page, so that would fit as well :)

2023-04-21 07:21 UTC, MartinSchuhmacher commented on src/pages/TaskCard.page.vue
> +			return payload as TaskCardParams;
why seting it here again if the type is set in line 351 ?

2023-04-21 07:21 UTC, MartinSchuhmacher commented on src/pages/TaskCard.page.vue
> +				await taskCardModule.updateTaskCard(createPayload());
I see why the new createPayload build structure is chosen, but seting `updateTaskCard` with a "create" parameter still feels odd to me

2023-04-21 07:21 UTC, MartinSchuhmacher commented on src/plugins/datetime.js
> +export const isInPast = (date) => {
maybe specify more with `dateIsInPast` or `timeIsInPast`?

2023-04-21 07:27 UTC, christian-darsow commented on src/pages/TaskCard.page.vue
> +			return payload as TaskCardParams;
it would be of type `Partial<TaskCardParams>`  then. what we don't expect, but TaskCardParams. I just set it to Partial, so that we can "build" it step by step

2023-04-21 07:30 UTC, christian-darsow commented on src/pages/TaskCard.page.vue
> +				await taskCardModule.updateTaskCard(createPayload());
:) I see... I thought more that this func creates the payload - and not that it is the create-payload. But well, obviously I will think about better naming

2023-04-21 07:57 UTC, christian-darsow commented on src/components/beta-task/types/visibilty.ts
> +export type VisibleState = "visible" | "notVisible" | "visibleAt";
Good point!

2023-04-21 09:13 UTC, christian-darsow commented on src/plugins/datetime.js
> +export const isInPast = (date) => {
good idea, changed as well

2023-04-21 09:45 UTC, MartinSchuhmacher submitted a review, later dismissed

2023-04-24 12:38 UTC, odalys-dataport requested changes

2023-04-24 12:38 UTC, odalys-dataport commented on src/components/beta-task/VisibilitySelector.vue
> +			required: (value: string) => !!value || t("common.validation.required"),
As mentioned by Franz, since we're working on this right now, we should add a specific validation error text

2023-04-24 12:38 UTC, odalys-dataport commented on src/components/beta-task/VisibilitySelector.vue
> +		const visibilityOptions = ref<VisibilityOption[]>([
this does not need to be a ref, since it does not change

2023-04-24 17:39 UTC, christian-darsow commented on src/components/beta-task/VisibilitySelector.vue
> +		const visibilityOptions = ref<VisibilityOption[]>([
yeap, changed that to normal array

2023-04-25 15:07 UTC, christian-darsow commented on src/components/beta-task/VisibilitySelector.vue
> +			required: (value: string) => !!value || t("common.validation.required"),
Adapted that to a more specific error message after talking to UX

2023-04-27 07:38 UTC, odalys-dataport approved these changes

2023-05-15 11:41 UTC, closed without merging