Bc 3348 frontend changes in status
hpi-schul-cloud/nuxt-client pull request #2494
Opened 2023-04-17 16:00 UTC by Michaellinaresxk

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-04-19 07:51 UTC, MateuszSapalaPassCon approved these changes

2023-04-26 04:09 UTC, muratmerdoglu-dp requested changes

2023-04-26 04:09 UTC, muratmerdoglu-dp commented on src/components/molecules/StatusAlerts.unit.ts
> -
Why do you need to remove this completely?

2023-04-26 04:09 UTC, muratmerdoglu-dp commented on src/components/molecules/StatusAlerts.vue
> +		style="border-radius: 4px"
We should avoid to add an inline styling.

2023-04-26 04:09 UTC, muratmerdoglu-dp commented on src/components/molecules/StatusAlerts.vue
> +			}"
Inline styling.

2023-04-26 04:09 UTC, muratmerdoglu-dp commented on src/components/molecules/StatusAlerts.vue
> +					style="overflow: visible; text-overflow: clip; white-space: normal"
inline styling

2023-04-26 04:09 UTC, muratmerdoglu-dp commented on src/components/molecules/StatusAlerts.vue
> +						flex-wrap: wrap;
Inline styling.

2023-04-26 04:09 UTC, muratmerdoglu-dp commented on src/components/molecules/StatusAlerts.vue
> +					style="font-size: 14px"
Inline styling.

2023-04-26 04:09 UTC, muratmerdoglu-dp commented on src/components/molecules/StatusAlerts.vue
> +	border-radius: 4px;
Using vuetify border-radius is better. (E.g. 'rounded-sm', 'rounded-lg' etc.)

2023-04-26 04:09 UTC, muratmerdoglu-dp commented on src/plugins/datetime.js
> +	if (isLocalTimeZone == true) {
```suggestion
	if (isLocalTimeZone) {
```

2023-04-26 08:23 UTC, Michaellinaresxk commented on src/components/molecules/StatusAlerts.unit.ts
> -
I removed the url because in this component according to the ticket issue we dont need it. 
<img width="448" alt="Screen Shot 2023-04-26 at 10 22 46 AM" src="https://user-images.githubusercontent.com/116801315/234515295-04b9ef35-5cb0-4252-a163-c84957306a14.png">

2023-04-26 13:53 UTC, Michaellinaresxk commented on src/components/molecules/StatusAlerts.vue
> +			}"
We agree with UI department for this particular exeption.

2023-04-26 13:58 UTC, Michaellinaresxk commented on src/components/molecules/StatusAlerts.vue
> +		style="border-radius: 4px"
Ready

2023-04-26 14:05 UTC, Michaellinaresxk commented on src/components/molecules/StatusAlerts.vue
> +					style="overflow: visible; text-overflow: clip; white-space: normal"
With UI department we accept in this case to add those lines to reset some vuetify unexpected behaviour.

2023-04-27 13:36 UTC, muratmerdoglu-dp requested changes

2023-05-05 07:17 UTC, muratmerdoglu-dp requested changes

2023-05-05 07:17 UTC, muratmerdoglu-dp commented on src/components/molecules/StatusAlerts.vue
> +		};
An unit test should be added if `getCreatedDate` method returns an expected result and if exists in `<template>`.

2023-05-05 07:17 UTC, muratmerdoglu-dp commented on src/components/molecules/StatusAlerts.vue
> +			border-top: 1px solid #e5e5e5;
Vuetify colors should be used here instead of hardcoding `#e5e5e5`. 
https://v2.vuetifyjs.com/en/styles/colors/#material-colors

2023-05-05 07:17 UTC, muratmerdoglu-dp commented on src/components/molecules/StatusAlerts.vue
> +		color: #1b1b1b;
Same above.

2023-05-05 07:17 UTC, muratmerdoglu-dp commented on src/locales/de.json
> +	"common.labels.updateAt": "Aktualisiert",
There is a `:` missing after the word `Aktualisiert`.

2023-05-05 07:21 UTC, muratmerdoglu-dp commented
<img width="496" alt="image" src="https://user-images.githubusercontent.com/64781656/236398220-590fecae-18ea-454f-86a1-fa494b7671c6.png">

The indents and colors are different between the client and nuxt_client.

2023-05-05 08:37 UTC, Michaellinaresxk commented on src/components/molecules/StatusAlerts.vue
> +		color: #1b1b1b;
> <img alt="image" width="496" src="https://user-images.githubusercontent.com/64781656/236398220-590fecae-18ea-454f-86a1-fa494b7671c6.png">
> 
> The indents and colors are different between the client and nuxt_client.

The Nuxt-client is the new version of the proyect, for this reason every new UI/UX implemantation for this component is apply on nuxt instead of legacy-client.   This behaviour is approve by

2023-05-05 15:19 UTC, muratmerdoglu-dp approved these changes

2023-05-05 15:44 UTC, merged