BC-2322-Getting data from get when changing a toggle
hpi-schul-cloud/nuxt-client pull request #2511
Opened 2023-05-04 11:58 UTC by VikDavydiuk

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-05-11 16:59 UTC, bn-pass submitted a review, later dismissed

2023-05-22 08:25 UTC, muratmerdoglu-dp requested changes

2023-05-22 08:25 UTC, muratmerdoglu-dp commented on src/store/schools.ts
> +
Probably `Vue.nextTick()` can solve the problem instead of adding another server call to the server.

2023-05-22 10:42 UTC, blazejpass submitted a review, later dismissed

2023-05-22 11:26 UTC, muratmerdoglu-dp approved these changes

2023-05-22 12:42 UTC, blazejpass approved these changes

2023-05-22 12:49 UTC, muratmerdoglu-dp approved these changes

2023-05-22 12:49 UTC, merged