THR-18 H5P Editor
hpi-schul-cloud/nuxt-client pull request #2517
Opened 2023-05-09 11:12 UTC by marode-cap

# Short Description
Adds the H5P microservice to the development server proxy

## Links to Ticket and related Pull-Requests
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4106

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-05-09 12:56 UTC, CeEv approved these changes

2023-05-10 08:15 UTC, marode-cap commented on webpack-config/dev-server-config.js
> +						// console.log("--- serverPath: ", path);
Removed unnecessary comments

2023-05-11 09:36 UTC, CeEv requested changes

2023-05-11 09:36 UTC, CeEv commented on openapitools-for-h5p-editor.json
> +}
Add a empty line at the end to make gitHub lucky.

2023-05-11 09:41 UTC, marode-cap commented on openapitools-for-h5p-editor.json
> +}
Added newline

2023-05-11 09:42 UTC, CeEv approved these changes

2023-05-11 10:43 UTC, merged