N21-5366 implement tools tab
hpi-schul-cloud/nuxt-client pull request #2535
Opened 2023-05-15 11:19 UTC by IgorCapCoder

# Short Description
adds a new tab in a course for new ctl-tools. This will become the only tools tab in future, but will be available together with the old lti tools tab for development purposes. Also the UI for adding a tool and editiing/deleting a tool is implemented here.

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-536
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/522

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-05-24 08:44 UTC, arnegns commented on src/locales/de.json
> +	"pages.rooms.tools.deleteDialog.content": "Möchten Sie wirklich das Tool '<i>{itemName}</i>' aus dem Kurs entfernen?",
Was the text a requirement? Otherwise i would prefer: "Möchten Sie das Tool '<i>{itemName}</i>' wirklich aus dem Kurs entfernen?" And also in any other translations

2023-05-24 08:44 UTC, arnegns commented on src/pages/rooms/room-overview.unit.js
> +import AuthModule from "../../store/auth";
Please use relative imports again :)

2023-05-24 08:44 UTC, arnegns commented on src/store/context-external-tool.ts
> +export default class ContextExternalToolsModule extends VuexModule {
Do we really want a own store for this? and do we want to store the tools in a store?

2023-05-24 08:44 UTC, arnegns commented on src/store/env-config.ts
> +			this.env.FEATURE_NEW_SCHOOL_ADMINISTRATION_PAGE_AS_DEFAULT_ENABLED ??
What happens if there feature flag was explicit set to false?

2023-05-24 09:18 UTC, MarvinOehlerkingCap commented on src/store/env-config.ts
> +			this.env.FEATURE_NEW_SCHOOL_ADMINISTRATION_PAGE_AS_DEFAULT_ENABLED ??
If the feature is false then the right-hand side is used and set to false. If you want to use true as default value then it would always be true though. The operation is supposed to give a default value if the env is not defined and for that case `??` is more correct then `||`.

2023-05-24 09:23 UTC, MarvinOehlerkingCap commented on src/store/context-external-tool.ts
> +export default class ContextExternalToolsModule extends VuexModule {
Idk, we can let the person decide that actually implements the server call. I am fine with this atm.

2023-05-25 09:49 UTC, arnegns approved these changes

2023-05-25 10:12 UTC, odalys-dataport requested changes

2023-05-25 10:12 UTC, odalys-dataport commented on src/components/external-tools/RoomExternalToolCard.vue
> +				data-testid="tool-card-logo"
this image is missing an alt text

2023-05-25 10:12 UTC, odalys-dataport commented on src/components/external-tools/RoomExternalToolCard.vue
> +		const t = (key: string): string => i18n?.tc(key, 0) || key;
Should this function be used in template instead of $t?

2023-05-25 10:12 UTC, odalys-dataport commented on src/locales/de.json
> +	"pages.rooms.tools.newTab": "neuer Tab",
Please start with a capital letter

2023-05-25 10:12 UTC, odalys-dataport commented on src/pages/rooms/external-tools/RoomExternalToolsOverview.vue
> +				contain
image is missing an alt text (alt-attribute)

2023-05-25 10:35 UTC, MarvinOehlerkingCap commented on src/components/external-tools/RoomExternalToolCard.vue
> +		const t = (key: string): string => i18n?.tc(key, 0) || key;
I am not sure. We still use $t in all of our templates for translation, but we use the injection of i18n when translating in the setup function. We also don't have a composable for translations as a unified way of using the t function in setups. This is something we could discuss in the arc group.

2023-05-26 08:51 UTC, odalys-dataport approved these changes

2023-05-26 10:42 UTC, merged