N21-362 launch CTL Tool
hpi-schul-cloud/nuxt-client pull request #2552
Opened 2023-05-30 14:32 UTC by MarvinOehlerkingCap

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-05-31 12:12 UTC, arnegns requested changes

2023-05-31 12:12 UTC, arnegns commented on src/components/external-tools/RoomExternalToolCard.unit.ts
>  			const tool: ContextExternalTool = {
Looks like factory could be useful :) ?

2023-05-31 12:12 UTC, arnegns commented on src/pages/rooms/external-tools/RoomExternalToolsOverview.vue
> +		const onClickTool = async (tool: ContextExternalTool) => {
Im missing some tests for launching

2023-06-01 08:58 UTC, arnegns approved these changes

2023-06-20 15:01 UTC, uidp requested changes

2023-06-22 14:48 UTC, uidp commented on src/pages/rooms/external-tools/RoomExternalToolsOverview.vue
> +			injectStrict<ContextExternalToolsModule>(CONTEXT_EXTERNAL_TOOLS_MODULE);
You can remove the type parameter and just write `injectStrict(CONTEXT_EXTERNAL_TOOLS_MODULE)`. ts will infer the type from the key (symbol).

2023-06-22 14:48 UTC, uidp approved these changes

2023-06-22 14:55 UTC, uidp approved these changes

2023-06-22 15:15 UTC, merged