BC-3341 -  FE - Display downloadable file in file element
hpi-schul-cloud/nuxt-client pull request #2553
Opened 2023-06-01 12:10 UTC by bergatco

# Short Description

Display selected file in file element.

## Links to Ticket and related Pull-Requests

https://ticketsystem.dbildungscloud.de/browse/BC-3341

Based on work done in :
https://ticketsystem.dbildungscloud.de/browse/BC-3296
https://github.com/hpi-schul-cloud/nuxt-client/pull/2542

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-06-02 12:56 UTC, bischofmax commented on src/components/feature-board/content-elements/FileContentElementDisplay.vue
> +			type: Object as () => FileRecordResponse,
```suggestion
			type: Object as PropType<FileRecordResponse>,
```

2023-06-05 06:41 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementDisplay.vue
> +			type: Object as () => FileRecordResponse,
Fixed! Also for `FileContentElementEdit`.

2023-06-05 07:12 UTC, SevenWaysDP requested changes

2023-06-05 07:12 UTC, SevenWaysDP commented on src/components/feature-board/content-elements/FileContentElementDisplay.vue
> +		<div class="file-info">
Bitte lass uns passende vuetify elemente finden

2023-06-05 07:12 UTC, SevenWaysDP commented on src/components/feature-board/board/BoardColumn.vue
> +			class="pl-2"
warum müssen wir so globalw Änderungen machen um unserer Element richtig darzustellen

2023-06-05 07:17 UTC, bischofmax commented on src/components/feature-board/board/BoardColumn.vue
> +			class="pl-2"
@bergatco Ich glaube das wird nur von GitHub wieder falsch dargestellt oder? Kommen die Änderungen von Dir?

2023-06-05 11:19 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementDisplay.unit.ts
> +		fileRecord: {
Fixed!

2023-06-05 11:20 UTC, bergatco commented on src/components/feature-board/types/DragAndDrop.ts
> +	className: "rounded-sm grey lighten-1 my-3 mx-3",
Ignored as not part of this PR! Changes seem to come from the `main` branch.

2023-06-05 11:21 UTC, SevenWaysDP approved these changes

2023-06-05 11:21 UTC, bergatco commented on src/components/feature-board/types/DragAndDrop.ts
> +	className: "rounded-sm grey lighten-1 my-3 mx-3",
Ignored as not part of this PR! Changes seem to come from the `main` branch.

2023-06-05 11:21 UTC, bergatco commented on src/components/feature-board/card/CardHost.vue
> +</style>
Ignored as not part of this PR! Changes seem to come from the `main` branch.

2023-06-05 11:21 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementDisplay.vue
> +		<div class="file-info">
Fixed!

2023-06-05 11:22 UTC, bergatco commented on src/components/feature-board/board/BoardColumn.vue
> +			class="pl-2"
Ignored as not part of this PR! Changes seem to come from the `main` branch.

2023-06-05 16:47 UTC, Loki-Afro approved these changes

2023-06-05 16:58 UTC, merged