BC-3997 - Board Error Handling
hpi-schul-cloud/nuxt-client pull request #2562
Opened 2023-06-07 12:58 UTC by muratmerdoglu-dp

# Short Description
As a user, I want the board to work as expected and want to get meaningful error messages when there is an error.

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-3997

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-06-19 10:50 UTC, uidp requested changes
I think we should think about how we can handle unsuccessful operations on the API more consistently. As far as I can see we are using different approaches:
- check the response status code
- check the response itself (resource) or its `id`
- use exceptions
Using the response value as an indicator for an unsuccessful operation doesn't look like a good approach IMHO.

2023-06-19 10:50 UTC, uidp commented on src/components/feature-board/state/BoardState.composable.ts
> +		const response = (await boardsApi.boardControllerGetBoardSkeleton(id)).data;
`response.data` is the created resource. If you want to access the response you should remove `.data`. The expected response status code for successfull operation is 200. So checking the status accordingly might make sense.

2023-06-19 10:50 UTC, uidp commented on src/components/feature-board/state/BoardState.composable.ts
> +		if (!response?.id) {
Maybe better check for status code? Also `response.data` cannot be `undefined` (no question mark needed).

2023-06-19 10:50 UTC, uidp commented on src/components/feature-board/state/BoardState.composable.ts
> +		if (isErrorCode(response?.status)) {
response is will never be `undefined`(no question mark needed)

2023-06-19 10:50 UTC, uidp commented on src/components/feature-board/state/BoardState.composable.ts
> +		if (isErrorCode(response?.status)) {
response is will never be undefined(no question mark needed)

2023-06-19 10:50 UTC, uidp commented on src/components/feature-board/state/BoardState.composable.ts
> +			if (isErrorCode(response?.status)) {
response is will never be undefined(no question mark needed)

2023-06-19 10:50 UTC, uidp commented on src/components/feature-board/state/BoardState.composable.ts
> +		if (isErrorCode(response?.status)) {
The return type of `deleteCardCall` is `AxiosPromise<void>`, so `response` will never be `undefined` (no question mark needed)

2023-06-19 10:50 UTC, uidp commented on src/components/feature-board/state/BoardState.composable.ts
> +		if (!newColumn?.id) {
Maybe it's better to check for the expected status code (see below).

2023-06-19 10:50 UTC, uidp commented on src/components/feature-board/state/CardState.composable.ts
> +			const errorText = generateErrorText("read", "boardCard");
What kind of exception is handled here? And why are we using exeptions for error handlich is the error handled by exceptions whereas we are using the api return value in the other places?

2023-06-19 10:50 UTC, uidp commented on src/components/feature-board/state/CardState.composable.ts
> +		if (isErrorCode(response?.status)) {
`response` will never be `undefined`.

2023-06-19 10:50 UTC, uidp commented on src/components/feature-board/state/CardState.composable.ts
> +		if (isErrorCode(response?.status)) {
`response` will never be `undefined`.

2023-06-19 10:50 UTC, uidp commented on src/components/feature-board/state/CardState.composable.ts
> +		if (!result.id) {
Maybe better to check by repose status.

2023-06-19 11:36 UTC, muratmerdoglu-dp commented on src/components/feature-board/state/BoardState.composable.ts
> +		await fetchBoard(board?.value.id);
Considering card moving, the move card operation is triggered by the user for example, the card is in the new position in board object but there is an error on backend call. In this case we need to fetch board data from the backend for consistency. So I think we should keep it as it is.

2023-06-19 12:13 UTC, muratmerdoglu-dp commented on src/components/feature-board/content-elements/FileContentElement.unit.ts
> +		const wrapper = shallowMount(FileContentElement as MountOptions<Vue>, {
My linter complains about if there is no casting.

2023-06-19 15:45 UTC, uidp approved these changes

2023-06-20 14:29 UTC, uidp approved these changes

2023-06-21 11:43 UTC, merged