BC-3799 Display extended file info
hpi-schul-cloud/nuxt-client pull request #2573
Opened 2023-06-15 10:24 UTC by dyedwiper

# Short Description

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-3799

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-06-15 11:17 UTC, bergatco commented
Please add  tests for your new component `FileInfoChips` as well as extend the tests for `FileContentElement` to check for the parent component handing down the correct properties to its child component.

2023-06-15 11:22 UTC, bergatco commented on src/components/feature-board/shared/FileInfoChips.vue
Is it already decided to re-use this component somewhere else? Otherwise I would prefer to keep the component for now close to our `FileContentElement` and rename it to `FileContentElementChips` and move it out of the `shared` folder.

2023-06-15 11:42 UTC, SevenWaysDP reviewed
Please create tests

2023-06-15 11:42 UTC, SevenWaysDP commented on src/components/feature-board/shared/FileInfoChips.vue
> +	<div>
Please use chip-groups

https://v2.vuetifyjs.com/en/components/chip-groups/#usage

2023-06-15 11:42 UTC, SevenWaysDP commented on src/components/feature-board/shared/FileInfoChips.vue
> +		},
Please define the props you just need [fileSize, fileName]

2023-06-15 11:42 UTC, SevenWaysDP commented on src/components/feature-board/shared/FileInfoChips.vue
> +		});
Move the logic to a helper or Composition

2023-06-15 12:56 UTC, dyedwiper commented on src/components/feature-board/shared/FileInfoChips.vue
> +		});
We moved it in the utils folder.

2023-06-15 13:03 UTC, dyedwiper commented on src/components/feature-board/shared/FileInfoChips.vue
We thought about that too and weren't sure. To our knowledge it is not decided to reuse that. So we move it where you suggest.

2023-06-15 13:59 UTC, SevenWaysDP commented on src/components/feature-board/shared/FileInfoChips.vue
> +		},
It is now removed from FileContentElementEdit. For generic elements: if we have legacy file Element?

2023-06-16 09:25 UTC, KalliSfak commented on src/components/feature-board/shared/FileInfoChips.vue
> +		},
We defined the fileSize and fileName in props

2023-06-19 05:37 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementChips.unit.ts
Please split up the tests! In this file please keep / add only tests related to the `FileContentElementChips` component and all of its displayed Parts. Move all the tests related to `getFileExtension` and `convertFileSizeToHumanReadable` to a new test file at `src/utils/fileHelper.unit.ts`
Further please also extend the tests in order to check, whether the chips do display the input data correctly

2023-06-19 06:46 UTC, SevenWaysDP commented on src/components/feature-board/content-elements/FileContentElementChips.unit.ts
> +	});
This are not unit tests. Here two tests are enough, further tests are needed for fileHelper

2023-06-21 14:04 UTC, dyedwiper commented on src/components/feature-board/shared/FileInfoChips.vue
> +	<div>
Ich hab mir die Stelle nochmal angeguckt, weil ich mich gewundert hatte, dass man die Chips disablen muss, sie aber in der Doku nicht interaktiv sind: https://vuetifyjs.com/en/components/chips/ Turns out, die Interaktivität kommt von der Chip-Group: https://vuetifyjs.com/en/components/chip-groups/ Da steht auch: "It is used for creating groups of selections using chips." Und wir wollen hier ja keine Selection. Daher hab da wieder ein div hin gemacht.

2023-06-22 10:16 UTC, dyedwiper commented on src/utils/fileHelper.ts
> +	const localeString = convertedSize.toLocaleString("de-DE", {
Wir haben jetzt "window.navigator.language" benutzt, um die Sprache vom Browser auszulesen. Es gäbe ja auch noch die Möglichkeit die eingestellte Sprache aus der Bildungscloud zu nehmen. Wir haben uns gefragt, was besser ist, und waren unschlüssig...

2023-06-22 10:24 UTC, SevenWaysDP commented on src/utils/fileHelper.ts
> +	const localeString = convertedSize.toLocaleString("de-DE", {
Kannst du diese Frage bei Frontändler stellen. Ich denke das wäre besser, wenn wir "eingestellte Sprache" uns richten. Aber ich habe keine Ahnung ob wir etwas übersehen.

2023-06-22 10:27 UTC, SevenWaysDP approved these changes

2023-06-22 11:36 UTC, bergatco commented on src/utils/fileHelper.ts
> +	const localeString = convertedSize.toLocaleString("de-DE", {
Die Nutzersprache wird in `nuxt-client/src/components/molecules/LanguageMenu.vue` gesetzt. Dazu wird die Funktion `updateUserLanguage` des `AuthModule` (`nuxt-client/src/store/auth.ts`) aufgerufen. Demnach wird die `locale` im `AuthModule` dann gesetzt. Dem entsprechend könnte man eventuell die Funktion `getLocale` verwenden, um die aktuelle Sprache zu bestimmen?

2023-06-22 12:06 UTC, KalliSfak submitted a review, later dismissed

2023-06-22 12:25 UTC, bergatco requested changes

2023-06-22 12:25 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementChips.vue
> +	<div class="ma-2">
I just did check the styling again the designs in Figma. Please use `padding` instead of a `margin` here.

```suggestion
	<div class="pa-2">
```

2023-06-22 12:25 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementChips.vue
> +		<v-chip class="mr-2" small>{{ humanReadableFileSize }}</v-chip>
I also found, that the `v-chips` are still having an `hover` effect. Please apply the changes suggested by @SevenWaysDP .

```suggestion
		<v-chip class="mr-2" disabled small>{{ fileExtension }}</v-chip>
		<v-chip class="mr-2" disabled small>{{ humanReadableFileSize }}</v-chip>
```

2023-06-22 12:25 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementChips.vue
> +</script>
I also found, that the `v-chips` are still having an `hover` effect. Please apply the changes suggested by @SevenWaysDP .

```suggestion
</script>

<style lang="scss" scoped>
.v-chip {
	opacity: 1;
}
</style>

```

2023-06-22 12:25 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementChips.vue
Otherwise the styling does look good and is according to the mocks. 👍

2023-06-22 12:43 UTC, dyedwiper commented on src/components/feature-board/content-elements/FileContentElementChips.vue
> +	<div class="ma-2">
I didn't know that you can look it up in Figma. Interesting! It won't make any visible difference at the moment. This would only be the case if we had a different background, but this might change sometime... So we will use padding.

2023-06-23 09:52 UTC, dyedwiper commented on src/components/feature-board/content-elements/FileContentElementChips.vue
> +		<v-chip class="mr-2" small>{{ humanReadableFileSize }}</v-chip>
I'm wondering where this hover effect comes from because a v-chip doesn't normally have it. What I found is that when hovering the following pseudo-element is rendered: ".theme--light.v-chip:hover::before" with style "opacity: 0.04;". Do you have any idea where that comes from?

2023-06-30 05:17 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElement.unit.ts
Please also add tests for other scenarios :

-  "when the file needs to be uploaded" & "when upload is successful", the chips should be visible in both modes, edit & view.
-  "when the file needs to be uploaded" & "when upload throws error", the chips should NOT be visible in both modes, edit & view.
- "when file is uploaded" & "when a virus is detected", the chips should be visible in both modes, edit & view.

2023-06-30 05:25 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementChips.vue
> +		<v-chip class="mr-2" small>{{ humanReadableFileSize }}</v-chip>
Unfortunately, I don't. I also found while doing some previous research (see [Colored section of Chips in vuetify docs](https://v2.vuetifyjs.com/en/components/chips/#colored) , that the "default" chip does have a hover effect. If you change the `color` of it, the hover effect disappears.
But as we are using the "default" color here, please implement the workaround kindly provided by @SevenWaysDP.

2023-06-30 05:26 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementChips.unit.ts
Maybe it would also be a good idea to add some test cases for edge cases, like when either file size or name are not available (undefined)?

2023-06-30 05:30 UTC, bergatco commented on src/utils/fileHelper.ts
> +import { authModule } from "@/store";
This line can be removed, as `authModule` is not used anywhere in the file.

2023-06-30 05:32 UTC, bergatco commented on src/utils/fileHelper.unit.ts
Please add also some edge cases, when no or wrong data is provided to both functions.

2023-07-03 09:25 UTC, KalliSfak commented on src/utils/fileHelper.ts
> +	const localeString = convertedSize.toLocaleString("de-DE", {
We used the i18n.n function for the localization.

2023-07-03 11:22 UTC, bergatco submitted a review, later dismissed

2023-07-03 12:31 UTC, bergatco approved these changes

2023-07-03 13:08 UTC, merged