BC-4210 - Adapt file content element
hpi-schul-cloud/nuxt-client pull request #2584
Opened 2023-06-21 07:21 UTC by bergatco

# Short Description

User story
While implementing and testing [BC-3296](https://ticketsystem.dbildungscloud.de/browse/BC-3296) / [BC-3441](https://ticketsystem.dbildungscloud.de/browse/BC-3441) some discrepancies between the currently implemented design of the file content element and the designs in Figma were found.

## Links to Ticket and related Pull-Requests

https://ticketsystem.dbildungscloud.de/browse/BC-4210

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-06-23 11:14 UTC, CeEv requested changes

2023-06-23 11:14 UTC, CeEv commented on src/components/feature-board/content-elements/FileContentElementAlert.vue
> +	color: var(--v-black-base) !important;
Should not !important avoid for any self written code?

2023-06-23 11:14 UTC, CeEv commented on src/components/feature-board/content-elements/FileContentElementDisplay.unit.ts
> +		expect(downloadLink.attributes("download")).toBe("");
This is "" in case of the data preparations? If it look different for production, it can be make sense to prepare the data in a way that we see it in test too. It can be a nice documentation.

2023-06-23 11:14 UTC, CeEv commented on src/components/feature-board/content-elements/FileContentElementDisplay.vue
> +					color="#8a9199"
Adding #8a9199 in this way looks wrong. Do we have a seperate file for all color css const that can we use in our application? Otherwise nobody has a good overview which color do we have.

2023-06-23 11:14 UTC, CeEv commented on src/components/feature-board/content-elements/FileContentElementEdit.unit.ts
> +			) as string;
"as string" ?

2023-06-23 11:14 UTC, CeEv commented on src/components/feature-board/shared/BoardMenu.vue
> +		const hasBackground = computed<boolean>(() => props.scope === "card");
Exists the card string as enum, const ?

2023-06-23 11:14 UTC, CeEv commented on src/utils/fileHelper.ts
> +	document.body.appendChild(link);
Add it > click it > remove it ...i do not know the context, the ui and so on. But by reading the code it look special. :D

2023-06-23 11:14 UTC, CeEv commented on src/utils/fileHelper.unit.ts
> +		it("should download the file", () => {
use setup function for preparations with when describe as senario. I expect that also error cases can be exits. 

"as any" is it possible to avoid "as any"

2023-06-26 06:40 UTC, bergatco commented on src/components/feature-board/shared/BoardMenu.vue
> +		const hasBackground = computed<boolean>(() => props.scope === "card");
Not that I am aware of. The `BoardMenu` itself does not keep or import such an enum type and handles it all "manually".

2023-06-26 06:45 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementAlert.vue
> +	color: var(--v-black-base) !important;
Fixed by removing `!important` as well as replacing the whole `<style>` section by using vuetify classes on the component itself!

2023-06-26 06:47 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementDisplay.vue
> +					color="#8a9199"
This is a custom color specifically requested by Franz / Anna / UX team. Franz and I were not aware of such a file and that's why I hard coded it here. Will drop a message to our front end channel in rocket chat, asking if such a place does exist. Will let you know about the results.

2023-06-26 06:50 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementEdit.unit.ts
> +			) as string;
Fixed by replacing `as string` with the correct function call `.toString()`!

2023-06-26 06:56 UTC, bergatco commented on src/utils/fileHelper.ts
> +	document.body.appendChild(link);
Basically this functionality does add a hidden `<a>` element to the page, fires its `click` event and removes it afterwards as it is no longer needed and should not clutter the page any further.
As this does not require for the current page to fulfill any prerequisites, the function should work at all places / pages.

2023-06-26 07:35 UTC, bergatco commented on src/utils/fileHelper.unit.ts
> +		it("should download the file", () => {
Fixed by adding a separate `setup` function as well as getting rid of the `as any`!

2023-06-26 07:38 UTC, bergatco commented on src/utils/fileHelper.ts
> +	document.body.appendChild(link);
Got an answer back from the "frontend guys" (Odalys to be precise). Central colors should be placed at `themes/base-vuetify.options.js`. Therefore moved the new color `deco-icon` to the respective file.

2023-06-26 07:45 UTC, CeEv commented on src/components/feature-board/shared/BoardMenu.vue
> +		const hasBackground = computed<boolean>(() => props.scope === "card");
Sounds ...not so good or? :D

2023-06-26 07:50 UTC, CeEv commented on src/utils/fileHelper.ts
> +	document.body.appendChild(link);
Your answer to the point before right? Color sounds good. 
THe <a> click stuff sound special. But is ok for me. Maybe a command with a hind why can be help for others that read the code later.

2023-06-26 08:06 UTC, bergatco commented on src/utils/fileHelper.ts
> +	document.body.appendChild(link);
Fixed by adding some explanations as a comment to the function!

2023-06-26 08:06 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementDisplay.vue
> +					color="#8a9199"
Got an answer back from the "frontend guys" (Odalys to be precise). Central colors should be placed at `themes/base-vuetify.options.js`. Therefore moved the new color `deco-icon` to the respective file.

2023-06-26 08:07 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementDisplay.unit.ts
> +		expect(downloadLink.attributes("download")).toBe("");
Fixed by using the file name for the `download` attributes!

2023-06-26 08:11 UTC, CeEv approved these changes

2023-06-26 11:10 UTC, bischofmax commented on src/components/feature-board/content-elements/FileContentElementEdit.unit.ts
> +	const setupProps = (isBlocked: boolean | undefined = undefined) => ({
Undefined als default value? Kann das raus?

2023-06-26 11:55 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementAlert.vue
> +		color="error"
`type` setzt sowohl `color` als auch das `icon`. Da wir hier aber das icon `$warning` und die Farbe `error` kombinieren, muss das hier separat gesetzt werden.

2023-06-26 11:57 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementEdit.unit.ts
> +	const setupProps = (isBlocked: boolean | undefined = undefined) => ({
Wenn ich das raus nehme, müsste ich sonst alle bestehenden `setup`-Aufrufe anpassen und dediziert `undefined` als Argument übergeben. So konnte ich die bestehenden Funktionen einfach weiter benutzen.

2023-06-26 12:02 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementEdit.unit.ts
> +			childComponent.vm.$emit("click");
As we are using the AAA pattern, from my point of view the "click" is part of the "action" part and therefore should be part of the "scenario" and not the "setup".

2023-06-26 13:55 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementEdit.unit.ts
> +	const setupProps = (isBlocked: boolean | undefined = undefined) => ({
Fixed by making the `isBlocked` argument optional!

2023-06-27 06:03 UTC, bischofmax approved these changes

2023-06-27 06:31 UTC, MartinSchuhmacher commented on src/components/feature-board/content-elements/FileContentElementDisplay.unit.ts
> +			console.log(wrapper.overview());
das muss noch raus, oder?

2023-06-27 06:31 UTC, MartinSchuhmacher commented on src/components/feature-board/content-elements/FileContentElementDisplay.vue
> +		isBlocked: {
ich frage mich ob die Bezeichnung `isBlocked` aussagekräftig genug ist. beim ersten Lesen ergibt sich für mich nicht direkt, was der Grund (in diesem Falle Herkunft der Prop) für das Blocking sein könnte. Ist dann vielmehr eine Frage der Lesbarkeit für mich.

2023-06-27 07:04 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementDisplay.unit.ts
> +			console.log(wrapper.overview());
Yep, wurde entfernt!

_(Muss mir echt angewöhnen vor dem Commit nochmal nach `wrapper.overview` suchen.)_

2023-06-27 07:05 UTC, bergatco commented on src/utils/fileHelper.ts
> +	link.hidden = true;
Hatte manchmal ein merkwürdiges "Artefakt" (schmaler rechteckiger Cursor hinter dem Link), wenn ich auf den Link geklickt habe. Daher habe ich das hinzugefügte Element "versteckt". Danach trat das "Artefakt" nicht mehr auf.

2023-06-27 09:45 UTC, christian-darsow commented on src/components/feature-board/shared/BoardMenu.vue
> +		const hasBackground = computed<boolean>(() => props.scope === "card");
We use a union type for that instead :) https://github.com/hpi-schul-cloud/nuxt-client/pull/2584/files#diff-e31811270c6a14d21793afca57975ce52d75d3363f3df1fd34b1dc8d5e309e64R45  also highlights passing wrong props in the IDE

2023-06-27 09:49 UTC, christian-darsow commented on src/components/feature-board/content-elements/FileContentElementEdit.vue
> +		<v-list
I wonder if a list really is the best possible component here? Even though a list with always one entry... it still a list. But might lead to a11y confusion to mark things as list. Do you know more about that?

2023-06-27 10:53 UTC, dyedwiper commented on src/components/feature-board/content-elements/FileContentElementEdit.vue
> +		<v-list
IMO it is wrong to use a list here because there is nothing listed here. You should always use the semantically appropriate HTML elements - for a11y but also for other devs who are reading the code.

2023-06-27 19:27 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementDisplay.vue
> +		isBlocked: {
Der Zustand des `SecurityScanStatus`, wenn ein Virus entdeckt wird, lautet `BLOCKED`. Daher ist es für mich verständlich.
Ich bin hier für Vorschläge offen. 😉

2023-06-27 19:28 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementEdit.vue
> +		<v-list
What would you suggest to use? A combination of `v-container`, `v-col` and `v-row`? Any other suggestions? I'm open to it.

2023-06-28 05:34 UTC, MartinSchuhmacher commented on src/components/feature-board/content-elements/FileContentElementDisplay.vue
> +		isBlocked: {
Hmm...nen richtig guter Vorschlag fällt mir gerade nicht ein, aber how about `isBlockedByVirus` ? :)

2023-06-28 05:34 UTC, MartinSchuhmacher commented on src/components/feature-board/content-elements/FileContentElementDisplay.vue
> +		isBlocked: {
oder auch `isBlockedByVirusScan`

2023-06-28 06:13 UTC, christian-darsow commented on src/components/feature-board/content-elements/FileContentElementEdit.vue
> +		<v-list
That sounds good to me, no other suggestion :)

2023-06-28 07:43 UTC, bischofmax commented on src/components/feature-board/content-elements/FileContentElementEdit.vue
> +			max-width="calc(100% - 44px)"
max-width="100%"?

2023-06-29 07:12 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementEdit.vue
> +			max-width="calc(100% - 44px)"
Unfortunately I need the `-44px` in order for the list to leave some space available for the `BoardMenu`. Otherwise the list will take the whole width of the element and the `BoardMenu` will be attached to it at the right hand side.

2023-06-30 10:39 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementEdit.vue
> +		<v-list
As my attempts to use `v-container`, `v-row` and `v-col` have all failed, @SevenWaysDP, @bischofmax and me took another look at the structure of `FileContentElementEdit` as well as `FileContentElementDisplay`.
We were able to simplify the structure quite a bit and even removed the `v-list` at all. Scanning through the Vuetify documentation we found, that it is quite common (or also desired) to use a `v-list-item` inside a `v-card`. And we also get rid of the `v-list-item-title` inside of the `v-list-item-content` and replaced it with some more HTML native "constructs" (either `<a>` for the link or `<span>` everywhere else).

_On a sidenote: Just looking on the Vuetify documentation, I think that  `v-container`, `v-row` and `v-col` are more appropriate for displaying a [Grid](https://v2.vuetifyjs.com/en/components/grids/), whereas the use cases displayed for a [List](https://v2.vuetifyjs.com/en/components/lists/) are more like our target designs._

2023-06-30 11:15 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementDisplay.vue
> +		isBlocked: {
Fixed by renamig `isBlocked` variable in `FileContentElement` to `isBlockedByVirusScan` and `isBlocked` prop of `FileContentElementEdit` as well as `FileContentElementDisplay` to `isDownloadAllowed`!

2023-07-03 07:11 UTC, SevenWaysDP approved these changes

2023-07-03 12:57 UTC, SevenWaysDP approved these changes

2023-07-03 13:41 UTC, SevenWaysDP approved these changes

2023-07-05 20:07 UTC, CeEv commented on src/components/feature-board/content-elements/FileContentElement.unit.ts
> +					const { wrapper } = setup(false);
Anmerkungen zu den setups via PN, aber kein merge Blocker.

2023-07-05 20:09 UTC, CeEv commented on src/components/feature-board/content-elements/FileContentElement.unit.ts
> +					const { wrapper } = setup(true, FileRecordScanStatus.BLOCKED);
Anmerkungen zu den setups via PN. Kein merge Blocker. Mit einen true/false verfälsch es bereits leicht den Sinn, aber der 2. Parameter sollte im Nachgang entfernt werden.

2023-07-05 20:18 UTC, CeEv commented on src/components/feature-board/content-elements/FileContentElementDisplay.unit.ts
> +		isDownloadAllowed: isDownloadAllowed ?? true,
Anstatt hier mit ?? zu arbeiten wäre ein default value in props einfacher und klarer.
isDownloadAllowed = true

2023-07-05 20:25 UTC, CeEv commented on src/components/feature-board/content-elements/FileContentElementDisplay.vue
> +	<v-list-item
v-list-item klinkt so als würde man es in einer Liste verwenden sollen. 

"The <template> tag is used as a placeholder when we want to use a built-in directive without rendering an element in the DOM." 
...mh wir wollen doch so kleinteilige partielle updates möglich machen. Darum sollte sich vue selbst kümmern. Evtl. muss ich über das template noch mal meditieren, aber es klinkt erstmal nicht so als ob es das macht, was wir wollen.
Evtl. könnt ihr mir später erklären was es tut.

2023-07-05 20:29 UTC, CeEv commented on src/components/feature-board/content-elements/FileContentElementEdit.unit.ts
> +		it("should find delete board menu action", () => {
Suchen wir die Board delete action, oder die content-element action? 
Desweiteren wäre das doch etwas das einmalig für alle elemente definiert wird mit entsprechenden Buttons und Tasten Events. Ich hatte mitbekommen, das es da auch Klärungsbedarf gibt, von daher erstmal ok. Nur ziemlich viel Code / Testcode den man sich hätte sparen können wenn es nicht Aufgabe jeder einzelnen content/text-elements wäre das neu zu definieren.

2023-07-05 20:35 UTC, CeEv commented on src/components/feature-board/content-elements/FileContentElementEdit.unit.ts
> +						[I18N_KEY as symbol]: { t: (key: string) => key },
Äh ja, total intuitive für ein Test. :D 
Klinkt nach der Lösung die mir auch direkt einfallen würde, wenn ich was mit i18n machen wollen würde... xD
Evtl. kann da das vue Chapter noch etwas an den setup vereinfachen.

2023-07-05 20:44 UTC, CeEv commented on src/utils/fileHelper.unit.ts
> +			const createElementSpy = jest
Das ist keine einmaliger mock return once, sondern ein genereller mock. Dieser sollte zumindest solange existieren wie man sich im gleichen describe befindet, oder sogar im gleichen unit.ts file. 
Dieser müsste dann explizit resettet werden via after/beforeEach. 

Sobald mehre it`s im describe sind, oder sub describes hinzugefügt werden z.B. mehre when .... die hier auch fehlen, dann könnte das unerwünschte Effekte haben.

2023-07-05 20:45 UTC, CeEv approved these changes

2023-07-06 05:05 UTC, merged