fix logo loading
hpi-schul-cloud/nuxt-client pull request #2588
Opened 2023-06-21 19:58 UTC by wiaderwek

# Short Description

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-3565

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-06-30 15:49 UTC, uidp requested changes

2023-06-30 15:49 UTC, uidp commented on dockerconf/nginx.conf.template
> +    set $csp "default-src 'self'; base-uri 'self'; script-src 'nonce-$request_id' 'strict-dynamic' 'unsafe-inline' https:; object-src 'none'; font-src 'self' data:; style-src 'self' 'unsafe-inline';
Why did you remove the `img-src` rules? I thought the issue was about the `connect-src` used with the `fetch` API?

2023-06-30 15:49 UTC, uidp commented on src/components/legacy/TheTopBar.vue
> +		loadLogoImg() {
I think the issue is not about loading the image from a base64 string when it gets displayed. That is covered by the `img-src` CSP rule and should be fine. Besides that the image doesn't seem to work.

2023-07-03 16:23 UTC, uidp requested changes

2023-07-03 16:23 UTC, uidp commented on src/components/legacy/TheTopBar.vue
> +			if (this.school && this.school.logo_dataUrl) {
It looks like we're getting an error when `logo_dataUrl` is `undefined`. Should we provide a reasonable default value?

2023-07-05 07:02 UTC, uidp requested changes

2023-07-05 07:02 UTC, uidp commented on src/components/legacy/TheTopBar.unit.js
> +		global.URL.revokeObjectURL = jest.fn();
Are `createObjectURL` and `revokeObjectURL` even used somewhere - because we are using `img-src data:` and not `blob:`?

2023-07-05 07:02 UTC, uidp commented on src/layouts/legacyLoggedIn.unit.js
> +		global.URL.revokeObjectURL = jest.fn();
Are `createObjectURL` and `revokeObjectURL` even used somewhere - because we are using `img-src data:` and not `blob:`?

2023-07-05 07:30 UTC, wiaderwek commented on src/components/organisms/administration/GeneralSettings.vue
>  		toBase64,
this is still used in save mehod to read file to base64

2023-07-05 09:21 UTC, uidp submitted a review, later dismissed

2023-07-06 09:49 UTC, uidp approved these changes

2023-07-06 09:51 UTC, merged