BC-4143 - text by enter
hpi-schul-cloud/nuxt-client pull request #2593
Opened 2023-06-22 13:15 UTC by christian-darsow

# Short Description
Create a new text element as the first element when hitting enter key within title field

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-4143

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-06-29 12:20 UTC, odalys-dataport submitted a review, later dismissed

2023-07-06 08:05 UTC, MartinSchuhmacher requested changes

2023-07-06 08:05 UTC, MartinSchuhmacher commented on src/components/feature-board/shared/BoardAnyTitleInput.vue
> +			if (textarea.value.value.length === textarea.value.selectionStart) {
`textarea.value.value` sounds really weird code wise. can we set `textarea.value` into another variable and make it more readable? also for line 116 then?

2023-07-06 08:29 UTC, christian-darsow commented on src/components/feature-board/shared/BoardAnyTitleInput.vue
> +			if (textarea.value.value.length === textarea.value.selectionStart) {
hm. the first `value` is for the reactive part. the second is then the property "value" of that reactive object ([HTMLTextAreaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement)). So somewhere in the code I guess we will always have that .value.value Do you have an idea how to make it more readable though?

2023-07-06 09:12 UTC, MartinSchuhmacher commented on src/components/feature-board/shared/BoardAnyTitleInput.vue
> +			if (textarea.value.value.length === textarea.value.selectionStart) {
if its like that then maybe something like `const reactiveTextarea = textarea.value` might fit as a first thought

2023-07-06 10:15 UTC, christian-darsow commented on src/components/feature-board/shared/BoardAnyTitleInput.vue
> +			if (textarea.value.value.length === textarea.value.selectionStart) {
To be honest, I don't like this idea very much. This `.value` syntax tells me that something is reactive. I always watch out for this syntax to know whether something is reactive or not - even before reading a vars name - what do you think about an alternative: a computed prop thats name states that it presents the textareas value length?

2023-07-06 11:09 UTC, MartinSchuhmacher commented on src/components/feature-board/shared/BoardAnyTitleInput.vue
> +			if (textarea.value.value.length === textarea.value.selectionStart) {
sounds good to me 👍

2023-07-06 14:53 UTC, christian-darsow commented on src/components/feature-board/shared/BoardAnyTitleInput.vue
> +			if (textarea.value.value.length === textarea.value.selectionStart) {
I moved the length calculation to a seperat function. This still needs that weird looking `.value.value` but makes it more readable by the function name I hope

2023-07-06 16:30 UTC, MartinSchuhmacher commented on src/components/feature-board/shared/BoardAnyTitleInput.vue
> +			if (textarea.value.value.length === textarea.value.selectionStart) {
I agree

2023-07-11 12:45 UTC, merged