BC-4455 - Injection error for "envConfigModule"
hpi-schul-cloud/nuxt-client pull request #2629
Opened 2023-07-06 06:17 UTC by bergatco

# Short Description

@christian-darsow pointed out to us, that by https://github.com/hpi-schul-cloud/nuxt-client/pull/2607/commits/74e1a1e0a01e2eb5eba8d4d79a172a446fac976a we introduced an injection error within the "LanguageMenu".

## Links to Ticket and related Pull-Requests

https://ticketsystem.dbildungscloud.de/browse/BC-4455

@SevenWaysDP original changes : https://github.com/hpi-schul-cloud/nuxt-client/pull/2607/commits/74e1a1e0a01e2eb5eba8d4d79a172a446fac976a

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-07-06 08:28 UTC, uidp requested changes

2023-07-06 08:28 UTC, uidp commented on src/main.ts
> +			envConfigModule,
I don't think we should inject the module twice. We should rather refactor the "old" OptionsAPI injects to using the injection keys, e.g.:
```typescript
inject: {
	notifierModule: { from: NOTIFIER_MODULE_KEY },
	i18n: { from: I18N_KEY },
},
```

2023-07-06 13:57 UTC, uidp approved these changes

2023-07-06 13:57 UTC, uidp commented on src/components/molecules/LanguageMenu.unit.ts
> +				[ENV_CONFIG_MODULE_KEY as symbol]: envConfigModuleMock,
`ENV_CONFIG_MODULE_KEY.valueOf()`?

2023-07-06 13:57 UTC, uidp commented on src/pages/user-login-migration/UserLoginMigrationError.page.unit.ts
> +					[ENV_CONFIG_MODULE_KEY as symbol]: envConfigModule,
`ENV_CONFIG_MODULE_KEY.valueOf()`?

2023-07-07 05:25 UTC, bergatco commented on src/components/molecules/LanguageMenu.unit.ts
> +				[ENV_CONFIG_MODULE_KEY as symbol]: envConfigModuleMock,
Fixed!

2023-07-07 05:25 UTC, bergatco commented on src/pages/user-login-migration/UserLoginMigrationError.page.unit.ts
> +					[ENV_CONFIG_MODULE_KEY as symbol]: envConfigModule,
Fixed!

2023-07-07 07:34 UTC, uidp approved these changes

2023-07-07 07:39 UTC, merged