BC-4332 update impressum SC BB: new minister
hpi-schul-cloud/nuxt-client pull request #2630
Opened 2023-07-06 09:38 UTC by KalliSfak

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-4332

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-07-06 13:15 UTC, bergatco requested changes

2023-07-06 13:15 UTC, bergatco commented on src/themes/brb/components/templates/impressum.vue
> +				Vertreten durch die Minister für Bildung, Jugend und Sport Steffen
```suggestion
				Vertreten durch den Minister für Bildung, Jugend und Sport Steffen
```

2023-07-07 08:34 UTC, bergatco approved these changes

2023-07-07 08:55 UTC, muratmerdoglu-dp approved these changes

2023-07-07 11:47 UTC, merged