BC-4383 - editor mvp
hpi-schul-cloud/nuxt-client pull request #2632
Opened 2023-07-06 10:25 UTC by christian-darsow

# Short Description
Adjust editor features and toolbar for board MVP 

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-4383

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-07-10 16:40 UTC, odalys-dataport requested changes

2023-07-10 16:40 UTC, odalys-dataport commented on src/components/common/editor/CKEditor.vue
> +						title: i18n.t("components.edtitor.highlight.dullPink").toString(),
There's a typo in the translation key here in editor throughout all changes

2023-07-11 05:44 UTC, MartinSchuhmacher commented on src/components/common/editor/CKEditor.vue
> +						color: "#c3e0f2",
does it make sense to set the color here "by hand" if the others are set via variables and also this one works with the background color being set by a class? maybe it would appear cleaner if these hard coded colors also appear via variables

2023-07-11 06:20 UTC, christian-darsow commented on src/components/common/editor/CKEditor.vue
> +						title: i18n.t("components.edtitor.highlight.dullPink").toString(),
copy - paste - paste - paste ... thx :)

2023-07-11 06:33 UTC, christian-darsow commented on src/components/common/editor/CKEditor.vue
> +						color: "#c3e0f2",
Good point!

2023-07-11 07:35 UTC, odalys-dataport approved these changes

2023-07-11 13:46 UTC, merged