BC-4207 - Admins should not be able to access ColumnBoards
hpi-schul-cloud/nuxt-client pull request #2635
Opened 2023-07-06 15:35 UTC by uidp

# Short Description
Admins should not be able to access ColumnBoards. We need to implement proper error handling if the server reports an unauthorized request to a column board by an admin.

## Links to Ticket and related Pull-Requests
[BC-4207](https://ticketsystem.dbildungscloud.de/browse/BC-4207)

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-07-10 09:11 UTC, hoeppner-dataport requested changes

2023-07-10 09:11 UTC, hoeppner-dataport commented on src/serverApi/v3/api.ts
> +    Task = 'task'
I think that is incorrect... probably it should be called now SubmissionContainer... think MilkyWay changed this name. You need to pull server-code and regenerate the api-file.

2023-07-10 17:17 UTC, uidp commented on src/serverApi/v3/api.ts
> +    Task = 'task'
ok, I re-generated the api client.

2023-07-11 07:02 UTC, hoeppner-dataport commented on src/serverApi/v3/api.ts
> +    Task = 'task'
Strange... read about renaming to "SubmissionContainer" in the release notes of susi. Anyway. Thanks for rechecking.

2023-07-11 07:02 UTC, hoeppner-dataport approved these changes

2023-07-11 07:02 UTC, merged