BC-4170 - Display images in cards
hpi-schul-cloud/nuxt-client pull request #2637
Opened 2023-07-07 08:51 UTC by bergatco

# Short Description

As a user, i want to have images displayed in cards, if an uploaded file is an image.

## Links to Ticket and related Pull-Requests

https://ticketsystem.dbildungscloud.de/browse/BC-4170

Work formerly done by @bischofmax : https://github.com/hpi-schul-cloud/nuxt-client/pull/2598

Link to deployment : https://default-bc-4170-display-images-in-cards.cd.dbildungscloud.dev/
Link to board : https://default-bc-4170-display-images-in-cards.cd.dbildungscloud.dev/rooms/64a7d1fa3a9f1bbd054e5a5d/board

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-07-13 09:26 UTC, CeEv requested changes

2023-07-13 09:26 UTC, CeEv commented on src/components/feature-board/content-elements/FileRecord.composable.unit.ts
> +import { ObjectIdMock } from "@@/tests/test-utils/ObjectIdMock";
Für Zeile 5 und 6 halte ich index files sinnvoll. 
import { ObjectIdMock, fileRecordResponseFactory } from "@@/tests/test-utils/".
Das würde die sicherlich noch kommenden Refactorings im test Bereich übersichtlicher machen.

2023-07-13 09:26 UTC, CeEv commented on src/components/feature-board/content-elements/FileRecord.composable.unit.ts
> +	it("should set isImage to be false", async () => {
when block für die ersten 3 it + dem setup dazu.

2023-07-13 09:26 UTC, CeEv commented on src/components/feature-board/content-elements/ImageFileDisplay.unit.ts
> +			propsData: { ...propsData, isEditMode: isEditMode ?? false },
isEditMode: isEditMode ?? false  --> isEditMode

2023-07-13 09:26 UTC, CeEv commented on src/components/feature-board/content-elements/ImageFileDisplay.unit.ts
> +	describe("when component is not in edit mode", () => {
Die 4 Its darüber sind auch alle in isEditMode=false und daher Teil des hier im when beschriebenen Senarios.

2023-07-13 09:26 UTC, CeEv commented on src/components/feature-board/content-elements/ImageFileDisplay.unit.ts
> +		it("should forward move-down:up from FileContentElementMenu", () => {
Wie oben schon angemerkt, die ganzen wiederholenden event handlings und test dafür sollten eigentlich nicht unser Part sein.

2023-07-13 09:26 UTC, CeEv commented on src/components/feature-board/content-elements/ImageFileDisplay.vue
> +	top: 8px;
Das hatte ich irgendwo schon mal bei einem aus dem Team Dune angemerkt und um Klärung Richtung UX gebeten. Wollen wir hier wirklich mit px arbeiten, oder nicht eher mit rem?

2023-07-13 09:26 UTC, CeEv commented on src/components/feature-board/shared/FileStorageApi.composable.ts
> +			// which is caught by this empty error block
..and when something go wrong in the logic, we do not see an error. :P
Ich denke das es keine Situation gibt in der das catchen eines errors eine gute Idee wäre. 
Theoretisch gilt für das ganze Projekt das ein catchen von errors und sogar ein re-throw ohne cause option nicht erlaubt ist. 
Daher ist hier noch arbeit offen.

2023-07-13 09:26 UTC, CeEv commented on src/utils/helpers.js
> +		signal?.throwIfAborted();
Muss er thrown, oder ist es auch möglich in das Promise.resolve() zu kommen bei programmatischer Beendigung.

2023-07-13 09:26 UTC, CeEv commented on tests/test-utils/composable-mocks/fileRecordMock.ts
> +export const setupFileRecordMock = (props: Props = {}) => {
Das ist eigentlich nicht der generische FileRecordMock, sonder der spezifische imageFileRecordMock. Daher wäre isImageMock vermutlich auch immer true. Daneben könnte es ein geben, der ein anderen zukünftigen type entspricht. Daher dann für isImage ein false liefert. 
Vermutlich ist aber der Ansatz isImage ..true/false zu verwenden in Erwartung das es noch audio, vidio etc.. kommt nicht der optimale Ansatz. Was es hier auch kompliziert macht test setups zu schaffen, die in Zukunft nicht noch mal modifiziert werden müssen.

2023-07-13 10:53 UTC, dyedwiper commented on src/components/feature-board/content-elements/FileRecord.composable.ts
> +			mimeType === "image/jpeg" ||
In one comment in the ticket Max mentioned also "image/bmp". Did you leave it out on purpose?

2023-07-14 09:37 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElement.vue
> +		const ac = new AbortController();
Fixed by renaming variable to `abortController`!

2023-07-14 09:43 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElement.vue
> +		const fileContentElement = ref(undefined);
Das ist so leider die Standard-Implementierung, welche von Team MilkyWay in #2566 bei uns so eingebaut wurde. Anscheinend ist das `undefined` hier so gewollt, da die Funktion `useBoardFocusHandler` als zweites Argument `element: Ref<HTMLElement | undefined>` erwartet.

2023-07-14 09:47 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementEdit.vue
> +		const onMoveElementDown = () => {
Das würde ich so unterschreiben. 🖊️

2023-07-14 09:48 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElement.vue
> +		const onKeydownArrow = (event: KeyboardEvent) => {
Gerne! 📝

2023-07-14 09:49 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementMenu.unit.ts
> +import FileContentElementMenu from "./FileContentElementMenu.vue";
Erledigt!

2023-07-14 09:56 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementMenu.unit.ts
> +		const multipleElementsSetupProps = () => ({
Fixed by cleaning up the `setupProps` function!

2023-07-14 10:02 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementMenu.vue
> +<template>
Das `template` ist notwendig, da Vue anscheinend entweder ein `template` oder eine `render`-Funktion benötigt (siehe https://v2.vuejs.org/v2/guide/render-function.html#:~:text=Vue%20recommends%20using%20templates%20to,the%2Dcompiler%20alternative%20to%20templates.&text=Hello%20world!)

![image](https://github.com/hpi-schul-cloud/nuxt-client/assets/129839305/d389c980-9bee-4aff-aeea-1085b9ea5638)

Ohne `template` bekomme ich obige Fehlermeldung.

2023-07-14 10:13 UTC, bergatco commented on src/components/feature-board/content-elements/FileRecord.composable.ts
> +			mimeType === "image/svg+xml";
Jup, *.svg-Datei funktioniert! 😁 

![image](https://github.com/hpi-schul-cloud/nuxt-client/assets/129839305/d15a66de-db6f-48f7-918c-699db79b9973)

2023-07-14 10:37 UTC, bergatco commented on src/components/feature-board/content-elements/FileRecord.composable.unit.ts
> +import { ObjectIdMock } from "@@/tests/test-utils/ObjectIdMock";
Ich habe `index.ts` für den Ordner `/test/test-utils` und all seine Unterordner angelegt / erweitert. Die Änderung des `import` aber nur hier vorgenommen, da ich ansonsten 244 Stellen in 171 Dateien anpassen hätte müssen und dies den PR unheimlich aufgeblasen hätte und zum anderen auch sehr unübersichtlich gemacht hätte.

2023-07-14 10:40 UTC, bergatco commented on src/components/feature-board/content-elements/FileRecord.composable.unit.ts
> +	it("should set isImage to be false", async () => {
Fixed by adding a `"when file record is not an image"` block around the `setup` as well as the first 3 `it`s!

2023-07-14 10:46 UTC, bergatco commented on src/components/feature-board/content-elements/ImageFileDisplay.unit.ts
> +			propsData: { ...propsData, isEditMode: isEditMode ?? false },
Fixed!

2023-07-14 10:49 UTC, bergatco commented on src/components/feature-board/content-elements/ImageFileDisplay.unit.ts
> +	describe("when component is not in edit mode", () => {
Fixed!

2023-07-14 10:55 UTC, bergatco commented on src/components/feature-board/content-elements/ImageFileDisplay.vue
> +	top: 8px;
Vor kurzem bin ich über [Toolbar](https://v2.vuetifyjs.com/en/components/toolbars/) bzw. die [App bar](https://v2.vuetifyjs.com/en/components/app-bars/) von Vuetify gestolpert. Generell bin ich ja sehr dazu geneigt, eins von beiden zu nutzen, um sich um die Positionierung des Menüs zu kümmern.
Das würde auch wunderbar zu unserer "Zoom-Bar" beim Anzeigen eines Bildes im Dateielement passen.

2023-07-14 11:15 UTC, bergatco commented on src/components/feature-board/content-elements/FileRecord.composable.ts
> +			mimeType === "image/jpeg" ||
Fixed by extending the allowed `mimeTypes` to also contain `image/bmp`!

2023-07-14 11:25 UTC, bergatco commented on src/components/feature-board/content-elements/ImageFileDisplay.vue
> +	<v-list-item
Fixed by replacing `v-list-item` with `div`! You were right, the `v-list-item` was here not required at all. Thanks for pointing it out!

2023-07-14 11:41 UTC, dyedwiper commented on src/components/feature-board/content-elements/FileContentElement.vue
> +		const fileContentElement = ref(undefined);
Das ist im Wesentlichen so, wie es in der Doku zu useFocus gezeigt wird: https://vueuse.org/core/useFocus/#change-focus-state

Es ist bloß seltsam undefined explizit zu übergeben, anstatt bloß `ref()` zu schreiben. 

In der Vue-Doku wird übrigens `ref(null)` verwendet: https://vuejs.org/guide/essentials/template-refs.html#accessing-the-refs

2023-07-17 04:23 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElement.unit.ts
>  			describe("when component is not in edit mode", () => {
Fixed by renaming `not in edit mode` to `in view mode`!

2023-07-17 04:54 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElement.unit.ts
> +						const { wrapper, deleteElementMock } = getWrapper({
Fixed by restructuring unit tests in `view mode` vs. `edit mode`!

2023-07-17 04:57 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElement.unit.ts
>  			describe("when component is not in edit mode", () => {
New structure does look like this :
```
describe("FileContentElement"
  describe("when component is in view mode"
    describe("when file needs to be uploaded"
      describe("when upload is successful"
        it("should be found in dom"
        it("should render FileContentElementDisplay component"
        it("should call upload"
        it("should set selected file to undefined"
        it("should render FileContentElementChips component"
      describe("when upload throws error"
        it("should call deleteElement"
        it("should call setSelectedFile"
        it("should not render FileContentElementChips component"
      describe("when file upload is not finished onMount"
        it("should render v-progress-linear component"
      describe("when file is uploaded"
        describe("when no virus is detected"
          it("should be found in dom"
          it("should render FileContentElementDisplay component"
          it("should hand over correct file name to FileContentElementDisplay"
          it("should hand over url to FileContentElementDisplay"
          it("should hand over isDownloadAllowed property to FileContentElementDisplay"
          it("should call fetchFile"
          it("should render FileContentElementChips component"
          describe("when file is an image"
            it("should render ImageFileDisplay component"
            it("should hand over correct file name to ImageFileDisplay"
            it("should hand over empty url to ImageFileDisplay"
            it("should hand over isDownloadAllowed property as false to ImageFileDisplay"
            it("should hand over isFirstElement property to ImageFileDisplay"
            it("should hand over isLastElement property to ImageFileDisplay"
            it("should hand over hasMultipleElements property to ImageFileDisplay"
        describe("when a virus is detected"
          it("should hand over correct file name to FileContentElementDisplay"
          it("should hand over empty url to FileContentElementDisplay"
          it("should render FileContentElementChips component"
          it("should hand over isDownloadAllowed property as false"
          it("should render FileContentElementAlert component"
          describe("when file is an image"
            it("should render ImageFileDisplay component"
            it("should hand over correct file name to ImageFileDisplay"
            it("should hand over empty url to ImageFileDisplay"
            it("should hand over isDownloadAllowed property as false to ImageFileDisplay"
            it("should hand over isFirstElement property to ImageFileDisplay"
            it("should hand over isLastElement property to ImageFileDisplay"
            it("should hand over hasMultipleElements property to ImageFileDisplay"
  describe("when component is in edit mode"
    describe("when file needs to be uploaded"
      describe("when upload is successful"
        it("should be found in dom"
        it("should render FileContentElementEdit component"
        it("should render FileContentElementChips component"
      describe("when upload throws error"
        it("should call deleteElement"
        it("should call setSelectedFile"
        it("should not render FileContentElementChips component"
      describe("when file is uploaded"
        describe("when no virus is detected"
          it("should be found in dom"
          it("should render FileContentElementEdit component"
          it("should render FileContentElementChips component"
          it("should hand over isDownloadAllowed property as true"
          it("should call deleteElement function when it receives delete:element event from child"
          describe("when file is an image"
            it("should render ImageFileDisplay component"
            it("should hand over correct file name to ImageFileDisplay"
            it("should hand over empty url to ImageFileDisplay"
            it("should hand over isDownloadAllowed property as true to ImageFileDisplay"
            it("should hand over isFirstElement property to ImageFileDisplay"
            it("should hand over isLastElement property to ImageFileDisplay"
            it("should hand over hasMultipleElements property to ImageFileDisplay"
        describe("when a virus is detected"
          it("should hand over correct file name to FileContentElementEdit"
          it("should hand over empty url to FileContentElementEdit"
          it("should hand over isDownloadAllowed property as false to FileContentElementEdit"
          it("should hand over isFirstElement property to FileContentElementEdit"
          it("should hand over isLastElement property to FileContentElementEdit"
          it("should hand over hasMultipleElements property to FileContentElementEdit"
          it("should render FileContentElementChips component"
          it("should render FileContentElementAlert component"
          it("should call deleteElement function when it receives delete:element event from child"
          describe("when file is an image"
            it("should render ImageFileDisplay component"
            it("should hand over correct file name to ImageFileDisplay"
            it("should hand over empty url to ImageFileDisplay"
            it("should hand over isDownloadAllowed property as false to ImageFileDisplay"
            it("should hand over isFirstElement property to ImageFileDisplay"
            it("should hand over isLastElement property to ImageFileDisplay"
            it("should hand over hasMultipleElements property to ImageFileDisplay"
```

2023-07-17 05:06 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElement.unit.ts
> +			const setup = () => {
Für den Fall, dass der Upload ein wenig länger dauert und der Powernutzer bereits anfängt die nächsten Karte zu bearbeiten, ist es schon möglich, dass der Upload erst im View-Mode erfolgreich ist. Von daher habe ich den Fall `when upload is successful` für beide Modi drin gelassen.

2023-07-17 05:07 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElement.unit.ts
>  	describe("when file is uploaded", () => {
Aufgrund der Umstrukturierung in "View Mode" vs. "Edit Mode" ist hier keine Unterscheidung mehr nötig.

2023-07-17 05:13 UTC, bergatco commented on src/components/feature-board/content-elements/ImageFileDisplay.vue
> +	top: 8px;
Fixed by replacing `8px` by `0.5 rem`!

2023-07-17 07:07 UTC, bergatco commented on src/utils/helpers.js
> +		signal?.throwIfAborted();
Der Aufruf `throwIfAborted` hier dient eigentlich nur dazu zu überprüfen, ob das Signal bereits im Vorhinein abgebrochen wurde. Sollte dies der Fall sein, wird die weitere Verarbeitung hier bereits abgebrochen und der Rest der Funktion nicht ausgeführt.
Da der `AbortController` generell mit dem werfen von Exception agiert, würde ich es hier gerne so drin lassen.

2023-07-17 07:16 UTC, bergatco commented on src/components/feature-board/shared/FileStorageApi.composable.ts
> +			// which is caught by this empty error block
Habe jetzt die Fehlerbehandlung mal ein wenig angepasst.
Dabei ist mir aufgefallen, dass wir scheinbar `AbortController` / `AbortSignal` aufgrund von Versionsunterschieden nicht korrekt verwenden. Wenn wir die Funktion `fetchPendingFileRecursively` mit Hilfe des `AbortController` abbrechen, bekommen wir keinen "sauberen" Fehler, sondern eine `DOMException: signal is aborted without reason`.
In der aktuellen Version (zumindest nicht in den Interfaces) wird aber das Argument `reason` für `AbortController.abort` nicht unterstützt.

2023-07-17 09:15 UTC, bergatco commented on src/components/feature-board/shared/FileStorageApi.composable.ts
> +			// which is caught by this empty error block
Fixed by removing whole function due to removal of the "active pulling" functionality of the `FileContentElement`!

2023-07-17 09:21 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElement.unit.ts
> +				describe("when file is an image", () => {
Das würde ich auch erwarten. 😉

2023-07-17 09:23 UTC, bergatco commented on src/components/feature-board/content-elements/ImageFileDisplay.unit.ts
> +		it("should forward move-down:up from FileContentElementMenu", () => {
📝

2023-07-17 09:25 UTC, bergatco commented on tests/test-utils/composable-mocks/fileRecordMock.ts
> +export const setupFileRecordMock = (props: Props = {}) => {
Aktuell kann ich leider nicht voraussehen, welche Typen wir zukünftig unterstützen werden. Von daher tendiere ich hier zum progressiven Ansatz.

2023-07-17 13:13 UTC, CeEv commented on src/components/feature-board/content-elements/FileContentElement.unit.ts
>  		isEditMode: boolean;
isEditMode: false;
isFirstElement: false;
isLastElement: false;
hasMultipleElements: false;

Also default values wären möglich um Code Zeilen zu sparen.

2023-07-17 13:18 UTC, CeEv submitted a review, later dismissed

2023-07-17 13:31 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElement.unit.ts
>  		isEditMode: boolean;
Default-Werte funktionieren hier leider nicht. 😞

2023-07-18 09:47 UTC, dyedwiper commented on src/components/feature-board/content-elements/FileContentElement.vue
> +		const fileContentElement = ref(undefined);
Willst du das nicht noch in `ref()` ändern? Gibt doch keinen Grund da `undefined` explizit zu übergeben, oder?

2023-07-18 09:58 UTC, dyedwiper commented on src/components/feature-board/content-elements/FileRecord.composable.unit.ts
> +		it("should set isBlockedByVirusScan to be false", async () => {
Dieser und der Test dadrunter gehören IMO nicht in diesen describe-block, weil die nichts damit zu tun haben, ob die Datei ein Bild ist.

2023-07-18 10:16 UTC, dyedwiper commented on src/components/feature-board/content-elements/FileContentElementMenu.vue
> +			<VIcon>
Why do we use `VIcon` here instead of `v-icon`? In a quick google search I couldn't find out what the difference is.. Does it work just the same? Do we want to be consistent with it?

2023-07-18 11:55 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElement.vue
> +		const fileContentElement = ref(undefined);
Fixed!

2023-07-18 12:05 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementMenu.vue
> +			<VIcon>
`VIcon` is the same as `v-icon`. One can be replaced by the other and vice versa. As we took the code snippet from Team Milkyway, I would like to keep it untouched.

2023-07-18 13:43 UTC, bergatco commented on src/components/feature-board/content-elements/FileRecord.composable.unit.ts
> +		it("should set isBlockedByVirusScan to be false", async () => {
Fixed by restructuring the unit tests for `FileRecord.composable`! Grouped the test cases based on the used property, `isImage` vs `isBlockedByVirusScan & url`.

2023-07-18 13:46 UTC, dyedwiper commented on src/components/feature-board/content-elements/ImageFileDisplay.unit.ts
> +	describe("when component is not in edit mode", () => {
Die oberen Tests in diesem describe-block sind doch unabhängig vom edit-mode. Nur der unterste hängt davon ab. Daher sollten die oberen Tests IMO eine Ebene nach oben.

2023-07-18 13:48 UTC, dyedwiper commented on src/components/feature-board/content-elements/FileRecord.composable.unit.ts
> +				it("should set isImage to be false", async () => {
Meinst du hier `isBlockedByVirusScan`?

2023-07-18 13:49 UTC, dyedwiper commented on src/components/feature-board/content-elements/FileRecord.composable.unit.ts
> +			describe("when file record is not an image", () => {
Diese Fallunterscheidung versteh ich wieder nicht. `isBlockedByVirusScan` & `url` sind doch unabhängig vom Mimetype.

2023-07-18 13:52 UTC, dyedwiper commented on src/components/feature-board/content-elements/FileRecord.composable.unit.ts
> +				describe("when file record is undefined", () => {
Die beiden Zeilen passen doch nicht zusammen. Wenn der file record undefined ist, dann kann doch nicht gleichzeitig das file vom Virenscanner geblockt sein.

2023-07-18 13:54 UTC, dyedwiper commented on src/components/feature-board/content-elements/FileRecord.composable.unit.ts
> +				describe("when file record is not an image", () => {
Auch hier spielt der Mimetype doch keine Rolle.

2023-07-19 04:43 UTC, bergatco commented on src/components/feature-board/content-elements/ImageFileDisplay.unit.ts
> +	describe("when component is not in edit mode", () => {
Fixed by moving the requested unit tests one level up!

2023-07-19 04:48 UTC, bergatco commented on src/components/feature-board/content-elements/FileRecord.composable.unit.ts
> +				it("should set isImage to be false", async () => {
Fixed by replacing unit tests with "should set isBlockedByVirusScan to be false" block!

2023-07-19 04:55 UTC, bergatco commented on src/components/feature-board/content-elements/FileRecord.composable.unit.ts
> +			describe("when file record is not an image", () => {
Fixed by removing redundant and unnecessary unit tests!

2023-07-19 04:59 UTC, bergatco commented on src/components/feature-board/content-elements/FileRecord.composable.unit.ts
> +				describe("when file record is undefined", () => {
Fixed by removing the "when file record is undefined" unit tests from the "when file is blocked by the virus scanner" block!

2023-07-19 05:02 UTC, bergatco commented on src/components/feature-board/content-elements/FileRecord.composable.unit.ts
> +				describe("when file record is not an image", () => {
Already fixed by removing redundant and unnecessary unit tests!

2023-07-19 08:22 UTC, dyedwiper commented on tests/test-utils/composable-mocks/fileRecordMock.ts
> +	return mocks;
No usage of the function makes use of the return value. So maybe remove it to make it clearer that the function is just used to setup the mock?

2023-07-19 08:24 UTC, dyedwiper commented on tests/test-utils/composable-mocks/fileRecordMock.ts
> +	const mockedSelectedFile = jest.mocked(useFileRecord);
And you could put this line just before line 27 because it is not used before.

2023-07-19 08:28 UTC, dyedwiper commented on tests/test-utils/composable-mocks/fileRecordMock.ts
> +export const setupFileRecordMock = (props: Props = {}) => {
I think this should be called `setupUseFileRecordMock` because otherwise it sounds like you would mock a file record but you mock a composable.

2023-07-19 08:40 UTC, dyedwiper commented on src/components/feature-board/content-elements/FileContentElementMenu.unit.ts
> +		it("should show all board menu items", () => {
The download and delete action are independent of the number of elements. So I wouldn't mention them here and call this 
```suggestion
		it("should show the move up and move down action", () => {
```
Same for the tests below.

2023-07-19 08:42 UTC, dyedwiper commented on src/components/feature-board/content-elements/FileContentElementMenu.unit.ts
> +		it("should find delete board menu action", () => {
The delete action is independent of the of the download action. Thus they should be tested independently too.

2023-07-19 09:31 UTC, bergatco commented on tests/test-utils/composable-mocks/fileRecordMock.ts
> +	const mockedSelectedFile = jest.mocked(useFileRecord);
Fixed!

2023-07-19 09:31 UTC, bergatco commented on tests/test-utils/composable-mocks/fileRecordMock.ts
> +	return mocks;
Fixed!

2023-07-19 10:07 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementMenu.unit.ts
> +		it("should show all board menu items", () => {
Fixed by restructuring `FileContentElement` unit tests! Separated different menu actions (`move up/down`, `download`, and `delete`) into separate scenarios.

2023-07-19 10:07 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementMenu.unit.ts
> +		it("should find delete board menu action", () => {
Fixed by restructuring `FileContentElement` unit tests! Separated different menu actions (`move up/down`, `download`, and `delete`) into separate scenarios.

2023-07-19 10:10 UTC, dyedwiper commented on src/components/feature-board/content-elements/ImageFileDisplay.vue
> +				@move-down:element="onMoveElementDown"
I think it would be clearer to just pass the function here, instead of listening to the events and then re-emitting them. Is there some reasoning behind doing it this way with the events? I see that it's done like this everywhere...

2023-07-19 10:12 UTC, dyedwiper commented on src/components/feature-board/content-elements/ImageFileDisplay.vue
> +				@move-down:element="onMoveElementDown"
...but as it is done everywhere like this, it's more of a general discussion. Not focussed on this PR. So I guess you should leave it here like this.

2023-07-19 10:15 UTC, dyedwiper commented on src/components/feature-board/content-elements/FileContentElementMenu.unit.ts
> +			describe("when move up menu action is clicked", () => {
This test and the one below should be one level up, I think. They are independent from the number of elements (even though the actions might not be available depending on the number).

2023-07-19 10:18 UTC, bergatco commented on src/components/feature-board/content-elements/ImageFileDisplay.vue
> +				@move-down:element="onMoveElementDown"
I think, this is required as the "movement" or "deletion" of a content element has to be done in the context of a "card" as there are some additional information (card id, index of elemenet, etc.) required. Therefore it would be very cumbersome having to pass on the function as well as all required functionalities to the subcomponents. That's why events were chosen. As the event data can be enriched by the required informations as it does bubble up.

2023-07-19 10:23 UTC, bergatco commented on src/components/feature-board/content-elements/FileContentElementMenu.unit.ts
> +			describe("when move up menu action is clicked", () => {
Fixed by moving "event / click checking" for `move up / down` actions one level up!

2023-07-19 10:27 UTC, bergatco commented on src/components/feature-board/content-elements/ImageFileDisplay.vue
> +				@move-down:element="onMoveElementDown"
Thanks a lot for your understanding! 😁

2023-07-19 10:29 UTC, dyedwiper commented on src/components/feature-board/content-elements/ImageFileDisplay.vue
> +				@move-down:element="onMoveElementDown"
At least here it is not cumbersome. You can just pass the `onMoveElementDown` function. Same in the FileContentElement. Maybe you can add this topic as a point in your concept ticket...

2023-07-19 10:45 UTC, dyedwiper approved these changes

2023-07-19 11:06 UTC, bergatco commented on src/components/feature-board/content-elements/ImageFileDisplay.vue
> +				@move-down:element="onMoveElementDown"
I already have it somewhat in my concept ticket (see https://ticketsystem.dbildungscloud.de/browse/BC-4555). As I would like to have the menu stuff all handled **above** our `FileContentElement` and therefore not having to cope with it at all within the content elements.

2023-07-20 04:30 UTC, merged