BC-4570 - Move "FileContentElement" and its subcomponents into separate folder
hpi-schul-cloud/nuxt-client pull request #2660
Opened 2023-07-18 14:32 UTC by bergatco

… folder

# Short Description

As with the ongoing implementation the folder `/src/components/feature-board` is getting quite full and somewhat messy. Therefore it was decided to move all files related to the "FileContentElement" and its subcomponent into a separate folder `file-content-element`.

## Links to Ticket and related Pull-Requests

https://ticketsystem.dbildungscloud.de/browse/BC-4570

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-07-19 10:52 UTC, CeEv requested changes

2023-07-19 10:52 UTC, CeEv commented on src/components/feature-board/content-elements/ContentElementList.vue
> +import FileContentElement from "./file-content-element/FileContentElement.vue";
Wollen wir mit ein index file arbeiten in dem die Parts stehen die auch außerhalb benötigt werden?

2023-07-19 10:52 UTC, CeEv commented on src/components/feature-board/content-elements/file-content-element/FileContentElement.unit.ts
> +jest.mock("../../shared/FileStorageApi.composable");
Ich bin mir bei dem File nicht sicher was drin ist. Ist das wirklich das API Interface? Wenn ja wäre es vermutlich kein composable. Zudem wäre die Frage ob das wirklich etwas ist das shared ist.

2023-07-19 10:52 UTC, CeEv commented on src/components/feature-board/content-elements/file-content-element/FileContentElement.vue
> +import { useDeleteBoardNodeConfirmation } from "../../shared/DeleteBoardNodeConfirmation.composable";
Gibt es ein ref link ala @shared/ ?
Der wäre aus meiner Sicht für *alle* relativen Pfade die außerhalb des eigenenen Bereiches ..in dem Fall file-content-elment folder zu empfehlen.

2023-07-19 13:49 UTC, bergatco commented on src/components/feature-board/content-elements/file-content-element/FileContentElement.vue
> +import { useDeleteBoardNodeConfirmation } from "../../shared/DeleteBoardNodeConfirmation.composable";
Fixed by replacing relative paths with new aliases!

- Replaced `../../shared/*` with `@boardShared/*` (`src/components/feature-board/shared/*`)
- replaced `../../state/*` with `@boardState/*` (`src/components/feature-board/state/*`)
- replaced `../../types/*` with `@boardTypes/*` (`src/components/feature-board/types/*`)

**HINT! The new aliases needs to be added to `tsconfig.json` as well as `jest.config.js` to be known!!!**

2023-07-19 13:50 UTC, bergatco commented on src/components/feature-board/content-elements/file-content-element/FileContentElement.vue
> +import { useDeleteBoardNodeConfirmation } from "../../shared/DeleteBoardNodeConfirmation.composable";
Applied changes to all files **WITHIN** the new folder, in order to not extend the scope of this PR.

2023-07-20 06:07 UTC, bergatco commented on src/components/feature-board/content-elements/ContentElementList.vue
> +import FileContentElement from "./file-content-element/FileContentElement.vue";
Fixed by adding an index file exporting `FileContentElement` and `useFileRecord` only for now!

2023-07-20 06:11 UTC, bergatco commented on src/components/feature-board/content-elements/file-content-element/FileContentElement.unit.ts
> +jest.mock("../../shared/FileStorageApi.composable");
Diese Frage sprengt leider den Rahmen dieses Tickets und daher würde ich damit gerne an das Frontend-Arc-Chapter verweisen. Sollten sich hier Änderungen ergeben, würde ich Dich bitte ein neues Ticket zu erstellen.

2023-07-20 18:55 UTC, MartinSchuhmacher approved these changes

2023-07-20 18:55 UTC, MartinSchuhmacher commented on src/components/feature-board/content-elements/ContentElementList.vue
> +import { PropType, computed, defineComponent } from "vue";
did you run the linter here and did that one sort the words like that? just irritated why "P" is before "c" and if that might has to do with capital letters

2023-07-21 04:28 UTC, bergatco commented on src/components/feature-board/content-elements/ContentElementList.vue
> +import { PropType, computed, defineComponent } from "vue";
That's correct! In my `.vscode/settings.json` I have enabled `editor.formatOnSave` as well as `source.organizeImports` for the `editor.codeActionsOnSave`. That's why on save the imports are sorted automatically.

```
{
	"[vue]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"[html]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"[javascript]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"[typescript]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"[json]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"editor.formatOnSave": true,
	"editor.codeActionsOnSave": {
		"source.organizeImports": true
	},
	"prettier.prettierPath": "",
	"sonarlint.connectedMode.project": {
		"connectionId": "schulcloud-verbund",
		"projectKey": "hpi-schul-cloud_nuxt-client"
	},
}
```

2023-07-21 05:31 UTC, MartinSchuhmacher approved these changes

2023-07-24 11:43 UTC, MartinSchuhmacher approved these changes

2023-07-24 11:55 UTC, merged