BC-4408 - TSC Footer
hpi-schul-cloud/nuxt-client pull request #2666
Opened 2023-07-20 08:59 UTC by davwas

# Short Description
Changed footer privacy policy translation and terms of use document on thr instance

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-4408

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-07-20 09:23 UTC, wiaderwek requested changes

2023-07-20 09:23 UTC, wiaderwek commented on src/store/filePaths.ts
> +					"Willkommensordner/Datenschutz/Nutzungsordnung.pdf";
better move to constant

2023-07-20 09:44 UTC, wiaderwek approved these changes

2023-07-21 06:56 UTC, MartinSchuhmacher approved these changes

2023-07-21 08:17 UTC, merged