Added rules to display alert-items with index.
hpi-schul-cloud/nuxt-client pull request #2708
Opened 2023-08-03 15:17 UTC by Michaellinaresxk

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-08-04 14:40 UTC, wiaderwek commented on src/components/topbar/TheTopBar.vue
> +						data-testid="logout-button"
you need to fix unit tests after this change

2023-08-04 14:43 UTC, bn-pass approved these changes

2023-08-04 16:32 UTC, bn-pass requested changes

2023-08-04 16:32 UTC, bn-pass commented on src/components/topbar/TheTopBar.unit.ts
> +			expect(wrapper.find("[ddata-testid='status-alerts-icon']").exists()).toBe(
Another typo (`ddata`).

2023-08-04 19:47 UTC, bn-pass approved these changes

2023-08-05 15:42 UTC, odalys-dataport approved these changes

2023-08-07 15:05 UTC, merged