BC-4737 - Remove users property from legacy task clean up task card in general
hpi-schul-cloud/nuxt-client pull request #2725
Opened 2023-08-09 06:27 UTC by MartinSchuhmacher

# Short Description

## Links to Ticket and related Pull-Requests

BC-4737
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4316
## Changes
- delete complete task card module from code
- backend and frontend 
- delete mongo collections 
- delete seed data
- delete permissions with prefix TASK_CARD_*** from code, seed and production db
- delete implementation of course endpoint only used for task-card BC-3691
- delete implementation of task filter for assigned users to legacy task BC-3411
- delete implementation of task assignments for legacy task BC-2393

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-08-09 09:56 UTC, odalys-dataport requested changes
Found a translation key that needs to be removed as well

2023-08-09 10:05 UTC, odalys-dataport commented on src/components/templates/TasksDashboardMain.vue
>  				!this.isStudent &&
Just a thought I'm having: We do have the method "isTeacher" as well, maybe that' nicer to read. But also checking for the permission should suffice here actually, no?

2023-08-09 11:18 UTC, MartinSchuhmacher commented on src/components/templates/TasksDashboardMain.vue
>  				!this.isStudent &&
the condition for "at least not a student" was present in the past and reflects the current behaviour. the "new" permission check was actually implemented by me during the implementation of beta task and covers additionally to the existing behaviour as a second security gate. so I would like to keep it like that to not do an additional refactoring here tbh

2023-08-09 11:27 UTC, odalys-dataport commented on src/components/templates/TasksDashboardMain.vue
>  				!this.isStudent &&
Yeah I just mentioned it because this has been a topic multiple times (brought up by Cedric), that we should not check for roles but permissions instead and that there was a case where students where able to add tasks (on nbc I think) before this page was implemented. We do not have to change anything about this right now, I just wanted to mention it

2023-08-09 11:27 UTC, odalys-dataport submitted a review, later dismissed

2023-08-09 12:58 UTC, christian-darsow submitted a review, later dismissed

2023-08-10 12:21 UTC, christian-darsow approved these changes

2023-08-10 12:37 UTC, merged