Thr 41 adjust csp rule
hpi-schul-cloud/nuxt-client pull request #2736
Opened 2023-08-15 06:19 UTC by SteKrause

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-08-22 14:17 UTC, uidp requested changes

2023-09-01 07:56 UTC, SteKrause commented on dockerconf/nginx.conf.template
> +    set $csp "default-src 'self'; base-uri 'self'; script-src 'nonce-$request_id' 'strict-dynamic' 'unsafe-inline' https:; script-src-elem 'nonce-$request_id' 'unsafe-inline' ${H5P_SCRIPT_SRC_URLS} h
Outdated: we chose another solution

2023-09-04 08:55 UTC, uidp approved these changes

2023-09-05 07:53 UTC, mamutmk5 requested changes

2023-09-05 07:53 UTC, mamutmk5 commented on Dockerfile
> +
shoud be work with the old line
It not necessary to copy the same files two times
```suggestion
COPY --from=build-stage /app/dist /usr/share/nginx/html
```

2023-09-05 07:53 UTC, mamutmk5 commented on dockerconf/nginx.conf.template
> +        root   /usr/share/nginx/html/h5p;
The one copy at the dockerfile works if we use at this line the old path.
The files at /usr/share/nginx/html/h5p and /usr/share/nginx/frontend are the same
```suggestion
        root   /usr/share/nginx/html;
```

2023-09-05 07:53 UTC, mamutmk5 commented on dockerconf/nginx.conf.template
> +        root   /usr/share/nginx/html/frontend;
The one copy at the dockerfile works if we use at this line the old path.
The files at /usr/share/nginx/html/h5p and /usr/share/nginx/frontend are the same
```suggestion
        root   /usr/share/nginx/html;
```

2023-09-05 14:29 UTC, SteKrause commented on Dockerfile
> +
If both locations have the same root path, bugs occur when loading the index.html in try_files.

2023-09-05 14:30 UTC, SteKrause commented on dockerconf/nginx.conf.template
> +        root   /usr/share/nginx/html/frontend;
If both locations have the same root path, bugs occur when loading the index.html in try_files.

2023-09-05 14:30 UTC, SteKrause commented on dockerconf/nginx.conf.template
> +        root   /usr/share/nginx/html/h5p;
If both locations have the same root path, bugs occur when loading the index.html in try_files.

2025-01-23 09:29 UTC, closed without merging

2025-01-23 09:29 UTC, Loki-Afro commented
ticket is closed, therefore I'll close this pr.