N21-841-use-user-login-migration
hpi-schul-cloud/nuxt-client pull request #2769
Opened 2023-08-25 12:43 UTC by mrikallab

# Short Description

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-841

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-09-08 07:23 UTC, arnegns commented on src/components/administration/AdminMigrationSection.unit.ts
> +import UserLoginMigrationModule from "../../store/user-login-migrations";
please use @store

2023-09-12 11:14 UTC, MarvinOehlerkingCap requested changes

2023-09-12 11:14 UTC, MarvinOehlerkingCap commented on src/store/user-login-migrations.unit.ts
> +					expect(module.setLoading).toHaveBeenCalledWith(true);
toHaveBeenNthCalledWith(1, true)
toHaveBeenNthCalledWith(2, false)
would be better

2023-09-12 11:14 UTC, MarvinOehlerkingCap commented on tests/test-utils/factory/userLoginMigrationResponse.factory.ts
> +		startedAt: `startedAt`,
I would also recommend to change the type definition to Date.

2023-09-13 12:03 UTC, mrikallab commented on src/store/user-login-migrations.ts
> +				throw createApplicationError(apiError.code);
@arnegns could you explain why we do it that way? I have no idea and can remember that you wrote the store actions..

2023-09-13 12:39 UTC, mrikallab commented on src/store/user-login-migrations.ts
> +					throw new Error("More than one migration found for user.");
I think we have no conflict here, because this error will be mapped to an ApiResponseError with message: unknown error in the catch block..

2023-09-21 09:51 UTC, MarvinOehlerkingCap submitted a review, later dismissed

2023-09-21 09:51 UTC, MarvinOehlerkingCap commented on src/store/user-login-migration/user-login-migration.mapper.ts
> +		const date = new Date(apiDateString.replace("Z", ""));
Why do you have to remove all Zs from the date? Data constructor should be able to convert ISO dates.

2023-09-21 09:51 UTC, MarvinOehlerkingCap commented on src/store/user-login-migration/user-login-migration.mapper.ts
> +			mandatorySince: this.mapToDate(userLoginMigration.mandatorySince),
```suggestion
			startedAt: new Date(userLoginMigration.startedAt),
			closedAt: new Date(userLoginMigration.closedAt),
			finishedAt: new Date(userLoginMigration.finishedAt),
			mandatorySince: new Date(userLoginMigration.mandatorySince),
```

2023-09-21 09:51 UTC, MarvinOehlerkingCap commented on src/store/user-login-migrations.ts
> +		this.userLoginMigration = userLoginMigration ?? undefined;
you don't need  ?? undefined

2023-09-21 09:51 UTC, MarvinOehlerkingCap commented on src/components/administration/AdminMigrationSection.unit.ts
> +						oauthMigrationFinalFinish: "",
please remove finalFinish and replace it with our current naming

2023-09-22 13:54 UTC, mrikallab commented on src/components/administration/AdminMigrationSection.unit.ts
> +						oauthMigrationFinalFinish: "",
that is deprecated and should be deleted in https://ticketsystem.dbildungscloud.de/browse/N21-820

2023-09-22 14:01 UTC, mrikallab commented on src/components/administration/AdminMigrationSection.vue
>  		const setMigration = async (available: boolean, mandatory: boolean) => {
fetchSchoolOAuthMigration is the old implementation, it will be removed in https://ticketsystem.dbildungscloud.de/browse/N21-820

2023-09-25 11:21 UTC, mrikallab commented on src/components/administration/AdminMigrationSection.vue
> +		const oauthMigration: ComputedRef<UserLoginMigrationFlags> = computed(
Because we need closedAt and finishedAt as strings and the other ones as boolean. We should keep the template clean, I think this solution is better..

2023-09-26 10:12 UTC, IgorCapCoder approved these changes

2023-09-26 10:32 UTC, merged