BC-4350 - mark task completed
hpi-schul-cloud/nuxt-client pull request #2779
Opened 2023-08-30 15:14 UTC by christian-darsow

# Short Description
Set a task as completed or not-completed as a student

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-4350

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-09-06 12:20 UTC, MartinSchuhmacher requested changes

2023-09-06 12:20 UTC, MartinSchuhmacher commented on src/components/feature-board-submission-element/SubmissionContentElement.vue
> +		const updateCompleted = (completed: boolean) => {
how about `updateCompletionState`?

2023-09-06 12:20 UTC, MartinSchuhmacher commented on src/components/feature-board-submission-element/SubmissionContentElementDisplay.vue
> +			return dayjs().isBefore(toRef(props, "dueDate").value);
is this supposed to mean `isEditable` if its a state instead of just `editable`?
also the return line seems a bit crowded.
how about:
`const dueDate = toRef(props, "dueDate").value`
and then
`const today = dayjs()` or `... dayjs(new Date())`
together with
`return today.isBefore(dueDate)`
What do you think about it ?

2023-09-06 12:20 UTC, MartinSchuhmacher commented on src/components/feature-board-submission-element/SubmissionContentElementState.composable.unit.ts
> +	const setup = (contentElementId = "123123") => {
what is the reason for defining the ID as a parameter? 
I was not able to figure out why this should be separately given to the setup function each time as an argument instead of just building it during runtime with the invoke of the setup function and a constant ID within that function.

2023-09-06 12:20 UTC, MartinSchuhmacher commented on src/components/feature-board-submission-element/SubmissionItemApi.composable.unit.ts
> +		it("should call boardSubmissionControllerUpdateSubmissionItem api", async () => {
guess this is not what it should call ^^

2023-09-06 17:23 UTC, christian-darsow commented on src/components/feature-board-submission-element/SubmissionContentElementDisplay.vue
> +			return dayjs().isBefore(toRef(props, "dueDate").value);
I agree, even though not that hard to get, the other way is even easier to understand. I adjusted that as you proposed. For the other question I think we are fine without the "is" and "editable" means "this can be edited"

2023-09-06 17:25 UTC, christian-darsow commented on src/components/feature-board-submission-element/SubmissionItemApi.composable.unit.ts
> +		it("should call boardSubmissionControllerUpdateSubmissionItem api", async () => {
ooops - that was the wrong copy / paste :) fixed that

2023-09-06 17:36 UTC, christian-darsow commented on src/components/feature-board-submission-element/SubmissionContentElementState.composable.unit.ts
> +	const setup = (contentElementId = "123123") => {
I added it as a parameter as I needed that ID value also in the expect parts, eg. here https://github.com/hpi-schul-cloud/nuxt-client/pull/2779/files#diff-1c82236680ddcfd69ce3d9162f5077f3e755054ada37781b8a1a2ce718ced3d7R52   We could also create it inside the setup function and return it from there.. but that doesn't make it cleaner in my opinion

2023-09-07 05:54 UTC, MartinSchuhmacher commented on src/components/feature-board-submission-element/SubmissionContentElementState.composable.unit.ts
> +	const setup = (contentElementId = "123123") => {
yeah I agree...the last option also came into my mind but just produces more code on other places instead ^^

2023-09-07 05:57 UTC, MartinSchuhmacher commented on src/components/feature-board-submission-element/SubmissionContentElementDisplay.vue
> +			return dayjs().isBefore(toRef(props, "dueDate").value);
I thought more in perspective of general code style and remembering about if its being a state and the question "is it this or that" then it should be with the "is". But thats only my assumption so if you say its fine, then we are fine :)

2023-09-07 05:57 UTC, MartinSchuhmacher approved these changes

2023-09-07 07:18 UTC, MartinSchuhmacher commented on tests/test-utils/factory/submissionItemResponseFactory.ts
> +import { userDataResponseFactory } from "@@/tests/test-utils/factory";
kannst du das hier noch fixen? (also den Import zusammenfassen)

2023-09-07 13:20 UTC, merged