N21-1236 add requirements to disable switch
hpi-schul-cloud/nuxt-client pull request #2780
Opened 2023-08-31 15:15 UTC by IgorCapCoder

# Short Description
the enableLdapSyncDuringMigration switch in the MigrationSection should be disabled when user login migration is not active

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-1236
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4373

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [x] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-09-04 10:57 UTC, arnegns requested changes

2023-09-04 10:57 UTC, arnegns commented on src/components/administration/AdminMigrationSection.unit.ts
> +		describe("when migration is active", () => {
You have the "when migration is active" describe block two times

2023-09-04 10:57 UTC, arnegns commented on src/components/administration/AdminMigrationSection.vue
> +			:disabled="!oauthMigration.oauthMigrationPossible"
Give this information to M.L.

2023-09-04 10:58 UTC, arnegns commented on src/components/administration/AdminMigrationSection.vue
> +			await schoolsModule.fetchSchool();
Did you test it?

2023-09-05 09:11 UTC, IgorCapCoder commented on src/components/administration/AdminMigrationSection.vue
> +			await schoolsModule.fetchSchool();
now i did ^^

2023-09-05 10:09 UTC, arnegns approved these changes

2023-09-05 13:43 UTC, merged