testing.
hpi-schul-cloud/nuxt-client pull request #2786
Opened 2023-09-04 22:15 UTC by Michaellinaresxk

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-09-11 17:24 UTC, bn-pass requested changes

2023-09-22 15:05 UTC, bn-pass submitted a review, later dismissed

2023-09-25 06:11 UTC, virgilchiriac commented on src/plugins/datetime.js
> +	const totalMinutesDiff = Math.abs(current.diff(time, "minute"));
days, minutes, hours, ago, etc this must also be translated
is there no library to handle this cases and support internationalization?

2023-09-25 08:35 UTC, Michaellinaresxk commented on src/plugins/datetime.js
> +	const totalMinutesDiff = Math.abs(current.diff(time, "minute"));
- dd.mm.yyyy it will be the new implementation about date time in european format.
 - I will deal with: days, minutes, hours, ago internationalization.

2023-09-26 08:10 UTC, virgilchiriac requested changes
I never heard about european date format. At the same time, for example, we are working on a date picker, and display the date in vue, and everywhere else in the application (nuxt client and legacy too) we consistently use localised date formats.  We cannot / should not use diferent date formats.

2023-09-26 10:25 UTC, virgilchiriac reviewed
FYI we are working on a date picker, and display the date in vue, where we used localised date formats.  We cannot / should not use diferent date formats - but this seems to be the only exception

2023-09-26 15:11 UTC, virgilchiriac requested changes

2023-09-26 15:11 UTC, virgilchiriac commented on src/locales/de.json
> +	"common.labels.days": "vor Tagen",
cannot test it, but how would this be be rendered as "vor 5 Tagen"? 
5 vor Tagen is not correct!
Also, sometimes Uppercase, other times lowercase...

2023-09-27 09:59 UTC, odalys-dataport commented on src/plugins/datetime.js
> +	const totalMinutesDiff = Math.abs(current.diff(time, "minute"));
We do not want to use the european format (which would be YYYY-MM-DD), but using specific formats for each language. You can find these date formats in the translation files under "date.format".

2023-09-27 10:30 UTC, odalys-dataport commented on src/plugins/datetime.js
> +	const totalMinutesDiff = Math.abs(current.diff(time, "minute"));
Ok, I clarified this with UX. For now we want to prioritise consistency over localisation. So we're going with the DD.MM.YYYY format.

Sorry for the hassle!

2023-09-27 10:52 UTC, odalys-dataport requested changes

2023-09-27 10:52 UTC, odalys-dataport commented on src/components/topbar/StatusAlerts.vue
> +							  " " +
Please move expressions like this into the script

2023-09-27 10:52 UTC, odalys-dataport commented on src/locales/de.json
> +	"common.labels.days": "vor Tagen",
Agreed, you can use parameters in translations to fix this

2023-09-27 10:52 UTC, odalys-dataport commented on src/locales/de.json
> +	"common.labels.hour": "Vor einer Stunde",
Please be more specific with the translation keys and change it so something like "hoursAgo", but as Virgil mentioned we should be able to remove these and use dayjs translations instead

2023-09-27 10:52 UTC, odalys-dataport commented on src/plugins/datetime.js
> +	return {
This is a pretty big change, have you checked that all occurrences where the "fromNow" function is used are still working?

2023-09-27 12:33 UTC, Michaellinaresxk commented on src/plugins/datetime.js
> +	const totalMinutesDiff = Math.abs(current.diff(time, "minute"));
Thank you for your clarification.

2023-10-04 12:34 UTC, odalys-dataport approved these changes

2023-10-16 14:55 UTC, odalys-dataport approved these changes

2023-10-17 14:26 UTC, bn-pass commented on src/plugins/datetime.js
> +	setDayjsLocale();
@Michaellinaresxk is there any reason to call this function on every `formatDateForAlerts()` function call? Wouldn't it be sufficient to just call it once for every time the script is loaded (as it looks like it configures the dayjs in its global scope, I don't see any relation to this function params)?

2023-10-17 16:07 UTC, merged