BC-3475 - As a user, I want to add/edit alternative text to images
hpi-schul-cloud/nuxt-client pull request #2790
Opened 2023-09-07 13:08 UTC by KalliSfak

# Short Description

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-3475

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-09-11 10:14 UTC, bischofmax commented on src/components/feature-board-file-element/content/display/image-display/AlternativeText.vue
> +<template>
Please move file to content folder

2023-09-11 10:22 UTC, bischofmax commented on src/components/feature-board-file-element/content/display/image-display/AlternativeText.vue
> +		<v-textarea
@marcoschulz86 used textarea in the designs. Thats why we decided to us it here.

2023-09-11 12:45 UTC, KalliSfak commented on src/components/feature-board-file-element/content/display/image-display/AlternativeText.vue
> +<template>
It is moved in alternative-text folder

2023-09-11 13:11 UTC, KalliSfak commented on src/components/feature-board-file-element/content/display/image-display/AlternativeText.vue
> +		<v-textarea
Changed to v-text-field

2023-09-11 13:11 UTC, KalliSfak commented on src/components/feature-board-file-element/content/display/image-display/AlternativeText.vue
> +			class="pt-2 ma-0 v-secondary-lighten1"
We do not need any more all these classes with v-text-field

2023-09-12 06:49 UTC, bergatco requested changes

2023-09-12 06:49 UTC, bergatco commented on src/components/feature-board-file-element/content/FileContent.unit.ts
> +			it("Should pass element to alterantive text", () => {
```suggestion
			it("Should pass element to alternative text", () => {
```

2023-09-12 06:49 UTC, bergatco commented on src/components/feature-board-file-element/content/FileContent.unit.ts
> +			it("Should be in dom", () => {
I find the "heading" a little bit confusing, as I am missing, "what" exactly should be found in the DOM.

2023-09-12 06:49 UTC, bergatco commented on src/components/feature-board-file-element/content/FileContent.unit.ts
> +			it("Should not be in dom", () => {
Same as above.
> I find the "heading" a little bit confusing, as I am missing, "what" exactly should be found in the DOM.

2023-09-12 06:49 UTC, bergatco commented on src/components/feature-board-file-element/content/FileContent.unit.ts
> +			it("Should not be in dom", () => {
Same as above.
> I find the "heading" a little bit confusing, as I am missing, "what" exactly should be found in the DOM.

2023-09-12 06:49 UTC, bergatco commented on src/components/feature-board-file-element/content/FileContent.unit.ts
> +			it("Should not be in dom", () => {
Same as above.
> I find the "heading" a little bit confusing, as I am missing, "what" exactly should be found in the DOM.

2023-09-12 06:49 UTC, bergatco commented on src/components/feature-board-file-element/content/FileContent.vue
> +		></AlternativeText>
```suggestion
		<AlternativeText
			v-if="isEditMode && fileProperties.previewUrl"
			:element="fileProperties.element"
		/>
```

2023-09-12 06:52 UTC, bischofmax commented on src/components/feature-board-file-element/content/alternative-text/AlternativeText.vue
> +		<v-text-field
Do we meet all a11y requirements here?

2023-09-13 13:07 UTC, SevenWaysDP requested changes

2023-09-13 13:07 UTC, SevenWaysDP commented on src/components/data-board/BoardApi.composable.unit.ts
> +					dueDate: new Date().toISOString(),
Why dueDate?

2023-09-14 04:58 UTC, bergatco commented on src/components/data-board/BoardApi.composable.unit.ts
> +					dueDate: new Date().toISOString(),
Because otherwise the test would fail with missing attribute "dueDate". 🤷‍♂️

2023-09-14 06:19 UTC, bischofmax commented on src/components/feature-board-file-element/content/alternative-text/AlternativeText.vue
> +			isEditMode: true,
Still need a decision on the removal of this prop.

2023-09-14 06:32 UTC, bischofmax commented on src/components/data-board/BoardApi.composable.unit.ts
> +					dueDate: new Date().toISOString(),
@KalliSfak The typing was wrong here because the isOptional decorator was missing in the backend in the FileContentElement. You can generate the api again and remove dueDate. But we could think of adding alternativeText here.

2023-09-14 06:54 UTC, bischofmax commented on src/components/feature-board-file-element/content/alternative-text/AlternativeText.vue
> +		const { modelValue } = useContentElementState({
It's quite handy to use useContentElementState here in the AlternativeText component, because we prevent a lot of emits and handling in the parent components. But AlternativeText becomes a stateful component that way. Do we want this? And we already use useContentElementState in the FileContentElement. useContentElementState was also designed to be used with the contentelement props, so I think this here is not the intended use case. Should we remove it here and add emits to handle the update of alternativeText?

2023-09-14 06:59 UTC, bergatco commented on src/components/feature-board-file-element/content/alternative-text/AlternativeText.vue
> +		const { modelValue } = useContentElementState({
I would suggest to decouple the component from `useContentElementState` here. I would also assume, that this is not the intended behavior. Plus I would like to have all the "connection" to the content element state in one place and not all over the components.

2023-09-14 14:56 UTC, SevenWaysDP approved these changes

2023-09-18 07:01 UTC, bischofmax commented on src/components/feature-board-file-element/content/FileContent.vue
> +			:text="fileProperties.element.content.alternativeText"
There is basically no need for the element in the fileProperties object. AlternativeText would be enough.

2023-09-18 07:08 UTC, bischofmax submitted a review, later dismissed

2023-09-18 07:25 UTC, KalliSfak commented on src/components/feature-board-file-element/content/FileContent.vue
> +			:text="fileProperties.element.content.alternativeText"
It would be resolved in the next pr.

2023-09-19 10:04 UTC, bischofmax approved these changes

2023-09-20 13:18 UTC, bischofmax submitted a review, later dismissed

2023-09-20 13:28 UTC, bischofmax approved these changes

2023-09-21 09:53 UTC, bischofmax approved these changes

2023-09-21 09:57 UTC, bergatco approved these changes

2023-09-21 11:10 UTC, merged