BC-4938 - Add school specific Terms of Use (Nutzungsordnung) for new school admin page
hpi-schul-cloud/nuxt-client pull request #2799
Opened 2023-09-11 11:37 UTC by davwas

# Short Description

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-4938

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-09-11 16:30 UTC, wiaderwek commented on src/components/organisms/administration/SchoolTermsFormDialog.vue
> +						t('pages.administration.school.index.termsOfUse.labels.uploadFile')
strange formatting

2023-09-11 16:31 UTC, wiaderwek submitted a review, later dismissed

2023-09-12 09:00 UTC, odalys-dataport requested changes

2023-09-12 12:48 UTC, davwas commented on src/components/organisms/administration/SchoolTerms.vue
> +										"DD.MM.YYYY HH:mm"
fixed

2023-09-12 12:48 UTC, davwas commented on src/components/organisms/administration/SchoolTerms.vue
> +		const t = (key: string, values?: VueI18n.Values | undefined): string => {
fixed, swapped to use composable

2023-09-12 12:49 UTC, davwas commented on src/components/organisms/administration/SchoolTerms.vue
> +		const pdfIcon = "$file_pdf_outline";
fixed, moved directly into the template

2023-09-12 12:49 UTC, davwas commented on src/components/organisms/administration/SchoolTermsFormDialog.vue
> +		const t = (key: string, values?: VueI18n.Values | undefined): string => {
fixed

2023-09-12 12:49 UTC, davwas commented on src/components/organisms/administration/SchoolTermsFormDialog.vue
> +		if (!notifierModule || !schoolsModule || !termsOfUseModule || !i18n) {
fixed, swapped inject for injectScript

2023-09-12 12:49 UTC, davwas commented on src/components/organisms/administration/SchoolTermsFormDialog.vue
> +			inject<TermsOfUseModule>("termsOfUseModule");
fixed, swapped inject for injectScript

2023-09-12 12:51 UTC, davwas commented on src/themes/brb/components/legacy/TheFooter.vue
> +					>
I know it looks ugly but I've changed it to remove extra spaces from footer links because it has been bothering me for some time now :) let me know if you want me to revert that
![image](https://github.com/hpi-schul-cloud/nuxt-client/assets/27923014/b752c6e2-950e-4b52-8355-92b2acf76cbc)

2023-09-12 12:52 UTC, davwas commented on src/themes/n21/components/legacy/TheFooter.vue
> +					>
[look here](https://github.com/hpi-schul-cloud/nuxt-client/pull/2799#discussion_r1322993584)

2023-09-12 13:53 UTC, odalys-dataport requested changes

2023-09-12 13:53 UTC, odalys-dataport commented on src/components/organisms/administration/SchoolPolicy.vue
> +					<v-icon>{{ "$file_pdf_outline" }}</v-icon>
You should be able to remove the brackets and quotation marks and just use the icon like
`<v-icon>$file_pdf_outline</v-icon>`

2023-09-12 13:53 UTC, odalys-dataport commented on src/themes/brb/components/legacy/TheFooter.vue
> +					>
Mh I wouldn't think that how we format our code should change the ui in any way, but it's not a biggie, so don't worry about it

2023-09-13 07:00 UTC, wiaderwek approved these changes

2023-09-13 15:59 UTC, merged