N21-1206 show classes and goups
hpi-schul-cloud/nuxt-client pull request #2808
Opened 2023-09-18 06:30 UTC by MBergCap

# Short Description
adds a page for class overview

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-1206
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4406
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3305
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/643

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-09-20 09:05 UTC, IgorCapCoder reviewed
missing unit tests ;)

2023-09-22 07:39 UTC, arnegns submitted a review, later dismissed

2023-09-22 07:39 UTC, arnegns commented on src/store/group.ts
> +	private error: object | null = null;
Please use BusinessError. Take a look into external tools store

2023-09-22 07:39 UTC, arnegns commented on src/store/group.ts
> +	private pagination: Pagination = {
Why you save pagination in the store? We dont get these from the server api. We only need it in the page / component. Please move it

2023-09-22 07:39 UTC, arnegns commented on src/store/group.ts
> +		return GroupApiFactory(undefined, "/v3", $axios);
There was no decision for the new structure (see data-board) until now. We should use composables to access the api instead of vuex stores because they are more like the pinia stores which could be used in the future.

So for now okay, but please keep in mind to use the new structure especially api access mechanism

2023-09-22 07:39 UTC, arnegns commented on src/store/group.ts
> +			const sortBy =
When you move the pagination and sorting you should use them as parameters here

2023-09-22 07:39 UTC, arnegns commented on src/store/group.ts
> +			this.setError(error as Error);
Please use the error mechanism like in externaltools

2023-09-22 07:39 UTC, arnegns commented on src/store/types/sort-order.enum.ts
> +export enum SortOrder {
Please use a new folder "group" for the types for this store

2023-09-22 07:39 UTC, arnegns commented on src/pages/administration/ClassOverview.page.vue
> +		const sortBy: ComputedRef<string> = computed(() => groupModule.getSortBy);
Please verify this and ask bb.. Should sortBy and pagination in the store? So when the user leaves the page and open it up again, should the sorting and pagination be the same?

2023-09-22 08:37 UTC, MarvinOehlerkingCap requested changes

2023-09-22 08:37 UTC, MarvinOehlerkingCap commented on src/pages/administration/ClassOverview.page.vue
> +			class="custom-table elevation-1"
is there a requirement to change the color or did you copy it from somewhere?

2023-09-22 08:37 UTC, MarvinOehlerkingCap commented on src/pages/administration/ClassOverview.page.vue
> +			groupModule.loadClassesForSchool();
I would recommend to await this, even if the linter says that onMounted does not expect a promise

2023-09-22 08:37 UTC, MarvinOehlerkingCap commented on src/store/types/sort-order.enum.ts
> +export enum SortOrder {
sort order looks like a very general type that can be used everywhere, not only for groups

2023-09-22 08:37 UTC, MarvinOehlerkingCap commented on src/store/group.ts
> +	private error: object | null = null;
Compared to the external tools store, I would recommend `BusinessError | null` as the type to better distinguish between having an error and not having one.

2023-09-22 08:37 UTC, MarvinOehlerkingCap commented on src/store/group.ts
> +			const mappedClasses: ClassInfo[] = response.data.data.map(
please export this to a separate mapper (see context external tools store)

2023-09-22 08:37 UTC, MarvinOehlerkingCap commented on src/store/group.unit.ts
> +			it("should update the classes", async () => {
you are missing a test for expecting that the store state has changed

2023-09-22 08:37 UTC, MarvinOehlerkingCap commented on src/utils/sidebar-base-items.ts
> +			{
you are missing the feature flag

2023-09-22 11:33 UTC, MBergCap commented on src/pages/administration/ClassOverview.page.vue
> +			class="custom-table elevation-1"
this is the color of the table header from the legacy client. There was no specific requirement. But this is how it looks like in the old client

2023-09-22 11:40 UTC, MarvinOehlerkingCap commented on src/pages/administration/ClassOverview.page.vue
> +			class="custom-table elevation-1"
we should use one style in the vue client and not copy legacy styles imo

2023-09-27 11:48 UTC, MBergCap commented on src/utils/sidebar-base-items.ts
> +			{
a function for the feature has been added

2023-09-27 11:48 UTC, MBergCap commented on src/store/group.unit.ts
> +			it("should update the classes", async () => {
fixed

2023-09-27 11:49 UTC, MBergCap commented on src/store/group.ts
> +			const mappedClasses: ClassInfo[] = response.data.data.map(
fixed

2023-09-27 11:49 UTC, MBergCap commented on src/pages/administration/ClassOverview.page.vue
> +			groupModule.loadClassesForSchool();
fixed

2023-09-27 11:49 UTC, MBergCap commented on src/pages/administration/ClassOverview.page.vue
> +			class="custom-table elevation-1"
custom-table class removed

2023-09-27 13:26 UTC, IgorCapCoder approved these changes

2023-09-27 13:36 UTC, MBergCap commented on src/pages/administration/ClassOverview.page.vue
> +		const sortBy: ComputedRef<string> = computed(() => groupModule.getSortBy);
After consultation with bb, the sorting and pagination can be saved like this

2023-09-27 13:37 UTC, MBergCap commented on src/store/group.ts
> +	private pagination: Pagination = {
After consultation with bb, the sorting and pagination can be saved like this

2023-09-27 13:47 UTC, merged