N21-1250 CTL board element
hpi-schul-cloud/nuxt-client pull request #2818
Opened 2023-09-20 13:44 UTC by MarvinOehlerkingCap

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-09-21 07:40 UTC, arnegns requested changes

2023-09-21 07:40 UTC, arnegns commented on src/components/data-board/BoardApi.composable.unit.ts
> +			const PAYLOAD = {
why is the variable capitalized?

2023-09-21 07:40 UTC, arnegns commented on src/components/feature-board/shared/AddElementDialog.vue
> +		const dialogWidth: ComputedRef<number> = computed(() =>
Something for north* @OliverHappe @uidp

2023-09-21 07:40 UTC, arnegns commented on src/components/page-board/ColumnBoard.page.vue
> +		onMounted(async () => {
can we load this if we have the first element from type external tool?

2023-09-21 11:57 UTC, MarvinOehlerkingCap commented on src/components/data-board/BoardApi.composable.unit.ts
> +			const PAYLOAD = {
idk why they did it like that, but it is the wrong style, so I will change it.

2023-09-22 09:23 UTC, arnegns approved these changes

2023-09-22 14:59 UTC, arnegns approved these changes

2023-09-22 15:00 UTC, merged

2023-09-26 08:22 UTC, uidp commented on src/components/feature-board/shared/AddElementDialog.vue
> +		const dialogWidth: ComputedRef<number> = computed(() =>
Hm, what happens, when there are a lot more `elementTypeOptions`?

2023-09-26 08:38 UTC, arnegns commented on src/components/feature-board/shared/AddElementDialog.vue
> +		const dialogWidth: ComputedRef<number> = computed(() =>
@uidp the number of elementTypeOptions is fixed at the moment or?