BC-4992-Upload school logo
hpi-schul-cloud/nuxt-client pull request #2820
Opened 2023-09-21 09:24 UTC by VikDavydiuk

# Short Description

## Links to Ticket and related Pull-Requests

- https://ticketsystem.dbildungscloud.de/browse/BC-4992
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/????

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-09-22 12:27 UTC, davwas requested changes

2023-09-22 12:27 UTC, davwas commented on src/components/organisms/administration/GeneralSettings.vue
> +				: null;
This will assign empty File with correct name to an input which means that if user sends the form without touching the input then the logo in the database will be overwritten with empty value.

2023-09-22 12:27 UTC, davwas commented on src/components/organisms/administration/GeneralSettings.vue
> +			this.localSchool.logo_name = logo ? logo.name : "";
This entire function seems redundant, you already have everything you need in a logoFile property so you can just convert it to base64 inside the save function instead of doing this on every input change.

2023-09-22 12:27 UTC, davwas commented on src/components/organisms/administration/GeneralSettings.vue
>  				logo: null,
I think this logo property is pretty much useless, you can add empty logo_dataUrl tho since you are copying database school object into localSchool object later.

2023-09-22 12:27 UTC, davwas commented on src/components/organisms/administration/GeneralSettings.vue
> +			updatedSchool.logo_name = this.localSchool.logo_name || "";
You could remove the localschool.logo and the onLogoChange function and just convert the logoFile.value to base64 right here. The name can also come from the logoFile object.

2023-09-22 20:08 UTC, VikDavydiuk commented on src/components/organisms/administration/GeneralSettings.vue
> +				: null;
Good catch , thanks)

2023-09-27 07:48 UTC, davwas approved these changes

2023-09-27 08:44 UTC, SevenWaysDP approved these changes

2023-10-02 09:23 UTC, merged