BC-4783 Migrate GET endpoints of school API
hpi-schul-cloud/nuxt-client pull request #2847
Opened 2023-10-06 08:15 UTC by dyedwiper

# Short Description

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-4783

https://github.com/hpi-schul-cloud/schulcloud-server/pull/4440
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3315

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-11-27 09:22 UTC, CeEv commented on src/store/schools.ts
> +		id: "",
I see that we have a school type and types for all sub classes. Why we have a need to define a wrong school setup with "nearly invalid" default data? Than we has not real information if it is fullfilled with a correct empty string, or it the fetch / mapping is invalid. But it is the code that already exists... :)

2023-11-28 12:56 UTC, dyedwiper commented on src/store/schools.ts
> +		id: "",
I wondered about that too. But should be a separate ticket to resolve this :)

2023-11-28 13:09 UTC, dyedwiper commented on src/pages/administration/migration.unit.ts
> +	id: "5f2987e020834114b8efd6f8",
These mocks also feel wrong to me, but I think this should be done in a separate ticket.

2023-11-30 07:20 UTC, uidp approved these changes

2023-11-30 07:20 UTC, uidp commented on src/store/schools.ts
> +const SCHOOL_FEATURES = Object.values(SchoolFeature);
😎

2023-11-30 07:20 UTC, uidp commented on src/store/schools.ts
> +		return this.school.systems ?? [];
Can `school.systems` ever be `undefined | null`? For me it doesn't look like that. Otherwise it looks like the response type includes an optional `systems` property. Maybe some mismatch that has to be resolved.

2023-11-30 07:20 UTC, uidp commented on src/store/schools.ts
> +		if (this.school.systems) {
see above - cannot be `undefined | null`?

2023-11-30 08:57 UTC, dyedwiper commented on src/store/schools.ts
> +		return this.school.systems ?? [];
It's because systems in the response is optional. One other possibility would be to map it to an empty array in `transformSchoolServerToClient` if it is undefined. Do you think that's better?

2023-12-13 10:11 UTC, uidp approved these changes

2023-12-13 10:12 UTC, uidp approved these changes

2023-12-13 15:31 UTC, CeEv commented on src/store/schools.ts
> +				$axios.get(`v1/systems/${systemId}`)
Ist v1 hier die richtige Quelle?

2023-12-13 15:40 UTC, CeEv requested changes

2023-12-13 15:40 UTC, CeEv commented on src/store/schools.ts
> +			if (error instanceof AxiosError) {
Sollte der Nutzer nicht auch im else Fall über ein Error informiert werden? Nur loading auf false setzten klinkt nicht richtig. 
Es sollte sich ja nur das Error Format unterschieden.

2023-12-13 15:40 UTC, CeEv commented on src/store/schools.unit.ts
> +						FEATURE_NEST_SYSTEMS_API_ENABLED: true,
Was macht die envirment? FEATURE_NEST_SYSTEMS_API_ENABLED

2023-12-13 15:40 UTC, CeEv commented on src/store/schools.unit.ts
> +		jest.spyOn(serverApi, "SystemsApiFactory").mockReturnValue(systemsApi);
Das überschreibt eine ganze Menge. Aber scheint ja den aktuellen Stand der Implementierung zu folgen.

2023-12-13 15:40 UTC, CeEv commented on src/store/schools.ts
> +		if (schoolFeature === "isTeamCreationByStudentsEnabled") {
if (schoolFeature ===  SCHOOL_FEATURES.IS_TEAM_CREATION .... oder wie auch immer das heißt.

2023-12-13 15:44 UTC, dyedwiper commented on src/store/schools.ts
> +				$axios.get(`v1/systems/${systemId}`)
Das hab ich nicht verändert. Einen ensprechenden Endpoint in v3 gibts auch noch nicht.

2023-12-13 15:47 UTC, dyedwiper commented on src/store/schools.ts
> +			if (error instanceof AxiosError) {
Ich find das auch komisch, aber das seh ich nicht als Teil dieses PRs, das zu ändern.

2023-12-13 15:54 UTC, dyedwiper commented on src/store/schools.unit.ts
> +						FEATURE_NEST_SYSTEMS_API_ENABLED: true,
Weiß ich nicht. Daran hab ich auch nichts geändert.

2023-12-14 09:28 UTC, CeEv approved these changes

2023-12-19 08:54 UTC, bergatco approved these changes

2023-12-19 08:54 UTC, merged