Remove functionality to show share and coty nextboart for teacher.
hpi-schul-cloud/nuxt-client pull request #2849
Opened 2023-10-06 14:57 UTC by Michaellinaresxk

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-11-13 09:49 UTC, bn-pass requested changes

2023-11-13 09:49 UTC, bn-pass commented on src/components/molecules/RoomLessonCard.vue
> -
To me it looks like this change would disable the whole functionality of copying the lesson content and **we do not want that for sure**. We just want to not copy the existing Nexboards.

2023-11-13 09:49 UTC, bn-pass commented on src/components/molecules/RoomLessonCard.vue
> -
Similar to above - **we do not want to disable the whole lesson sharing feature**, we just want to disable copying the existing Nexboards.

2023-12-08 11:03 UTC, davwas commented
Closing this pull request as I will be reopening my own.

2023-12-08 11:03 UTC, closed without merging