BC - 5426 - Add a delete option to the school specific Privacy Policy and Terms of Use
hpi-schul-cloud/nuxt-client pull request #2853
Opened 2023-10-09 07:44 UTC by davwas

# Short Description

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-5426

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-10-09 08:53 UTC, blazejpass approved these changes

2023-10-09 09:17 UTC, blazejpass approved these changes

2023-10-11 09:16 UTC, odalys-dataport requested changes

2023-10-17 12:08 UTC, davwas commented on src/components/organisms/administration/SchoolPolicy.vue
> +										t("format.date")
fixed

2023-10-17 12:17 UTC, davwas commented on src/components/organisms/administration/SchoolPolicy.unit.ts
> +			expect((wrapper.vm as any).isDeletePolicyDialogOpen).toBe(false);
I've marked wrapper as any, apparently there is no easy way of using vue-test-utils with typescript: https://github.com/vuejs/vue-test-utils/issues/255
I haven't seen it solved differently in our app either.

2023-10-17 12:17 UTC, davwas commented on src/components/organisms/administration/SchoolTerms.unit.ts
> +			expect((wrapper.vm as any).isDeleteTermsDialogOpen).toBe(false);
I've marked wrapper as any, apparently there is no easy way of using vue-test-utils with typescript: https://github.com/vuejs/vue-test-utils/issues/255
I haven't seen it solved differently in our app either.

2023-10-17 12:21 UTC, blazejpass submitted a review, later dismissed

2023-10-18 07:58 UTC, blazejpass approved these changes

2023-10-18 08:11 UTC, blazejpass approved these changes

2023-10-18 10:39 UTC, odalys-dataport requested changes

2023-10-18 10:39 UTC, odalys-dataport commented on src/components/organisms/administration/SchoolPolicy.vue
> +									date: dayjs(privacyPolicy.publishedAt).format("DD.MM.YYYY"),
Please use DATETIME_FORMAT exported from datetime plugin

2023-10-18 11:02 UTC, davwas commented on src/components/organisms/administration/SchoolPolicy.vue
> +									date: dayjs(privacyPolicy.publishedAt).format("DD.MM.YYYY"),
I think you have commented on the outdated file :)
The newest version uses different date displaying method.

2023-10-18 11:05 UTC, odalys-dataport approved these changes

2023-10-18 11:06 UTC, merged