N21-1248 Configure External Tools in Boards
hpi-schul-cloud/nuxt-client pull request #2860
Opened 2023-10-12 14:27 UTC by MarvinOehlerkingCap

# Short Description
- add configuration dialog for external tool elements on boards

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-1248
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4471

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-10-16 06:43 UTC, arnegns requested changes

2023-10-16 06:43 UTC, arnegns commented on src/components/data-external-tool/ContextExternalToolApi.composable.ts
> +	const fetchDisplayDataCall = async (
Why you named it fetchDisplayDataCall instead of fetchDisplayData?

2023-10-16 06:43 UTC, arnegns commented on src/components/feature-board-external-tool-element/ExternalToolElement.vue
> +		<div class="card d-flex gap-8 grey lighten-4">
At first i thougt you are using a vuetify styleclass. i would like to rename the styleclass to something like element-card e.g. because of overlapping namespaces

2023-10-16 06:43 UTC, arnegns commented on src/components/feature-board-external-tool-element/ExternalToolElement.vue
> +					contain
What's this? cant find it in the api

2023-10-16 06:43 UTC, arnegns commented on src/components/feature-board-external-tool-element/ExternalToolElement.vue
> +		<ExternalToolElementConfigurationDialog
I think a data-testid will be needed for cypress tests :)

2023-10-16 06:43 UTC, arnegns commented on src/components/feature-board/card/CardHost.vue
> +			await fetchDisplayData(props.cardId);
I dont know what CardHost is exactly.. but are you sure that we alway want to fetch / try to fetch our tool data?

2023-10-16 06:43 UTC, arnegns commented on src/store/context-external-tools.ts
>  	name: "contextExternalToolsModule",
We should create a ticket to remove this store and use the composable for loading the data. Could you create it - deprecate this store and link the ticket here?

2023-10-16 06:53 UTC, MarvinOehlerkingCap commented on src/components/data-external-tool/ContextExternalToolApi.composable.ts
> +	const fetchDisplayDataCall = async (
Because DataPort uses the -Call suffix for their api calls in composables

2023-10-16 06:54 UTC, arnegns commented
The context external tool will not be deleted if i remove the element from a card..

2023-10-16 08:07 UTC, MarvinOehlerkingCap commented on src/components/feature-board-external-tool-element/ExternalToolElement.vue
> +					contain
https://v2.vuetifyjs.com/en/api/v-img/#props-contain

2023-10-16 08:20 UTC, MarvinOehlerkingCap commented on src/store/context-external-tools.ts
>  	name: "contextExternalToolsModule",
https://ticketsystem.dbildungscloud.de/browse/N21-1381

2023-10-16 09:16 UTC, arnegns approved these changes

2023-10-17 13:20 UTC, arnegns submitted a review, later dismissed

2023-10-18 07:30 UTC, arnegns submitted a review, later dismissed

2023-10-19 08:04 UTC, arnegns approved these changes

2023-10-19 08:04 UTC, merged