N21 1264 new class page extension
hpi-schul-cloud/nuxt-client pull request #2865
Opened 2023-10-16 14:18 UTC by IgorCapCoder

# Short Description
To replace the functionality of the old classes table, the action icons for classes (not groups) are added

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-1264

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-10-17 07:35 UTC, arnegns requested changes

2023-10-17 07:35 UTC, arnegns commented on src/locales/de.json
> +	"pages.administration.classes.deleteDialog.content": "\"Möchten Sie wirklich die Klasse '<i>{itemName}</i>' löschen?\"",
The sentence structure doesn't look right

2023-10-17 07:35 UTC, arnegns commented on src/pages/administration/ClassOverview.page.unit.ts
> +import { authModule } from "../../store";
Check your imports

2023-10-17 07:35 UTC, arnegns commented on src/pages/administration/ClassOverview.page.unit.ts
> +				expect(dialog.exists()).toBeTruthy();
You should check for the prop on your component instead because the dialog also exists in the dom but is hidden

2023-10-17 07:35 UTC, arnegns commented on src/pages/administration/ClassOverview.page.vue
> +					v-if="hasPermission && !item.externalSourceName"
you could move this v-if logic to script block

2023-10-17 07:35 UTC, arnegns commented on src/pages/administration/ClassOverview.page.vue
> +						@click="onDeleteClass"
You should use the same name convention for both buttons.. so i would suggest onConfirmClassDeletion

2023-10-17 07:35 UTC, arnegns commented on src/pages/administration/ClassOverview.page.vue
> +					@click="editItem(item)"
I dont like the name editItem. The variable name is item but what you are editing?

2023-10-17 07:35 UTC, arnegns commented on src/pages/administration/ClassOverview.page.vue
> +					@click="onOpenDeleteDialog(item)"
the name should be deleteXYZ. The on convention regards to the events

2023-10-17 07:35 UTC, arnegns commented on src/store/group.unit.ts
> +	// TODO test deleteClass method by mocking the v1 axios call
Todo?

2023-10-17 07:35 UTC, arnegns commented on src/store/group.unit.ts
> +import { classInfoFactory } from "../../tests/test-utils/factory/classInfoFactory";
use @@/tests/..

2023-10-17 07:35 UTC, arnegns commented on src/store/group.unit.ts
> +				expect(module.getClasses).toEqual([]);
the first expect should be enough

2023-10-18 13:06 UTC, MarvinOehlerkingCap requested changes

2023-10-18 13:06 UTC, MarvinOehlerkingCap commented on src/pages/administration/ClassOverview.page.unit.ts
> +
this component test is missing tests for displaying items in the table and displaying an empty state

2023-10-18 13:06 UTC, MarvinOehlerkingCap commented on src/pages/administration/ClassOverview.page.unit.ts
> +
PS: if you don't want to test the table component itself, then at least test if you used the api of the component correctly by checking if the props are set correctly

2023-10-19 07:42 UTC, IgorCapCoder commented on src/locales/de.json
> +	"pages.administration.classes.deleteDialog.content": "\"Möchten Sie wirklich die Klasse '<i>{itemName}</i>' löschen?\"",
after analyzing all locales doublequotes are used most often. But single quotes and other options are also used more than once. Maybe this could be cleaned up in the future :)

2023-10-20 08:03 UTC, MarvinOehlerkingCap submitted a review, later dismissed

2023-10-20 10:28 UTC, arnegns submitted a review, later dismissed

2023-10-20 12:57 UTC, MarvinOehlerkingCap approved these changes

2023-10-20 13:14 UTC, MarvinOehlerkingCap approved these changes

2023-10-20 13:30 UTC, merged