BC-4550 - Browser back on page Tools does not lead to previous page
hpi-schul-cloud/nuxt-client pull request #2889
Opened 2023-10-30 08:09 UTC by davwas

# Short Description

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-4550

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-10-30 13:59 UTC, wiaderwek approved these changes

2023-11-01 07:29 UTC, muratmerdoglu-dp requested changes

2023-11-01 07:29 UTC, muratmerdoglu-dp commented on src/pages/rooms/RoomDetails.page.vue
> +							throw error;
What is expected to see with throwing an error? The 'throwing' an error redirects to the general error page without any information.

2023-11-01 07:29 UTC, muratmerdoglu-dp commented on src/pages/rooms/RoomDetails.page.vue
> +		// fixes https://ticketsystem.dbildungscloud.de/browse/BC-4550
Do we need to add a ticket name while the GitHub history shows the commit and PR's info? I think it's best to remove the comments.

2023-11-02 09:12 UTC, davwas commented on src/pages/rooms/RoomDetails.page.vue
> +		// fixes https://ticketsystem.dbildungscloud.de/browse/BC-4550
removed the comments

2023-11-02 09:19 UTC, davwas commented on src/pages/rooms/RoomDetails.page.vue
> +							throw error;
Those are client side errors, they would just be logged to browser console, no redirection happens here.
I just wanted to prevent 'NavigationDuplicated' error to be spammed to console but I still want to see other errors if they occur.
Also NavigationDuplicated is more like a warning really, meaning that you won't be redirected because you are already there.

2023-11-02 11:34 UTC, davwas commented on src/pages/rooms/RoomDetails.page.vue
> +							throw error;
I was wrong, this will indeed redirect due to global error handling in our app, removed the catch block as discussed

2023-11-02 12:00 UTC, muratmerdoglu-dp approved these changes

2023-11-02 12:05 UTC, wiaderwek approved these changes

2023-11-06 09:59 UTC, merged