BC-5863 - remove tiptap
hpi-schul-cloud/nuxt-client pull request #2926
Opened 2023-11-24 12:46 UTC by christian-darsow

# Short Description
As a step towards vue3 we remove tiptap usage in news section and change to CK5 

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-5863

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-12-04 10:18 UTC, MartinSchuhmacher requested changes

2023-12-04 10:34 UTC, christian-darsow commented on src/components/feature-editor/config.ts
> +const newsPlugins = [
Good point! Adjusted the order

2023-12-04 10:38 UTC, MartinSchuhmacher approved these changes

2023-12-04 11:49 UTC, odalys-dataport requested changes

2023-12-04 11:49 UTC, odalys-dataport commented on src/components/organisms/FormNews.unit.js
>  import setupStores from "@@/tests/test-utils/setupStores";
Since we're touching this file now, it would be nice to migrate it to typescript

2023-12-04 18:52 UTC, christian-darsow commented on src/components/organisms/FormNews.unit.js
>  import setupStores from "@@/tests/test-utils/setupStores";
ich war mal so nice und habe es nach TS portiert. außerdem ein paar tests hinzugefügt und einen useless (aber auch schon geskipten test) entfernt

2023-12-04 20:24 UTC, odalys-dataport submitted a review, later dismissed

2023-12-05 19:00 UTC, odalys-dataport approved these changes

2023-12-06 15:07 UTC, merged