N21 1479 provisioning options
hpi-schul-cloud/nuxt-client pull request #2948
Opened 2023-12-08 15:54 UTC by IgorCapCoder

# Short Description
add feature to set options for group provisioning from moin.schule. With FEATURE_PROVISIONING_OPTIONS_ENABLED = true the edit button of the moin.schule system (in Authentication section of new admin page) redirects to the new options page.

## Links to Ticket and related Pull-Requests
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4631
https://ticketsystem.dbildungscloud.de/browse/N21-1479
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/734
https://github.com/hpi-schul-cloud/e2e-system-tests/pull/162

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes
![image](https://github.com/hpi-schul-cloud/nuxt-client/assets/93926487/f7d5e50d-aa60-4291-a8e5-c2353efb133d)

## Checklist before merging

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [x] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-12-13 10:49 UTC, arnegns requested changes

2023-12-13 10:49 UTC, arnegns commented on src/components/data-provisioning-options/type/index.ts
> +export * from "./ProvisioningOptions";
Please use explicit export

2023-12-13 10:49 UTC, arnegns commented on src/router/routes.ts
> +			"school_system_view",
Dont we have an permission enum of api generation?

2023-12-13 10:49 UTC, arnegns commented on src/router/vue-client-route.js
> +	`^/administration/school-settings/provisioning-options/?$`,
Do we need a new entry in dof app?

2023-12-13 11:23 UTC, IgorCapCoder commented on src/components/administration/ProvisioningOptionsPage.vue
> +				href: "/administration/",
/administration ist still legacy, therefor i use the href here

2023-12-13 11:27 UTC, IgorCapCoder commented on src/components/data-provisioning-options/ProvisioningOptionsApi.composable.unit.ts
> +				).toHaveBeenCalledWith("", "systemId", provisioningOptions);
that is the mocked getSchool.id from the mocked store, which is "" because i don't set it anywhere

2023-12-13 11:33 UTC, IgorCapCoder commented on src/components/organisms/administration/AuthSystems.unit.js
> +			// { _id: "1", type: "sample system" }, // deletable: false, editable: false
this is quite an old unit test which is very hard to grasp without the comments. We are using an array of found 'td's. Without comments you wouldn't know what system you got at array[indexNumber] and if the system is editable/deletable. (I also updated the comments because the logic has sinbce then changed and no one adjusted the comments for it ^^)

2023-12-13 14:37 UTC, IgorCapCoder commented on src/components/organisms/administration/AuthSystems.unit.js
> +		it("should display the edit system button for oauth system, when provisioning options feature flag is true and redirect to provisioning options page", () => {
i don't want to completely destroy the test structure here, so i shorten the description :)

2023-12-13 14:43 UTC, IgorCapCoder commented on src/router/routes.ts
> +			"school_system_view",
isn't used anywhere else here...

2023-12-13 14:56 UTC, arnegns commented on src/components/administration/ProvisioningOptionsPage.unit.ts
> +describe("ProvisioningOptionsPage", () => {
You could use ProvisioningOptionsPage.name

2023-12-13 15:31 UTC, arnegns commented on src/components/data-provisioning-options/ProvisioningOptionsApi.composable.ts
> +			handleError(error);
Please test this

2023-12-15 06:23 UTC, arnegns requested changes

2023-12-15 06:23 UTC, arnegns commented on src/components/administration/ProvisioningOptionsPage.vue
> +	setup(props) {
Please add buildPageTitle for a11y support

2023-12-15 06:23 UTC, arnegns commented on src/components/data-provisioning-options/ProvisioningOptionsApi.composable.unit.ts
> +import { NOTIFIER_MODULE_KEY } from "../../utils/inject";
Check imports

2023-12-15 07:48 UTC, arnegns requested changes

2023-12-15 07:48 UTC, arnegns commented on src/components/data-provisioning-options/ProvisioningOptionsState.composable.ts
> +			if (apiError.code !== 404) {
Please use HttpStatusCode

2023-12-15 07:48 UTC, arnegns commented on src/components/data-provisioning-options/ProvisioningOptionsState.composable.ts
> +			const apiError = mapAxiosErrorToResponseError(errorResponse);
I would prefer to map the error in the api composable and just do error handling here

2023-12-15 07:48 UTC, arnegns commented on src/components/data-provisioning-options/ProvisioningOptionsState.composable.unit.ts
> +import { notifierModule } from "../../store";
Please check imports

2023-12-15 10:42 UTC, arnegns requested changes

2023-12-15 10:42 UTC, arnegns commented on src/components/data-provisioning-options/ProvisioningOptionsState.composable.unit.ts
> +			it("should show notification", async () => {
should not show

2023-12-15 11:46 UTC, arnegns approved these changes

2023-12-15 13:04 UTC, merged