N21-1583 copying ctl tools info
hpi-schul-cloud/nuxt-client pull request #2951
Opened 2023-12-11 07:49 UTC by mrikallab

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2023-12-11 14:29 UTC, IgorCapCoder requested changes

2023-12-11 14:29 UTC, IgorCapCoder commented on src/components/copy-result-modal/CopyResultModal.vue
> +			return this.hasFeatureCtlsToolsenabled
you already test for the feature flag in the "isShow" property which hangs in an v-if statement in the template. So without the feature flag the whole modal would not be shown. Is there a reason why you would like to do it twice?

2023-12-11 14:29 UTC, IgorCapCoder commented on src/components/share/ImportModal.vue
> +								`components.molecules.import.courses.options.ctlTools.infoText`
it seems like you could avoid the v-if all together if you would set $(parentType) to "course" and change the language key according to that

2023-12-11 14:29 UTC, IgorCapCoder commented on src/components/copy-result-modal/CopyResultModal.unit.ts
> +			envConfigModule.setEnvs({ FEATURE_CTL_TOOLS_TAB_ENABLED: true } as Envs);
what do you think about a test with feature = false

2023-12-11 14:29 UTC, IgorCapCoder commented on src/components/share/ImportModal.unit.ts
> +	describe("when ctl tools are enabled", () => {
with feature = false you would expect $t(`components.molecules.import.${parentType}.options.infoText`). How do you feel about testing that?

2023-12-11 14:29 UTC, IgorCapCoder commented on src/components/share/ShareModal.vue
> +										`components.molecules.share.courses.options.ctlTools.infotext`
see above: is it possible to use the already provided structure?

2023-12-11 14:54 UTC, mrikallab commented on src/components/copy-result-modal/CopyResultModal.unit.ts
> +			envConfigModule.setEnvs({ FEATURE_CTL_TOOLS_TAB_ENABLED: true } as Envs);
The test of the deactivated feature is above.

2023-12-12 07:21 UTC, mrikallab commented on src/components/share/ImportModal.vue
> +								`components.molecules.import.courses.options.ctlTools.infoText`
I can not avoid the v-if, need to check on the feature flag

2023-12-12 08:40 UTC, IgorCapCoder submitted a review, later dismissed

2023-12-12 12:24 UTC, IgorCapCoder approved these changes

2023-12-12 12:28 UTC, merged