EW-694 Common Cartridge Course Import
hpi-schul-cloud/nuxt-client pull request #3010
Opened 2024-01-17 09:03 UTC by psachmann

# Short Description
Adding a new modal and import/upload dialog to allow users the import of courses from Common Cartridge files.

## Links to Ticket and related Pull-Requests
- <https://ticketsystem.dbildungscloud.de/browse/EW-694>
- <https://github.com/hpi-schul-cloud/schulcloud-server/pull/4700>
- <https://github.com/hpi-schul-cloud/dof_app_deploy/pull/763>
- <https://github.com/hpi-schul-cloud/end-to-end-tests/pull/????>

## Deployment
Environment variables `FEATURE_COMMON_CARTRIDGE_IMPORT_ENABLED` must be set to `true`.

## Screenshots of UI changes

TODO: insert screenshots here

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-01-30 14:30 UTC, Fshmit approved these changes

2024-01-30 15:04 UTC, mkreuzkam-cap submitted a review, later dismissed

2024-02-22 11:38 UTC, mkreuzkam-cap commented on src/store/rooms.unit.ts
> +				expect(setAlertDataMock).toHaveBeenCalledWith({
This fails. I think the mocking of the API is missing and the text should be "pages.rooms.ccImportCourse.success"

2024-02-26 08:58 UTC, psachmann commented on src/store/rooms.unit.ts
> +				expect(setAlertDataMock).toHaveBeenCalledWith({
Fixed the test.

2024-02-28 08:49 UTC, mkreuzkam-cap submitted a review, later dismissed

2024-02-29 12:01 UTC, SevenWaysDP submitted a review, later dismissed

2024-03-12 15:39 UTC, mkreuzkam-cap requested changes

2024-03-12 15:39 UTC, mkreuzkam-cap commented on src/store/rooms.unit.ts
> +		describe("uploadCourse", () => {
This method no longer exists in RoomModule. Remove these tests

2024-03-13 08:45 UTC, psachmann commented on src/store/rooms.unit.ts
> +		describe("uploadCourse", () => {
Done.

2024-03-13 09:02 UTC, psachmann commented on src/components/templates/RoomWrapper.vue
> +							label: this.$t("pages.rooms.fab.import.course"),
Is now resolved

2024-03-13 09:07 UTC, mkreuzkam-cap commented on src/serverApi/v3/api.ts
> +        courseControllerImportCourse: async (file: any, options: any = {}): Promise<RequestArgs> => {
This method is now duplicated

2024-03-13 09:12 UTC, mkreuzkam-cap approved these changes

2024-03-13 13:00 UTC, mkreuzkam-cap approved these changes

2024-03-13 13:02 UTC, merged