BC-6174: fix components/feature-board-submission-element tests
hpi-schul-cloud/nuxt-client pull request #3036
Opened 2024-01-23 16:36 UTC by uidp

# Short Description
Vue3 upgrade: fix components/feature-board-submission-element tests

## Links to Ticket and related Pull-Requests
BC-6174

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-01-23 19:33 UTC, odalys-dataport commented on src/components/feature-board-submission-element/components/SubmissionContentElement.unit.ts
> +			await nextTick();
In my test cases I was able to remove them and the tests still worked. Please check

2024-01-24 09:43 UTC, uidp commented on src/components/feature-board-submission-element/components/SubmissionContentElement.unit.ts
> -	createMock<ReturnType<typeof useSubmissionContentElementState>>();
The component complains about the wrong property types that come from `createMock` because when "automocked" everything is just a `jest.fn()`. That's why we had to define the mock more specific.

2024-01-24 09:44 UTC, uidp commented on src/components/feature-board-submission-element/components/SubmissionContentElement.unit.ts
> +			await nextTick();
Good point. Removed the `nextTick()`s.

2024-01-24 10:29 UTC, odalys-dataport commented on src/components/feature-board-submission-element/components/SubmissionContentElement.unit.ts
> -	createMock<ReturnType<typeof useSubmissionContentElementState>>();
I see, thanks!

2024-01-24 10:32 UTC, odalys-dataport requested changes

2024-01-24 10:32 UTC, odalys-dataport commented on src/components/feature-board-submission-element/components/SubmissionItemsTeacherDisplay.unit.ts
>  			await nextTick();
There's another occurance here

2024-01-24 16:22 UTC, uidp commented on src/components/feature-board-submission-element/components/SubmissionItemsTeacherDisplay.unit.ts
>  			await nextTick();
Removed.

2024-01-24 16:22 UTC, merged