BC-6349 N21-1715 fix tool autocomplete
hpi-schul-cloud/nuxt-client pull request #3082
Opened 2024-02-08 15:45 UTC by arnegns

# Short Description
v-img cant be used in a prepend slot in v-list-item any longer. Another complex solution to use the prepend-avatar and uses it slot to diplay the image and set rounded to 0

## Links to Ticket and related Pull-Requests
- https://ticketsystem.dbildungscloud.de/browse/N21-1715
- https://ticketsystem.dbildungscloud.de/browse/BC-6349

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-02-08 16:06 UTC, odalys-dataport requested changes

2024-02-08 16:06 UTC, odalys-dataport commented on src/components/external-tools/configuration/ExternalToolSelectionRow.vue
> +      -->
Please remove the comments :)

Also I'm curious to know, why v-img doesn't work here

2024-02-08 16:06 UTC, odalys-dataport commented on src/components/external-tools/configuration/ExternalToolSelectionRow.vue
> +			<img :src="item.logoUrl" class="mx-2" :style="getStyle()" />
Please add the style through a class instead of inline styling

2024-02-09 07:23 UTC, arnegns commented on src/components/external-tools/configuration/ExternalToolSelectionRow.vue
> +      -->
Me too. That's why I debugged something and you now have to specify the width additionally so that a placeholder exists that can be replaced by the img

2024-02-09 08:38 UTC, odalys-dataport requested changes

2024-02-09 08:38 UTC, odalys-dataport commented on src/components/external-tools/configuration/ExternalToolSelectionRow.vue
> +				:width="$props.maxHeight"
Isn't it possible to just use `maxHeight` etc here without the `$props`?

2024-02-09 08:54 UTC, odalys-dataport approved these changes

2024-02-09 08:54 UTC, merged