BC-6371 Switch to new me-v3-api
hpi-schul-cloud/nuxt-client pull request #3131
Opened 2024-03-01 15:30 UTC by dyedwiper

# Short Description

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-6371

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-03-05 15:31 UTC, SevenWaysDP commented on src/store/auth.ts
> +			this.addPermmission("TEAMS_ENABLED");
```suggestion
			this.addPermission("TEAMS_ENABLED");
```

2024-03-05 15:31 UTC, SevenWaysDP commented on src/components/organisms/administration/PrivacySettings.unit.js
> +			authModule.addPermmission("SCHOOL_EDIT");
```suggestion
			authModule.addPermission("SCHOOL_EDIT");
```

2024-03-06 08:27 UTC, dyedwiper commented on src/store/auth.ts
> +	me?: MeResponse;
What should be the starting value then?

2024-03-06 11:24 UTC, dyedwiper commented on src/store/auth.ts
> +	me?: MeResponse;
As discussed in meeting, we leave this optional, because it is set in the `login` method and we don't know for sure if this method was called. 

I just looked it up again and `login` is only called on app startup when a JWT is present: https://github.com/hpi-schul-cloud/nuxt-client/blob/main/src/main.ts#L119 I think, this is not a real use case at the moment, but it is still technically possible, and might be a use case in the future, when you can open a page of the nuxt client without being logged in.

2024-03-06 11:33 UTC, dyedwiper commented on src/components/topbar/TheTopBar.vue
> +		},
Ich lasse es jetzt erst mal so, weil ich mir nicht ganz sicher bin, was die beste Lösung ist im Zusammenspiel mit der Parent-Komponente.

2024-03-06 12:15 UTC, SevenWaysDP requested changes

2024-03-06 12:15 UTC, SevenWaysDP commented on src/store/auth.ts
> +			this.setLocale(data.language);
Ich glaube das soll auch in setMe ausgeführt werden, weil das kann von wo anderes gesetzt werden

2024-03-06 14:16 UTC, SevenWaysDP approved these changes

2024-03-06 14:52 UTC, SevenWaysDP approved these changes

2024-03-07 12:13 UTC, SevenWaysDP approved these changes

2024-03-07 14:00 UTC, merged