BC-3933 - draft-status / visibility of course-board to students
hpi-schul-cloud/nuxt-client pull request #3132
Opened 2024-03-03 20:58 UTC by MartinSchuhmacher

# Short Description
As a teacher I want to make sure that students can only see and access my board when I want them to and that I am always aware what my students see to ensure that they do not see content that is not intended.

## Links to Ticket and related Pull-Requests
BC-3933

## Changes

## Screenshots of UI changes
(see Ticket for UX designs)

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-03-08 09:35 UTC, uidp commented on src/components/ui-board/BoardMenuActionRevert.unit.ts
> +describe("BoardMenuActionPublish Component", () => {
`BoardMenuActionRevert` ?

2024-03-08 09:35 UTC, uidp commented on src/components/ui-board/BoardMenuActionRevert.vue
> +export default defineComponent({
Maybe we should use `<script setup>` here?

2024-03-08 09:35 UTC, uidp commented on src/components/data-board/BoardApi.composable.ts
> +	const publishBoard = async (boardId: string, isVisible: boolean) => {
Maybe something like `updateBoardPublished` `updateBoardVisibility` would be more appropriate? I would expect that `publishBoard` does only the "publish" action and not both "publish" and "unpublish".

2024-03-08 09:35 UTC, uidp commented on src/components/data-board/BoardState.composable.ts
> +			await publishBoard(board.value.id, newVisibility);
Ah okay, it looks like `updateBoardVisibility` was already taken 😃

2024-03-08 09:35 UTC, uidp commented on src/components/feature-board/board/Board.vue
> +					@revert:board="onRevertPublishedBoard"
Maybe better `onUnpublishBoard`? The board might be published in the first place so there would be nothing to "revert" actually.

2024-03-08 10:10 UTC, odalys-dataport requested changes

2024-03-08 10:10 UTC, odalys-dataport commented on src/components/molecules/RoomBoardCard.vue
> +	let titleSuffix = "";
You can set the titleSuffix right away and then instead do

```
if (isDraft.value) {
  return titlePrefix + titleSuffix;
}

return titlePrefix;
```

2024-03-08 10:10 UTC, odalys-dataport commented on src/components/molecules/RoomBoardCard.vue
> +const getStyleClasses = () => {
You don't need a function for this, since it's fairly simple. Above in the template you can do this instead:

`:class="{ 'board-hidden': isDraft }"`

https://vuejs.org/guide/essentials/class-and-style

2024-03-08 10:10 UTC, odalys-dataport commented on src/components/molecules/RoomBoardCard.vue
> +const handlePublish = () => {
We've been using the convention "onPublish" "onRevert"

2024-03-08 10:10 UTC, odalys-dataport commented on src/components/molecules/RoomBoardCard.vue
> +		dataTestId: "content-card-board-menu-publish",
I feel like this causes inconsistency as our data test ids are written "data-testid", so in this line and line 134 it should probably be "dataTestid" instead.

2024-03-08 10:10 UTC, odalys-dataport commented on src/components/templates/RoomDashboard.vue
> +						<room-board-card
Why did you change how this component is written here? Afaik writing them in camelCase ensures better type safety.

2024-03-08 10:10 UTC, odalys-dataport commented on src/components/templates/RoomDashboard.vue
> +							:role="role"
If this is not an ARIA role, this property should be renamed to avoid confusion!

2024-03-08 10:10 UTC, odalys-dataport commented on src/components/templates/RoomDashboard.vue
> +							@revert-board="revertPublishedElement(item.content.id)"
event reminder

2024-03-08 10:10 UTC, odalys-dataport commented on src/components/templates/RoomDashboard.vue
> +				<room-board-card
syntax reminder

2024-03-08 10:10 UTC, odalys-dataport commented on src/components/templates/RoomDashboard.vue
> +					:role="role"
role reminder

2024-03-08 10:10 UTC, odalys-dataport commented on src/components/templates/RoomDashboard.vue
> +					v-if="item.type === cardTypes.ColumnBoard && item.content.published"
Preferably move this into the script

2024-03-08 10:10 UTC, odalys-dataport commented on src/components/templates/RoomDashboard.vue
> -					@revert-lesson="revertPublishedElement(item.content.id)"
Why have these handlers been removed? Can the functions that are being called be removed as well?

2024-03-08 10:10 UTC, odalys-dataport commented on src/components/ui-board/BoardMenuActionPublish.vue
> +<script lang="ts">
Since this is a new component, let's use script setup :D

2024-03-08 11:03 UTC, odalys-dataport requested changes

2024-03-08 11:03 UTC, odalys-dataport commented on src/components/feature-board/board/BoardHeader.vue
> +					<BoardMenuActionPublish v-if="isDraft" @click="onPublishBoard" />
The other BoardMenuAction components handle their visibility inside their component. Maybe we should adjust to that.

2024-03-10 15:24 UTC, MartinSchuhmacher commented on src/components/feature-board/board/BoardHeader.vue
> +					<BoardMenuActionPublish v-if="isDraft" @click="onPublishBoard" />
the others (move components) adjust their visibility regarding the global vars for the columns. in this case if would mean handing the prop needed into the component to make the visiblity working correctly. it would actually mean more code for the same logic. if you both prefer it this way I can change it, it just feels odd to me

2024-03-10 15:25 UTC, MartinSchuhmacher commented on src/components/ui-board/BoardMenuActionPublish.vue
> +<script lang="ts">
done, but gives me an error because the export does not seem to work correclty, maybe I am missing sth:

<img width="938" alt="grafik" src="https://github.com/hpi-schul-cloud/nuxt-client/assets/55735359/8380182b-78e9-479c-b6c8-b7fc01c812a1">

2024-03-10 15:26 UTC, MartinSchuhmacher commented on src/components/templates/RoomDashboard.vue
> -					@revert-lesson="revertPublishedElement(item.content.id)"
removed it here as the students should not have these options (and its not working for them anyway) so I removed the handlers. the functions being used are still needed for the teacher view

2024-03-10 15:27 UTC, MartinSchuhmacher commented on src/components/ui-board/BoardMenuActionRevert.vue
> +export default defineComponent({
done

2024-03-10 15:27 UTC, MartinSchuhmacher commented on src/components/ui-board/BoardMenuActionRevert.unit.ts
> +describe("BoardMenuActionPublish Component", () => {
you're right, thx for the hint!

2024-03-10 15:37 UTC, MartinSchuhmacher commented on src/components/data-board/BoardApi.composable.ts
> +	const publishBoard = async (boardId: string, isVisible: boolean) => {
I updated the values within `BoardApi` and `BoardState` now to make them more according to the other calls :)

2024-03-10 15:37 UTC, MartinSchuhmacher commented on src/components/data-board/BoardState.composable.ts
> +			await publishBoard(board.value.id, newVisibility);
see the comment in BoardApi

2024-03-10 16:15 UTC, MartinSchuhmacher commented on src/components/feature-board/board/Board.vue
> +					@revert:board="onRevertPublishedBoard"
done

2024-03-10 16:16 UTC, MartinSchuhmacher commented on src/components/feature-board/board/Board.vue
> +			}, 100);
done

2024-03-10 16:16 UTC, MartinSchuhmacher commented on src/components/feature-board/board/BoardHeader.vue
> +		}}</v-chip>
done ;)

2024-03-10 16:20 UTC, MartinSchuhmacher commented on src/components/feature-board/board/BoardHeader.vue
> +		isDraft: {
to me the "isVisible" perspective comes from the BE transforming from the name of the property within DB.
in our case from FE perspective the concrete differentiation if something is a draft makes more sense here as this is more the user perspective. 
to me both perspectives have their rights and to me could exist next to each other, as we only use the isDraft to determine for the menu especially, but I'm open for discussion :)

2024-03-10 16:21 UTC, MartinSchuhmacher commented on src/components/molecules/RoomBoardCard.unit.ts
> +	title: string | undefined;
both is possible and to me more a question of personal preference.
I dont care to be honest and changed it to your suggestion

2024-03-10 16:22 UTC, MartinSchuhmacher commented on src/components/feature-board/board/BoardHeader.vue
> -
have been done already :D

2024-03-10 16:23 UTC, MartinSchuhmacher commented on src/components/molecules/RoomBoardCard.unit.ts
> +		it("should not show card actions for students at all or for teachers on published boards", async () => {
I don't really get what is meant exactly but we can talk about it tomorrow

2024-03-10 16:45 UTC, MartinSchuhmacher commented on src/components/molecules/RoomBoardCard.vue
> +const handlePublish = () => {
done

2024-03-10 16:47 UTC, MartinSchuhmacher commented on src/components/molecules/RoomBoardCard.vue
> +	"revert-board",
done

2024-03-10 16:50 UTC, MartinSchuhmacher commented on src/components/molecules/RoomBoardCard.vue
> +	let titleSuffix = "";
very good hint, thx! done

2024-03-10 16:50 UTC, MartinSchuhmacher commented on src/components/molecules/RoomBoardCard.vue
> +const cardTitle = () => {
done

2024-03-10 16:51 UTC, MartinSchuhmacher commented on src/components/molecules/RoomBoardCard.vue
> +const getStyleClasses = () => {
you're right, that one got lost in my work. changed it right away :)

2024-03-10 16:54 UTC, MartinSchuhmacher commented on src/components/molecules/RoomBoardCard.vue
> +		dataTestId: "content-card-board-menu-publish",
this is a huge issue regarding QA and tests in cypress as a lot of their tests regard on "I" instead of "i", we had to change that as well for other tests. I also could find both usages in vue code (with more ones being written as "dataTestId" but of course you are right regarding consistency. I will post a sticky on our board to discuss that together with ankush tomorrow

2024-03-10 16:58 UTC, MartinSchuhmacher commented on src/components/templates/RoomDashboard.vue
> +						<room-board-card
changed that when I began working on the ticket but you're right, did not change that back, did it now

2024-03-10 17:04 UTC, MartinSchuhmacher commented on src/components/templates/RoomDashboard.vue
> +							:role="role"
you are right, changed that, also for task and lesson cards

2024-03-10 17:04 UTC, MartinSchuhmacher commented on src/components/templates/RoomDashboard.vue
> +							@revert-board="revertPublishedElement(item.content.id)"
done

2024-03-10 17:05 UTC, MartinSchuhmacher commented on src/components/templates/RoomDashboard.vue
> +				<room-board-card
done

2024-03-10 17:05 UTC, MartinSchuhmacher commented on src/components/templates/RoomDashboard.vue
> +					:role="role"
done

2024-03-10 17:09 UTC, MartinSchuhmacher commented on src/components/templates/RoomDashboard.vue
> +					v-if="item.type === cardTypes.ColumnBoard && item.content.published"
I would be prefer having that not in script as its a condition directly on the handled item in the list and puting it as a computed would mean some unnecessary code in my opinion

2024-03-11 09:59 UTC, odalys-dataport requested changes

2024-03-11 09:59 UTC, odalys-dataport commented on src/components/molecules/RoomBoardCard.unit.ts
> +		it("should not show card actions for students at all or for teachers on published boards", async () => {
When reading these test cases they just read to me like they are gonna be e2e tests as well. I'm not saying they are wrong, I was just thinking about if we're gonna duplicate these in our e2e tests basically.

2024-03-11 09:59 UTC, odalys-dataport commented on src/components/templates/RoomDashboard.vue
> +					v-if="item.type === cardTypes.ColumnBoard && item.content.published"
It's about easier readability. That we have easy to read variables in the template and don't have to spend more seconds than necessary to understand when this is visible.

2024-03-11 10:00 UTC, odalys-dataport commented on src/components/feature-board/board/BoardHeader.vue
> +					<BoardMenuActionPublish v-if="isDraft" @click="onPublishBoard" />
I don't have a strong opinion on this

2024-03-11 10:28 UTC, MartinSchuhmacher commented on src/components/feature-board/board/Board.vue
> +			if (newVisibility) {
we can, due to the rebounce (needed for mounting) it appears a short second after clicking the button but to me its also fine. will adjust it

2024-03-11 10:38 UTC, MartinSchuhmacher commented on src/components/templates/RoomDashboard.vue
> +					v-if="item.type === cardTypes.ColumnBoard && item.content.published"
adjusted

2024-03-11 10:44 UTC, odalys-dataport submitted a review, later dismissed

2024-03-11 14:09 UTC, uidp commented on src/components/feature-board/board/BoardHeader.vue
> +		isDraft: {
Actually I think it should be named differently in the Server as well. I'm not sure why it is called `isVisible` there because the use case is more about publishing / unpublishing the board than changing its general visibility.

2024-03-12 09:45 UTC, virgilchiriac commented on src/serverApi/v3/api.ts
>  }
some stuff landed here from create board ticket...

2024-03-12 10:52 UTC, MartinSchuhmacher commented on src/serverApi/v3/api.ts
>  }
as this was merged yesterday it came in yes. I already removed a duplicate

2024-03-12 12:50 UTC, MartinSchuhmacher commented on src/serverApi/v3/api.ts
>  }
I also just updated the api file again with the recent merges to server

2024-03-12 13:17 UTC, uidp approved these changes

2024-03-12 13:31 UTC, merged