BC-6794 Add check if column board has drawing as its child
hpi-schul-cloud/nuxt-client pull request #3159
Opened 2024-03-20 09:52 UTC by blazejpass

# Short Description
For copy course functionality if there is whiteboard in column board we need to display a message about not copying the content of drawing.

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-6794

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-03-20 12:53 UTC, wiaderwek requested changes

2024-03-20 12:53 UTC, wiaderwek commented on src/store/room.unit.ts
> +				const mockApi = {
move to setup function, add additional description for those it with description like "when room has drawing child"

2024-03-20 12:53 UTC, wiaderwek commented on src/store/room.unit.ts
> +			it("should catch error in catch block", async () => {
same here

2024-03-20 12:53 UTC, wiaderwek commented on src/store/room.unit.ts
> +				const roomModule = new RoomModule({});
move to setup function

2024-03-20 13:31 UTC, blazejpass commented on src/store/room.unit.ts
> +				const mockApi = {
done

2024-03-20 13:31 UTC, blazejpass commented on src/store/room.unit.ts
> +				const roomModule = new RoomModule({});
done

2024-03-20 13:31 UTC, blazejpass commented on src/store/room.unit.ts
> +			it("should catch error in catch block", async () => {
done

2024-03-20 13:32 UTC, wiaderwek approved these changes

2024-03-21 08:17 UTC, blazejpass commented on src/components/copy-result-modal/CopyResultModal.vue
> +			return this.isCourse && roomModule.getHasDrawingChild;
I'm not sure, because request is providing with info about only new copied course and result failed copied elements.
It is done in copy.ts -> copy()->setCopyResult() and setCopyResultFailedItems()

2024-03-22 12:16 UTC, wiaderwek approved these changes

2024-03-25 07:25 UTC, CeEv commented on src/store/room.ts
> +	get getHasDrawingChild(): boolean {
I am unsure about this change. Drawing or not sound not like what we want on this level. I see that also code from task and lesson is placed in this store. But its feel for me wrong.

2024-03-26 07:52 UTC, muratmerdoglu-dp commented on src/store/room.ts
> +	get getHasDrawingChild(): boolean {
I think there are three options:

1- Current implementation. At room-details level there is no info if the course has a white-board element or not, the client has to make an extra call to the server again if the course has.

2- At the copy-service level(backend). The backend copy service should send the proper info about the course that already has the element. So that there is no need for extra calling at the client level.

3- Only showing the info in the UI to the users that something like 'the white-board element which is probably included in this course was not copied'.

2024-03-26 08:34 UTC, blazejpass commented on src/store/room.ts
> +	get getHasDrawingChild(): boolean {
For second option we would have to add property with just information if course copy has drawing child.
![image](https://github.com/hpi-schul-cloud/nuxt-client/assets/118356546/aa6d41ee-db63-42ad-af96-8800b15a7437)

2024-03-26 08:55 UTC, Metauriel commented on src/store/room.ts
> +	get getHasDrawingChild(): boolean {
the copy algorithm in the backend builds a tree of all things in the course that are copied. However, in the mapping to the response object, the tree is currently discarded for courses (but I think not for Tasks or Lessons).

It would be possible to change that by adding the children to the response mapping. Then in the frontend you could do a quick scan of the tree to see if there is an element of the relevant type

2024-03-27 07:51 UTC, wiaderwek submitted a review, later dismissed

2024-03-27 08:44 UTC, davwas approved these changes

2024-03-27 08:52 UTC, wiaderwek submitted a review, later dismissed

2024-03-27 09:03 UTC, davwas submitted a review, later dismissed

2024-03-27 09:34 UTC, muratmerdoglu-dp requested changes

2024-03-27 09:34 UTC, muratmerdoglu-dp commented on src/store/copy.unit.ts
> +			describe("when drawing element is not among types in passed property", () => {
What it should do `"when drawing element is not among types in passed property"`.
I think using `it('should do ....)` pattern will be clear and more readable.

2024-03-27 09:34 UTC, muratmerdoglu-dp commented on src/store/copy.unit.ts
> +			describe("when drawing element is among types in passed property", () => {
Same above

2024-03-27 09:45 UTC, muratmerdoglu-dp approved these changes

2024-03-28 13:09 UTC, merged