BC-6770 - Create a list board
hpi-schul-cloud/nuxt-client pull request #3199
Opened 2024-04-12 21:28 UTC by MartinSchuhmacher

# Short Description
When creating a new board, I want to be able to choose between the single-column and multi-column board type so that I can create my content flexibly and according to my needs.

## Links to Ticket and related Pull-Requests
BC-6770
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4914

## Changes
- provide button to add list board from room board detail page
- show list board type in card item headline
- adjust order of areas vertically in list board
- adjust remaining functionality according to column board for list board

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-04-18 12:38 UTC, odalys-dataport requested changes

2024-04-18 12:38 UTC, odalys-dataport commented on src/components/templates/RoomDashboard.vue
> +				itemName: this.$t("pages.room.boardCard.label.courseBoard"),
Since we're touching this, can we be a little more consistent with our naming here? This was also requested in a product demo recently, that we should either use Column Board or Course Board, but not both.

2024-04-18 12:38 UTC, odalys-dataport commented on src/components/templates/RoomDashboard.vue
> +			if (itemLayout === "list") {
Instead of strings, we could make this an enum, no?

2024-04-18 12:38 UTC, odalys-dataport commented on src/components/templates/RoomDashboard.vue
> +			if (itemLayout === "list") {
I saw that there is an enum for that, why are we not using that here?

2024-04-18 12:38 UTC, odalys-dataport commented on src/modules/feature/board/board/Board.vue
> +				<div :class="isListBoard ? 'mx-auto mt-9' : ''">
In my honest opinion we should not mix and match like this. Every board component is now full of condititions needing to know which board type it is and I think we should find a cleaner solution for that.

Off topic: I also just noticed that `BoardAddCardButton` is in the board feature folder, but should be in the board ui folder instead.

2024-04-18 15:19 UTC, odalys-dataport requested changes

2024-04-18 15:19 UTC, odalys-dataport commented on src/modules/ui/board/BoardMenuActionMoveColumnUp.unit.ts
> +			expect(action.exists()).toBeFalsy();
please no truthy and falsy :)

2024-04-18 15:19 UTC, odalys-dataport commented on src/modules/ui/board/BoardMenuActionMoveColumnUp.unit.ts
> +			expect(action.exists()).toBeFalsy();
please no truthy and falsy :)

2024-04-18 15:19 UTC, odalys-dataport commented on src/modules/ui/board/BoardMenuActionMoveColumnUp.unit.ts
> +			listItemComponent.vm.$emit("click", { preventDefault: jest.fn() });
If you feel like it, let's change it to `trigger("click")` or remove this test all together, since we're basically just testing vue and vuetify :D

2024-04-18 15:19 UTC, odalys-dataport commented on src/modules/ui/board/BoardMenuActionMoveColumnUp.vue
> +		@click="onClick"
You like to order imports alphabetically, I like to have properties first, then events. Can we make a deal here? :D

2024-04-18 15:19 UTC, odalys-dataport commented on src/modules/ui/board/BoardMenuActionMoveColumnUp.vue
> +		@click="onClick"
You like to order imports alphabetically, I like to have properties first, then events. Can we make a deal here? :D

I'm also curious to why our linter is not complaining about the `v-if` not being the first, we used to have that rule too and I think it makes a lot of sense.

2024-04-18 15:19 UTC, odalys-dataport commented on src/modules/ui/room-details/RoomBoardCard.unit.ts
> +	layout: string;
Let's make this of type `BoardLayout`

2024-04-18 15:19 UTC, odalys-dataport commented on src/modules/ui/room-details/RoomBoardCard.unit.ts
> +const mockDraftListBoardData = {
I think somewhere here you made changes to the `boardResponseFactory`, does it make sense to use that here?

2024-04-18 15:19 UTC, odalys-dataport commented on src/modules/ui/room-details/RoomBoardCard.unit.ts
> +							wrapper.find(".title-board-card").element.textContent;
We do not want to find components or elements by class names, please use something else. This occurs multiple times in this file for `boardCardTitle`

2024-04-18 15:19 UTC, odalys-dataport commented on src/pages/rooms/RoomDetails.page.vue
> +					icon: "$mdi_custom_grid_outline",
I think we didn't want to use the $-Syntax for icons anymore for better type safety, but I'm not sure

2024-04-19 07:50 UTC, MartinSchuhmacher commented on src/components/templates/RoomDashboard.vue
> +				itemName: this.$t("pages.room.boardCard.label.courseBoard"),
talked about that with Franz, he will talk with UX first and we will change it after their decision

2024-04-19 08:06 UTC, MartinSchuhmacher commented on src/components/templates/RoomDashboard.vue
> +			if (itemLayout === "list") {
changed

2024-04-19 08:07 UTC, MartinSchuhmacher commented on src/modules/feature/board/board/Board.vue
> +				<div :class="isListBoard ? 'mx-auto mt-9' : ''">
discussed, will be a follow up

2024-04-19 08:09 UTC, MartinSchuhmacher commented on src/modules/feature/board/board/Board.vue
> +								:class="isListBoard ? 'mx-auto my-0' : ''"
changed

2024-04-19 08:10 UTC, MartinSchuhmacher commented on src/modules/feature/board/board/Board.vue
> +								@move:column-up="onMoveColumnBeforePosition(index, element.id)"
agree on that, unified it so far at least for the emit calls, but we can clean that more up in the follow up

2024-04-19 08:12 UTC, MartinSchuhmacher commented on src/modules/feature/board/board/Board.vue
> +const onMoveColumnBeforePosition = async (
I left them for now as it makes more sense to me in the current structure to have it separate. If we unify the components further, we can of course unify those as well, for now I would like to keep them separate for the PoC. 

I will change the naming though, I also did not like it totally but couldn't make up a better name. We can go with forward and backward as you suggested. Will change that.

2024-04-19 08:20 UTC, MartinSchuhmacher commented on src/modules/feature/board/board/BoardColumnGhost.vue
> +				:class="ghostColumnStyle"
yes I know, but to be honest I dont like that mixing in this regard (yeah I know what you are thinking now  ^^ ) and find it cleaner to have it all together in the setup area

2024-04-19 08:21 UTC, MartinSchuhmacher commented on src/modules/feature/board/board/BoardColumnGhostHeader.vue
> +				<VIcon>{{ mdiPlus }}</VIcon> {{ title }}
opinion received :)

2024-04-19 08:22 UTC, MartinSchuhmacher commented on src/modules/feature/board/board/BoardColumnHeader.unit.ts
> +			it("should not be possible", async () => {
nice one! good suggestion, thx!

2024-04-19 08:31 UTC, MartinSchuhmacher commented on src/modules/ui/board/BoardMenuActionMoveColumnDown.unit.ts
> +			expect(action.exists()).toBeTruthy();
changed

2024-04-19 08:33 UTC, MartinSchuhmacher commented on src/modules/ui/board/BoardMenuActionMoveColumnUp.unit.ts
> +			expect(action.exists()).toBeFalsy();
changed

2024-04-19 08:33 UTC, MartinSchuhmacher commented on src/modules/ui/board/BoardMenuActionMoveColumnUp.unit.ts
> +			expect(action.exists()).toBeFalsy();
changed

2024-04-19 08:33 UTC, MartinSchuhmacher commented on src/modules/ui/board/BoardMenuActionMoveColumnUp.unit.ts
> +			listItemComponent.vm.$emit("click", { preventDefault: jest.fn() });
see discussion above

2024-04-19 08:38 UTC, MartinSchuhmacher commented on src/modules/ui/board/BoardMenuActionMoveColumnUp.vue
> +		@click="onClick"
I tried to be not that strict anymore regarding the imports :D 
but isnt it like this here with icon as property first and when the click event?

2024-04-19 08:39 UTC, MartinSchuhmacher commented on src/modules/ui/board/BoardMenuActionMoveColumnUp.vue
> +		@click="onClick"
changed the if position

2024-04-19 08:40 UTC, MartinSchuhmacher commented on src/modules/ui/board/BoardMenuActionMoveColumnUp.vue
> +		@click="onClick"
changed the order, I hope thats what you meant.

2024-04-19 08:46 UTC, MartinSchuhmacher commented on src/modules/ui/room-details/RoomBoardCard.unit.ts
> +const mockDraftListBoardData = {
not exactly, as the data for this room is a little different from the one used on the board (which the one in `boardResponseFactory` is used for)

2024-04-19 08:48 UTC, MartinSchuhmacher commented on src/modules/ui/room-details/RoomBoardCard.unit.ts
> +							wrapper.find(".title-board-card").element.textContent;
there are 197 results when I search for this way of using class names to find a component/element in our vue repo. so why exactly do we not want to use that anymore?

2024-04-19 08:49 UTC, MartinSchuhmacher commented on src/pages/rooms/RoomDetails.page.vue
> +					icon: "$mdi_custom_grid_outline",
it did not work otherwise for me at least as this was the custom icon I got from Franz

2024-04-19 08:50 UTC, MartinSchuhmacher commented on src/pages/rooms/RoomDetails.page.vue
> +					icon: "$mdi_custom_grid_outline",
ah nevermind, I thought you meant the headline for the cards, you are right here it works also without

2024-04-19 08:52 UTC, MartinSchuhmacher commented on src/pages/rooms/RoomDetails.page.vue
> +					icon: "$mdi_custom_grid_outline",
need to rephrase, it does not work otherwise

2024-04-19 09:41 UTC, odalys-dataport commented on src/modules/ui/board/BoardMenuActionMoveColumnUp.vue
> +		@click="onClick"
I can’t see properly right now, but what I mean is: v-if, :icon, data-testid, whatever properties, first event, only more events after this

2024-04-19 09:45 UTC, odalys-dataport commented on src/modules/ui/room-details/RoomBoardCard.unit.ts
> +							wrapper.find(".title-board-card").element.textContent;
Yes, in the past we did that a lot. And there were also classes added to components for the sole reason of using them for unit tests, which can be very confusing when looking at a template. Those class names when used for styling can also change over time and then you have to adjust all the tests too. So at some point we decided that we want to avoid that and prefer using the data-testids.

2024-04-19 09:46 UTC, odalys-dataport commented on src/pages/rooms/RoomDetails.page.vue
> +					icon: "$mdi_custom_grid_outline",
Okay, I’m not sure either, maybe we can ask Uwe about it.

2024-04-19 09:54 UTC, MartinSchuhmacher commented on src/modules/ui/board/BoardMenuActionMoveColumnUp.vue
> +		@click="onClick"
yep, then I did correctly :)

2024-04-19 09:55 UTC, MartinSchuhmacher commented on src/modules/ui/room-details/RoomBoardCard.unit.ts
> +							wrapper.find(".title-board-card").element.textContent;
ok, will rewrite the mentioned tests in this file to use the testid

2024-04-20 09:14 UTC, uidp submitted a review, later dismissed

2024-04-20 09:14 UTC, uidp commented on src/modules/feature/board/board/BoardColumnHeader.vue
> +		},
Maybe a good idea to think about a provider like `BOARD_HAS_MULTIPLE_COLUMNS` (in the future) to avoid property drilling? Just an idea...

2024-04-20 09:14 UTC, uidp commented on src/modules/ui/room-details/RoomBoardCard.unit.ts
> +	layout: BoardLayout.List,
We should think about test factories in the future.

2024-04-20 16:39 UTC, MartinSchuhmacher commented on src/components/icons/custom/index.ts
> +	mdi_custom_grid_outline: mdiCustomGridOutline,
within the file its like a mixture of snake and camel case, but I agree that for so many names in one word camelCase might be the better choice, will change that 👍

2024-04-20 16:40 UTC, MartinSchuhmacher commented on src/modules/feature/board/board/BoardColumnHeader.vue
> +		},
guess thats one of the points we should consider for the refactoring incoming

2024-04-20 16:44 UTC, MartinSchuhmacher commented on src/modules/ui/room-details/RoomBoardCard.unit.ts
> +	layout: BoardLayout.List,
noted that as well on miro

2024-04-20 16:50 UTC, MartinSchuhmacher commented on src/components/templates/RoomDashboard.vue
> +								)
you are right, but to properly use that, we would need more refactoring in this file, which I'm not open for in this ticket tbh ^^

2024-04-20 16:56 UTC, MartinSchuhmacher commented on src/modules/feature/board/board/BoardColumn.unit.ts
> +				columnHeader.vm.$emit("move:column-up");
indeed you are right as usual :) changed that

2024-04-22 06:44 UTC, uidp approved these changes

2024-04-22 07:38 UTC, odalys-dataport approved these changes

2024-04-22 07:55 UTC, merged