N21-1858 prevent migration to same login system
hpi-schul-cloud/nuxt-client pull request #3208
Opened 2024-04-16 11:55 UTC by MBergCap

# Short Description

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/N21-1858
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4934

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-04-17 13:20 UTC, arnegns requested changes

2024-04-17 13:20 UTC, arnegns commented on src/components/administration/AdminMigrationSection.vue
> +			<v-alert
Please use the notifier. We dont use the v-alert anylonger

2024-04-17 13:20 UTC, arnegns commented on src/composables/user-login-migration-mappings.composable.ts
> +		).find(([key]) => businessError.message.startsWith(key))?.[1];
Please use the type of the loggable expection instead of the beginnging of the the message

2024-04-18 09:32 UTC, MBergCap commented on src/components/administration/AdminMigrationSection.vue
> +			<v-alert
after a discussion with BB, the information should be displayed as an error alert under the start button

2024-04-18 09:32 UTC, MBergCap commented on src/composables/user-login-migration-mappings.composable.ts
> +		).find(([key]) => businessError.message.startsWith(key))?.[1];
done

2024-04-18 10:20 UTC, arnegns requested changes

2024-04-18 10:20 UTC, arnegns commented on src/composables/user-login-migration-mappings.composable.ts
> +		"IDENTICAL_USER_LOGIN_MIGRATION_SYSTEM",
Maybe something for @alweber-cap and the arc group: idea to generate those type with api and reuse it here instead of have both strings in sync or a decorator in server to mark those loggables which types are used in the ui

2024-04-18 10:20 UTC, arnegns commented on src/composables/user-login-migration-mappings.composable.unit.ts
> +		it("should return undefined when error is undefined", () => {
Please use our AAA pattern for testing also here in the client. https://documentation.dbildungscloud.dev/docs/schulcloud-server/Coding-Guidelines/testing

I would expect here more describes like: "when error is undefined" with it("should return undefined") so you define apiErrors and everything in a setup for each describe block

2024-04-18 10:20 UTC, arnegns commented on src/locales/de.ts
> +		"Das moin.schule System kann nicht gefunden werden!",
Shouldnt be "moin.schule-System" ?

2024-04-18 10:20 UTC, arnegns commented on src/locales/de.ts
> +		"Die Migration kann nicht gestartet werden, weil das Ziel-Login-System und das aktuelle Login-System Ihrer Schule gleich sind!",
Weird grammatic.
Maybe better: 
Die Migration kann nicht gestartet werden, da das Ziel-Login-System und das derzeitige Login-System Ihrer Schule identisch sind.

2024-04-19 06:47 UTC, MBergCap commented on src/composables/user-login-migration-mappings.composable.unit.ts
> +		it("should return undefined when error is undefined", () => {
fixed

2024-04-19 06:48 UTC, MBergCap commented on src/locales/de.ts
> +		"Die Migration kann nicht gestartet werden, weil das Ziel-Login-System und das aktuelle Login-System Ihrer Schule gleich sind!",
fixed

2024-04-19 07:24 UTC, MBergCap commented on src/locales/de.ts
> +		"Das moin.schule System kann nicht gefunden werden!",
fixed

2024-04-19 07:57 UTC, arnegns approved these changes

2024-04-19 07:59 UTC, merged