N21-1679-ctl-config-states
hpi-schul-cloud/nuxt-client pull request #3230
Opened 2024-05-02 11:14 UTC by mrikallab

# Short Description
This PR will introduce new ctl state incomplete operational. Tools that are incomplete operational should be launchable, if they have no outdated state.

## Links to Ticket and related Pull-Requests
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4970
https://ticketsystem.dbildungscloud.de/browse/N21-1677

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-05-02 22:40 UTC, IgorCapCoder requested changes

2024-05-02 22:40 UTC, IgorCapCoder commented on src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.ts
> +	const determineChipStatusTitle = (
I don't know if you are setting up a logic, which is about to get more complex here, but the way it is now it seems like you can take big shortcuts and reduce complexity. See below.

2024-05-02 22:40 UTC, IgorCapCoder commented on src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.ts
> +			if (toolConfigStatus.isDeactivated) {
As you are returning the same key here whether it is a student or a teacher and after a return there are no other checks, you could just check for this status in the beginning of the function (line 10) and be done with in it :)

Wasn't the deactivated status chip an additional one? If so, you cannot use a return statement here, because it will end the function and no other status can be obtained.

2024-05-02 22:40 UTC, IgorCapCoder commented on src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.ts
> +			} else if (
the 3 status options here are also present in the teacher case and you are returning the same key, so you could check for these statuses outside of the if(role) condition. These would lower complexity.

2024-05-02 22:40 UTC, IgorCapCoder commented on src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.ts
> +				toolConfigStatus.isIncompleteOperationalOnScopeContext
This looks weird. If i read this right, a teacher would see a statuschip of "outdated" for an invompete operational tool, but a student would not. Is thiscorrect? If so, this is the only part which needs an if (role) condition. If not you can make your life even easier here ^^

2024-05-02 22:40 UTC, IgorCapCoder commented on src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.ts
> +				toolConfigStatus.isIncompleteOnScopeContext
I know, the logic in this file is not your fault 😅 and maybe the file will look cleaner after some changes, but as it is now, it is really hard to read. I'm not sure if private methods would help here, this is at least what we do in the server, like canTeacherSolveThis or isProblemOnScopeContext or something better could help the reading flow, if there even is one here...

2024-05-02 22:40 UTC, IgorCapCoder commented on src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.unit.ts
> +				it("should return translationkey for incomplete operational ", () => {
I am still unsure about this requirement, but the it() and the expect do not fit ^^

2024-05-02 22:40 UTC, IgorCapCoder commented on src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.unit.ts
> +					expect(result).toEqual("pages.rooms.tools.outdated");
this seems like an outdated, the it expects an incomplete (which we don't have anymore, right?). They should fit better :)

2024-05-02 22:40 UTC, IgorCapCoder commented on src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.unit.ts
> +					expect(result).toEqual("pages.rooms.tools.outdated");
ExpectAndItMismatchException ;)

2024-05-02 22:40 UTC, IgorCapCoder commented on src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.unit.ts
> +					expect(result).toEqual("pages.rooms.tools.outdated");
ExpectAndItMismatchException

2024-05-02 22:40 UTC, IgorCapCoder commented on src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.unit.ts
> +	describe("determineChipStatusTitle", () => {
if my comments to this function in the composable file made sense, you can save yourself around 250 lines here :D

2024-05-02 22:40 UTC, IgorCapCoder commented on src/serverApi/v3/api.ts
> +    CollaborativeTextEditorElement = 'COLLABORATIVE_TEXT_EDITOR_ELEMENT',
why is this here? :O

2024-05-03 08:55 UTC, MarvinOehlerkingCap requested changes

2024-05-03 08:55 UTC, MarvinOehlerkingCap commented on src/modules/feature/board-external-tool-element/ExternalToolElement.vue
> +		const isToolIncompleteOperational: ComputedRef<boolean> = computed(
you added this, but never used it. I think isToolIncomplete and isToolOutdated only exist to block the launch.

2024-05-03 08:55 UTC, MarvinOehlerkingCap commented on src/components/rooms/RoomExternalToolCard.vue
> +					>{{ t(toolChipTitle) }}
use $t over t in the template

2024-05-03 08:55 UTC, MarvinOehlerkingCap commented on src/modules/feature/board-external-tool-element/ExternalToolElementAlert.vue
> +				t(toolDeactivatedMessage, {
$t

2024-05-03 08:55 UTC, MarvinOehlerkingCap commented on src/modules/feature/board-external-tool-element/ExternalToolElementAlert.vue
> +		<WarningAlert v-if="isToolIncompleteOperational" color="info">
The WarningAlert-Component has no color prop. Use InfoAlert for the info alert.

2024-05-03 08:55 UTC, MarvinOehlerkingCap commented on src/modules/feature/board-external-tool-element/ExternalToolElementAlert.vue
>  				!!props.toolStatus?.isOutdatedOnScopeSchool ||
toolStatus is required, so a ? should not be neccessary

2024-05-06 08:07 UTC, IgorCapCoder submitted a review, later dismissed

2024-05-06 08:10 UTC, MarvinOehlerkingCap commented on src/modules/ui/chip/WarningChip.unit.ts
> +describe("WarningChip", () => {
Same comments as in InfoChip.unit.ts

2024-05-06 09:39 UTC, mrikallab commented on src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.ts
> +	const determineChipStatusTitle = (
Because there is still an else case and I don't want to return an emtpy string

2024-05-06 13:41 UTC, MarvinOehlerkingCap requested changes

2024-05-06 13:41 UTC, MarvinOehlerkingCap commented on src/components/rooms/RoomExternalToolCard.vue
> +					{{ $t(toolChipTitle) }}
```suggestion
					{{ $t("pages.rooms.tools.outdated") }}
```

2024-05-06 13:41 UTC, MarvinOehlerkingCap commented on src/components/rooms/RoomExternalToolCard.vue
> +					>{{ $t(toolChipTitle) }}
```suggestion
					>{{ $t("pages.rooms.tools.outdated") }}
```

2024-05-06 13:41 UTC, MarvinOehlerkingCap commented on src/components/rooms/RoomExternalToolCard.vue
> +		);
```suggestion
		const showAsIncompleteOperational: ComputedRef = computed(
			() => props.tool.status.isIncompleteOperationalOnScopeContext && isTeacher
		);
```

2024-05-06 13:41 UTC, MarvinOehlerkingCap commented on src/components/rooms/RoomExternalToolCard.vue
> +		});
```suggestion
```

2024-05-06 13:41 UTC, MarvinOehlerkingCap commented on src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.ts
> +	};
```suggestion
```

2024-05-06 13:41 UTC, MarvinOehlerkingCap commented on src/modules/feature/board-external-tool-element/ExternalToolElement.vue
> +				!displayData.value?.status?.isIncompleteOnScopeContext
why `status?` and above not? is status optional or not?

2024-05-06 13:41 UTC, MarvinOehlerkingCap commented on src/modules/feature/board-external-tool-element/ExternalToolElement.vue
> +				!displayData.value?.status.isOutdatedOnScopeSchool ||
&&

2024-05-06 14:10 UTC, mrikallab commented on src/modules/feature/board-external-tool-element/ExternalToolElement.vue
> +				!displayData.value?.status?.isIncompleteOnScopeContext
copy paste mistake

2024-05-06 14:12 UTC, mrikallab commented on src/modules/feature/board-external-tool-element/ExternalToolElement.vue
> +				!displayData.value?.status.isOutdatedOnScopeSchool ||
islaunchable = incomplete or outdated, why should I use && here?

2024-05-06 14:31 UTC, mrikallab commented on src/modules/feature/board-external-tool-element/ExternalToolElement.vue
> +				!displayData.value?.status.isOutdatedOnScopeSchool ||
mittagstief, sorry

2024-05-07 08:27 UTC, MarvinOehlerkingCap approved these changes

2024-05-07 11:11 UTC, merged