N21-1901 visualize ctl tool states
hpi-schul-cloud/nuxt-client pull request #3252
Opened 2024-05-22 12:46 UTC by IgorCapCoder

# Short Description
In Mediaboard the states of ctl tool media are shown as chips and the respective error messages are shown when an unlaunchable tool is tried to get launched.

## Links to Ticket and related Pull-Requests
- https://ticketsystem.dbildungscloud.de/browse/N21-1901
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5019

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [x] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-05-27 11:56 UTC, MarvinOehlerkingCap requested changes

2024-05-27 11:56 UTC, MarvinOehlerkingCap commented on src/modules/feature/media-shelf/MediaBoardExternalToolElement.vue
> +import { ComputedRef } from "vue/dist/vue";
from "vue"

2024-05-27 11:56 UTC, MarvinOehlerkingCap commented on src/modules/feature/media-shelf/MediaBoardExternalToolElement.vue
> +import WarningChip from "@/modules/ui/chip/WarningChip.vue";
from "@ui-chip"

2024-05-27 11:56 UTC, MarvinOehlerkingCap commented on src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.unit.ts
> +				const composable = mountComposable(
I changed the test structure a bit in [N21-1991](https://github.com/hpi-schul-cloud/nuxt-client/pull/3260#top). Maybe you can also use it.

2024-05-27 11:56 UTC, MarvinOehlerkingCap commented on src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.unit.ts
> +					const translation =
you don't need to use the t function since you mocked it to return the key and I think it is better to read when you put the expected value in the toEqual() directly, 
(so `.toEqual("common.medium.alert.deactivated common.medium.information.admin")`)

2024-05-27 13:11 UTC, IgorCapCoder commented on src/modules/data/external-tool/ContextExternalToolConfigurationStatus.composable.unit.ts
> +				const composable = mountComposable(
changed to new structure ✅

2024-05-27 13:17 UTC, MarvinOehlerkingCap approved these changes

2024-05-27 14:01 UTC, MarvinOehlerkingCap requested changes

2024-05-28 07:25 UTC, MarvinOehlerkingCap approved these changes

2024-05-28 07:33 UTC, MarvinOehlerkingCap requested changes

2024-05-28 07:33 UTC, MarvinOehlerkingCap commented on src/modules/feature/media-shelf/MediaBoardExternalToolElement.vue
> +			text: t("error.loading"),
```suggestion
			text: t("error.load"),
```

2024-05-28 07:39 UTC, IgorCapCoder commented on src/modules/feature/media-shelf/MediaBoardExternalToolElement.vue
> +			text: t("error.loading"),
😲 what a trap 😂

2024-05-28 07:51 UTC, MarvinOehlerkingCap approved these changes

2024-05-28 07:57 UTC, merged