N21-2019 show media shelf tool usages
hpi-schul-cloud/nuxt-client pull request #3298
Opened 2024-06-21 10:42 UTC by IgorCapCoder

# Short Description
when school admin deletes a school external tool, the tool usages from media shelf are also shown

## Links to Ticket and related Pull-Requests
- https://n21-2019-show-tool-usage.nbc.dbildungscloud.dev/administration/school-settings

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-06-27 11:23 UTC, IgorCapCoder commented on src/components/administration/ExternalToolSection.vue
> +						:class="isMediaBoardUsageVisible ? 'text-md mb-0' : 'text-md'"
😎

2024-06-27 11:52 UTC, arnegns requested changes

2024-06-27 11:52 UTC, arnegns commented on src/components/administration/ExternalToolSection.vue
> +			if (!metadata.value) return false;
Please use brackets here

2024-06-27 11:52 UTC, arnegns commented on src/components/administration/ExternalToolSection.vue
> +			return (
Please dont use inline returns. Just return a variable

2024-06-27 11:52 UTC, arnegns commented on src/locales/de.ts
> +	"components.administration.externalToolsSection.dialog.content.header":
nice

2024-06-27 11:52 UTC, arnegns commented on src/components/administration/ExternalToolSection.vue
> +						:class="isMediaBoardUsageVisible ? 'text-md mb-0' : 'text-md'"
I am missing a test here :)

2024-06-27 11:52 UTC, arnegns commented on tests/test-utils/factory/schoolExternalToolMetadataFactory.ts
> +import { Factory } from "fishery";
Please check your import order :)

2024-06-27 14:22 UTC, GordonNicky commented on src/components/administration/ExternalToolSection.vue
> +			if (!metadata.value) return false;
added in [ce5a21f](https://github.com/hpi-schul-cloud/nuxt-client/pull/3298/commits/ce5a21fba1686cf081dd68e76ac17f7fa8526228)

2024-06-27 14:22 UTC, GordonNicky commented on src/components/administration/ExternalToolSection.vue
> +			return (
changed in [ce5a21f](https://github.com/hpi-schul-cloud/nuxt-client/pull/3298/commits/ce5a21fba1686cf081dd68e76ac17f7fa8526228)

2024-06-27 14:22 UTC, GordonNicky commented on tests/test-utils/factory/schoolExternalToolMetadataFactory.ts
> +import { Factory } from "fishery";
order swapped in [ce5a21f](https://github.com/hpi-schul-cloud/nuxt-client/pull/3298/commits/ce5a21fba1686cf081dd68e76ac17f7fa8526228) :)

2024-06-27 15:21 UTC, arnegns approved these changes

2024-06-28 11:56 UTC, GordonNicky commented on src/components/administration/ExternalToolSection.vue
> +						:class="isMediaBoardUsageVisible ? 'text-md mb-0' : 'text-md'"
Implemented in [ce5a21f](https://github.com/hpi-schul-cloud/nuxt-client/pull/3298/commits/ce5a21fba1686cf081dd68e76ac17f7fa8526228), I hope it is not too much

2024-07-05 08:00 UTC, merged