N21-2052 adjust ctl autocomplete
hpi-schul-cloud/nuxt-client pull request #3313
Opened 2024-07-03 08:28 UTC by arnegns

# Short Description
Makes it possbile to paste in urls to autocomplete on ctl configuration page to select the matching tool and automatically fill in the params

## Links to Ticket and related Pull-Requests
- https://ticketsystem.dbildungscloud.de/browse/N21-2052
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5094

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-07-10 08:30 UTC, MarvinOehlerkingCap requested changes

2024-07-10 08:30 UTC, MarvinOehlerkingCap commented on src/components/external-tools/configuration/external-tool-url-insertion.composable.unit.ts
> +		it("should return true when provided text is a valid url for an external tool", () => {
the "when" scenario should be its own describe and the test itself should have the AAA-pattern. 
```
const { isValidUrl } = setup(); // Arrange

const result = isValidUrl(url); // Act

expect(result).toBeTruthy(); // Assert
```
For more information on the test structure see https://documentation.dbildungscloud.dev/docs/schulcloud-server/Coding-Guidelines/testing

2024-07-10 08:30 UTC, MarvinOehlerkingCap commented on src/components/external-tools/configuration/external-tool-url-insertion.composable.unit.ts
> +			}
you could use jests build in .each function instead of using a for loop, like
```
it.each([
	{ url: "http..." },
	{ url: "http..." },
])("should return true for $url", () => {
	const { isValidUrl } = setup();

	const result = isValidUrl(url);

	expect(result).toBeTruthy();
});
```

2024-07-10 08:30 UTC, MarvinOehlerkingCap commented on src/components/external-tools/configuration/external-tool-url-insertion.composable.unit.ts
> +		templates.push(schoolExternalToolConfigurationTemplateFactory.build());
prefer: `const templates = schoolExternalToolConfigurationTemplateFactory.buildList(4);`

2024-07-10 08:30 UTC, MarvinOehlerkingCap commented on src/components/external-tools/configuration/external-tool-url-insertion.composable.unit.ts
> +				addPathParamsToTemplate(templateWithPathParams);
use the factories to build your objects, like
```
schoolExternalToolConfigurationTemplateFactory.build({
	baseUrl: "xyz",
	parameters: toolParameterFactory.buildList(3, {
		isOptional: false,
	}),
})
```
and prefer to create individual named objects over accessing arrays, like
```
const templateWithPathParams = schoolExternalToolConfigurationTemplateFactory.build({ parameters: [...] });
const templateWithoutPathParams = schoolExternalToolConfigurationTemplateFactory.build({ parameters: [] });
...
const templates = [templateWithPathParams, templateWithoutPathParams];
```

2024-07-10 08:30 UTC, MarvinOehlerkingCap commented on src/components/external-tools/configuration/external-tool-url-insertion.composable.unit.ts
> +				expect(findMatchingTemplate(testUrl, templates)).toBeDefined();
One test (`it`) should only test one thing. When you have multiple expects in a test it usually (not always) means that you have different test scenarios. Here for example "when the url has path parameters" and "when the url has query parameters"

2024-07-10 08:30 UTC, MarvinOehlerkingCap commented on src/components/external-tools/configuration/external-tool-url-insertion.composable.unit.ts
> +				testUrl += "/test-add-fault/";
Test data should be written clearly so that everyone can understand it without thinking much, so prefer to not use logic to build you data.

2024-07-10 08:30 UTC, MarvinOehlerkingCap commented on src/components/external-tools/configuration/external-tool-url-insertion.composable.unit.ts
> +					return;
Your test data should be adjusted according to the test, instead of adjusting the test according to the test data.

2024-07-10 08:30 UTC, MarvinOehlerkingCap commented on src/components/external-tools/configuration/ExternalToolConfigurator.unit.ts
> +		// TODO: comment in the test when https://github.com/vuetifyjs/vuetify/pull/16272 is merged
I will check myself if there is a way to test it

2024-07-10 15:13 UTC, GordonNicky commented on src/components/external-tools/configuration/ExternalToolConfigurator.unit.ts
> +	// TODO: new tests for combobox
fixed by your commit [73806b5](https://github.com/hpi-schul-cloud/nuxt-client/pull/3313/commits/73806b530865807b84ad0c417c95739dabd23122)

2024-07-10 15:26 UTC, GordonNicky commented on src/components/external-tools/configuration/external-tool-url-insertion.composable.unit.ts
> +				testUrl += "/test-add-fault/";
simplified the composable tests in [e204700](https://github.com/hpi-schul-cloud/nuxt-client/pull/3313/commits/e204700e0c86c3b1e6c905f2ff10957a14a899fa)

2024-07-10 15:26 UTC, GordonNicky commented on src/components/external-tools/configuration/external-tool-url-insertion.composable.unit.ts
> +				expect(findMatchingTemplate(testUrl, templates)).toBeDefined();
simplified the composable tests in [e204700](https://github.com/hpi-schul-cloud/nuxt-client/pull/3313/commits/e204700e0c86c3b1e6c905f2ff10957a14a899fa), no longer relevant

2024-07-10 15:35 UTC, GordonNicky commented on src/components/external-tools/configuration/ExternalToolConfigurator.unit.ts
> +		// TODO: comment in the test when https://github.com/vuetifyjs/vuetify/pull/16272 is merged
your commit [73806b5](https://github.com/hpi-schul-cloud/nuxt-client/pull/3313/commits/73806b530865807b84ad0c417c95739dabd23122) added a test for setting & extracting the parameters, the commit [5439fa4](https://github.com/hpi-schul-cloud/nuxt-client/pull/3313/commits/5439fa4538856d4bf0bf5f433c46f587e0e90051) added a test for filtering the selection list. I think that covers most of the new implementations.

2024-07-11 09:11 UTC, MarvinOehlerkingCap requested changes

2024-07-11 09:11 UTC, MarvinOehlerkingCap commented on src/components/external-tools/configuration/external-tool-url-insertion.composable.unit.ts
> +					expect(matchedTemplate).toBeDefined();
you could return the template that you want to test for from the setup and then check if it its equivalent here. At the moment you don't know if it selected the correct template, just that it selected one.

2024-07-11 09:11 UTC, MarvinOehlerkingCap commented on src/components/external-tools/configuration/external-tool-url-insertion.composable.unit.ts
> +					);
In Typescript/JavaScript you don't have to create an array before you fill it btw. You can just initialize it with the content like:
```
const pathParameters = [
	toolParameterFactory.build({
		...
	}),
	toolParameterFactory.build({
		...
	})
];
```

2024-07-11 09:11 UTC, MarvinOehlerkingCap commented on src/components/external-tools/configuration/external-tool-url-insertion.composable.unit.ts
> +					expect(matchedTemplate).toBeDefined();
Same as one of the tests above. It is better to check if it matches the specific template.

2024-07-11 09:11 UTC, MarvinOehlerkingCap commented on src/components/external-tools/configuration/external-tool-url-insertion.composable.unit.ts
> +					expect(matchedTemplate).toBeDefined();
same as above

2024-07-11 11:56 UTC, MarvinOehlerkingCap approved these changes

2024-07-11 12:46 UTC, merged