BC-7397 - Rename board types
hpi-schul-cloud/nuxt-client pull request #3330
Opened 2024-07-18 10:25 UTC by uidp

# Short Description

The current naming of the two boards has to be replaced ("Board" => "Bereich").

This has an effect on:

- creating a board 
- board cards in the course

## Links to Ticket and related Pull-Requests
BC-7397

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-07-18 15:03 UTC, odalys-dataport approved these changes

2024-07-18 18:29 UTC, MartinSchuhmacher requested changes

2024-07-18 18:29 UTC, MartinSchuhmacher commented on src/locales/de.ts
> +	"pages.rooms.fab.add.listBoard": "Neues Bereich | einspaltig",
`Neuer` Bereich

2024-07-22 05:45 UTC, MartinSchuhmacher submitted a review, later dismissed

2024-07-22 16:33 UTC, odalys-dataport approved these changes

2024-07-23 07:43 UTC, merged