BC-7664 Rename old stores
hpi-schul-cloud/nuxt-client pull request #3345
Opened 2024-07-31 13:46 UTC by wolfganggreschus

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-08-08 06:26 UTC, MartinSchuhmacher requested changes
* room-details/index.ts not needed anymore?

2024-08-08 06:26 UTC, MartinSchuhmacher commented on src/components/rooms/CourseBaseCard.unit.ts
> +import RoomBaseCard from "./CourseBaseCard.vue";
RoomBaseCard

2024-08-08 06:26 UTC, MartinSchuhmacher commented on src/components/rooms/CourseExternalToolCard.unit.ts
> +import RoomExternalToolCard from "./CourseExternalToolCard.vue";
RoomExternalToolCard

2024-08-08 06:26 UTC, MartinSchuhmacher commented on src/components/rooms/CourseExternalToolCard.vue
> +import RoomBaseCard from "./CourseBaseCard.vue";
RoomBaseCard

2024-08-09 08:27 UTC, wolfganggreschus commented on src/pages/courses/course-overview.unit.js
> +		const CourseModal = wrapper.findComponent({ name: "course-modal" });
wrapper.findComponent(CourseModal); -> doesn't work here. Don't know why...

2024-08-09 13:44 UTC, virgilchiriac commented on src/store/types/course.ts
> +	courseId: string;
todo check if is this accurate

2024-08-09 14:06 UTC, virgilchiriac commented on src/pages/courses/tools/CourseExternalToolsOverview.vue
> +			:room-id="courseId"
is this really so? 
should we not see something like :course-id="courseId" or :course-id="roomId"

2024-08-16 07:47 UTC, wolfganggreschus commented
Replaced by new PR https://github.com/hpi-schul-cloud/nuxt-client/pull/3361

2024-08-16 07:47 UTC, closed without merging