BC-7256 - Adaptive preview for file (only pdf with preview) and link element
hpi-schul-cloud/nuxt-client pull request #3362
Opened 2024-08-15 12:20 UTC by NFriedo

# Short Description

## Links to Ticket and related Pull-Requests
BC-7256

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-08-20 09:58 UTC, muratmerdoglu-dp requested changes

2024-08-20 09:58 UTC, muratmerdoglu-dp commented on src/composables/mimeType.composable.ts
> +};
I think this file should not be a composable file because there is no need to make it stateful. The return values of `isPdfMimeType, isAudioMimeType, isVideoMimeType` should also be not reactive (computed, ref, etc..). So, I think the function should be moved to the utils file (fileHelper).

2024-08-20 09:58 UTC, muratmerdoglu-dp commented on src/modules/feature/board-file-element/content/FileContent.vue
> +const mimeType = computed(() => props.fileProperties.mimeType);
An alternative way to prevent losing reactivity of props is using `toRef` or `toRefs` instead of using `computed`.
E.g.: `const { mimeType } = toRefs(props).fileProperties.value;`

2024-08-20 09:58 UTC, muratmerdoglu-dp commented on src/modules/feature/board-file-element/content/display/FileDisplay.vue
> +		<slot />
Are these slots used somewhere?

2024-08-20 09:58 UTC, muratmerdoglu-dp commented on src/modules/feature/board-file-element/content/display/FileDisplay.vue
> +const mimeType = computed(() => props.fileProperties.mimeType);
Same as above.

2024-08-20 09:58 UTC, muratmerdoglu-dp commented on src/modules/feature/board-file-element/content/inputs/FileInputs.vue
> +const mimeType = computed(() => props.fileProperties.mimeType);
Same as above

2024-08-20 11:43 UTC, NFriedo commented on src/composables/mimeType.composable.ts
> +};
moved back to file helper

2024-08-20 11:44 UTC, NFriedo commented on src/modules/feature/board-file-element/content/FileContent.vue
> +const mimeType = computed(() => props.fileProperties.mimeType);
Thank you for the hint! 
Removed because mimeType moved back to file helper

2024-08-20 13:38 UTC, NFriedo commented on src/modules/feature/board-file-element/content/display/FileDisplay.vue
> +		<slot />
I investigated the slots here. This is used for the 3 dot menu on the preview images. 
 So implementation is quite confusing but we still need them.

2024-08-23 09:47 UTC, muratmerdoglu-dp submitted a review, later dismissed

2024-08-23 13:05 UTC, muratmerdoglu-dp approved these changes

2024-08-26 06:36 UTC, merged