BC-7823 - implement rooms page
hpi-schul-cloud/nuxt-client pull request #3370
Opened 2024-08-21 06:42 UTC by uidp

# Short Description
As a teacher, I want to get an overview over all rooms I am part of or which I created.

## Links to Ticket and related Pull-Requests
BC-7823

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-08-26 16:00 UTC, MartinSchuhmacher commented on src/modules/feature/room-directory/RoomGrid.vue
> +		<VCustomEmptyState
do we already have an svg for the empty room state provided by UX?

2024-08-26 16:00 UTC, MartinSchuhmacher commented on src/types/room/Room.ts
> +export type Room = {
did we already talk about data model or how we wana structure it with BE?

2024-08-26 16:00 UTC, MartinSchuhmacher commented on src/modules/feature/room-directory/RoomGrid.vue
> +	margin-right: -20px;
not a big fan of these negative values

2024-08-27 08:09 UTC, uidp commented on src/modules/feature/room-directory/RoomGrid.vue
> +		<VCustomEmptyState
Good question. I thought not. That's why the "old" empty state.

2024-08-27 08:13 UTC, uidp commented on src/modules/feature/room-directory/RoomGrid.vue
> +	margin-right: -20px;
Yes, agreed. Generally we have to talk to UX about the tile layout. Maybe we can then improve that. The existing layout in the course rooms page is also a little bit confusing. So not quite sure how to build the new layout yet.

2024-08-27 11:12 UTC, odalys-dataport requested changes

2024-08-27 11:12 UTC, odalys-dataport commented on config/webpack/webpack.common.js
> +			"@feature-room-directory": getDir("src/modules/feature/room-directory"),
Why the `directory` suffix? We didn't do that for any other feature.

2024-08-27 11:12 UTC, odalys-dataport commented on src/locales/en.ts
> +	"pages.rooms.active.emptyState": "There are currently no rooms here.",
"Time statements" in English are always either at the end or at the beginning of a sentence. So this should be "Currently there are no rooms here." or "There are no rooms here currently.", preferably the first version.

2024-08-27 11:12 UTC, odalys-dataport commented on src/modules/feature/room-directory/RoomGrid.vue
> +		<VCustomEmptyState
I think we can move on without UX details like this, it'll come with time.

2024-08-27 11:12 UTC, odalys-dataport commented on src/modules/feature/room-directory/RoomGrid.vue
> +	margin-right: -20px;
I agree, I'm confused by this as well. We should try to find a better solution in the future.

2024-08-27 11:12 UTC, odalys-dataport commented on src/modules/feature/room-directory/RoomTile.vue
> +</template>
I'd love there to be an empty line between template and script :D

2024-08-27 11:12 UTC, odalys-dataport commented on src/modules/feature/room-directory/RoomTile.vue
> +	@include excerpt(
Could you tell me more about this?

2024-08-27 11:30 UTC, uidp commented on src/locales/en.ts
> +	"pages.rooms.active.emptyState": "There are currently no rooms here.",
Fixed that.

2024-08-27 11:32 UTC, uidp commented on src/modules/feature/room-directory/RoomTile.vue
> +</template>
Fixed.

2024-08-27 11:35 UTC, uidp commented on src/modules/feature/room-directory/RoomTile.vue
> +	@include excerpt(
This is a SCSS `@excerpt` helper we where using in various places in our code, e.g. in:
- `src/components/atoms/vRoomAvatar.vue`
- `src/components/lern-store/ContentCard.vue`
- `src/components/molecules/vRoomGroupAvatar.vue`
Thought it might be a good idea to use it again (for now).

2024-08-27 12:18 UTC, odalys-dataport commented on config/webpack/webpack.common.js
> +			"@feature-room-directory": getDir("src/modules/feature/room-directory"),
What's wrong with just `rooms`?

2024-08-29 09:44 UTC, uidp commented on config/webpack/webpack.common.js
> +			"@feature-room-directory": getDir("src/modules/feature/room-directory"),
I changed it to `@feature/room`. Actually it makes a lot of sense when we put there. I also moved the state composable under that module.

2024-08-29 13:54 UTC, odalys-dataport approved these changes

2024-08-29 15:37 UTC, merged