BC-7812 - Implement timeout to show error notifications
hpi-schul-cloud/nuxt-client pull request #3371
Opened 2024-08-21 11:26 UTC by muratmerdoglu-dp

# Short Description

## Links to Ticket and related Pull-Requests
https://ticketsystem.dbildungscloud.de/browse/BC-7812

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-08-28 06:19 UTC, hoeppner-dataport requested changes
Only some small suggestions on what can be improved.

2024-08-28 06:19 UTC, hoeppner-dataport commented on src/modules/data/board/socket/socket.ts
> +			if (timeoutFn.isPending.value) {
Is it possible that the code gets to this line without timeoutFn being defined... is a questionmark or a check against undefined maybe needed here?

2024-08-28 06:19 UTC, hoeppner-dataport commented on src/modules/data/board/socket/socket.unit.ts
> +		it("should not show connection restored notification when 'isInitialConnection' is true", () => {
The when part of this text should be a wrapping "describe" and should not use variable names:
```
describe("when the client connects for the first time", () => {
  it("should not show 'connection restored'-notification", () => {
```
same changes suggested for the following it(s).

2024-08-28 06:19 UTC, hoeppner-dataport commented on src/modules/data/board/socket/socket.unit.ts
> +			jest.clearAllMocks();
jest.clearAllMocks should be placed in an afterAll()

2024-08-28 06:19 UTC, hoeppner-dataport commented on src/modules/data/board/socket/socket.unit.ts
> +			getOrInitialiseBoardStore();
Maybe a setup-function can be useful here.

2024-09-02 06:57 UTC, NFriedo commented on src/modules/data/board/socket/socket.unit.ts
> -	beforeEach(() => {
Is there a reason why you removed the beforeEach() here? 
I think it would be better to have it there, to keep the tests independent from each other 🤔

2024-09-02 06:57 UTC, NFriedo commented on src/modules/data/board/socket/socket.unit.ts
> -	// values are created only once when the module is loaded and initially used.
Why did you remove this comment?

2024-09-02 07:17 UTC, muratmerdoglu-dp commented on src/modules/data/board/socket/socket.unit.ts
> -	beforeEach(() => {
`mockSocket.connected = true;` can be moved into `beforeEach()`, it make sense. But assigning `dispatchMock = jest.fn();` in every iteration is not necessary.

2024-09-02 07:17 UTC, muratmerdoglu-dp commented on src/modules/data/board/socket/socket.unit.ts
> -	// values are created only once when the module is loaded and initially used.
It's unclear "which two things", that's why these comments were removed.

2024-09-02 07:29 UTC, NFriedo commented on src/modules/data/board/socket/socket.unit.ts
> -	// values are created only once when the module is loaded and initially used.
I think it was about the following two lines. So maybe it would be better two write "We need to set the following two lines[...]" instead of removing it completely? Or do you think the info is not necessary?

2024-09-02 07:42 UTC, NFriedo approved these changes

2024-09-02 14:02 UTC, merged