N21 2075 sync existing course
hpi-schul-cloud/nuxt-client pull request #3373
Opened 2024-08-23 09:36 UTC by mrikallab

# Short Description

## Links to Ticket and related Pull-Requests

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-09-02 12:58 UTC, IgorCapCoder requested changes

2024-09-02 14:55 UTC, IgorCapCoder requested changes

2024-09-02 14:55 UTC, IgorCapCoder commented on src/pages/administration/RoomsOverview.page.vue
> +// vuetify typing: https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDataTable/composables/sort.ts#L29-L29
i know this is also in the class overview page code. But why do we need a comment here about vuetify typing?

2024-09-02 14:55 UTC, IgorCapCoder commented on src/pages/administration/RoomsOverview.page.vue
> +const getInstituteTitle: ComputedRef<string> = computed(() => {
this is the 4th page which has the exact same code... isn't it time for a composable? 😅

2024-09-02 14:55 UTC, IgorCapCoder commented on src/pages/administration/RoomsOverview.page.vue
> +	margin-bottom: -2px;
isn't it nice to have a page to copy from :D

2024-09-02 14:55 UTC, IgorCapCoder commented on src/pages/administration/RoomsOverview.page.unit.ts
> +	const findTableComponen = (wrapper: VueWrapper) => {
i guess you mean ...Component ;)

2024-09-02 14:55 UTC, IgorCapCoder commented on src/pages/administration/RoomsOverview.page.unit.ts
> +
As we have a special logic for when to show the sync button, we should test this here.
- course not synced -> show icon (already tested implicitly)
- course already synced -> do not show icon
What happens when course sync feature flag is false?

2024-09-02 17:48 UTC, mrikallab commented on src/modules/feature/course-sync/StartNewCourseSyncDialog.unit.ts
> +	});
Why should we test that no redirect happened, when click on cancel button.. ? 
I think the better thing is to test, if the dialog is closed after emitted cancel event.

2024-09-02 18:01 UTC, mrikallab commented on src/store/env-config-defaults.ts
> +	CALENDAR_SERVICE_ENABLED: false,
Normally this Feature is not provided in Nuxt or in Server. It is only provided in the old client. I think, if there is a problem with the server and we did not get any response, then this flag should be false.. but this is just my opinion. 
Do you have an Idea when it makes sense to set the default to true? Is "as this flag is true in all instances" an argument to set the default to true ?

2024-09-02 19:28 UTC, mrikallab commented on src/pages/administration/RoomsOverview.page.unit.ts
> +
It was not possible to test it with exist or visible, but testing if the id is provided on the element works.
I also saw that there is no such feature test in ClassOverview.. but this is not the main thing here..

2024-09-02 19:38 UTC, mrikallab commented on src/pages/administration/RoomsOverview.page.vue
> +const getInstituteTitle: ComputedRef<string> = computed(() => {
Sure, maybe for the 5th page 😅.
 I think this PR is big enough to change 4 pages know and test everything. 
 We should take it to the DP refactoring ticket after DP reviewed this beautiful PR.

2024-09-02 20:01 UTC, mrikallab commented on src/serverApi/v3/api.ts
> +/**
looks for me like someone forgot to generate the api

2024-09-02 20:02 UTC, mrikallab commented on src/serverApi/v3/api.ts
> -    /**
export class LoginResponse {
	@ApiProperty()
	accessToken: string;

	constructor(props: LoginResponse) {
		this.accessToken = props.accessToken;
	}
}


that is the login response from the server

2024-09-03 10:52 UTC, IgorCapCoder submitted a review, later dismissed

2024-09-03 12:10 UTC, IgorCapCoder approved these changes

2024-09-03 21:57 UTC, merged