BC - 8214 - fix jumping headings on room pages
hpi-schul-cloud/nuxt-client pull request #3418
Opened 2024-10-07 16:26 UTC by wolfganggreschus

# Short Description

On the following pages the headline of the page is not at the same place:

    room details page
    room overview page
    room edit/create page

## Links to Ticket and related Pull-Requests

BC-8214
## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-10-18 06:30 UTC, muratmerdoglu-dp commented on src/styles/settings.scss
> +      "size": 33px,
This changing affects all `h3` elements in the project. Avoid setting certain numbers in the setting file. It should be a calculation of the variables. If you still need to change `size` or `line-height` in some places, please override it in its scope.

2024-10-18 12:37 UTC, muratmerdoglu-dp commented on src/components/templates/DefaultWireframe.vue
> +			/>
<v-divider v-if="showBorder" class="mb-8 mx-n6" />

2024-10-18 13:19 UTC, muratmerdoglu-dp commented on src/components/templates/DefaultWireframe.vue
> +			/>
```suggestion
			<v-divider v-if="showBorder" class="mb-8 mx-n6" />
```

2024-10-18 13:19 UTC, muratmerdoglu-dp commented on src/modules/feature/board/board/BoardHeader.vue
> +					class="ml-n4"
![image](https://github.com/user-attachments/assets/51c29f9d-47a5-4132-9791-dac5f4ae1a97)
Is this spacing correct?

2024-10-18 13:19 UTC, muratmerdoglu-dp commented on src/components/templates/DefaultWireframe.vue
> +	line-height: 40px;
Repeated the same codes can be collected in one place (somewhere in src/styles/ folder), allowing us to manage them in one place. But the class name shouldn't be text-h3, might be something like room-text-h3. Because text-h3 class comes from Vuetify.

2024-10-21 09:22 UTC, odalys-dataport requested changes

2024-10-21 09:22 UTC, odalys-dataport commented on src/styles/settings.scss
> +  $breadcrumbs-item-padding: 0px,
Please move this below all lines concerning typo

2024-10-21 10:51 UTC, wolfganggreschus commented on src/modules/feature/board/board/BoardHeader.vue
> +					class="ml-n4"
According to Franz, it's fine

2024-10-21 12:04 UTC, odalys-dataport approved these changes

2024-10-21 13:52 UTC, merged