BC-8187 - Create and use Boards in Rooms
hpi-schul-cloud/nuxt-client pull request #3436
Opened 2024-11-04 16:23 UTC by uidp

# Short Description

As a teacher and student I want to be able to use a new single or multicolumn board within a room

## Links to Ticket and related Pull-Requests
BC-8187

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-11-07 10:00 UTC, MartinSchuhmacher commented on src/modules/page/room/RoomDetails.page.vue
> +		title: "Raum-Board", // t("pages.room.boardCard.label.courseBoard"),
?

2024-11-07 10:23 UTC, odalys-dataport requested changes

2024-11-07 10:23 UTC, odalys-dataport commented on src/modules/data/room/RoomDetails.store.ts
>  			const responseError = mapAxiosErrorToResponseError(error);
We should handle an error here properly by displaying an alert and staying on the current page.

2024-11-07 10:23 UTC, odalys-dataport commented on src/modules/feature/room/BoardGrid.vue
> +	<v-row class="mt-4" data-testid="board-grid">
I don't think we need a data-testid for the grid, but maybe we ask Ankush

2024-11-07 10:23 UTC, odalys-dataport commented on src/modules/feature/room/BoardTile.vue
> +		<div
Why are we not using `VCardTitle` and `VCardSubtitle` here?

2024-11-07 10:23 UTC, odalys-dataport commented on src/modules/feature/room/BoardTile.vue
> +		v-if="board"
I feel like we should move this if to the parent component. Inside the BoardTile component the board data should be present otherwise there is no need to render the BoardTile component

2024-11-07 10:23 UTC, odalys-dataport commented on src/modules/feature/room/BoardTile.vue
> +		role="link"
Knowing there is gonna be a board, we can then use the `to` prop, which will declare the card as a link automatically, which should either add the role link automatically as well or make it obsolete. semantic html > setting roles manually

2024-11-07 10:23 UTC, odalys-dataport commented on src/modules/feature/room/BoardTile.vue
> +		:class="{ 'board-hidden': isHidden }"
The naming of the class and the variable is a little confusing in my opinion as the card is not actually hidden it just gets a different look.

2024-11-07 10:23 UTC, odalys-dataport commented on src/modules/feature/room/BoardTile.vue
> +	const icon = isListBoard.value ? "$gridOutline" : mdiViewDashboardOutline;
Why are we using the `"$gridOutline"` here instead of importing the icon?

2024-11-07 10:23 UTC, odalys-dataport commented on src/modules/feature/room/RoomDetails.vue
>  		<div>
Is this div still necessary?

2024-11-07 10:23 UTC, odalys-dataport commented on src/modules/page/room/RoomDetails.page.vue
>  	<div v-if="isLoading" />
Maybe it's time we show a proper loading state?

2024-11-07 10:23 UTC, odalys-dataport commented on src/modules/page/room/RoomDetails.page.vue
> +	// TODO refine permissions
Can this be done now or is there a ticket for this?

2024-11-07 10:23 UTC, odalys-dataport commented on src/modules/page/room/RoomDetails.page.vue
> +const fabItems = computed(() => {
I feel like this code (defining fabItems) is incredibly hard to read

2024-11-07 10:23 UTC, odalys-dataport commented on src/modules/page/room/RoomDetails.page.vue
> +	} else if (event === "board-create") {
Maybe that's just me, but I prefer two ifs over else if

2024-11-07 10:42 UTC, uidp commented on src/modules/data/room/RoomDetails.store.ts
> +			).data.data;
Wir haben das bereits an verschiedenen Stellen. Und zwar immer bei Pagination-Responses. Die haben ein `data` für die axios Response Daten und ein `data` für die Elemente. Man könnte evtl. darüber nachdenken, die Pagination Response so zu ändern, dass der Property Name für die "Items" anders als `data` heißt.

2024-11-07 11:09 UTC, uidp commented on src/modules/page/room/RoomDetails.page.vue
> +		title: "Raum-Board", // t("pages.room.boardCard.label.courseBoard"),
Fixed that.

2024-11-07 11:20 UTC, uidp commented on src/modules/data/board/BoardPageInformation.composable.ts
> +	const contextType = computed(() => contextInfo.value?.type);
Ok, I changed `contextInfo` to `boardContext`. Since the composable is used in a couple of places changing `contextType` would require some refactoring or at least lead to some confusion if we would only rename it locally.  So I would rather leave it that way (for now). Actually `roomId` isn't precise eather because there are potentially other board contexts than room (aka course).

2024-11-07 11:23 UTC, uidp commented on src/modules/data/room/RoomDetails.store.ts
>  			const responseError = mapAxiosErrorToResponseError(error);
But that would be very unlikely because the room should be already found by the previous API request. So I would see that as an unexpected error.

2024-11-07 11:33 UTC, uidp commented on src/modules/feature/room/BoardTile.vue
> +		<div
We can actually. Was just a first prototype. So I didn't use the components. I updated the code.

2024-11-07 11:37 UTC, uidp commented on src/modules/feature/room/BoardTile.vue
> +		v-if="board"
I think it can even be left out entirely because it should always be defined.

2024-11-07 11:39 UTC, uidp commented on src/modules/feature/room/BoardTile.vue
> +		role="link"
Right. Works even with the enter key.

2024-11-07 11:45 UTC, uidp commented on src/modules/feature/room/BoardTile.vue
> +		:class="{ 'board-hidden': isHidden }"
Semantically, I think it should be something like `isDraft`. But then it's quite confusing when the API property is called `isVisible`. Generally I would prefer the `isPublished` / `isDraft` approach. But we decided in favor of `isVisible` 🤨

2024-11-07 11:48 UTC, odalys-dataport commented on src/modules/data/room/RoomDetails.store.ts
>  			const responseError = mapAxiosErrorToResponseError(error);
Unless the error is impossible we should still handle it though no?

2024-11-07 11:49 UTC, uidp commented on src/modules/feature/room/BoardTile.vue
> +	const icon = isListBoard.value ? "$gridOutline" : mdiViewDashboardOutline;
The icon `mdiViewGridOutline` is different and looks more like `mdiViewDashboardOutline`. That has to be fixed in the final version.

2024-11-07 11:50 UTC, odalys-dataport commented on src/modules/feature/room/BoardTile.vue
> +		:class="{ 'board-hidden': isHidden }"
Yea, it's a little confusing, because it's visible for the teacher but not for the student in the future. Within this component I'd still prefer to move away from `isHidden` and `board-hidden`.

2024-11-07 11:53 UTC, uidp commented on src/modules/feature/room/RoomDetails.vue
>  		<div>
Moved the check to `RoomDetailsPage` and add `required: true` to the property declaration.

2024-11-07 11:57 UTC, uidp commented on src/modules/page/room/RoomDetails.page.vue
>  	<div v-if="isLoading" />
We're still at the prototype stage. I suggest to add that later. Maybe we come up with something better than the old static skeleton?

2024-11-07 12:01 UTC, uidp commented on src/modules/page/room/RoomDetails.page.vue
> +const fabItems = computed(() => {
Well, that's a way to aggregate the fab items based on the permissions of the user. Maybe we can think about refactoring that somehow.

2024-11-07 12:31 UTC, odalys-dataport commented on src/modules/page/room/RoomDetails.page.vue
>  	<div v-if="isLoading" />
Let's create a ticket for that then, so it's not forgotten.

2024-11-07 14:28 UTC, odalys-dataport requested changes

2024-11-07 14:28 UTC, odalys-dataport commented on src/modules/feature/room/BoardTile.vue
> +		role="link"
Please remove `role="link"` as well :)

2024-11-07 14:28 UTC, odalys-dataport commented on src/modules/feature/room/RoomDetails.vue
> +	<div>
Is this surrounding div necessary?

2024-11-08 11:21 UTC, odalys-dataport approved these changes

2024-11-08 14:31 UTC, merged