BC-8348 - Implement Sharing and Copying of Room Boards
hpi-schul-cloud/nuxt-client pull request #3452
Opened 2024-11-14 11:41 UTC by uidp

# Short Description
We have to implement sharing and copying of boards that are associated to rooms. Currently this is only possible for boards that belong to courses. In order to do this we have to extend the ShareTokenModule and BoardModule.

## Links to Ticket and related Pull-Requests
BC-8348

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [x] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-11-29 11:17 UTC, odalys-dataport requested changes

2024-11-29 11:17 UTC, odalys-dataport commented on src/locales/es.ts
> +		"Elija habitación",
We decided on going with "sala" instead of "habitación"

2024-11-29 11:17 UTC, odalys-dataport commented on src/modules/page/room/RoomDetails.page.vue
> +								@click="deleteBoard"
A while ago we decided that "on" + eventName is our convention to name event handlers

2024-12-02 17:35 UTC, uidp commented on src/locales/es.ts
> +		"Elija habitación",
Ok, can you help with the right translation? What would it be then?

2024-12-03 20:58 UTC, uidp commented on src/modules/page/room/RoomDetails.page.vue
> +								@click="deleteBoard"
Ok, but it reads much better this way IMHO (like "At click: delete board"). And what about methods that are called from event handlers + from other methods? Should we wrap these methods in `on<method>` functions so they can be called in event handlers? Example would be `createBoard` which is called from `fabItemClickHandler`.

2024-12-04 10:44 UTC, odalys-dataport commented on src/modules/data/room/roomMembers/roomMembers.composable.unit.ts
> +					roleName: RoleName.Roomeditor,
Shouldn't it be `RoomEditor`?

2024-12-04 10:44 UTC, odalys-dataport commented on src/modules/feature/room/RoomMembers/AddMembers.unit.ts
> +			await roleComponent.vm.$emit("update:modelValue", RoleName.Roomviewer);
Same here with `RoomViewer`, maybe you can explain

2024-12-04 11:02 UTC, uidp commented on src/modules/data/room/roomMembers/roomMembers.composable.unit.ts
> +					roleName: RoleName.Roomeditor,
That name comes from the API Spec and results from the "specific" naming in the Server. This comes from generated code.

2024-12-04 11:02 UTC, uidp commented on src/modules/feature/room/RoomMembers/AddMembers.unit.ts
> +			await roleComponent.vm.$emit("update:modelValue", RoleName.Roomviewer);
see above

2024-12-04 14:14 UTC, MartinSchuhmacher commented on src/locales/es.ts
> +		"Seleccione la habitación al que desea importar el tablero.",
Seleccione la sala en la que desea importar el tablero.

2024-12-04 14:23 UTC, odalys-dataport submitted a review, later dismissed

2024-12-04 14:28 UTC, uidp commented on src/modules/page/room/RoomDetails.page.unit.ts
> +	canDeleteRoom: ref(false),
Well, can be distinct actions, right?

2024-12-04 14:31 UTC, uidp commented on src/modules/data/board/BoardPageInformation.composable.unit.ts
> +		const setup = async () => {
removed.

2024-12-04 14:32 UTC, uidp commented on src/locales/es.ts
> +		"Seleccione la habitación al que desea importar el tablero.",
Fixed.

2024-12-04 14:35 UTC, MartinSchuhmacher approved these changes

2024-12-04 16:18 UTC, closed without merging