EW-1060 redirected the common cartridge export to the cc-microservice
hpi-schul-cloud/nuxt-client pull request #3457
Opened 2024-11-22 08:34 UTC by Fshmit

# Short Description

- The export endpoint is redirected to the Common Cartridge microservice. The export request now goes to the microservice instead of the schulcloud server.
- Information regarding the export of files was deleted, as the export of files is now implemented and executable. 

## Links to Ticket and related Pull-Requests
[Ticket](https://ticketsystem.dbildungscloud.de/browse/EW-1060)
## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-12-10 14:18 UTC, MajedAlaitwniCap commented on src/components/molecules/CommonCartridgeExportModal.vue
> -							{{ $t(`components.molecules.export.options.info.point1`) }}
should this be removed from language Files?

2024-12-11 09:16 UTC, MajedAlaitwniCap requested changes

2024-12-11 09:16 UTC, MajedAlaitwniCap commented on src/store/course-room-details.ts
> +			// const response = await CoursesApiFactory(
when should this be deleted?

2024-12-13 10:33 UTC, psachmann requested changes

2024-12-13 10:33 UTC, psachmann commented on package.json
> +		"generate-client:common-cartridge": "node generate-client.js -u 'http://localhost:3350/api/v3/docs-json/' -p 'src/commonCartridgeApi/v3' -c 'openapitools-for-common-cartridge.json'"
Deletion commend is missing and use the openapi-generator-cli directly in the same way we are generating the clients in the server.

2024-12-13 10:33 UTC, psachmann commented on openapitools-for-common-cartridge.json
Create one openapitools.json file with the config.

2024-12-16 09:58 UTC, psachmann submitted a review, later dismissed

2024-12-17 09:20 UTC, psachmann commented on src/store/course-room-details.ts
> +			// const response = await CoursesApiFactory(
Comment removed

2024-12-17 12:08 UTC, psachmann submitted a review, later dismissed

2024-12-18 13:37 UTC, MajedAlaitwniCap submitted a review, later dismissed

2024-12-18 13:58 UTC, psachmann approved these changes

2024-12-18 14:14 UTC, MajedAlaitwniCap approved these changes

2024-12-18 14:31 UTC, merged