N21-1506 sharing ctl tools
hpi-schul-cloud/nuxt-client pull request #3461
Opened 2024-11-26 01:03 UTC by IgorCapCoder

# Short Description

renewing the share modals for course, boards, topics to increase readability and new feature of sharing ctl tools across schools.

## Links to Ticket and related Pull-Requests
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5353
- https://ticketsystem.dbildungscloud.de/browse/N21-1506

## Changes

## Data-security

## Deployment

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Checklist before merging

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [ ] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [ ] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-12-02 09:07 UTC, MarvinOehlerkingCap requested changes

2024-12-02 12:53 UTC, IgorCapCoder commented on src/components/share/ImportModal.vue
> +							ctlToolsEnabled &&
this could be done, though there are different data test ids which might be messy to implement dynamically... look at the new solution - maybe is is ok :)

2024-12-03 00:47 UTC, IgorCapCoder commented on src/components/share/ShareModal.vue
> +										data-testid="share-modal-external-tools-info"
both ctl lines are always shown together (use the same logic), so to test if they exist, one should suffice. There is also only one line with a data-testid for the last 4 lines because of the same reason. I could give every line a test id, but i don't think that it's necessary or even useful.

2024-12-03 11:57 UTC, MarvinOehlerkingCap submitted a review, later dismissed

2024-12-05 14:22 UTC, MarvinOehlerkingCap commented on src/components/copy-result-modal/CopyResultModalListItem.vue
> +				if (element.type === CopyApiResponseTypeEnum.ExternalTool) {
this should not be needed, when it is not implemented as a feedback child

2024-12-05 14:28 UTC, MarvinOehlerkingCap commented on src/store/copy.ts
> +			if (type === CopyApiResponseTypeEnum.ExternalTool) return true;
CopyApiResponseTypeEnum.ExternalTool should not be implemented yet, since you get `Raum · <link to course edit page>` in the copy result otherwise, which is confusing. We need more concrete requirements on how it should look like before we can implement it.

2024-12-05 14:32 UTC, MarvinOehlerkingCap commented on src/components/copy-result-modal/CopyResultModal.vue
> +			console.log(JSON.stringify(items));
no console.log

2024-12-05 14:47 UTC, GordonNicholasCap commented on src/components/share/ImportModal.vue
> +					<div>
It was probably overlooked during refactoring, I will remove it

2024-12-05 15:05 UTC, GordonNicholasCap commented on src/components/share/ShareModal.vue
> +const isCourse = computed(() => props.type === "courses");
It was probably forgotten to be removed, I will remove it

2024-12-06 10:24 UTC, MarvinOehlerkingCap approved these changes

2024-12-09 08:26 UTC, merged