BC-8193 - Expanding and registering BBB
hpi-schul-cloud/nuxt-client pull request #3469
Opened 2024-12-05 10:57 UTC by MartinSchuhmacher

# Short Description
Start implementing BBB on boards.

## Links to Ticket and related Pull-Requests
BC-8193
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5354
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/1061

## Changes
- VC element in FE
- creating element in BE via request
- show note for users if not yet started
- show note if feature is deactivated
- show dot if VC is running

## Screenshots of UI changes
https://www.figma.com/design/gcmoQwOKHOSjK8d1Z90yQQ/Raum?node-id=1578-18680&node-type=canvas&t=33UdDz7C8PuxRTPE-0

## Checklist before merging

- [x] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] PO: Any deviation from requirements was agreed with Product-Owner / ticket author / support-team
- [x] DEV: Every new component is implemented having accessibility in mind (e.g. aria-label, role property)

> Notice: Please keep this Pull-Request as a Draft (or add WIP label), until it is ready to be reviewed

2024-12-13 12:50 UTC, odalys-dataport requested changes

2024-12-13 12:50 UTC, odalys-dataport commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementCreate.vue
> +export default defineComponent({
Please use script setup

2024-12-13 12:50 UTC, odalys-dataport commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementDisplay.unit.ts
> +			const titleElement = wrapper.find(".content-element-title");
Please don't use css classes to find elements

2024-12-13 12:50 UTC, odalys-dataport commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementDisplay.unit.ts
> +		const setup = (propsData: {
Can `setup()` and `getWrapper()` maybe be combined?

2024-12-13 12:50 UTC, odalys-dataport commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementDisplay.unit.ts
> +		it("should show 'not enabled for teacher' alert when feature is disabled", () => {
When you use a "when" in the `it` statement, use a describe block instead :)

2024-12-13 12:50 UTC, odalys-dataport commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementDisplay.vue
> +	<div ref="videoConferenceContentElementDisplay" tabindex="-1">
This ref doesn't seem to be used?

2024-12-13 16:25 UTC, uidp submitted a review, later dismissed

2024-12-13 16:25 UTC, uidp commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementDisplay.unit.ts
> +			const titleElement = wrapper.find(".content-element-title");
Why not? Should we rather use `data-testid`?

2024-12-13 16:25 UTC, uidp commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementDisplay.unit.ts
> +		const setup = (propsData: {
Actually it might be desirable to have local `setup` methods specific for each (larger) `describe` block that do not take any parameters and do specify exactly what the local setup is like. We could implement this using a more generic global `setupGeneric` or `getWrapper` etc. method which takes all necessary parameters to build the specific `setup`s.
In this test both - `setup` and `getWrapper` - take parameters. That doesn't seem ideal IMHO.

2024-12-13 20:55 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElement.vue
> +			<v-dialog
agree that this would make sense to exist as a separate component also for the course implementation, but not sure if thats high priority enough to block us, lets talk on monday

2024-12-13 20:55 UTC, MartinSchuhmacher commented on src/locales/de.ts
> +		"Das Element ist nicht mehr verfügbar. Bitte an Admin wenden.",
will do

2024-12-13 20:55 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElement.vue
> +			@keydown.stop
works fine, thx

2024-12-13 20:56 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElement.vue
> +		<v-card
changed that

2024-12-13 20:56 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElement.vue
> +	<div ref="videoConferenceContentElement">
you're right, I removed that

2024-12-13 20:56 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElement.vue
> +				><BoardMenu
fixed that

2024-12-13 20:56 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElement.vue
> +				><BoardMenu
fixed that

2024-12-13 20:57 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElement.vue
> +			<v-custom-dialog
implemented the VDialog directly with buttons and so on

2024-12-13 20:57 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElement.vue
> +				data-testId="error-dialog"
thx for mentioning! I mixed that up a little, still confused about the naming of our data-testid stuff

2024-12-13 21:02 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElement.vue
> +const onClick = async () => {
agree, will fix that

2024-12-13 21:06 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementCreate.unit.ts
> +		describe("when enter is pressed", () => {
I like that, will apply accordingly

2024-12-13 21:13 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementCreate.unit.ts
> +				await nextTick();
yup, removed that

2024-12-13 21:14 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementCreate.vue
> +	<div data-testid="board-video-conference-element-create" tabindex="-1">
forgot to remove, thx for mentioning!

2024-12-14 11:49 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementCreate.vue
> +export default defineComponent({
adjusted the script

2024-12-14 12:01 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementDisplay.unit.ts
> +			const titleElement = wrapper.find(".content-element-title");
adjusted the ´VideoConferenceContentElementDisplay´ and `ContentElementBar` components to use only data test ids in testing

2024-12-14 21:29 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementDisplay.unit.ts
> +		const setup = (propsData: {
adjusted all three unit test files for the new components with a more general `setupWrapper` method to be used for general purpose

2024-12-14 21:43 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementDisplay.unit.ts
> +		it("should show 'not enabled for teacher' alert when feature is disabled", () => {
will adjust as much as possible

2024-12-14 21:46 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElementDisplay.vue
> +	<div ref="videoConferenceContentElementDisplay" tabindex="-1">
removed, as well as the unused tabindex

2024-12-14 21:57 UTC, MartinSchuhmacher commented on src/modules/data/board/BoardApi.composable.ts
> +			} as VideoConferenceElementContentBody;
you could do that, but in comparison you would need
``` typescript
const body: VideoConferenceElementContentBody = { 
     content: element.content  as VideoConferenceContentBody, 
     type: ContentElementType.VideoConference, 
} 
return body;
```

which does not really bring any advantage in my opinion, what do you think?

2024-12-15 19:23 UTC, MartinSchuhmacher commented on src/modules/feature/board-video-conference-element/components/VideoConferenceContentElement.vue
> +			<v-dialog
took a first look, would like to do that in the follow up (additional to the composable approach) within BC-8168 if thats ok for you

2024-12-16 07:01 UTC, uidp commented on src/modules/data/board/BoardApi.composable.ts
> +			} as VideoConferenceElementContentBody;
Well that could be simplified if we'd be using type guards instead of comparing to the `ContentElementType`.
```typescript
const isVideoConferenceElement = (element: AnyContentElement): element is VideoConferenceElement {
    return element.type === ContentElementType.VideoConference;
}

if (isVideoConferenceElement(element)) {
    // now element should be of type VideoConferenceElement
    const body: VideoConferenceElementContentBody = { 
        content: element.content, // content should be assignable now 
        type: ContentElementType.VideoConference, 
    } 
    return body;
}
```
Hope that was correct. Like I said, just a thought. Maybe not necessary to change now.

2024-12-16 07:30 UTC, MartinSchuhmacher commented on src/modules/data/board/BoardApi.composable.ts
> +			} as VideoConferenceElementContentBody;
interesting approach, would like to discuss that further, but yes, would mean a lot of changes so maybe at a later point... ^^

2024-12-16 10:33 UTC, uidp submitted a review, later dismissed

2024-12-16 10:36 UTC, odalys-dataport submitted a review, later dismissed

2024-12-16 10:39 UTC, uidp approved these changes

2024-12-16 10:55 UTC, odalys-dataport approved these changes

2024-12-16 12:44 UTC, merged